var _CHAR_TABS=[{id:"overview",label:"Geral"},{id:"attrs",label:"Atributos"},{id:"combat",label:"Combate"},{id:"feats",label:"Feitos"},];var _CHAR_TAB_STORAGE_KEY="valdoria_char_tab";function renderCharDetails(container,data){if(!container||!data)return;container.innerHTML="";var wrap=document.createElement("div");wrap.className="char-details";var hdr=document.createElement("div");hdr.className="char-details-header";var nameEl=document.createElement("div");nameEl.className="char-details-name";var badge=data.badge?data.badge+" ":"";var nameTxt=badge+data.name+" Lv."+data.level+" "+data.class_name;if(data.subclass)nameTxt+=" — "+data.subclass;nameEl.textContent=nameTxt;hdr.appendChild(nameEl);var metaEl=document.createElement("div");metaEl.className="char-details-meta";var metaTxt="🏷️ "+data.race;if(data.background)metaTxt+=" | 📜 "+data.background;metaEl.textContent=metaTxt;hdr.appendChild(metaEl);wrap.appendChild(hdr);var tabRow=document.createElement("div");tabRow.className="char-tabs";var savedTab=localStorage.getItem(_CHAR_TAB_STORAGE_KEY)||"overview";var panels={};for(var i=0;i<_CHAR_TABS.length;i++){var t=_CHAR_TABS[i];var btn=document.createElement("button");btn.className="char-tab"+(savedTab===t.id?" active":"");btn.textContent=t.label;btn.setAttribute("data-tab",t.id);(function(tabId,tabBtn){tabBtn.onclick=function(){var allTabs=tabRow.querySelectorAll(".char-tab");for(var j=0;j<allTabs.length;j++){allTabs[j].classList.toggle("active",allTabs[j].getAttribute("data-tab")===tabId);}
for(var key in panels){panels[key].classList.toggle("active",key===tabId);}
try{localStorage.setItem(_CHAR_TAB_STORAGE_KEY,tabId);}catch(e){console.warn('[GAME]',e);}};})(t.id,btn);tabRow.appendChild(btn);}
wrap.appendChild(tabRow);panels["overview"]=_buildOverviewPanel(data);panels["attrs"]=_buildAttrsPanel(data);panels["combat"]=_buildCombatPanel(data);panels["feats"]=_buildFeatsPanel(data);for(var key in panels){panels[key].className="char-tab-panel"+(savedTab===key?" active":"");wrap.appendChild(panels[key]);}
container.appendChild(wrap);}
function _buildOverviewPanel(data){var panel=document.createElement("div");panel.appendChild(_makeBar("❤️",data.hp.cur,data.hp.max,_hpBarClass(data.hp.cur,data.hp.max)));panel.appendChild(_makeBar(data.mp.icon||"💧",data.mp.cur,data.mp.max,"mp"));var xpLabel=_abbreviate(data.xp.cur)+"/"+_abbreviate(data.xp.max)+" XP";panel.appendChild(_makeBarCustom("✨",data.xp.cur,data.xp.max,"xp",xpLabel));var hdLabel=data.hd.cur+"/"+data.hd.max+" ("+data.hd.die+")";panel.appendChild(_makeBarCustom("🎲",data.hd.cur,data.hd.max,"hd",hdLabel));var resRow=document.createElement("div");resRow.className="char-resources";resRow.appendChild(_makeResourceBadge("Valdoritas",data.gold,'<span class="vi vi-coin sm"><\/span>'));resRow.appendChild(_makeResourceBadge("🎒",data.items,"Itens"));if(data.potions>0){resRow.appendChild(_makeResourceBadge("🧪",data.potions,"Poções"));}
panel.appendChild(resRow);var sumRow=document.createElement("div");sumRow.className="char-summary-row";sumRow.appendChild(_makeSummaryBadge("🌟",data.skill_count+" habilidade(s)"));sumRow.appendChild(_makeSummaryBadge("🗡️",data.equipped_count+" equipado(s)"));panel.appendChild(sumRow);if(data.conditions&&data.conditions.length>0){var condDiv=document.createElement("div");condDiv.className="char-conditions";condDiv.textContent="⚠️ "+data.conditions.join(" · ");panel.appendChild(condDiv);}
return panel;}
function _makeBar(icon,cur,max,type){var pct=max>0?Math.round((cur/max)*100):0;var row=document.createElement("div");row.className="char-bar-row";var iconEl=document.createElement("span");iconEl.className="char-bar-icon";iconEl.textContent=icon;row.appendChild(iconEl);var track=document.createElement("div");track.className="char-bar-track";var fill=document.createElement("div");fill.className="char-bar-fill "+type;fill.style.width=pct+"%";track.appendChild(fill);row.appendChild(track);var label=document.createElement("span");label.className="char-bar-label";label.textContent=cur+"/"+max;row.appendChild(label);return row;}
function _makeBarCustom(icon,cur,max,type,labelText){var bar=_makeBar(icon,cur,max,type);bar.querySelector(".char-bar-label").textContent=labelText;return bar;}
function _hpBarClass(cur,max){return typeof vBarHpClass==='function'?vBarHpClass(cur,max):(max>0?(cur/max):1)>0.60?'hp':(max>0?(cur/max):1)>0.25?'hp-warn':'hp-crit';}
function _makeResourceBadge(icon,val,label){var badge=document.createElement("div");badge.className="char-resource-badge";badge.innerHTML=icon+" <span class=\"val\">"+val+"</span> "+label;return badge;}
function _makeSummaryBadge(icon,text){var badge=document.createElement("div");badge.className="char-summary-badge";badge.textContent=icon+" "+text;return badge;}
function _abbreviate(n){if(n>=1000){if(n%1000===0)return(n/1000)+"k";return(n/1000).toFixed(1).replace(".0","")+"k";}
return""+n;}
function _buildAttrsPanel(data){var panel=document.createElement("div");var grid=document.createElement("div");grid.className="char-attr-grid";for(var i=0;i<data.attrs.length;i++){var a=data.attrs[i];var card=document.createElement("div");card.className="char-attr-card";var iconEl=document.createElement("span");iconEl.className="char-attr-icon";iconEl.textContent=a.icon;card.appendChild(iconEl);var labelEl=document.createElement("div");labelEl.className="char-attr-label";labelEl.textContent=a.label;card.appendChild(labelEl);var valEl=document.createElement("div");valEl.className="char-attr-val";valEl.textContent=a.val;card.appendChild(valEl);var modEl=document.createElement("div");modEl.className="char-attr-mod";modEl.textContent=(a.mod>=0?"+":"")+a.mod;card.appendChild(modEl);grid.appendChild(card);}
panel.appendChild(grid);return panel;}
function _buildCombatPanel(data){var panel=document.createElement("div");var grid=document.createElement("div");grid.className="char-combat-grid";var c=data.combat;var dexSign=c.ac.dex_mod>=0?"+":"";grid.appendChild(_makeCombatCard("🛡️","Defesa (CA)",c.ac.total,"10 "+dexSign+c.ac.dex_mod+"(DEX) + "+c.ac.equip_ac+"(Itens)"));grid.appendChild(_makeCombatCard("🎯","Ataque",(c.atk.total>=0?"+":"")+c.atk.total,(c.atk.stat_mod>=0?"+":"")+c.atk.stat_mod+"("+c.atk.stat+") + "+c.atk.prof+"(Prof.) + "+c.atk.item_bonus+"(Item)"));grid.appendChild(_makeCombatCard("💥","Dano",c.dmg.die+" "+(c.dmg.bonus>=0?"+":"")+c.dmg.bonus,c.dmg.die+"(Arma) + "+c.dmg.bonus+"(Bônus)"));grid.appendChild(_makeCombatCard("📋","Proficiência","+"+c.prof,""));panel.appendChild(grid);return panel;}
function _makeCombatCard(icon,label,val,formula){var card=document.createElement("div");card.className="char-combat-card";var iconEl=document.createElement("span");iconEl.className="char-combat-icon";iconEl.textContent=icon;card.appendChild(iconEl);var info=document.createElement("div");info.className="char-combat-info";var labelEl=document.createElement("div");labelEl.className="char-combat-label";labelEl.textContent=label;info.appendChild(labelEl);var valEl=document.createElement("div");valEl.className="char-combat-val";valEl.textContent=val;info.appendChild(valEl);if(formula){var formulaEl=document.createElement("div");formulaEl.className="char-combat-formula";formulaEl.textContent=formula;info.appendChild(formulaEl);}
card.appendChild(info);return card;}
function _buildFeatsPanel(data){var panel=document.createElement("div");if(!data.feats||data.feats.length===0){var empty=document.createElement("div");empty.className="char-feats-empty";empty.textContent="Nenhum feito registrado ainda. Explore Valdoria e conquiste glória!";panel.appendChild(empty);return panel;}
var list=document.createElement("div");list.className="char-feats-list";for(var i=0;i<data.feats.length;i++){var item=document.createElement("div");item.className="char-feat-item";item.textContent=data.feats[i];list.appendChild(item);}
panel.appendChild(list);return panel;}