function renderQuestDiary(container,data){container.innerHTML='';var wrap=document.createElement('div');wrap.className='quest-diary';if(data.flash){var flash=document.createElement('div');flash.className='quest-flash';flash.innerHTML='\ud83d\udcac <em>\u201c'+vEsc(data.flash)+'\u201d</em>';wrap.appendChild(flash);}
var searchWrap=document.createElement('div');searchWrap.className='quest-search-wrap';var searchInput=document.createElement('input');searchInput.type='text';searchInput.className='quest-search-input';searchInput.placeholder='\ud83d\udd0d Pesquisar miss\u00f5es...';searchWrap.appendChild(searchInput);wrap.appendChild(searchWrap);var filters=[{id:'all',icon:'\ud83d\udccb',label:'Todas'},{id:'story',icon:'\u2694\ufe0f',label:'Hist\u00f3ria'},{id:'daily',icon:'\ud83d\udd04',label:'Di\u00e1rias'},{id:'done',icon:'\u2705',label:'Feitas'},];var activeFilter='all';var tabRow=document.createElement('div');tabRow.className='quest-filter-tabs';for(var i=0;i<filters.length;i++){var f=filters[i];var tab=document.createElement('button');tab.className='quest-filter-tab'+(activeFilter===f.id?' active':'');tab.textContent=f.icon+' '+f.label;tab.setAttribute('data-filter',f.id);(function(fid,tabEl){tabEl.onclick=function(){activeFilter=fid;var allTabs=tabRow.querySelectorAll('.quest-filter-tab');for(var t=0;t<allTabs.length;t++){allTabs[t].classList.toggle('active',allTabs[t].getAttribute('data-filter')===fid);}
_applyQuestFilter(wrap,fid,searchInput.value);};})(f.id,tab);tabRow.appendChild(tab);}
wrap.appendChild(tabRow);searchInput.oninput=function(){_applyQuestFilter(wrap,activeFilter,searchInput.value);};if(data.turnin&&data.turnin.length>0){for(var ti=0;ti<data.turnin.length;ti++){var t=data.turnin[ti];var banner=document.createElement('button');banner.className='quest-turnin-banner';banner.setAttribute('data-qsection','turnin');var bannerText=t.count>1?'\ud83d\udcdc Entregar '+t.count+' Miss\u00f5es':'\ud83d\udcdc Entregar: '+vEsc(t.titles[0]);banner.innerHTML='<strong>'+bannerText+'</strong>'
+'<span class="quest-turnin-loc">'+vEsc(t.loc)+'</span>';(function(cb){banner.onclick=function(){doAction(cb);};})(t.cb);wrap.appendChild(banner);}}
if(data.story&&data.story.length>0){var storyHdr=_questSectionHdr('\u2694\ufe0f','Missões em Andamento');storyHdr.setAttribute('data-qsection','story');wrap.appendChild(storyHdr);for(var si=0;si<data.story.length;si++){var sCard=_renderQCard(data.story[si]);sCard.setAttribute('data-qsection','story');sCard.setAttribute('data-qtitle',(data.story[si].title||'').toLowerCase());wrap.appendChild(sCard);}}
if(data.daily&&data.daily.length>0){var dailyHdr=_questSectionHdr('\ud83d\udd04','Tarefas do Dia');dailyHdr.setAttribute('data-qsection','daily');wrap.appendChild(dailyHdr);for(var di=0;di<data.daily.length;di++){var dCard=_renderQCard(data.daily[di],true);dCard.setAttribute('data-qsection','daily');dCard.setAttribute('data-qtitle',(data.daily[di].title||'').toLowerCase());wrap.appendChild(dCard);}}
if(data.done&&data.done.length>0){var doneHdr=_questSectionHdr('\u2705','Feitos Realizados');doneHdr.setAttribute('data-qsection','done');wrap.appendChild(doneHdr);for(var ci=0;ci<data.done.length;ci++){var d=data.done[ci];var doneCard=document.createElement('div');doneCard.className='quest-card quest-card--done';doneCard.setAttribute('data-qsection','done');doneCard.setAttribute('data-qtitle',(d.title||'').toLowerCase());doneCard.innerHTML='<div class="quest-card-header">'
+'<span class="quest-title quest-title--done">'+vEsc(d.title)+'</span></div>'
+'<div class="quest-rewards-mini">\u2728 '+d.xp+' XP \u00b7 \ud83d\udcb0 '+d.gold+' <span class="vi vi-coin sm"></span></div>';wrap.appendChild(doneCard);}}
if(data.failed&&data.failed.length>0){var failHdr=_questSectionHdr('\u274c','Miss\u00f5es Perdidas');failHdr.setAttribute('data-qsection','done');wrap.appendChild(failHdr);for(var fi=0;fi<data.failed.length;fi++){var fq=data.failed[fi];var failCard=document.createElement('div');failCard.className='quest-card quest-card--failed';failCard.setAttribute('data-qsection','done');failCard.setAttribute('data-qtitle',(fq.title||'').toLowerCase());failCard.innerHTML='<div class="quest-card-header">'
+'<span class="quest-title quest-title--failed">\ud83d\udc80 '+vEsc(fq.title)+'</span></div>';if(fq.cb_retry){var retryBtn=document.createElement('button');retryBtn.className='quest-retry-btn';retryBtn.textContent='\ud83d\udd04 Tentar Novamente';(function(cb){retryBtn.onclick=function(e){e.stopPropagation();doAction(cb);};})(fq.cb_retry);failCard.appendChild(retryBtn);}
wrap.appendChild(failCard);}}
var totalQ=(data.story||[]).length+(data.daily||[]).length
+(data.done||[]).length+(data.failed||[]).length;if(totalQ===0){var empty=document.createElement('div');empty.className='quest-empty';var _eText=document.createElement('div');_eText.className='quest-empty-text';_eText.textContent='\ud83d\udcdc Nenhuma miss\u00e3o ativa';empty.appendChild(_eText);var _eHint=document.createElement('div');_eHint.className='quest-empty-hint';_eHint.textContent='Converse com os habitantes de Eld\u00f3ria ou visite o Quadro de Miss\u00f5es na Guilda dos Aventureiros.';
empty.appendChild(_eHint);var _eCta=document.createElement('div');_eCta.className='quest-empty-cta';_eCta.textContent='\ud83c\udfe0 Visitar Locais';_eCta.onclick=function(){doAction('action_city_locations');};empty.appendChild(_eCta);wrap.appendChild(empty);}
var emptyFilter=document.createElement('div');emptyFilter.className='quest-empty quest-empty-filter';emptyFilter.style.display='none';emptyFilter.innerHTML='<div class="quest-empty-text">Nenhuma miss\u00e3o nesta categoria.</div>';wrap.appendChild(emptyFilter);container.appendChild(wrap);}
function _applyQuestFilter(wrap,filter,searchText){var query=(searchText||'').toLowerCase().trim();var sections=wrap.querySelectorAll('[data-qsection]');var visibleCount=0;for(var i=0;i<sections.length;i++){var el=sections[i];var section=el.getAttribute('data-qsection');var title=el.getAttribute('data-qtitle')||'';var showByTab=(filter==='all')||(filter==='story'&&section==='story')||(filter==='daily'&&section==='daily')||(filter==='done'&&section==='done')||section==='turnin';var showBySearch=!query||!title||title.indexOf(query)>=0;var isHeader=el.classList.contains('quest-section-hdr');if(isHeader){var hasVisible=false;var next=el.nextElementSibling;while(next&&next.getAttribute('data-qsection')===section&&!next.classList.contains('quest-section-hdr')){var nextTitle=next.getAttribute('data-qtitle')||'';var nextSearch=!query||!nextTitle||nextTitle.indexOf(query)>=0;if(showByTab&&nextSearch){hasVisible=true;break;}
next=next.nextElementSibling;}
el.style.display=hasVisible?'':'none';}else{var show=showByTab&&showBySearch;el.style.display=show?'':'none';if(show&&section!=='turnin')visibleCount++;}}
var emptyEl=wrap.querySelector('.quest-empty-filter');if(emptyEl){var totalQ=wrap.querySelectorAll('.quest-card').length;emptyEl.style.display=(totalQ>0&&visibleCount===0)?'':'none';}}
function _questSectionHdr(icon,label){var el=document.createElement('div');el.className='quest-section-hdr';el.innerHTML='<span class="quest-section-icon">'+icon+'</span>'
+'<span class="quest-section-label">'+label+'</span>';return el;}
function _renderQCard(q,isDaily){var card=document.createElement('div');card.className='quest-card'+(q.ready?' quest-card--ready':'');card.setAttribute('data-element','quest-card');card.onclick=function(){doAction(q.cb);};var hdr=document.createElement('div');hdr.className='quest-card-header';var npcIcon=q.npc_icon||'\u2694\ufe0f';var catBadge='';if(q.cat==='daily'){catBadge='<span class="quest-cat-badge quest-cat--daily">DI\u00c1RIA</span>';}else if(q.cat==='story'){catBadge='<span class="quest-cat-badge quest-cat--story">HIST\u00d3RIA</span>';}else if(q.cat==='side'){catBadge='<span class="quest-cat-badge quest-cat--side">SECUND\u00c1RIA</span>';}
hdr.innerHTML='<span class="quest-npc-icon">'+npcIcon+'</span>'
+'<span class="quest-title">'+vEsc(q.title)+'</span>'
+catBadge
+(q.ready?'<span class="quest-ready-badge">\u2705</span>':'');card.appendChild(hdr);if(q.chain){var chainEl=document.createElement('div');chainEl.className='quest-chain-badge';chainEl.textContent='Cap\u00edtulo '+q.chain.part+' de '+q.chain.total;card.appendChild(chainEl);}
if(q.obj){var objEl=document.createElement('div');objEl.className='quest-objective';objEl.innerHTML='<em>'+vEsc(q.obj)+'</em>';card.appendChild(objEl);}
if(q.npc){var npcEl=document.createElement('div');npcEl.className='quest-card-npc';npcEl.textContent=q.npc;card.appendChild(npcEl);}
return card;}
function renderQuestDetail(container,q){container.innerHTML='';var wrap=document.createElement('div');wrap.className='quest-detail';if(q.ready){var readyBanner=document.createElement('div');readyBanner.className='quest-ready-banner';readyBanner.textContent='✅ Pronta para entrega';wrap.appendChild(readyBanner);}if(q.chain){var chainEl=document.createElement('div');chainEl.className='quest-chain-indicator';chainEl.innerHTML='\ud83d\udd17 <span>Cap\u00edtulo '+q.chain.part+' de '+q.chain.total+'</span>';if(q.chain.next_title){chainEl.innerHTML+='<span class="quest-chain-next">\u2192 Pr\u00f3ximo: '+vEsc(q.chain.next_title)+'</span>';}
wrap.appendChild(chainEl);}
if(q.desc){var descEl=document.createElement('div');descEl.className='quest-detail-desc';descEl.textContent=q.desc;wrap.appendChild(descEl);}
if(q.obj&&q.status==='active'){var objBlock=document.createElement('div');objBlock.className='quest-detail-objective';if(q.ready){objBlock.innerHTML='<div class="quest-detail-obj-label">\ud83d\udcdc O que voc\u00ea sabe</div>'
+'<div class="quest-detail-obj-text"><em>A miss\u00e3o est\u00e1 cumprida. Resta apenas reportar o feito.</em></div>';}else{objBlock.innerHTML='<div class="quest-detail-obj-label">\ud83d\udcdc O que voc\u00ea sabe</div>'
+'<div class="quest-detail-obj-text"><em>'+vEsc(q.obj)+'</em></div>';}
wrap.appendChild(objBlock);}
if(q.objectives&&q.objectives.length>0){var hasCompleted=false;for(var ci=0;ci<q.objectives.length;ci++){if(q.objectives[ci].state==='done'){hasCompleted=true;break;}}
if(hasCompleted){var timeline=document.createElement('div');timeline.className='quest-timeline';var tlHdr=document.createElement('div');tlHdr.className='quest-timeline-header';tlHdr.textContent='\ud83d\udcd6 Sua Jornada At\u00e9 Aqui';timeline.appendChild(tlHdr);for(var i=0;i<q.objectives.length;i++){var o=q.objectives[i];if(o.state==='future')continue;var step=document.createElement('div');step.className='quest-step quest-step--'+o.state;var marker=o.state==='done'?'\u2705':'\u25b8';step.innerHTML='<span class="quest-step-marker">'+marker+'</span>'
+'<span class="quest-step-text"><em>'+vEsc(o.text)+'</em></span>';timeline.appendChild(step);}
wrap.appendChild(timeline);}}
if(q.hint){var hintEl=document.createElement('div');hintEl.className='quest-detail-hint';hintEl.innerHTML='\ud83d\udcd6 <em>'+vEsc(q.hint)+'</em>';wrap.appendChild(hintEl);}
if(q.npc){var npcBlock=document.createElement('div');npcBlock.className='quest-detail-npc';var npcIc=q.npc_icon||'\ud83d\udc64';npcBlock.innerHTML=npcIc+' '+vEsc(q.npc);wrap.appendChild(npcBlock);}
var rewBlock=document.createElement('div');rewBlock.className='quest-detail-rewards';rewBlock.innerHTML='<div class="quest-detail-rewards-label">\ud83d\udc8e Recompensas Prometidas</div>';var rewList=document.createElement('div');rewList.className='quest-detail-rewards-list';var _rewHtml='';if(q.xp)_rewHtml+='<span class="quest-reward-item">\u2728 '+q.xp+' XP</span>';if(q.gold)_rewHtml+='<span class="quest-reward-item">\ud83d\udcb0 '+q.gold+' Valdoritas</span>';if(q.items&&q.items.length>0){for(var ii=0;ii<q.items.length;ii++){_rewHtml+='<span class="quest-reward-item">\ud83c\udf81 '+vEsc(q.items[ii])+'</span>';}}
rewList.innerHTML=_rewHtml;rewBlock.appendChild(rewList);wrap.appendChild(rewBlock);
container.appendChild(wrap);}
function renderQuestTurnin(container,data){container.innerHTML='';var wrap=document.createElement('div');wrap.className='quest-turnin';if(data.npc){var npcEl=document.createElement('div');npcEl.className='quest-turnin-npc';npcEl.innerHTML='\ud83d\udc64 <b>'+vEsc(data.npc)+'</b>';wrap.appendChild(npcEl);}
if(data.dialogue){var dlg=document.createElement('div');dlg.className='quest-turnin-dialogue';dlg.innerHTML='\ud83d\udcac <em>\u201c'+vEsc(data.dialogue)+'\u201d</em>';wrap.appendChild(dlg);}
if(data.quests&&data.quests.length>0){var qList=document.createElement('div');qList.className='quest-turnin-list';for(var i=0;i<data.quests.length;i++){var qItem=document.createElement('div');qItem.className='quest-turnin-item';qItem.style.animationDelay=(i*0.15)+'s';qItem.innerHTML='\u2705 <b>'+vEsc(data.quests[i].title)+'</b>';if(data.quests[i].narrative){qItem.innerHTML+='<div class="quest-turnin-narrative">'+_safeQ(data.quests[i].narrative)+'</div>';}
qList.appendChild(qItem);}
wrap.appendChild(qList);}
var rewBlock=document.createElement('div');rewBlock.className='quest-turnin-rewards';rewBlock.innerHTML='<div class="quest-turnin-rewards-label">\ud83d\udc8e Recompensas</div>';var rewItems=document.createElement('div');rewItems.className='quest-turnin-rewards-grid';var delay=(data.quests?data.quests.length:0)*0.15+0.3;if(data.xp){var xpEl=document.createElement('div');xpEl.className='quest-turnin-reward-item quest-turnin-reveal';xpEl.style.animationDelay=delay+'s';xpEl.innerHTML='<span class="quest-turnin-reward-icon">\u2728</span>'
+'<span class="quest-turnin-reward-val">+'+data.xp+'</span>'
+'<span class="quest-turnin-reward-lbl">XP</span>';rewItems.appendChild(xpEl);delay+=0.2;}
if(data.gold){var goldEl=document.createElement('div');goldEl.className='quest-turnin-reward-item quest-turnin-reveal';goldEl.style.animationDelay=delay+'s';goldEl.innerHTML='<span class="quest-turnin-reward-icon">\ud83d\udcb0</span>'
+'<span class="quest-turnin-reward-val">+'+data.gold+'</span>'
+'<span class="quest-turnin-reward-lbl">GP</span>';rewItems.appendChild(goldEl);delay+=0.2;}
if(data.items&&data.items.length>0){for(var ii=0;ii<data.items.length;ii++){var itemEl=document.createElement('div');itemEl.className='quest-turnin-reward-item quest-turnin-reveal';itemEl.style.animationDelay=delay+'s';itemEl.innerHTML='<span class="quest-turnin-reward-icon">\ud83c\udf81</span>'
+'<span class="quest-turnin-reward-val">'+vEsc(data.items[ii])+'</span>';rewItems.appendChild(itemEl);delay+=0.2;}}
rewBlock.appendChild(rewItems);wrap.appendChild(rewBlock);if(data.leveled){var lvl=document.createElement('div');lvl.className='quest-turnin-levelup quest-turnin-reveal';lvl.style.animationDelay=(delay+0.3)+'s';lvl.innerHTML='\ud83c\udf89 <b>LEVEL UP!</b> N\u00edvel '+data.level;wrap.appendChild(lvl);}
if(data.current_gold!==undefined){var goldLine=document.createElement('div');goldLine.className='quest-turnin-gold';goldLine.innerHTML='\ud83d\udcb0 <b>Seu Ouro:</b> '+data.current_gold+' <span class="vi vi-coin sm"><\/span>';wrap.appendChild(goldLine);}
container.appendChild(wrap);}
function renderQuestAbandon(container,data){container.innerHTML='';var wrap=document.createElement('div');wrap.className='quest-abandon';var iconEl=document.createElement('div');iconEl.className='quest-abandon-icon';iconEl.textContent='\u26a0\ufe0f';wrap.appendChild(iconEl);var titleEl=document.createElement('div');titleEl.className='quest-abandon-title';titleEl.textContent='Abandonar Miss\u00e3o?';wrap.appendChild(titleEl);var nameEl=document.createElement('div');nameEl.className='quest-abandon-name';nameEl.innerHTML='\ud83d\udcdc '+vEsc(data.title);wrap.appendChild(nameEl);var warnEl=document.createElement('div');warnEl.className='quest-abandon-warn';warnEl.textContent=data.is_daily?'Ao desistir, tudo que foi feito se perder\u00e1. Tarefas di\u00e1rias abandonadas contam para o limite do dia.':'Ao desistir, voc\u00ea perder\u00e1 tudo que conquistou nesta jornada. Poder\u00e1 retom\u00e1-la mais tarde.';wrap.appendChild(warnEl);container.appendChild(wrap);}
function renderQuestTracker(container,data){if(!data.quests||data.quests.length===0)return;var wrap=document.createElement('div');wrap.className='quest-tracker';wrap.innerHTML='<div class="quest-tracker-hdr">\ud83d\udcdc Missões</div>';for(var i=0;i<data.quests.length;i++){var q=data.quests[i];var row=document.createElement('div');row.className='quest-tracker-row'+(q.ready?' quest-tracker-row--ready':'');row.onclick=(function(cb){return function(){doAction(cb);};})(q.cb);var statusText=q.ready?'Conclu\u00edda':(q.obj||'...');row.innerHTML='<span class="quest-tracker-title">'+vEsc(q.title)+'</span>'
+'<span class="quest-tracker-status">'+(q.ready?'\u2705':'\u25b8')+'</span>';wrap.appendChild(row);}
var viewAll=document.createElement('div');viewAll.className='quest-tracker-view-all';viewAll.textContent='Ver todas ▸';viewAll.onclick=function(){doAction('action_quests');};wrap.appendChild(viewAll);var firstBlock=container.querySelector('.text-block, .v-bar-row');if(firstBlock&&firstBlock.nextSibling){container.insertBefore(wrap,firstBlock.nextSibling.nextSibling||null);}else{container.appendChild(wrap);}}
function _safeQ(text){if(!text)return'';var s=vEsc(text);s=s.replace(/&lt;b&gt;/g,'<b>').replace(/&lt;\/b&gt;/g,'</b>');s=s.replace(/&lt;i&gt;/g,'<i>').replace(/&lt;\/i&gt;/g,'</i>');return s;}