var S={token:'',apiBase:'',uid:0,currentScreen:null,transitioning:false,lastActionTime:0,screenVersion:0,};var SESSION_KEY='valdoria_session';function _saveSession(){try{localStorage.setItem(SESSION_KEY,JSON.stringify({token:S.token,apiBase:S.apiBase,uid:S.uid,charId:S.charId,ts:Date.now(),}));}catch(e){}}
function _restoreSession(){try{var raw=localStorage.getItem(SESSION_KEY);if(!raw)return false;var d=JSON.parse(raw);if(Date.now()-d.ts>30*60*1000)return false;if(S.charId&&d.charId&&S.charId!==d.charId){console.warn('[GAME] Stored session is for different character:',d.charId,'vs',S.charId);localStorage.removeItem(SESSION_KEY);return false;}
if(!S.token&&d.token)S.token=d.token;if(!S.apiBase&&d.apiBase)S.apiBase=d.apiBase;if(!S.uid&&d.uid)S.uid=d.uid;if(!S.charId&&d.charId)S.charId=d.charId;return true;}catch(e){return false;}}
var DEBOUNCE_MS=200;var RETRY_MAX=2;var RETRY_BASE_MS=1000;var FETCH_TIMEOUT_MS=12000;var HEALTH_TIMEOUT_MS=3000;var HEALTH_RETRIES=2;var HEALTH_RETRY_MS=1000;var LOADING_TIMEOUT_MS=15000;var MIN_LOADING_MS=window.VALDORIA_MIN_LOAD_MS||5000;var SCREEN_CACHE_KEY='valdoria_game_screen';var SCREEN_CACHE_TTL=1800000;var _loadingTimeoutId=null;function _clog(msg){if(window.ValdoriaErrors)ValdoriaErrors.log(msg);}
async function init(){console.debug('[GAME] init() started');console.debug('[GAME] URL:',window.location.href);if(typeof initImmersive==='function')initImmersive();var _spaParams=window.__spaRouteParams||{};const params=new URLSearchParams(window.location.search);S.token=_spaParams.token||params.get('token')||'';S.apiBase=(_spaParams.api||params.get('api')||window.location.origin||'').replace(/\/$/,'');S.uid=parseInt(_spaParams.uid||params.get('uid')||'0',10);S.charId=_spaParams.char||params.get('char')||'';if(S.charId){SESSION_KEY='valdoria_session_'+S.charId;SCREEN_CACHE_KEY='valdoria_game_screen_'+S.charId;try{localStorage.removeItem('valdoria_session');localStorage.removeItem('valdoria_game_screen');}catch(e){}}
if(S.apiBase&&window.ApiDiscovery){ApiDiscovery.init(S.apiBase,function(newUrl){S.apiBase=newUrl;if(window.ValdoriaErrors&&ValdoriaErrors.updateApiBase){ValdoriaErrors.updateApiBase(newUrl);}});}
if(!S.token||!S.uid||!S.apiBase)_restoreSession();if(S.token&&S.uid&&S.apiBase)_saveSession();console.debug('[GAME] Params: token='+(S.token?S.token.substring(0,8)+'...':'MISSING')+' api='+(S.apiBase||'MISSING')+' uid='+S.uid+' char='+(S.charId||'none'));if(typeof initParticles==='function')initParticles();if(window.ValdoriaErrors){ValdoriaErrors.init({appName:'GAME',apiBase:S.apiBase,token:S.token,uid:S.uid,getScreenId:()=>S.currentScreen?S.currentScreen.screen_id||'':'',onRetry:async()=>{showLoading(true);_clog('RETRY health check...');const ok=await checkHealth();if(!ok){_clog('RETRY health FAILED');hideLoading();showError('⚠️ Servidor indisponível no momento. Estamos tentando reconectar!');return;}
_clog('RETRY health OK → loading state');if(S.currentScreen){fetchState(false);}else{startGame();}},});}
if(!S.token||!S.uid||!S.apiBase){console.error('[GAME] Missing required params - token:',!!S.token,'uid:',S.uid,'apiBase:',!!S.apiBase);showError('🔐 Parâmetros de sessão inválidos. Feche e selecione seu personagem novamente.');return;}
if(window.Telegram&&Telegram.WebApp){console.debug('[GAME] Telegram WebApp detected, version:',Telegram.WebApp.version||'unknown');Telegram.WebApp.ready();Telegram.WebApp.expand();try{Telegram.WebApp.disableVerticalSwipes();}catch(e){}
try{Telegram.WebApp.setHeaderColor('#2a2420');Telegram.WebApp.setBackgroundColor('#2a2420');}catch(e){}
Telegram.WebApp.BackButton.show();Telegram.WebApp.BackButton.onClick(()=>{if(window.vPopup&&vPopup.isOpen()){vPopup.hide();return;}
if(window.ValdoriaExitConfirm){ValdoriaExitConfirm.show();}else{_closeGameHub();}});window.__valdoriaExitAction=function(){_closeGameHub();};}else{console.warn('[GAME] Telegram WebApp NOT detected - running outside Telegram?');}
history.replaceState({screen:'init'},'');history.pushState({screen:'game'},'');window.addEventListener('popstate',(e)=>{history.pushState({screen:'game'},'');if(window.vPopup&&vPopup.isOpen()){vPopup.hide();return;}
if(window.ValdoriaExitConfirm){ValdoriaExitConfirm.show();}else{_closeGameHub();}});document.addEventListener('visibilitychange',()=>{if(document.visibilityState!=='visible')return;const errOverlay=document.getElementById('v-err-overlay');if(errOverlay&&errOverlay.style.display!=='none'){_clog('VISIBILITY → visible with error overlay, retrying...');const retryBtn=document.getElementById('v-err-retry');if(retryBtn&&retryBtn.onclick){setTimeout(()=>retryBtn.onclick(),500);}
return;}
if(S.currentScreen){fetchState(true);}});window.addEventListener('pageshow',e=>{if(e.persisted&&S.currentScreen)fetchState(true);});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'){_saveSession();if(S.currentScreen)cacheScreen(S.currentScreen);}});window.addEventListener('offline',()=>{_clog('NETWORK → OFFLINE');console.warn('[GAME] Network went offline');});window.addEventListener('online',()=>{_clog('NETWORK → ONLINE');console.debug('[GAME] Network back online');const errOverlay=document.getElementById('v-err-overlay');const errMsg=document.getElementById('v-err-msg');if(errOverlay&&errOverlay.style.display!=='none'&&errMsg){const msg=errMsg.textContent||'';if(msg.includes('Sem conexão')||msg.includes('indisponível')){_clog('NETWORK → auto-retry after coming online');if(typeof showToast==='function')showToast('Conexão restaurada, reconectando...');setTimeout(()=>{const retryBtn=document.getElementById('v-err-retry');if(retryBtn&&retryBtn.onclick)retryBtn.onclick();},1500);}}});if(typeof _initConnectionStatus==="function")_initConnectionStatus();if(typeof _initDebugConsole==="function")_initDebugConsole();_clog('INIT health check → '+S.apiBase+'/api/game/health');console.debug('[GAME] Starting health check to:',S.apiBase+'/api/game/health');showLoading();const healthy=await _waitForHealthy();if(!healthy)return;window.addEventListener('session-reopened',function(e){console.debug('[GAME] Session reopened, reloading screen');var data=e.detail;if(data&&data.text){if(data.sv!==undefined)S.screenVersion=data.sv;renderScreen(data);}else if(data&&data.transition){handleTransition(data.transition);}else{startGame();}});const isReturn=params.get('return')==='game';console.debug('[GAME] Route: isReturn='+isReturn+' hasCharId='+!!S.charId);try{if(isReturn){console.debug('[GAME] -> returnFromWebApp()');await returnFromWebApp();}else if(S.charId){console.debug('[GAME] -> startGame() with charId='+S.charId);await startGame();}else{console.debug('[GAME] -> showCharacterSelect()');await showCharacterSelect();}}catch(routeError){console.error('[GAME] Route error:',routeError);hideLoading();showError('⚠️ Erro ao carregar o jogo. Feche e tente novamente.');}
if(window.SessionHeartbeat){SessionHeartbeat.init({apiBase:S.apiBase,token:S.token,uid:S.uid});}}
async function checkHealth(){const url=`${S.apiBase}/api/game/health`;for(let attempt=0;attempt<=HEALTH_RETRIES;attempt++){if(attempt>0){console.debug('[GAME] Health retry',attempt,'/',HEALTH_RETRIES,'- waiting',HEALTH_RETRY_MS+'ms');await sleep(HEALTH_RETRY_MS);}
_clog(`HEALTH attempt ${attempt}/${HEALTH_RETRIES}`);console.debug('[GAME] checkHealth() attempt',attempt,'url:',url);try{const controller=new AbortController();const tid=setTimeout(()=>controller.abort(),HEALTH_TIMEOUT_MS);const t0=Date.now();const resp=await fetch(url,{method:'GET',headers:{},signal:controller.signal,});clearTimeout(tid);const elapsed=Date.now()-t0;_clog(`HEALTH response: ${resp.status} ${resp.statusText} (${elapsed}ms)`);console.debug('[GAME] Health response status:',resp.status);if(!resp.ok){_clog(`HEALTH FAIL: HTTP ${resp.status} ${resp.statusText}`);console.error('[GAME] Health check failed:',resp.status,resp.statusText);continue;}
const data=await resp.json();_clog(`HEALTH data: ${JSON.stringify(data)}`);console.debug('[GAME] Health data:',JSON.stringify(data));if(data.status==='ok'&&data.engine){if(typeof _updateConnectionStatus==='function')_updateConnectionStatus('connected');if(data.api&&S.apiBase&&data.api!==S.apiBase){_clog(`HEALTH: tunnel URL changed! ${S.apiBase} -> ${data.api}`);console.debug('[GAME] Tunnel URL changed, updating apiBase in memory');S.apiBase=data.api;if(window.ApiDiscovery)ApiDiscovery.updateBase(data.api);if(window.ValdoriaErrors&&ValdoriaErrors.updateApiBase)ValdoriaErrors.updateApiBase(data.api);}
return true;}
_clog('HEALTH engine not ready: '+JSON.stringify(data));console.warn('[GAME] Engine not ready:',data);continue;}catch(e){_clog(`HEALTH ERROR: ${e.name}: ${e.message}`);console.error('[GAME] Health check error:',e.name,e.message);}}
_clog(`HEALTH EXHAUSTED after ${HEALTH_RETRIES + 1} attempts`);console.error('[GAME] Health check failed after',HEALTH_RETRIES+1,'attempts');return false;}
var API_URL_DISCOVERY=window.__spaRouteName?'api-url.json':'../api-url.json';async function _discoverApiUrl(){try{var _acDisc=new AbortController();var _tidDisc=setTimeout(function(){_acDisc.abort();},4000);const resp=await fetch(API_URL_DISCOVERY+'?t='+Date.now(),{cache:'no-store',signal:_acDisc.signal,});clearTimeout(_tidDisc);if(!resp.ok)return null;const data=await resp.json();const url=(data.url||'').replace(/\/$/,'');if(url&&url!==S.apiBase){_clog('DISCOVERY: found new API URL: '+url);console.debug('[GAME] Discovered new API URL:',url);return url;}}catch(e){_clog('DISCOVERY failed: '+(e.message||e));}
return null;}
var HEALTH_POLL_INTERVAL=2000;var HEALTH_POLL_MAX=3;async function _waitForHealthy(){let ok=await checkHealth();if(ok)return true;_clog('INIT health failed — trying discovery before polling');console.debug('[GAME] Health failed, trying API URL discovery first...');const newUrl=await _discoverApiUrl();if(newUrl){S.apiBase=newUrl;if(window.ValdoriaErrors&&ValdoriaErrors.updateApiBase)ValdoriaErrors.updateApiBase(newUrl);if(window.ApiDiscovery)ApiDiscovery.updateBase(newUrl);await sleep(2000);ok=await checkHealth();if(ok){_clog('DISCOVERY: health OK with new URL');console.debug('[GAME] Discovery succeeded, health OK with new URL:',newUrl);return true;}
_clog('DISCOVERY: new URL found but health still failing');}
_clog('INIT polling (server may be restarting)...');console.debug('[GAME] Polling silently (server may be restarting)...');for(let i=1;i<=HEALTH_POLL_MAX;i++){await sleep(HEALTH_POLL_INTERVAL);ok=await checkHealth();if(ok){_clog(`INIT health poll ${i} OK`);return true;}
_clog(`INIT health poll ${i}/${HEALTH_POLL_MAX} failed`);}
_clog('INIT all health attempts exhausted — showing error overlay');console.error('[GAME] All health attempts failed — showing error overlay (not auto-closing)');hideLoading();showError('\u26a0\ufe0f Servidor indispon\u00edvel no momento. Estamos tentando reconectar!');return false;}
function _sendDataReconnect(){_clog('sendData reconnect — bot will send fresh menu');const tg=window.Telegram&&window.Telegram.WebApp;const doClose=()=>{if(tg&&tg.close)tg.close();else window.close();};if(S.apiBase&&S.token&&S.uid){fetch(S.apiBase+'/api/game/close',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:S.token,user_id:S.uid}),}).then(()=>{_clog('Close via API OK');doClose();}).catch(()=>{_clog('Close via API failed, using sendData');_sendDataFallback(tg,'webapp_reconnect');setTimeout(doClose,1000);});return false;}
if(tg&&tg.sendData){_sendDataFallback(tg,'webapp_reconnect');setTimeout(doClose,1000);return false;}
hideLoading();showError('⚠️ Servidor indisponível. Feche este mini app e toque em "Retomar Jornada" novamente.');return false;}
function _sendDataFallback(tg,action){if(tg&&tg.sendData){try{tg.sendData(JSON.stringify({action,webapp:'GAME'}));}
catch(e){_clog('sendData failed: '+e.message);}}}
async function apiCall(endpoint,body={},retries=RETRY_MAX){const url=`${S.apiBase}${endpoint}`;_clog(`API → ${endpoint}`);console.debug('[GAME] apiCall:',endpoint,'body:',JSON.stringify(body).substring(0,200));const headers={'Content-Type':'application/json','Authorization':`Bearer ${S.token}`,};if(window.Telegram?.WebApp?.initData){headers['X-Telegram-Init-Data']=Telegram.WebApp.initData;}
if(endpoint.includes('/action')||endpoint.includes('/text')||endpoint.includes('/transition')){headers['X-Idempotency-Key']=crypto.randomUUID();}
for(let attempt=0;attempt<=retries;attempt++){try{if(attempt>0){_clog(`API ${endpoint} retry ${attempt}/${retries}`);console.debug('[GAME] apiCall retry',attempt,'/',retries,'for',endpoint);}
const controller=new AbortController();const tid=setTimeout(()=>controller.abort(),FETCH_TIMEOUT_MS);const t0=Date.now();const resp=await fetch(url,{method:endpoint.includes('/image/')?'GET':'POST',headers,body:endpoint.includes('/image/')?undefined:JSON.stringify({user_id:S.uid,...body}),signal:controller.signal,});clearTimeout(tid);const elapsed=Date.now()-t0;console.debug('[GAME] apiCall response:',endpoint,'status:',resp.status,`(${elapsed}ms)`);if(resp.status===429){_clog(`API ${endpoint} → 429 RATE LIMITED`);console.warn('[GAME] Rate limited on',endpoint,'- waiting 2s');if(typeof showToast==='function')showToast('\u23F3 Calma, aventureiro(a)! Aguarde um momento...',2000);haptic('warning');await sleep(2000);continue;}
if(resp.status===401||resp.status===403){const reason=resp.status===401?'session_expired':'invalid_init_data';_clog(`API ${endpoint} \u2192 ${resp.status} ${reason.toUpperCase()}`);console.error('[GAME]',reason,`(${resp.status}) for`,endpoint);const tg=window.Telegram&&Telegram.WebApp;const doClose=()=>{if(tg&&tg.close)tg.close();else window.close();};if(S.apiBase&&S.token&&S.uid){fetch(S.apiBase+'/api/game/close',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:S.token,user_id:S.uid}),}).then(()=>doClose()).catch(()=>{_sendDataFallback(tg,'webapp_error_close');setTimeout(doClose,1000);});return null;}
if(tg&&tg.sendData){_sendDataFallback(tg,'webapp_error_close');setTimeout(doClose,1000);return null;}
showError('\ud83d\udd10 Sess\u00e3o expirada. Feche e selecione seu personagem novamente.');return null;}
let data;try{data=await resp.json();}catch(jsonErr){_clog(`API ${endpoint} → JSON PARSE ERROR: ${jsonErr.message}`);console.error('[GAME] Failed to parse JSON response for',endpoint,':',jsonErr);const rawText=await resp.text().catch(()=>'(could not read body)');_clog(`API ${endpoint} → raw body: ${rawText.substring(0, 150)}`);console.error('[GAME] Raw response body:',rawText.substring(0,500));if(attempt===retries){showError('⚠️ Resposta inesperada do servidor. Tente novamente.');return null;}
continue;}
if(resp.ok){if(typeof _trackApiPerf==='function')_trackApiPerf(endpoint,elapsed);_clog(`API ${endpoint} → OK (${elapsed}ms)`);console.debug('[GAME] apiCall OK:',endpoint,'keys:',Object.keys(data).join(','),'text_len:',(data.text||'').length,'buttons:',(data.buttons||[]).length,'transition:',data.transition?JSON.stringify(data.transition).substring(0,80):'none');return data;}
_clog(`API ${endpoint} → ERROR ${resp.status} (${elapsed}ms): ${JSON.stringify(data).substring(0, 200)}`);console.error('[GAME] API error:',resp.status,JSON.stringify(data).substring(0,300));if(attempt===retries){const msg=data&&data.error==='player_not_found'?'Personagem não encontrado. Feche e selecione novamente.':'Erro no servidor. Tente novamente.';showError(msg);return null;}}catch(e){const isTimeout=e.name==='AbortError';const isCorsBlock=e.name==='TypeError';_clog(`API ${endpoint} → ${isTimeout ? 'TIMEOUT ' + FETCH_TIMEOUT_MS + 'ms' : e.name + ': ' + e.message}`);console.error('[GAME] fetch error on',endpoint,':',isTimeout?'TIMEOUT after '+FETCH_TIMEOUT_MS+'ms':e.name+': '+e.message);if(isCorsBlock){_clog('API: tunnel dead mid-session — trying discovery');const newUrl=await _discoverApiUrl();if(newUrl){S.apiBase=newUrl;if(window.ValdoriaErrors&&ValdoriaErrors.updateApiBase)ValdoriaErrors.updateApiBase(newUrl);_clog('API: recovered with new URL: '+newUrl);continue;}
_clog('API: discovery failed — sendData reconnect');if(typeof _trackApiLatency==='function')_trackApiLatency(0,false);_sendDataReconnect();return null;}
if(attempt===retries){const cached=loadCachedScreen();if(cached&&!S.currentScreen){renderScreen(cached);showToast('Reconectando...');}
if(typeof _trackApiLatency==='function')_trackApiLatency(0,false);showError(isTimeout?(navigator.onLine?'O servidor demorou demais para responder. Pode estar sobrecarregado.':'Sem conexão com a internet. Verifique seu Wi-Fi ou dados móveis.'):(navigator.onLine?'Não foi possível conectar. Verifique sua internet e tente novamente.':'Sem conexão. Verifique sua internet.'));return null;}
const backoff=RETRY_BASE_MS*Math.pow(2,attempt);const jitter=Math.random()*500;console.debug('[GAME] Backoff:',Math.round(backoff+jitter)+'ms before retry',(attempt+1));await sleep(backoff+jitter);}}
return null;}
async function startGame(){console.debug('[GAME] startGame() called, charId:',S.charId||'none');showLoading();const startBody=S.charId?{char_id:S.charId}:{};const tgPlatform=(window.Telegram&&Telegram.WebApp&&Telegram.WebApp.platform)||'';if(tgPlatform)startBody.platform=tgPlatform;const did=(window.DeviceId&&DeviceId.get)?DeviceId.get():'';if(did)startBody.device_id=did;const data=await apiCall('/api/game/start',startBody);await hideLoadingWithDelay();if(data&&!data.error){if(data.sv!==undefined)S.screenVersion=data.sv;if(data.transition&&!data.text){console.debug('[GAME] startGame() got transition:',JSON.stringify(data.transition).substring(0,100));handleTransition(data.transition);}else{console.debug('[GAME] startGame() success, rendering screen');renderScreen(data);}}else if(data&&data.error){console.error('[GAME] startGame() server error:',data.error);if(data.error==='invalid_session'){showError('🔐 Sessão expirada. Feche e selecione seu personagem novamente.');}}else{console.error('[GAME] startGame() returned null/empty data');showError('🌐 Não foi possível conectar. Verifique sua internet e tente novamente.');}}
async function fetchState(silent){console.debug('[GAME] fetchState() silent:',silent);if(!silent)showLoading();const data=await apiCall('/api/game/state');if(!silent)await hideLoadingWithDelay();if(data&&!data.error){if(data.sv!==undefined)S.screenVersion=data.sv;if(data.transition&&!data.text){console.debug('[GAME] fetchState() got transition:',JSON.stringify(data.transition).substring(0,100));handleTransition(data.transition);}else{if(silent&&S.currentScreen&&data.text===S.currentScreen.text&&data.screen_id===S.currentScreen.screen_id){console.debug('[GAME] fetchState() silent — screen unchanged, skip re-render');return;}
console.debug('[GAME] fetchState() rendering screen, text_len:',(data.text||'').length);renderScreen(data);}}else if(data&&data.error){console.error('[GAME] fetchState() server error:',data.error);}else if(!silent&&!data){console.error('[GAME] fetchState() returned null - apiCall already showed error');}}
function _showGamePopup(data){var popup=data.popup||{};var bodyHtml='';if(data.text){bodyHtml+='<div style="font-size:var(--v-font-body);color:var(--v-text);line-height:1.6;margin-bottom:var(--v-space-md);">'
+data.text+'</div>';}
var actionsHtml='';if(data.buttons&&data.buttons.length>0){for(var r=0;r<data.buttons.length;r++){var row=data.buttons[r];if(!row||row.length===0)continue;if(row.length>=2){actionsHtml+='<div class="v-popup-btn-row">';for(var b=0;b<row.length;b++){actionsHtml+='<button class="v-popup-btn" data-action="'+(row[b].cb||'')+'">'
+(row[b].text||'')+'</button>';}
actionsHtml+='</div>';}else{actionsHtml+='<button class="v-popup-btn" data-action="'+(row[0].cb||'')+'">'
+(row[0].text||'')+'</button>';}}}
actionsHtml+='<button class="v-popup-btn v-popup-btn--cancel" data-action="cancel">🏠 Voltar</button>';vPopup.show({header:popup.title||'',headerClass:popup.headerClass||'',body:bodyHtml,actions:actionsHtml});}
async function _closeGameHub(){window.__valdoria_close_sent=true;if(window.SessionHeartbeat)SessionHeartbeat.stop();try{const controller=new AbortController();const tid=setTimeout(()=>controller.abort(),2000);await fetch(S.apiBase+'/api/game/close',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+S.token},body:JSON.stringify({user_id:S.uid}),signal:controller.signal,}).catch(e=>console.warn('[GAME] cleanup:',e));clearTimeout(tid);}catch(e){}
valdoriaSpaClose();}
async function doAction(callbackData){if(S.transitioning)return;if(callbackData==='action_toggle_footer')return;if(window.actionGuard&&!actionGuard.acquire())return;const now=Date.now();if(now-S.lastActionTime<DEBOUNCE_MS){if(window.actionGuard)actionGuard.release();return;}
S.lastActionTime=now;haptic('light');const locCtx=(typeof _detectLocationTransition==='function')?_detectLocationTransition(callbackData):null;if(locCtx)showLocationTransition(locCtx);const t0=Date.now();const data=await apiCall('/api/game/action',{cb:callbackData,sv:S.screenVersion});if(!data){hideLocationTransition();if(window.actionGuard)actionGuard.release();return;}
if(data.sv!==undefined)S.screenVersion=data.sv;if(data.error==='no_response'){hideLocationTransition();if(window.actionGuard)actionGuard.release();if(typeof showToast==='function')showToast('Ação não processada. Tente novamente.');return;}
if(data.error==='action_rejected'){hideLocationTransition();if(window.actionGuard)actionGuard.release();console.debug('[GAME] Action rejected by server:',data.reason);return;}
if(data.close){hideLocationTransition();if(window.actionGuard)actionGuard.release();valdoriaSpaClose();return;}
if(data.char_select){hideLocationTransition();if(window.actionGuard)actionGuard.release();if(typeof showCharacterSelect==='function')showCharacterSelect();return;}
if(data.travel_prep){hideLocationTransition();if(window.actionGuard)actionGuard.release();if(typeof showTravelPrep==='function')showTravelPrep(data.travel_prep);return;}
if(data.quest_diary&&typeof showQuestDiaryPopup==='function'){hideLocationTransition();if(window.actionGuard)actionGuard.release();showQuestDiaryPopup(data.quest_diary);return;}
if(data.quest_detail&&typeof showQuestPopup==='function'){hideLocationTransition();if(window.actionGuard)actionGuard.release();showQuestPopup(data.quest_detail);return;}
if(data.quest_board&&typeof showQuestBoard==='function'){hideLocationTransition();if(window.actionGuard)actionGuard.release();showQuestBoard(data.quest_board);return;}
if(data.popup&&window.vPopup){hideLocationTransition();if(window.actionGuard)actionGuard.release();_showGamePopup(data);return;}
if(!data.text&&!data.screen_id&&!data.transition&&!data.error){console.warn('[GAME] Empty response from action — forcing hub reload to prevent trap');if(window.actionGuard)actionGuard.release();hideLocationTransition();returnFromWebApp();return;}
if(data.transition&&!data.text){const elapsed=Date.now()-t0;const remaining=locCtx?Math.max(0,getLocTransitionMs()-elapsed):0;if(remaining>0)await sleep(remaining);hideLocationTransition();if(window.actionGuard)actionGuard.release();handleTransition(data.transition);return;}
if(data.toast)showToast(data.toast);if(data.alert){const alertDur=(typeof calcReadTime==='function')?calcReadTime(data.alert,'toast-warn'):3000;showToast(data.alert,alertDur);}
if(data.timer){showTimerOverlay(data.timer);}
if(data.inn_animation&&typeof playInnAnimation==='function'){hideLocationTransition();const result=await new Promise(resolve=>playInnAnimation(data.inn_animation,resolve));if(!result?.skipped&&data.inn_animation.dream_insight){try{const diRes=await apiCall('/api/game/action',{cb:'inn_dream_insight'});if(diRes?.toast)showToast(diRes.toast);}catch(e){console.warn('[GAME] dream insight action failed',e);}}
if(data.text||data.buttons){renderScreen(data);}
return;}
if(data.text||data.buttons){const elapsed=Date.now()-t0;const remaining=locCtx?Math.max(0,getLocTransitionMs()-elapsed):0;if(remaining>0)await sleep(remaining);hideLocationTransition();const isBack=/^(action_universal_back|city_back|back|voltar)/.test(callbackData);animateScreenTransition(()=>renderScreen(data),isBack?'back':'forward');if(data.transition&&data.text){console.debug('[GAME] Screen has WebApp link:',data.transition.to);}}else{hideLocationTransition();}
if(window.actionGuard)actionGuard.release();}
async function doText(text){if(S.transitioning||!text.trim())return;S.lastActionTime=Date.now();haptic('light');const data=await apiCall('/api/game/text',{text:text.trim()});if(data&&!data.error){animateScreenTransition(()=>renderScreen(data));}}
function cacheScreen(screen){try{if(screen&&(screen.waiting_for_text||screen.timer))return;localStorage.setItem(SCREEN_CACHE_KEY,JSON.stringify({uid:S.uid,charId:S.charId||'',ts:Date.now(),screen,}));}catch(e){}}
function loadCachedScreen(){try{const raw=localStorage.getItem(SCREEN_CACHE_KEY);if(!raw)return null;const parsed=JSON.parse(raw);const{uid,ts,screen}=parsed;var charId=parsed.charId||'';if(uid!==S.uid||(S.charId&&charId&&S.charId!==charId)||Date.now()-ts>SCREEN_CACHE_TTL){localStorage.removeItem(SCREEN_CACHE_KEY);return null;}
if(typeof _trackCacheHit==='function')_trackCacheHit();return screen;}catch(e){return null;}}
function haptic(style){if(!window.vHaptic)return;if(style==='warning')vHaptic.warning();else if(style==='success')vHaptic.success();else if(style==='error')vHaptic.error();else vHaptic.impact(style||'light');}
function sleep(ms){return new Promise(resolve=>setTimeout(resolve,ms));}
var _logQueue=[];var _logFlushTimer=null;var _LOG_FLUSH_INTERVAL=2000;var _LOG_MAX_QUEUE=50;var _origLog=console.log.bind(console);var _origWarn=console.warn.bind(console);var _origError=console.error.bind(console);function _queueLog(level,args){const msg=Array.from(args).map(a=>typeof a==='object'?JSON.stringify(a).substring(0,200):String(a)).join(' ');if(!msg.includes('[GAME]'))return;_logQueue.push({level,msg:msg.substring(0,500)});if(_logQueue.length>=_LOG_MAX_QUEUE)_flushLogs();}
console.log=function(){_origLog.apply(console,arguments);_queueLog('info',arguments);};console.warn=function(){_origWarn.apply(console,arguments);_queueLog('warn',arguments);};console.error=function(){_origError.apply(console,arguments);_queueLog('error',arguments);};function _flushLogs(){if(!_logQueue.length||!S.apiBase)return;const entries=_logQueue.splice(0,_LOG_MAX_QUEUE);fetch(`${S.apiBase}/api/game/log`,{method:'POST',headers:{'Content-Type':'application/json',},body:JSON.stringify({entries}),}).catch(()=>{});}
_logFlushTimer=setInterval(_flushLogs,_LOG_FLUSH_INTERVAL);setInterval(function(){if(window.vPerf&&S.apiBase)vPerf.flush(S.apiBase,S.token);},10*60*1000);window.addEventListener('beforeunload',()=>{_flushLogs();if(window.vPerf&&S.apiBase){vPerf.flush(S.apiBase,S.token);}});if(!window.__spaRouteName){document.addEventListener('DOMContentLoaded',()=>{console.debug('[GAME] DOMContentLoaded fired, starting init...');init().catch(e=>{console.error('[GAME] init() CRASHED:',e.message);if(typeof showError==='function'){showError('Erro ao iniciar o jogo: '+e.message,e);}});});}
var _prefetchedStart=null;function _prefetchStart(charId){if(!charId||!S.apiBase||!S.token)return;var url=S.apiBase+'/api/game/start';var prefetchDid=(window.DeviceId&&DeviceId.get)?DeviceId.get():'';var body=JSON.stringify({user_id:S.uid,char_id:charId,device_id:prefetchDid});var _acLog=new AbortController();var _tidLog=setTimeout(function(){_acLog.abort();},8000);fetch(url,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+S.token},body:body,signal:_acLog.signal,}).then(function(r){clearTimeout(_tidLog);return r.json();}).then(function(data){if(data&&!data.error){_prefetchedStart={charId:charId,data:data,ts:Date.now()};}}).catch(function(){});}
var _connPill=null;var _connState='connected';var _connCollapseTimer=null;var _recentApiTimes=[];function _initConnectionStatus(){_connPill=document.createElement('div');_connPill.className='connection-status';_connPill.id='connection-status';_connPill.innerHTML='<span class="conn-dot"></span><span class="conn-label">Conectado</span>';document.body.appendChild(_connPill);_connPill.addEventListener('click',function(){if(_connState!=='connected')return;_connPill.classList.toggle('collapsed');if(!_connPill.classList.contains('collapsed')){_scheduleCollapse(3000);}});_scheduleCollapse(3000);window.addEventListener('offline',function(){_updateConnectionStatus('offline');});window.addEventListener('online',function(){_updateConnectionStatus('connected');});}
function _updateConnectionStatus(state){if(!_connPill)return;_connState=state;_connPill.classList.remove('offline','slow','collapsed');if(_connCollapseTimer){clearTimeout(_connCollapseTimer);_connCollapseTimer=null;}
var label=_connPill.querySelector('.conn-label');if(state==='offline'){_connPill.classList.add('offline');if(label)label.textContent='Sem conexão';}else if(state==='slow'){_connPill.classList.add('slow');if(label)label.textContent='Conexão lenta';}else{if(label)label.textContent='Conectado';_scheduleCollapse(3000);}}
function _scheduleCollapse(ms){if(_connCollapseTimer)clearTimeout(_connCollapseTimer);_connCollapseTimer=setTimeout(function(){if(_connPill&&_connState==='connected'){_connPill.classList.add('collapsed');}},ms);}
function _trackApiLatency(elapsedMs,success){_recentApiTimes.push({ms:elapsedMs,ok:success});if(_recentApiTimes.length>5)_recentApiTimes.shift();if(!success){_updateConnectionStatus('offline');return;}
var recent=_recentApiTimes.filter(function(x){return x.ok;});if(recent.length>=3){var avg=recent.reduce(function(s,x){return s+x.ms;},0)/recent.length;if(avg>3000){_updateConnectionStatus('slow');}
else if(_connState!=='connected'){_updateConnectionStatus('connected');}}else if(_connState==='offline'){_updateConnectionStatus('connected');}}
function _focusFirstAction(){requestAnimationFrame(function(){var btn=document.querySelector('#content .btn-hero, #content .btn-action, #bottom-panel .btn-action');if(btn&&typeof btn.focus==='function'){btn.focus({preventScroll:true});}});}
var _debugTapCount=0;var _debugTapTimer=null;function _initDebugConsole(){document.addEventListener('click',function(e){var target=e.target;if(!target||!target.classList)return;if(target.classList.contains('char-select-title')||target.classList.contains('loading-title')){_debugTapCount++;if(_debugTapTimer)clearTimeout(_debugTapTimer);_debugTapTimer=setTimeout(function(){_debugTapCount=0;},800);if(_debugTapCount>=3){_debugTapCount=0;_showDebugConsole();}}});}
function _showDebugConsole(){var existing=document.getElementById('debug-console');if(existing){existing.style.display=existing.style.display==='none'?'':'none';return;}
var div=document.createElement('div');div.id='debug-console';div.className='debug-console';div.style.display='';var closeBtn=document.createElement('button');closeBtn.className='debug-close';closeBtn.textContent='\u2715';closeBtn.onclick=function(){div.style.display='none';};div.appendChild(closeBtn);var info=[['Sess\u00e3o','Token: '+(S.token?S.token.substring(0,12)+'...':'N/A')],['API Base',S.apiBase||'N/A'],['User ID',S.uid||'N/A'],['Char ID',S.charId||'N/A'],['Screen ID',S.currentScreen?(S.currentScreen.screen_id||'N/A'):'N/A'],['Screen Version',S.screenVersion||0],['Cache',localStorage.getItem('valdoria_game_screen')?'Presente ('+Math.round(localStorage.getItem('valdoria_game_screen').length/1024)+'KB)':'Vazio'],['Font',(typeof getSelectedFont==='function'?getSelectedFont():'N/A')],['Immersive',_immersiveCollapsed?'Recolhido':'Expandido'],['Platform',(window.Telegram&&Telegram.WebApp?Telegram.WebApp.platform:'browser')||'unknown'],['TG Version',(window.Telegram&&Telegram.WebApp?Telegram.WebApp.version:'N/A')||'N/A'],['Viewport',window.innerWidth+'x'+window.innerHeight],['Perf',_perfMetrics?JSON.stringify(_perfMetrics):'N/A'],];for(var i=0;i<info.length;i++){var sec=document.createElement('div');sec.className='debug-section';sec.innerHTML='<span class="debug-label">'+info[i][0]+':</span> '+info[i][1];div.appendChild(sec);}
document.body.appendChild(div);}
var _perfMetrics={apiCalls:0,totalMs:0,avgMs:0,cacheHits:0,renders:0};function _trackApiPerf(endpoint,elapsedMs){_perfMetrics.apiCalls++;_perfMetrics.totalMs+=elapsedMs;_perfMetrics.avgMs=Math.round(_perfMetrics.totalMs/_perfMetrics.apiCalls);if(typeof _trackApiLatency==='function')_trackApiLatency(elapsedMs,true);if(window.vPerf)vPerf.recordApi(endpoint,elapsedMs,200);}
function _trackRender(){_perfMetrics.renders++;}
function _trackCacheHit(){_perfMetrics.cacheHits++;}