var _TIPS_NARRATIVE=['As muralhas de pedra se erguem enquanto os portões rangem ao abrir...','O som de bigornas e o aroma de pão fresco preenchem as ruas empedradas...','Guardas patrulham as ameias enquanto comerciantes montam suas barracas...','O vento traz murmúrios da taverna e risos de crianças brincando na praça...','Tochas acesas iluminam os brasões entalhados nos portais da cidade...','O sino do templo ecoa pela manhã, despertando a cidade de seu sono...','Mercadores ajustam suas bancas, exibindo relíquias de terras distantes...','O cheiro de cerveja e carne assada escapa pelas portas da estalagem...',];var _TIPS_MECHANICS=['⚔️ Dica: Rolagens de ataque 20 são acertos críticos — dano dobrado!','🛡️ Dica: Descansar na estalagem recupera todos os dados de vida.','💰 Dica: Venda itens que não usa no mercado da cidade.','📜 Dica: Converse com NPCs para descobrir quests escondidas.','🏰 Dica: A Guilda de Aventureiros oferece missões com boas recompensas.','🧪 Dica: Poções podem ser usadas durante o combate como ação bônus.','⭐ Dica: Suba de nível para desbloquear novas habilidades de classe.','🐉 Dica: Inimigos mais fortes concedem mais XP e ouro.','🎯 Dica: Advantage dobra suas chances — posicione-se bem!','🧪 Dica: Poções de cura restauram 2d4+2 pontos de vida.','🛡️ Dica: Classe de Armadura (CA) determina se ataques acertam você.','🔮 Dica: Magias de concentração se perdem ao receber dano.','🗺️ Dica: Explore cada localização — segredos estão por toda parte.','⚔️ Dica: Ataques de oportunidade atingem inimigos que fogem.','💠 Dica: Cada classe tem recursos únicos — conheça os seus!','🏰 Dica: O ferreiro pode forjar equipamentos poderosos.',];var _LOADING_TIPS=_TIPS_NARRATIVE.concat(_TIPS_MECHANICS);var _loadingTipTimer=null;var _loadingTipIndex=0;var _loadingProgressTimer=null;var _loadingProgress=0;var _loadingStartTime=0;var _isRetryLoading=false;var _loadingHiding=false;var _loadingSlowTimer=null;function showLoading(isRetry=false){_loadingHiding=false;var skelEl=document.getElementById('skeleton');if(window.__spaRevisit&&!isRetry&&skelEl){skelEl.style.display='';var loadEl=document.getElementById('loading');if(loadEl)loadEl.style.display='none';return;}const el=document.getElementById('loading');if(el){el.style.display='';el.classList.remove('exit-cinematic','hidden');el.style.opacity='';el.style.transition='';el.removeAttribute('data-phase');}
const circle=el?el.querySelector('.magic-circle'):null;if(circle){circle.style.removeProperty('--ring-outer');circle.style.removeProperty('--ring-mid');circle.style.removeProperty('--ring-inner');}
_isRetryLoading=isRetry;_loadingStartTime=Date.now();_startLoadingProgress();_startLoadingTimeout();_startSlowWarning();if(isRetry){_stopLoadingTips();const tipEl=document.getElementById('loading-tip');if(tipEl)tipEl.textContent='🔄 Reconectando ao servidor...';}else{_startLoadingTips();}
setTimeout(()=>{const gemEl=document.getElementById('mc-gem');if(gemEl&&el&&el.style.display!=='none'){gemEl.classList.add('gem-hint');setTimeout(()=>gemEl.classList.remove('gem-hint'),1500);}},3000);}
function hideLoading(){var _skelH=document.getElementById('skeleton');if(_skelH)_skelH.style.display='none';const el=document.getElementById('loading');if(!el||el.style.display==='none')return;if(_loadingHiding)return;_loadingHiding=true;_stopLoadingProgress();_stopLoadingTimeout();_stopSlowWarning();_isRetryLoading=false;const retryBtn=document.getElementById('loading-retry');if(retryBtn)retryBtn.style.display='none';const bar=document.getElementById('loading-progress');const stageEl=document.getElementById('loading-stage');if(bar)bar.style.width='100%';_loadingProgress=100;_updateLoadingPhase(100);if(stageEl)stageEl.textContent='Pronto!';_triggerCompletionPulse(el);const isLite=el.classList.contains('loading-lite');const exitMs=isLite?300:500;const readyPause=400;setTimeout(()=>{el.classList.add('exit-cinematic');_stopLoadingTips();setTimeout(()=>{el.style.display='none';_loadingHiding=false;el.classList.remove('exit-cinematic');el.style.opacity='';el.style.transition='';const circle=el.querySelector('.magic-circle');if(circle){circle.style.removeProperty('--ring-outer');circle.style.removeProperty('--ring-mid');circle.style.removeProperty('--ring-inner');}
el.removeAttribute('data-phase');if(stageEl)stageEl.textContent='';},exitMs);},readyPause);setTimeout(()=>{if(el.style.display!=='none'){console.warn('[GAME] Loading force-hidden after safety net');el.style.display='none';_loadingHiding=false;el.classList.remove('exit-cinematic');el.removeAttribute('data-phase');}},readyPause+exitMs+500);}
async function hideLoadingWithDelay(){const elapsed=Date.now()-_loadingStartTime;const remaining=MIN_LOADING_MS-elapsed;if(remaining>0)await sleep(remaining);hideLoading();}
function forceHideLoading(){var skelEl=document.getElementById('skeleton');if(skelEl)skelEl.style.display='none';const el=document.getElementById('loading');if(!el||el.style.display==='none')return;_loadingHiding=false;_stopLoadingProgress();_stopLoadingTimeout();_stopSlowWarning();_stopLoadingTips();_isRetryLoading=false;el.style.display='none';el.classList.remove('exit-cinematic','hidden');el.style.opacity='';el.style.transition='';el.removeAttribute('data-phase');const stageEl=document.getElementById('loading-stage');if(stageEl)stageEl.textContent='';const circle=el.querySelector('.magic-circle');if(circle){circle.style.removeProperty('--ring-outer');circle.style.removeProperty('--ring-mid');circle.style.removeProperty('--ring-inner');}
const retryBtn=document.getElementById('loading-retry');if(retryBtn)retryBtn.style.display='none';}
function _updateRingSpeed(pct){const el=document.getElementById('loading');const circle=el?el.querySelector('.magic-circle'):null;if(!circle)return;const factor=1-(pct/100)*0.6;circle.style.setProperty('--ring-outer',(60*factor)+'s');circle.style.setProperty('--ring-mid',(35*factor)+'s');circle.style.setProperty('--ring-inner',(45*factor)+'s');}
function _updateLoadingPhase(pct){const el=document.getElementById('loading');if(!el)return;if(pct>=90)el.setAttribute('data-phase','2');else if(pct>=50)el.setAttribute('data-phase','1');else el.removeAttribute('data-phase');_updateRingSpeed(pct);}
function _triggerCompletionPulse(overlay){if(!overlay)return;const waves=overlay.querySelectorAll('.mc-completion-wave');waves.forEach(w=>w.classList.add('active'));try{if(window.Telegram&&Telegram.WebApp&&Telegram.WebApp.HapticFeedback){Telegram.WebApp.HapticFeedback.impactOccurred('heavy');}}catch(_){}}
function _startLoadingProgress(){_stopLoadingProgress();_loadingProgress=0;const bar=document.getElementById('loading-progress');const stageEl=document.getElementById('loading-stage');if(bar)bar.style.width='0%';if(stageEl)stageEl.textContent='';_loadingProgressTimer=setInterval(()=>{const elapsed=Date.now()-_loadingStartTime;const minLoad=(typeof MIN_LOADING_MS!=='undefined')?MIN_LOADING_MS:5000;const targetPct=Math.min(95,(elapsed/minLoad)*95);_loadingProgress+=(targetPct-_loadingProgress)*0.12;if(bar)bar.style.width=_loadingProgress+'%';_updateLoadingPhase(_loadingProgress);},200);}
function _stopLoadingProgress(){if(_loadingProgressTimer){clearInterval(_loadingProgressTimer);_loadingProgressTimer=null;}}
function _startLoadingTips(){_stopLoadingTips();const elapsed=Date.now()-_loadingStartTime;const pool=elapsed<5000?_TIPS_NARRATIVE:_TIPS_MECHANICS;_loadingTipIndex=Math.floor(Math.random()*pool.length);const tipEl=document.getElementById('loading-tip');if(tipEl)tipEl.textContent=pool[_loadingTipIndex];_loadingTipTimer=setInterval(()=>{const now=Date.now()-_loadingStartTime;const currentPool=now<5000?_TIPS_NARRATIVE:_TIPS_MECHANICS;_loadingTipIndex=(_loadingTipIndex+1)%currentPool.length;const tipEl=document.getElementById('loading-tip');if(tipEl){tipEl.classList.add('tip-exit');setTimeout(()=>{tipEl.textContent=currentPool[_loadingTipIndex];tipEl.classList.remove('tip-exit');tipEl.classList.add('tip-enter');setTimeout(()=>tipEl.classList.remove('tip-enter'),350);},300);}},4500);}
function _stopLoadingTips(){if(_loadingTipTimer){clearInterval(_loadingTipTimer);_loadingTipTimer=null;}}
(function _initGemTap(){function setup(){const gemEl=document.getElementById('mc-gem');if(!gemEl)return;let cooldown=false;gemEl.addEventListener('click',()=>{if(cooldown)return;cooldown=true;if(typeof ValdoriaAudio!=='undefined'&&ValdoriaAudio._warmUp)ValdoriaAudio._warmUp();gemEl.classList.add('tapped');const burst=document.createElement('div');burst.className='mc-gem-burst';gemEl.appendChild(burst);try{if(window.Telegram&&Telegram.WebApp&&Telegram.WebApp.HapticFeedback){Telegram.WebApp.HapticFeedback.impactOccurred('light');}}catch(_){}
setTimeout(()=>{gemEl.classList.remove('tapped');if(burst.parentNode)burst.parentNode.removeChild(burst);cooldown=false;},600);});}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',setup);}else{setup();}})();function _startLoadingTimeout(){_stopLoadingTimeout();if(typeof LOADING_TIMEOUT_MS==='undefined')return;_loadingTimeoutId=setTimeout(()=>{const el=document.getElementById('loading');if(el&&el.style.display!=='none'){console.error('[GAME] Loading timeout — server did not respond in time');hideLoading();showError('O servidor demorou demais para responder. Tente novamente.');}},LOADING_TIMEOUT_MS);}
function _stopLoadingTimeout(){if(typeof _loadingTimeoutId!=='undefined'&&_loadingTimeoutId){clearTimeout(_loadingTimeoutId);_loadingTimeoutId=null;}}
function _startSlowWarning(){_stopSlowWarning();_loadingSlowTimer=setTimeout(()=>{const el=document.getElementById('loading');if(el&&el.style.display!=='none'){const tipEl=document.getElementById('loading-tip');if(tipEl){tipEl.style.opacity='0';setTimeout(()=>{tipEl.textContent=_isRetryLoading?'⏳ Servidor demorando para responder...':'⏳ Conexão lenta — verifique seu sinal ou tente novamente';tipEl.style.opacity='';tipEl.classList.add('loading-tip-slow');},300);}
const retryBtn=document.getElementById('loading-retry');if(retryBtn){retryBtn.style.display='';retryBtn.onclick=()=>{retryBtn.style.display='none';if(typeof init==='function'){showLoading(true);init();}else{window.location.reload();}};}}},10000);}
function _stopSlowWarning(){if(_loadingSlowTimer){clearTimeout(_loadingSlowTimer);_loadingSlowTimer=null;}
const tipEl=document.getElementById('loading-tip');if(tipEl)tipEl.classList.remove('loading-tip-slow');}
function animateScreenTransition(renderFn,direction){const screenEl=document.getElementById('screen');const panelEl=document.getElementById('bottom-panel');if(!screenEl){renderFn();return;}
const isBack=direction==='back';const isForward=direction==='forward';const outClass=isBack?'slide-back-out':isForward?'slide-left-out':'fade-out';const inClass=isBack?'slide-back-in':isForward?'slide-left-in':'fade-in';screenEl.classList.add(outClass);if(panelEl){panelEl.style.opacity='0.7';panelEl.style.transition='opacity 0.2s ease';}
setTimeout(()=>{renderFn();screenEl.classList.remove(outClass);screenEl.classList.add(inClass);if(panelEl){panelEl.style.opacity='1';panelEl.style.transition='opacity 0.25s ease';}
setTimeout(()=>{screenEl.classList.remove(inClass);if(panelEl)panelEl.style.transition='';},300);},250);}
var _timerInterval=null;var _timerDone=false;function showTimerOverlay(timer){if(!timer)return;const overlay=document.getElementById('timer-overlay');const secondsEl=document.getElementById('timer-seconds');const labelEl=document.getElementById('timer-label');const arcEl=document.getElementById('timer-arc');const skipBtn=document.getElementById('timer-skip');if(!overlay)return;_timerDone=false;let remaining=timer.seconds;const total=timer.seconds;const circumference=2*Math.PI*36;secondsEl.textContent=remaining;labelEl.textContent=timer.type==='reaction'?'Reação!':'Decidir!';arcEl.style.strokeDashoffset='0';overlay.style.display='';skipBtn.style.display='none';skipBtn.classList.remove('visible');const finishTimer=()=>{if(_timerDone)return;_timerDone=true;clearInterval(_timerInterval);overlay.style.display='none';skipBtn.onclick=null;skipBtn.classList.remove('visible');if(timer.timeout_cb){doAction(timer.timeout_cb);}};setTimeout(()=>{if(!_timerDone){skipBtn.style.display='';skipBtn.classList.add('visible');skipBtn.onclick=finishTimer;}},500);_timerInterval=setInterval(()=>{remaining--;if(remaining<=0){finishTimer();return;}
secondsEl.textContent=remaining;const offset=circumference*(1-remaining/total);arcEl.style.strokeDashoffset=offset.toString();},1000);}
function hideTimerOverlay(){_timerDone=true;if(_timerInterval)clearInterval(_timerInterval);const overlay=document.getElementById('timer-overlay');if(overlay)overlay.style.display='none';}
var _LOC_TRANSITIONS={city_tavern:{icon:'🍺',text:'Caminhando até a Taverna...'},city_temple:{icon:'⛪',text:'Seguindo ao Templo...'},city_market:{icon:'🏪',text:'Indo ao Mercado...'},city_bank:{icon:'🏦',text:'Entrando no Banco...'},city_guild:{icon:'⚔️',text:'Chegando na Guilda...'},city_arena:{icon:'🏟️',text:'Entrando na Arena...'},city_locations:{icon:'🏰',text:'Explorando a cidade...'},depart:{icon:'🗺️',text:'Partindo para aventura...'},action_depart:{icon:'🗺️',text:'Partindo para aventura...'},trail_:{icon:'🥾',text:'Seguindo a trilha...'},explore_:{icon:'🧭',text:'Explorando o caminho...'},action_city_entry:{gate:true,text:'Avistando os portões de Eldoria...'},action_enter_city:{gate:true,text:'Entrando em Eldoria...'},return_city:{gate:true,text:'Retornando à cidade...'},action_return:{gate:true,text:'Retornando à cidade...'},city_back:{gate:true,text:'Voltando à praça central...'},combat_end:{icon:'⚔️',text:'Recolhendo espólios...'},rest:{icon:'🏕️',text:'Descansando...'},long_rest:{icon:'🛏️',text:'Descansando na estalagem...'},};var _NO_TRANSITION=/^(inv|char|status|help|settings|quest_view|action_universal_back|menu|equip|unequip|use_|sell_|buy_|deposit|withdraw|donate|skill_|feat_|spell_|npc_talk|dialogue|gossip|quest_accept|quest_deliver|shop_|inn_pay_)/;var LOC_TRANSITION_MS=1500;var LOC_GATE_MS=2200;var _locTransitionActive=false;var _locTransitionIsGate=false;function _detectLocationTransition(cb){if(!cb||_NO_TRANSITION.test(cb))return null;if(_LOC_TRANSITIONS[cb])return _LOC_TRANSITIONS[cb];for(const[prefix,ctx]of Object.entries(_LOC_TRANSITIONS)){if(prefix.endsWith('_')&&cb.startsWith(prefix))return ctx;}
return null;}
function showLocationTransition(ctx){var el=document.getElementById('loc-transition');if(!el)return;_locTransitionActive=true;_locTransitionIsGate=!!ctx.gate;el.classList.remove('hiding');el.style.display='';var gateEl=document.getElementById('loc-gate');var iconEl=document.getElementById('loc-icon');var textEl=document.getElementById('loc-text');var isCity=!!ctx.gate;if(gateEl)gateEl.style.display=isCity?'':'none';if(iconEl){iconEl.style.display=isCity?'none':'';if(!isCity)iconEl.textContent=ctx.icon||'🗺️';}
if(textEl)textEl.textContent=ctx.text||'Viajando...';if(isCity&&gateEl){gateEl.classList.remove('opening');void gateEl.offsetWidth;gateEl.classList.add('opening');}
haptic(isCity?'heavy':'medium');}
function hideLocationTransition(){var el=document.getElementById('loc-transition');if(!el||!_locTransitionActive)return;_locTransitionActive=false;_locTransitionIsGate=false;el.classList.add('hiding');setTimeout(function(){el.style.display='none';el.classList.remove('hiding');var g=document.getElementById('loc-gate');if(g)g.classList.remove('opening');},400);}
function getLocTransitionMs(){return _locTransitionIsGate?LOC_GATE_MS:LOC_TRANSITION_MS;}
var _immersiveCollapsed=false;var _immersiveEligible=false;var IMMERSIVE_KEY='valdoria_immersive';function initImmersive(){try{_immersiveCollapsed=localStorage.getItem(IMMERSIVE_KEY)==='1';}catch(e){_immersiveCollapsed=false;}
const toggleBtn=document.getElementById('immersive-toggle');const restoreBtn=document.getElementById('immersive-restore');if(toggleBtn){toggleBtn.onclick=()=>{haptic('light');_setImmersive(true);};}
if(restoreBtn){restoreBtn.onclick=()=>{haptic('light');_setImmersive(false);};}}
function _setImmersive(collapsed){_immersiveCollapsed=collapsed;try{localStorage.setItem(IMMERSIVE_KEY,collapsed?'1':'0');}catch(e){}
_applyImmersive();}
function _applyImmersive(){const toggle=document.getElementById('immersive-toggle');const restore=document.getElementById('immersive-restore');const panel=document.getElementById('bottom-panel');const screen=document.getElementById('screen');if(!_immersiveEligible){if(toggle)toggle.style.display='none';if(restore)restore.style.display='none';if(panel)panel.classList.remove('immersive-collapsed');if(screen)screen.classList.remove('immersive-full');updateBottomPadding();return;}
if(_immersiveCollapsed){if(toggle)toggle.style.display='none';if(panel)panel.classList.add('immersive-collapsed');if(restore)restore.style.display='';if(screen)screen.classList.add('immersive-full');}else{var collapsedPad=screen?parseFloat(getComputedStyle(screen).paddingBottom)||48:48;var prevScroll=screen?screen.scrollTop:0;if(panel)panel.classList.remove('immersive-collapsed');if(toggle)toggle.style.display='';if(restore)restore.style.display='none';if(screen)screen.classList.remove('immersive-full');updateBottomPadding();if(screen&&prevScroll>0){requestAnimationFrame(function(){requestAnimationFrame(function(){var expandedPad=parseFloat(screen.style.paddingBottom)||120;var delta=expandedPad-collapsedPad;if(delta>0){screen.scrollTop=Math.min(prevScroll+delta,screen.scrollHeight-screen.clientHeight);}});});}}}
function updateImmersiveEligibility(screen){_immersiveEligible=!!(screen&&screen.immersive);if(_immersiveCollapsed&&_immersiveEligible){_immersiveCollapsed=false;}
_applyImmersive();}
var FONT_OPTIONS=[{id:'medievalsharp',name:'MedievalSharp',family:"'MedievalSharp', serif"},{id:'cinzel',name:'Cinzel',family:"'Cinzel', serif"},{id:'imfell',name:'IM Fell English',family:"'IM Fell English', serif"},{id:'pirataone',name:'Pirata One',family:"'Pirata One', cursive"},{id:'almendra',name:'Almendra',family:"'Almendra', serif"},{id:'metamorphous',name:'Metamorphous',family:"'Metamorphous', serif"},];var FONT_KEY='valdoria_font';function getSelectedFont(){try{let id=localStorage.getItem(FONT_KEY)||'medievalsharp';if(id==='uncial'){id='medievalsharp';localStorage.setItem(FONT_KEY,id);}
return id;}catch(e){return'medievalsharp';}}
function applyGameFont(){const id=getSelectedFont();const opt=FONT_OPTIONS.find(f=>f.id===id);if(!opt)return;document.body.style.setProperty('--user-font',opt.family);document.body.dataset.font=id;document.body.style.fontFamily=opt.family;}
function selectGameFont(fontId){const opt=FONT_OPTIONS.find(f=>f.id===fontId);if(!opt)return;try{localStorage.setItem(FONT_KEY,fontId);}catch(e){}
applyGameFont();document.querySelectorAll('.font-pick-btn').forEach(btn=>{btn.classList.toggle('active',btn.dataset.fontId===fontId);});haptic('light');}
function injectFontPicker(contentEl){const section=document.createElement('div');section.className='font-picker-section';const label=document.createElement('div');label.className='font-picker-label';label.textContent='🔤 Fonte do Jogo';section.appendChild(label);const grid=document.createElement('div');grid.className='font-picker-grid';const currentId=getSelectedFont();for(const f of FONT_OPTIONS){const btn=document.createElement('button');btn.type='button';btn.className='font-pick-btn'+(f.id===currentId?' active':'');btn.style.fontFamily=f.family;btn.dataset.fontId=f.id;const nameSpan=document.createElement('span');nameSpan.textContent=f.name;btn.appendChild(nameSpan);const check=document.createElement('span');check.className='font-check';check.textContent='✓';btn.appendChild(check);btn.onclick=()=>selectGameFont(f.id);grid.appendChild(btn);}
section.appendChild(grid);contentEl.appendChild(section);}
function injectAudioSettings(contentEl){if(typeof ValdoriaAudio==='undefined')return;const section=document.createElement('div');section.className='audio-settings-section';section.innerHTML='';const musicMuted=ValdoriaAudio.isMusicMuted();const sfxMuted=ValdoriaAudio.isSFXMuted();const musicVol=Math.round(ValdoriaAudio.getVolume()*100);const sfxVol=Math.round(ValdoriaAudio.getSFXVolume()*100);const header=document.createElement('div');header.className='audio-settings-header settings-accordion-header';header.innerHTML='🔊 Som <span class="accordion-arrow">▼</span>';const audioContent=document.createElement('div');audioContent.className='settings-accordion-body';const audioCollapsed=localStorage.getItem('valdoria_settings_audio_collapsed')==='1';if(audioCollapsed){audioContent.style.display='none';header.querySelector('.accordion-arrow').textContent='▶';}
header.onclick=function(){const isHidden=audioContent.style.display==='none';audioContent.style.display=isHidden?'':'none';header.querySelector('.accordion-arrow').textContent=isHidden?'▼':'▶';localStorage.setItem('valdoria_settings_audio_collapsed',isHidden?'0':'1');};section.appendChild(header);audioContent.appendChild(_audioRow('🎵 Música',!musicMuted,musicVol,(enabled)=>{ValdoriaAudio.toggleMusic();_refreshAudioSettings(contentEl);},(val)=>{ValdoriaAudio.setVolume(val/100);}));audioContent.appendChild(_audioRow('⚔️ Efeitos',!sfxMuted,sfxVol,(enabled)=>{ValdoriaAudio.toggleSFX();_refreshAudioSettings(contentEl);},(val)=>{ValdoriaAudio.setSFXVolume(val/100);if(ValdoriaAudio.previewSFX)ValdoriaAudio.previewSFX();}));section.appendChild(audioContent);contentEl.appendChild(section);}
function _audioRow(label,enabled,volume,onToggle,onVolume){const row=document.createElement('div');row.className='audio-settings-row';const toggle=document.createElement('button');toggle.className='audio-toggle'+(enabled?' on':'');toggle.innerHTML='<span class="audio-toggle-label">'+label+'</span>'+'<span class="audio-toggle-status">'+(enabled?'🟢':'⚪')+'</span>';toggle.onclick=()=>{try{var tg=window.Telegram&&window.Telegram.WebApp;if(tg&&tg.HapticFeedback)tg.HapticFeedback.impactOccurred('light');}catch(e){}onToggle(!enabled);};row.appendChild(toggle);if(enabled){const sliderWrap=document.createElement('div');sliderWrap.className='audio-vol-wrap';const slider=document.createElement('input');slider.type='range';slider.className='audio-vol-slider';slider.min='0';slider.max='100';slider.value=String(volume);slider.setAttribute('aria-label',label+' volume');slider.style.setProperty('--fill',volume+'%');const pct=document.createElement('span');pct.className='audio-vol-pct';pct.textContent=volume+'%';slider.addEventListener('input',(e)=>{e.stopPropagation();const val=parseInt(e.target.value,10);pct.textContent=val+'%';slider.style.setProperty('--fill',val+'%');onVolume(val);});slider.addEventListener('touchstart',(e)=>e.stopPropagation(),{passive:true});slider.addEventListener('touchmove',(e)=>e.stopPropagation(),{passive:true});sliderWrap.appendChild(slider);sliderWrap.appendChild(pct);row.appendChild(sliderWrap);}
return row;}
function _refreshAudioSettings(contentEl){const old=contentEl.querySelector('.audio-settings-section');if(old)old.remove();injectAudioSettings(contentEl);}
function injectGameSettings(contentEl,settingsData){if(!settingsData)return;if(settingsData.toggles&&settingsData.toggles.length>0){var section=document.createElement("div");section.className="settings-section";var header=document.createElement("div");header.className="settings-section-header";header.textContent="⚔️ Jogo";section.appendChild(header);for(var i=0;i<settingsData.toggles.length;i++){var t=settingsData.toggles[i];var row=document.createElement("div");row.className="settings-toggle-row";var btn=document.createElement("button");btn.type="button";btn.className="settings-toggle"+(t.enabled?" on":"");var left=document.createElement("span");left.className="settings-toggle-left";left.innerHTML='<span class="settings-toggle-emoji">'+(t.emoji||'')+'</span>'+'<span class="settings-toggle-info">'+'<span class="settings-toggle-label">'+t.label+'</span>'+'<span class="settings-toggle-desc">'+(t.desc||'')+'</span>'+'</span>';var status=document.createElement("span");status.className="settings-toggle-status";status.textContent=t.enabled?"🟢":"⚪";btn.appendChild(left);btn.appendChild(status);btn.setAttribute("data-cb",t.cb);btn.onclick=function(){haptic("light");if(typeof doAction==="function")doAction(this.getAttribute("data-cb"));};row.appendChild(btn);section.appendChild(row);}
contentEl.appendChild(section);}
if(settingsData.extras&&settingsData.extras.length>0){var section2=document.createElement("div");section2.className="settings-section";var header2=document.createElement("div");header2.className="settings-section-header";header2.textContent="📩 Outros";section2.appendChild(header2);for(var j=0;j<settingsData.extras.length;j++){var ex=settingsData.extras[j];var btn2=document.createElement("button");btn2.type="button";btn2.className="settings-extra-btn";btn2.textContent=(ex.emoji?ex.emoji+" ":"")+ex.label;btn2.setAttribute("data-cb",ex.cb);btn2.onclick=function(){haptic("light");if(typeof doAction==="function")doAction(this.getAttribute("data-cb"));};section2.appendChild(btn2);}
contentEl.appendChild(section2);}}
function triggerScreenShake(intensity){var screen=document.getElementById('screen');if(!screen)return;var cls=intensity==='heavy'?'shake-heavy':'shake-light';screen.classList.remove('shake-light','shake-heavy');void screen.offsetHeight;screen.classList.add(cls);screen.addEventListener('animationend',function onEnd(){screen.classList.remove(cls);screen.removeEventListener('animationend',onEnd);});if(typeof haptic==='function')haptic(intensity==='heavy'?'heavy':'medium');}
function injectReferralScreen(contentEl,data){var section=document.createElement('div');section.className='referral-screen';var codeBox=document.createElement('div');codeBox.className='referral-code-box';var codeLabel=document.createElement('div');codeLabel.className='referral-code-label';codeLabel.textContent='\ud83d\udccb Seu C\u00f3digo';var codeValue=document.createElement('div');codeValue.className='referral-code-value';codeValue.textContent=data.code||'---';var codeHint=document.createElement('div');codeHint.className='referral-code-hint';codeHint.textContent='Toque para copiar';codeBox.appendChild(codeLabel);codeBox.appendChild(codeValue);codeBox.appendChild(codeHint);codeBox.onclick=function(){if(navigator.clipboard){navigator.clipboard.writeText(data.code||'');if(typeof vToast==='function')vToast('C\u00f3digo copiado!','success');haptic('success');}};section.appendChild(codeBox);var stats=document.createElement('div');stats.className='referral-stats';var stat1=document.createElement('div');stat1.className='referral-stat';stat1.innerHTML='<span class="referral-stat-value">'+(data.count||0)+'</span>'+'<span class="referral-stat-label">Indica\u00e7\u00f5es</span>';var stat2=document.createElement('div');stat2.className='referral-stat';stat2.innerHTML='<span class="referral-stat-value">\ud83e\ude99 '+(data.next_reward||50)+'</span>'+'<span class="referral-stat-label">Pr\u00f3xima</span>';stats.appendChild(stat1);stats.appendChild(stat2);section.appendChild(stats);var tiersBox=document.createElement('div');tiersBox.className='referral-tiers';var tiersTitle=document.createElement('div');tiersTitle.className='referral-tiers-title';tiersTitle.textContent='\ud83d\udcca Escala de Recompensas';tiersBox.appendChild(tiersTitle);var tiers=data.tiers||[];for(var i=0;i<tiers.length;i++){var t=tiers[i];var maxLabel=t.max>=9999?'\u221e':t.max;var isCurrent=(data.count||0)+1>=t.min&&(data.count||0)+1<=t.max;var tierEl=document.createElement('div');tierEl.className='referral-tier'+(isCurrent?' current':'');tierEl.innerHTML='<span class="tier-range">'+t.min+'-'+maxLabel+'</span>'+'<span class="tier-reward">\ud83e\ude99 '+t.referrer+' GP</span>'+'<span class="tier-friend">\ud83e\udd1d '+t.referee+' GP</span>';tiersBox.appendChild(tierEl);}
section.appendChild(tiersBox);var desc=document.createElement('div');desc.className='referral-desc';desc.textContent='Compartilhe seu c\u00f3digo com amigos! Quando eles criarem uma conta e inserirem o c\u00f3digo, ambos recebem ouro.';section.appendChild(desc);contentEl.appendChild(section);}
function showImmersiveTooltip(){var key='valdoria_immersive_hint';try{var count=parseInt(localStorage.getItem(key)||'0');if(count>=3||_immersiveCollapsed)return;localStorage.setItem(key,String(count+1));}catch(e){return;}
var toggle=document.getElementById('immersive-toggle');if(!toggle||toggle.style.display==='none')return;var tip=document.createElement('div');tip.className='immersive-tooltip';tip.textContent='Toque para recolher o menu';toggle.parentElement.appendChild(tip);requestAnimationFrame(function(){tip.style.opacity='1';tip.style.transform='translateY(0)';});setTimeout(function(){tip.style.opacity='0';tip.style.transform='translateY(4px)';setTimeout(function(){if(tip.parentNode)tip.parentNode.removeChild(tip);},300);},3000);}
