function _playCinematicResult(result,actionType){const isResolution=result.phase==='victory'||result.phase==='defeat'||result.phase==='ended'||result.phase==='fled';const hasRoll=result.lr&&(result.lr.r||result.lr.d||result.lr.t==='death_save');const isNonCombatAction=actionType==='initiative'||actionType==='proceed'||actionType==='restore';const oldPhase=currentState?.ph||currentState?.phase||'';if(!hasRoll||isNonCombatAction||oldPhase!=='active'){currentState=result;if(result.phase==='ended'){showCombatEnded();}
else if(isResolution){if(result.phase==='defeat'&&result.ds_history&&result.ds_history.length>0){renderDeathSaveReplay(result,function(){renderResolution(result);});}else{renderResolution(result);}}
else{renderArena(result);}
return;}
_cinematicInProgress=true;const _cinematicSafetyTimer=setTimeout(()=>{if(_cinematicInProgress){console.warn('[COMBAT] Cinematic safety timeout — force reset');clearTimeout(_cinematicWarnTimer);_cinematicInProgress=false;startPolling();}},20000);try{const attackerName=currentState?.p?.n||'Aventureiro';const _antTexts={'skill':`✨ ${attackerName} conjura!`,'attack':`⚔️ ${attackerName} avança!`,'save':`✨ ${attackerName} conjura!`,'auto_hit':`✨ ${attackerName} conjura!`,'aoe':`🔥 ${attackerName} conjura!`,'heal':`✨ ${attackerName} cura!`,'util':`✨ ${attackerName} prepara!`,'item_throw':`🎯 ${attackerName} arremessa!`,'death_save':`💀 ${attackerName} luta pela vida...`,};let anticipationText=_antTexts[result.lr.t]||`⚔️ ${attackerName} avança!`;const _sn=result.lr.sn;if(_sn){const rt=result.lr.t;if(rt==='item_throw')anticipationText=`🎯 ${attackerName} arremessa ${_sn}!`;else if(rt==='heal')anticipationText=`✨ ${attackerName} usa ${_sn}!`;else if(rt==='util')anticipationText=`✨ ${attackerName} invoca ${_sn}!`;else if(['skill','save','auto_hit','aoe'].includes(rt))anticipationText=`✨ ${attackerName} lança ${_sn}!`;}
_showAnticipation(anticipationText);setTimeout(()=>{initDice(result.lr);const _rt=result.lr.t||'attack';const _isDmgType=['attack','skill','save','auto_hit','aoe','item_throw'].includes(_rt);if(_isDmgType&&!result.lr.miss&&result.lr.d>0){const _floatDelay=['auto_hit','aoe'].includes(_rt)?TIMING.FLOAT_DELAY_FAST:TIMING.FLOAT_DELAY_NORMAL;if(_rt==='aoe'){const enemyCards=document.querySelectorAll('.entity.enemy');const hitCount=Math.min(result.lr.hits||enemyCards.length,enemyCards.length);for(let i=0;i<hitCount;i++){const cachedCard=enemyCards[i];setTimeout(()=>{_showDamageFloat(result.lr.d,result.lr.dt,null,!!result.lr.crit,cachedCard);_flashEnemyCard(cachedCard,result.lr.dt,!!result.lr.crit);},_floatDelay+i*200);}}else{setTimeout(()=>{_showDamageFloat(result.lr.d,result.lr.dt,'.entity.enemy',!!result.lr.crit);const enemyCard=document.querySelector('.entity.enemy');if(enemyCard)_flashEnemyCard(enemyCard,result.lr.dt,!!result.lr.crit);},_floatDelay);}}
if(_isDmgType&&result.lr.miss){const _missDelay=TIMING.BASE_MISS;setTimeout(()=>{_showMissFloat('.entity.enemy');const enemyCard=document.querySelector('.entity.enemy');if(enemyCard){enemyCard.classList.add('miss-deflect');setTimeout(()=>enemyCard.classList.remove('miss-deflect'),ValdoriaMotion.duration(400,0));}},_missDelay);}
let baseDelay;if(_rt==='death_save')baseDelay=3800;else if(_rt==='heal'||_rt==='util')baseDelay=2800;else if(_rt==='auto_hit'||_rt==='aoe')baseDelay=3600;else if(_rt==='save')baseDelay=(result.lr.saved&&!result.lr.half)?2600:5200;else baseDelay=(result.lr.miss||result.lr.d<=0)?2600:5200;const hasKill=result.lr.kill;const totalDelay=hasKill?baseDelay+TIMING.KILL_EXTENSION:baseDelay;const isBossKill=hasKill&&currentState?.e?.some(e=>e.leg&&e.hp>0);if(hasKill){setTimeout(()=>{const enemyCards=document.querySelectorAll('.entity.enemy');enemyCards.forEach(card=>card.classList.add('death-anim'));vHaptic.burst('kill');if(typeof ValdoriaAudio!=='undefined')ValdoriaAudio.playSFX('sfx_enemy_death');if(window._combatVfx){enemyCards.forEach(card=>window._combatVfx.kill(card,result.lr.dt||'slashing'));if(isBossKill){window._combatVfx.flash('rgba(255,215,0,0.4)',600);setTimeout(()=>{enemyCards.forEach(card=>window._combatVfx.kill(card,'radiant'));},300);}}
if(isBossKill){_shakeApp('heavy');}},baseDelay);}
setTimeout(()=>{clearTimeout(_cinematicSafetyTimer);clearTimeout(_cinematicWarnTimer);_cinematicInProgress=false;currentState=result;if(result.phase==='ended'){showCombatEnded();}
else if(isResolution){if(result.phase==='defeat'&&result.ds_history&&result.ds_history.length>0){renderDeathSaveReplay(result,function(){renderResolution(result);});}else{renderResolution(result);}}
else{renderArena(result);}},totalDelay);},TIMING.ANTICIPATION);}catch(e){console.error('[COMBAT] Cinematic exception — force reset',e);clearTimeout(_cinematicSafetyTimer);clearTimeout(_cinematicWarnTimer);_cinematicInProgress=false;currentState=result;renderArena(result);}}
function _showTurnBanner(text,type){document.querySelectorAll('.turn-banner').forEach(b=>b.remove());const el=document.createElement('div');el.className=`turn-banner ${type || ''}`;el.innerHTML=`<span class="turn-banner-text">${text}</span>`;document.body.appendChild(el);requestAnimationFrame(()=>{requestAnimationFrame(()=>el.classList.add('visible'));});if(type==='player')vHaptic.medium();else if(type==='enemy')vHaptic.tap();else if(type==='ally')vHaptic.select();setTimeout(()=>{el.classList.remove('visible');setTimeout(()=>el.remove(),ValdoriaMotion.duration(400,0));},TIMING.TURN_BANNER);}
function _showRoundBanner(roundNum){document.querySelectorAll('.turn-banner').forEach(b=>b.remove());const el=document.createElement('div');el.className='turn-banner round';el.innerHTML=`<span class="turn-banner-text">── Rodada ${roundNum} ──</span>`;document.body.appendChild(el);requestAnimationFrame(()=>{requestAnimationFrame(()=>el.classList.add('visible'));});vHaptic.select();setTimeout(()=>{el.classList.remove('visible');setTimeout(()=>el.remove(),ValdoriaMotion.duration(400,0));},TIMING.ROUND_BANNER);}
function _showComboCounter(count){let el=document.getElementById('comboCounter');if(!el){el=document.createElement('div');el.id='comboCounter';el.className='combo-counter';document.body.appendChild(el);}
el.textContent=`x${count}`;el.classList.remove('combo-pop');void el.offsetWidth;el.classList.add('combo-pop');clearTimeout(el._hideTimer);el._hideTimer=setTimeout(()=>el.classList.remove('combo-pop'),3000);}
function _showAnticipation(text){const el=document.createElement('div');el.className='anticipation-overlay';el.innerHTML=`<span class="anticipation-text">${text}</span>`;document.body.appendChild(el);requestAnimationFrame(()=>{requestAnimationFrame(()=>el.classList.add('visible'));});setTimeout(()=>{el.classList.remove('visible');setTimeout(()=>el.remove(),ValdoriaMotion.duration(200,0));},TIMING.ANTICIPATION);}
function _dmgFlashClass(dt){return _DMG_FLASH_TYPES.has(dt)?`dmg-flash-${dt}`:'dmg-flash';}
function _flashEnemyCard(card,damageType,isCrit){if(!card||!document.body.contains(card))return;const flashCls=_dmgFlashClass(damageType);card.classList.remove(flashCls,'dmg-shake');void card.offsetWidth;card.classList.add(flashCls);setTimeout(()=>card.classList.remove(flashCls),ValdoriaMotion.duration(400,0));const shakeCls=isCrit?'enemy-hit-heavy':'dmg-shake';card.classList.add(shakeCls);setTimeout(()=>card.classList.remove(shakeCls),ValdoriaMotion.duration(isCrit?600:500,0));_showImpactFlash(card,isCrit);if(isCrit){_shakeApp('heavy');vHaptic.burst('crit');}else{_shakeApp('light');}
if(window._combatVfx){window._combatVfx.impact(card,damageType||'slashing',{});}}
function _showMissFloat(targetSelector,cachedEl){const target=cachedEl||document.querySelector(targetSelector||'.entity.enemy');if(!target||!document.body.contains(target))return;const rect=target.getBoundingClientRect();const el=document.createElement('div');el.className='damage-float miss';el.textContent='Esquivou!';const _mx=Math.max(30,Math.min(window.innerWidth-30,rect.left+rect.width/2));el.style.left=_mx+'px';el.style.top=rect.top+'px';document.body.appendChild(el);setTimeout(()=>el.remove(),ValdoriaMotion.duration(1000,500));}
function _showDamageFloat(damage,damageType,targetSelector,isCrit,cachedEl){const target=cachedEl||document.querySelector(targetSelector||'.entity.enemy');if(!target||!document.body.contains(target))return;const rect=target.getBoundingClientRect();const el=document.createElement('div');el.className='damage-float'+(isCrit?' crit':'');const _dIco={fire:'🔥',cold:'❄️',lightning:'⚡',necrotic:'💀',radiant:'✨',poison:'🧪',acid:'🧪',psychic:'🔮',thunder:'💨',force:'💫',slashing:'⚔️',piercing:'🏹',bludgeoning:'🔨'};const _ico=isCrit?'💥':(_dIco[damageType]||'⚔️');el.textContent=`${_ico} -${damage}`;if(!isCrit)el.style.color=(typeof DMG_TYPE_COLORS!=='undefined'&&DMG_TYPE_COLORS[damageType])||'#ff4444';const _fx=Math.max(30,Math.min(window.innerWidth-30,rect.left+rect.width/2));el.style.left=_fx+'px';el.style.top=rect.top+'px';document.body.appendChild(el);setTimeout(()=>el.remove(),ValdoriaMotion.duration(isCrit?1500:1200,isCrit?800:600));}
function _showHealFloat(amount,targetSelector,cachedEl){const target=cachedEl||document.querySelector(targetSelector||'.entity.player');if(!target||!document.body.contains(target))return;const rect=target.getBoundingClientRect();const el=document.createElement('div');el.className='damage-float heal';el.textContent=`💚 +${amount}`;const _hx=Math.max(30,Math.min(window.innerWidth-30,rect.left+rect.width/2));el.style.left=_hx+'px';el.style.top=rect.top+'px';document.body.appendChild(el);setTimeout(()=>el.remove(),ValdoriaMotion.duration(1200,600));}
function _showHealFlash(){let flash=document.getElementById('healFlash');if(!flash){flash=document.createElement('div');flash.id='healFlash';flash.className='viewport-flash heal-flash';document.body.appendChild(flash);}
flash.classList.remove('active');void flash.offsetWidth;flash.classList.add('active');setTimeout(()=>flash.classList.remove('active'),ValdoriaMotion.duration(400,200));}

function _animateHpBars(state){const current=new Map();if(state.p)current.set('player',{hp:state.p.hp,mhp:state.p.mhp});(state.e||[]).forEach((e,i)=>current.set(`e${i}_${e.n}`,{hp:e.hp,mhp:e.mhp}));(state.a||[]).forEach((a,i)=>current.set(`a${i}_${a.n}`,{hp:a.hp,mhp:a.mhp}));current.forEach((cur,key)=>{const prev=_prevHpState.get(key);if(!prev||prev.hp===cur.hp)return;const oldPct=prev.mhp>0?(prev.hp/prev.mhp)*100:0;const newPct=cur.mhp>0?(cur.hp/cur.mhp)*100:0;let fillEl=null;if(key==='player'){fillEl=document.querySelector('.zone-player .bar-fill');}else if(key.startsWith('e')){const idx=parseInt(key.charAt(1));const els=document.querySelectorAll('.zone-enemies .hp-mini-fill');if(els[idx])fillEl=els[idx];}else if(key.startsWith('a')){const idx=parseInt(key.charAt(1));const els=document.querySelectorAll('.zone-allies .hp-mini-fill');if(els[idx])fillEl=els[idx];}
if(!fillEl)return;const isDamage=newPct<oldPct;const isHeal=newPct>oldPct;if(isDamage){const track=fillEl.parentElement;if(track&&document.body.contains(fillEl)){let ghost=track.querySelector('.bar-ghost');if(!ghost){ghost=document.createElement('div');ghost.className='bar-ghost';track.insertBefore(ghost,fillEl);}
ghost.style.transition='none';ghost.style.transform='scaleX('+(oldPct/100)+')';requestAnimationFrame(()=>{ghost.style.transition='transform 1.2s ease-in var(--v-transition-base)';ghost.style.transform='scaleX('+(newPct/100)+')';});}}
if(isHeal){fillEl.classList.add('healing');setTimeout(()=>fillEl.classList.remove('healing'),ValdoriaMotion.duration(700,0));}
fillEl.style.transition='none';fillEl.style.transform='scaleX('+(oldPct/100)+')';requestAnimationFrame(()=>{requestAnimationFrame(()=>{fillEl.style.transition='transform 0.65s ease-out';fillEl.style.transform='scaleX('+(newPct/100)+')';});});});current.forEach((v,k)=>_prevHpState.set(k,v));}
function _checkPlayerDamage(state){if(!state.p)return;const curHp=state.p.hp;if(_prevPlayerHp>0&&curHp<_prevPlayerHp){const dmgTaken=_prevPlayerHp-curHp;const playerEl=document.querySelector('.entity.player');if(playerEl){playerEl.classList.remove('dmg-shake');void playerEl.offsetWidth;playerEl.classList.add('dmg-shake');setTimeout(()=>playerEl.classList.remove('dmg-shake'),ValdoriaMotion.duration(500,0));const pFlashCls=_dmgFlashClass(_lastEnemyDmgType);playerEl.classList.add(pFlashCls);setTimeout(()=>playerEl.classList.remove(pFlashCls),ValdoriaMotion.duration(400,0));vHaptic.heavy();sfxPlayerHit();_showDamageFloat(dmgTaken,_lastEnemyDmgType,'.entity.player');_showImpactFlash(playerEl,false);}
if(window._combatVfx){window._combatVfx.impact(playerEl,_lastEnemyDmgType||'slashing',{});const dtFlash=(typeof VFX_PROFILES!=='undefined'&&VFX_PROFILES[_lastEnemyDmgType]?.flashColor)||'rgba(255,60,30,0.3)';window._combatVfx.flash(dtFlash,400);}else{_showViewportFlash();}}
if(_prevPlayerHp>0&&curHp>_prevPlayerHp){const healAmt=curHp-_prevPlayerHp;_showHealFloat(healAmt,'.entity.player');_showHealFlash();if(typeof ValdoriaAudio!=='undefined')ValdoriaAudio.playSFX('sfx_heal');}
_prevPlayerHp=curHp;}
function _clearStatusTracking(){_prevStatusState.clear();_prevPlayerHp=0;_prevHpState.clear();}
function _checkStatusChanges(state){const vfx=window._combatVfx;if(!vfx)return;const entities=[];if(state.p)entities.push({key:'player',se:state.p.se||[],sel:'.entity.player'});(state.e||[]).forEach((e,i)=>entities.push({key:`e${i}`,se:e.se||[],sel:`.entity.enemy[data-enemy-idx="${i}"]`}));(state.a||[]).forEach((a,i)=>entities.push({key:`a${i}`,se:a.se||[],sel:`.entity.ally:nth-child(${i + 2})`}));for(const ent of entities){const prev=_prevStatusState.get(ent.key)||[];const prevSet=new Set(prev);const curSet=new Set(ent.se);for(const s of ent.se){if(!prevSet.has(s)){const el=document.querySelector(ent.sel);if(el){if(STATUS_BUFFS.has(s))vfx.buff(el);else vfx.debuff(el);}
break;}}
if(ent.key==='player'||ent.key.startsWith('a')){let cleansed=false;for(const s of prev){if(!curSet.has(s)&&!STATUS_BUFFS.has(s)){cleansed=true;break;}}
if(cleansed){const el=document.querySelector(ent.sel);if(el)vfx.heal(el);}}
_prevStatusState.set(ent.key,[...ent.se]);}
const prevConc=_prevStatusState.get('_conc')||'';const curConc=state.p?.conc||'';if(prevConc&&!curConc){const pEl=document.querySelector('.entity.player');if(pEl)vfx.debuff(pEl);vfx.flash('rgba(160,60,200,0.3)',400);const spellName=prevConc.replace(/_/g,' ');showNarration('💔 Concentração quebrada: '+spellName+'!','miss');vHaptic.heavy();}
_prevStatusState.set('_conc',curConc);}
function _showViewportFlash(){let flash=document.getElementById('viewportFlash');if(!flash){flash=document.createElement('div');flash.id='viewportFlash';flash.className='viewport-flash';document.body.appendChild(flash);}
flash.classList.remove('active');void flash.offsetWidth;flash.classList.add('active');setTimeout(()=>flash.classList.remove('active'),ValdoriaMotion.duration(400,200));}