if(typeof vPopup!=='undefined')vPopup.hide();
var tg=window.Telegram?.WebApp;if(tg){tg.ready();tg.expand();window.__valdoriaExitAction=function(){if(!currentState){stopAllIntervals();try{tg.close();}catch(e){console.warn('[COMBAT]',e);}return;}
closeCombat('back');};}
var _spaP=window.__spaRouteParams||{};var params=new URLSearchParams(window.location.search);if(_spaP){Object.keys(_spaP).forEach(function(k){if(!params.has(k))params.set(k,_spaP[k]);});}
var token=params.get('token')||'';var apiBase=params.get('api')||'';var userId=parseInt(params.get('uid')||'0');var rawData=params.get('data');var originApp=params.get('origin')||(apiBase?'game':'');var isApiMode=!!apiBase;var currentState=null;var _lastAnimatedRoll=null;var _initDiceAnimated=false;var _initAnimationInProgress=false;var _prevHpState=new Map();var _prevStatusState=new Map();var _prevPlayerHp=0;var _lastEnemyDmgType='slashing';var _audioCtx=null;var _audioUnlocked=false;var _currentPositions=null;var _cinematicInProgress=false;var _diceAnimating=false;var _cinematicWarnTimer=null;var _bonusHapticFired=false;var _reactionHapticFired=false;var _reactionAutoTimer=null;var _lastRenderedPhase=null;var _hitStreak=0;var _initDice3d=null;var _dmgDice3d=null;var TIMING={D20_ROLL:1200,D20_HOLD:800,MISS_HOLD:2400,SKIP_DELAY:500,CINEMATIC_WARN:5000,CINEMATIC_MAX:20000,POLL_ACTIVE:2000,POLL_ENEMY:3000,POLL_IDLE:5000,FLOAT_DELAY_FAST:2200,FLOAT_DELAY_NORMAL:3800,BASE_HIT:5200,BASE_MISS:2600,KILL_EXTENSION:1200,ANTICIPATION:350,TURN_BANNER:1800,ROUND_BANNER:1200,ENEMY_MISS_DELAY:1800,ENEMY_DMG_DELAY:2700,ENEMY_NARR_DELAY:2200,ENEMY_RESOLVE_MISS:2400,ENEMY_RESOLVE_HIT:4100,};function _shakeApp(intensity){const app=document.getElementById('app');if(!app)return;const cls=intensity==='heavy'?'shake-heavy':'shake-light';const dur=intensity==='heavy'?450:300;app.classList.remove('shake-light','shake-heavy');void app.offsetWidth;app.classList.add(cls);setTimeout(()=>app.classList.remove(cls),ValdoriaMotion.duration(dur,0));}
function _showImpactFlash(targetEl,isCrit){if(!targetEl)return;const rect=targetEl.getBoundingClientRect();const flash=document.createElement('div');flash.className='impact-flash'+(isCrit?' crit':'');flash.style.left=(rect.left+rect.width/2-(isCrit?35:25))+'px';flash.style.top=(rect.top+rect.height/2-(isCrit?35:25))+'px';flash.style.position='fixed';document.body.appendChild(flash);flash.addEventListener('animationend',()=>flash.remove());}
var _timerInterval=null;var _timerRemaining=0;var _timerMax=0;var _pollInterval=null;var _heartbeatInterval=null;class CombatAPI{constructor(base,tok,uid){this.base=base.replace(/\/$/,'');this.token=tok;this.userId=uid;}
_baseHeaders(){const h={'Content-Type':'application/json','Authorization':`Bearer ${this.token}`};if(window.Telegram?.WebApp?.initData){h['X-Telegram-Init-Data']=Telegram.WebApp.initData;}
return h;}
async getState(){const r=await fetchT(`${this.base}/api/combat/state`,{method:'POST',headers:this._baseHeaders(),body:JSON.stringify({user_id:this.userId}),});if(!r.ok){const body=await r.json().catch(()=>({}));if(body.status==='displaced'&&window.SessionHeartbeat){SessionHeartbeat.handleDisplaced(body.device||'');throw new Error('displaced');}
const err=new Error(body.error||`API ${r.status}`);err.status=r.status;throw err;}
return r.json();}
async checkHealth(){try{const r=await fetchT(`${this.base}/api/combat/health`,{method:'GET'});if(!r.ok)return{status:'unreachable'};return r.json();}catch(e){return{status:'unreachable'};}}
async sendAction(data){const h=this._baseHeaders();h['X-Idempotency-Key']=crypto.randomUUID();const r=await fetchT(`${this.base}/api/combat/action`,{method:'POST',headers:h,body:JSON.stringify({user_id:this.userId,...data}),});if(!r.ok){const body=await r.json().catch(()=>({}));if(body.status==='displaced'&&window.SessionHeartbeat){SessionHeartbeat.handleDisplaced(body.device||'');throw new Error('displaced');}
const err=new Error(body.error||`API ${r.status}`);err.status=r.status;throw err;}
return r.json();}}
var api=isApiMode?new CombatAPI(apiBase,token,userId):null;if(apiBase&&window.ApiDiscovery){ApiDiscovery.init(apiBase,function(newUrl){if(api)api.base=newUrl;});}
function b64Decode(str){const std=str.replace(/-/g,'+').replace(/_/g,'/');const pad=std.length%4;const padded=pad?std+'='.repeat(4-pad):std;const binary=atob(padded);const bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return new TextDecoder().decode(bytes);}
var BIOME_NAMES={forest:'Floresta',cave:'Caverna',graveyard:'Cemiterio',swamp:'Pantano',volcanic:'Vulcanico',snow:'Neve',desert:'Deserto',mountain:'Montanha',plains:'Planicie',dungeon:'Masmorra',city:'Cidade',ruins:'Ruinas',};var STATUS_ICONS={poisoned:'🧪',blinded:'🌑',paralyzed:'⚡',prone:'🦶',restrained:'🕸️',frightened:'😱',stunned:'💫',grappled:'👐',petrified:'🪨',exhausted:'😫',marked:'🎯',blessed:'✨',hexed:'👁️',burning:'🔥',frozen:'❄️',sleeping:'💤',charmed:'💖',deafened:'🔇',incapacitated:'🚫',invisible:'👻',surprised:'❗',exposed:'🎯',inspired:'🎵',concentrated:'🔮',raging:'💢',wild_shaped:'🐾',};var STATUS_PT={poisoned:'Envenenado',blinded:'Cego',paralyzed:'Paralisado',prone:'Derrubado',restrained:'Preso',frightened:'Amedrontado',stunned:'Atordoado',grappled:'Agarrado',petrified:'Petrificado',exhausted:'Exausto',marked:'Marcado',blessed:'Abençoado',hexed:'Amaldiçoado',burning:'Queimando',frozen:'Congelado',sleeping:'Dormindo',charmed:'Encantado',deafened:'Surdo',incapacitated:'Incapacitado',invisible:'Invisível',surprised:'Surpreso',exposed:'Exposto',inspired:'Inspirado',concentrated:'Concentrado',raging:'Furioso',wild_shaped:'Forma Selvagem',weakened:'Enfraquecido',cursed:'Amaldiçoado',corroded:'Corroído',mocked:'Provocado',enraged:'Enfurecido',regenerating:'Regenerando',slowed:'Lento',pushed:'Empurrado',};var STATUS_BUFFS=new Set(['blessed','inspired','invisible','raging','wild_shaped','concentrated','regenerating',]);var DMG_ICONS={slashing:'🗡️',piercing:'🏹',bludgeoning:'🔨',fire:'🔥',cold:'❄️',lightning:'⚡',necrotic:'💀',radiant:'✨',psychic:'🧠',thunder:'💥',poison:'🧪',acid:'🟢',force:'💠',};var ATK_TYPE_LABELS={melee:'Corpo a corpo',ranged:'À distância',magic:'Mágico'};var RES_CLASS_MAP={'Mana':'mp','Ki':'ki','Fúria':'fury','Vigor':'vigor','Inspiração':'inspiration','Pacto':'pact','Energia':'energy',};var RES_ICON_MAP={'Mana':'💧','Ki':'⚡','Fúria':'💢','Vigor':'💪','Inspiração':'🎵','Pacto':'👁️','Energia':'⚡',};if(window.ValdoriaErrors){ValdoriaErrors.init({appName:'COMBAT',apiBase:apiBase,token:token,uid:userId,});}
if(window.SessionHeartbeat&&apiBase&&token&&userId){SessionHeartbeat.init({apiBase:apiBase,token:token,uid:userId});}
window.addEventListener('session-reopened',function(e){console.debug('[COMBAT] Session reopened, reloading combat state');currentState=null;loadCombatState();});if(isApiMode){loadCombatState();}else if(rawData){try{const state=JSON.parse(b64Decode(rawData));currentState=state;renderArena(state);if(window._combatLoadingCtrl)window._combatLoadingCtrl.hide();}catch(e){console.error('[COMBAT]','Dados corrompidos',e);document.getElementById('app').innerHTML='<div class="no-data"><h2>Erro</h2><p>Dados de combate corrompidos.</p></div>';var lo=document.getElementById('combatLoading');if(lo){lo.classList.add('exit-cinematic');setTimeout(function(){lo.classList.add('hidden');},ValdoriaMotion.duration(950,400));}}}else{document.getElementById('app').innerHTML='<div class="no-data"><h2>Combate</h2><p>Nenhum dado recebido.</p></div>';var lo=document.getElementById('combatLoading');if(lo){lo.classList.add('exit-cinematic');setTimeout(function(){lo.classList.add('hidden');},ValdoriaMotion.duration(950,400));}}
async function loadCombatState(retryCount=0){try{const state=await api.getState();if(state.error==='no_combat'||state.phase==='ended'){showCombatEnded();return;}
currentState=state;if(state.phase&&!state.ph)state.ph=state.phase;renderArena(state);startHeartbeat();if(window._combatLoadingCtrl)window._combatLoadingCtrl.hide();}catch(e){if(retryCount<2){console.warn('[COMBAT] Load failed, retrying in 1.5s... (attempt '+(retryCount+1)+')');await new Promise(r=>setTimeout(r,1500));return loadCombatState(retryCount+1);}
console.error('[COMBAT]','Erro ao carregar',e);const health=await api.checkHealth();if(health.api&&health.api!==api.base){console.debug('[COMBAT] Tunnel URL changed, updating apiBase in memory');api.base=health.api;if(window.ApiDiscovery)ApiDiscovery.updateBase(health.api);}
if(health.status==='unreachable'){document.getElementById('app').innerHTML='<div class="no-data"><h2>Servidor Indisponível</h2><p>O servidor de combate não está respondendo. Tente novamente em alguns segundos.</p></div>';}else if(e.status===401||e.status===403){document.getElementById('app').innerHTML='<div class="no-data"><h2>Sessão Expirada</h2><p>Feche esta janela e reabra o combate no Telegram.</p></div>';}else{document.getElementById('app').innerHTML='<div class="no-data"><h2>Erro de Conexão</h2><p>Não foi possível carregar o combate.</p></div>';}
var lo=document.getElementById('combatLoading');if(lo){lo.classList.add('exit-cinematic');setTimeout(function(){lo.classList.add('hidden');},ValdoriaMotion.duration(950,400));}}}
function showCombatEnded(){stopAllIntervals();_initDiceAnimated=false;_initAnimationInProgress=false;if(typeof _clearStatusTracking==='function')_clearStatusTracking();document.getElementById('app').innerHTML='<div class="no-data"><h2>Combate Encerrado</h2><p>Este combate já foi finalizado.</p></div>';if(isApiMode&&originApp){setTimeout(()=>transitionFromArena('ended'),ValdoriaMotion.duration(1500,800));}else{setTimeout(()=>{try{if(tg)tg.close();}catch(e){console.warn('[COMBAT] tg.close() failed',e);}},2000);}}
function closeCombat(result){stopAllIntervals();if(isApiMode&&originApp){transitionFromArena(result);return;}
if(tg){window.__valdoria_close_sent=true;tg.sendData(JSON.stringify({action:'combat_close',token:token,result:result}));setTimeout(function(){try{if(tg.close)tg.close();}catch(e){console.warn('[COMBAT] tg.close() failed',e);}},1000);}}
async function transitionFromArena(result){const body={from:'combat',to:originApp,user_id:userId,payload:{result:result}};const _th={'Content-Type':'application/json','Authorization':`Bearer ${token}`};if(window.Telegram?.WebApp?.initData){_th['X-Telegram-Init-Data']=Telegram.WebApp.initData;}
_th['X-Idempotency-Key']=crypto.randomUUID();try{const resp=await fetchT(`${apiBase}/api/webapp/transition`,{method:'POST',headers:_th,body:JSON.stringify(body)});if(resp.ok){const data=await resp.json();if(data.url){window.__valdoria_transitioning=true;valdoriaSpaNav(data.url);return;}}
const errMsg=resp.status===401?'Sessão expirada — reabra o jogo':resp.status>=500?'Servidor indisponível — tente novamente':'Erro ao sair do combate';console.error('[COMBAT] Transition failed:',resp.status,errMsg);showError(errMsg+'. Fechando...');return;}catch(e){console.error('[COMBAT] Transition error:',e);}
showError('Erro de conexão. Fechando...');setTimeout(()=>{try{if(tg)tg.close();}catch(e){console.warn('[COMBAT] tg.close() failed',e);}},2000);}
async function transitionToLevelup(){const body={from:'combat',to:'levelup',user_id:userId,payload:{}};const _th={'Content-Type':'application/json','Authorization':`Bearer ${token}`};if(window.Telegram?.WebApp?.initData){_th['X-Telegram-Init-Data']=Telegram.WebApp.initData;}
_th['X-Idempotency-Key']=crypto.randomUUID();try{const resp=await fetchT(`${apiBase}/api/webapp/transition`,{method:'POST',headers:_th,body:JSON.stringify(body)});if(resp.ok){const data=await resp.json();if(data.url){window.__valdoria_transitioning=true;valdoriaSpaNav(data.url);return;}}
console.error('[COMBAT] Transition to levelup failed');}catch(e){console.error('[COMBAT] Transition to levelup error:',e);}
closeCombat('victory');}
async function transitionToInventoryFromArena(){const body={from:'combat',to:'inventory',user_id:userId,payload:{}};const _th={'Content-Type':'application/json','Authorization':`Bearer ${token}`};if(window.Telegram?.WebApp?.initData){_th['X-Telegram-Init-Data']=Telegram.WebApp.initData;}
_th['X-Idempotency-Key']=crypto.randomUUID();try{const resp=await fetchT(`${apiBase}/api/webapp/transition`,{method:'POST',headers:_th,body:JSON.stringify(body)});if(resp.ok){const data=await resp.json();if(data.url){window.__valdoria_transitioning=true;valdoriaSpaNav(data.url);return;}}
console.error('[COMBAT] Transition to inventory failed');}catch(e){console.error('[COMBAT] Transition to inventory error:',e);}}
function renderDeathSaveReplay(state,onComplete){stopAllIntervals();var app=document.getElementById('app');var dsHist=state.ds_history||[];var ds=state.ds||{s:0,f:0};var stabilized=ds.s>=3;var _replaySkipped=false;var trackerHtml='<div class="ds-tracker">';trackerHtml+='<div class="ds-row ds-row-success"><span class="ds-row-label">\u2714</span>';for(var i=0;i<3;i++)trackerHtml+='<div class="ds-dot success-slot" data-idx="'+i+'"></div>';trackerHtml+='</div>';trackerHtml+='<div class="ds-row ds-row-failure"><span class="ds-row-label">\u2718</span>';for(var i=0;i<3;i++)trackerHtml+='<div class="ds-dot failure-slot" data-idx="'+i+'"></div>';trackerHtml+='</div></div>';app.innerHTML='<div class="death-save-replay">'+'<div class="ds-header">\u2696\uFE0F Salvaguardas contra Morte</div>'+
trackerHtml+'<div class="ds-roll-display" id="dsRollDisplay"></div>'+'<div class="ds-roll-counter" id="dsRollCounter"></div>'+'<div class="ds-outcome" id="dsOutcome"></div>'+'<button class="v-skip-btn ds-skip" id="dsSkipBtn" style="display:none">Pular \u25B8</button>'+'</div>';if(typeof ValdoriaAudio!=='undefined')ValdoriaAudio.play('defeat');if(window._combatVfx)window._combatVfx.flash('rgba(120,20,20,0.35)',800);vHaptic.heavy();var skipBtn=document.getElementById('dsSkipBtn');setTimeout(function(){if(!_replaySkipped&&skipBtn)skipBtn.style.display='';},500);if(skipBtn)skipBtn.onclick=function(){if(_replaySkipped)return;_replaySkipped=true;skipBtn.style.display='none';_fillAllDotsInstant(dsHist);_showFinalOutcome();setTimeout(onComplete,1200);};function _fillAllDotsInstant(history){var si=0,fi=0;for(var h=0;h<history.length;h++){var roll=history[h];if(roll.crit){si++;}
else if(roll.crit_fail){fi=Math.min(fi+2,3);}
else if(roll.success){si++;}
else{fi++;}}
var sDots=document.querySelectorAll('.ds-dot.success-slot');var fDots=document.querySelectorAll('.ds-dot.failure-slot');for(var s=0;s<Math.min(si,3);s++){if(sDots[s])sDots[s].classList.add('filled');}
for(var f=0;f<Math.min(fi,3);f++){if(fDots[f])fDots[f].classList.add('filled');}}
function _showFinalOutcome(){var outcomeEl=document.getElementById('dsOutcome');if(!outcomeEl)return;if(stabilized){outcomeEl.innerHTML='<span class="ds-outcome-text ds-stabilized">\u2728 Estabilizado! Voc\u00EA acorda com 1 HP.</span>';if(window._combatVfx)window._combatVfx.flash('rgba(68,170,136,0.3)',500);}else{outcomeEl.innerHTML='<span class="ds-outcome-text ds-death">\uD83D\uDC80 Sucumbiu aos ferimentos...</span>';if(window._combatVfx)window._combatVfx.flash('rgba(200,30,30,0.4)',600);}
outcomeEl.classList.add('visible');}
var successIdx=0,failIdx=0;var rollIdx=0;function _animateNextRoll(){if(_replaySkipped||rollIdx>=dsHist.length){if(!_replaySkipped){_showFinalOutcome();setTimeout(function(){if(!_replaySkipped)onComplete();},ValdoriaMotion.duration(2000,1000));}
return;}
var roll=dsHist[rollIdx];var rollDisplay=document.getElementById('dsRollDisplay');var rollCounter=document.getElementById('dsRollCounter');if(rollCounter)rollCounter.textContent='Rolagem '+(rollIdx+1);var lr={t:'death_save',r:roll.r,d:0,crit:roll.crit,crit_fail:roll.crit_fail,success:roll.success};_initDiceDeathSave(lr);setTimeout(function(){if(_replaySkipped)return;var dotFilled=false;if(roll.crit){var sDots=document.querySelectorAll('.ds-dot.success-slot');if(sDots[successIdx]){sDots[successIdx].classList.add('filled','pulse');dotFilled=true;}
successIdx++;}else if(roll.crit_fail){var fDots=document.querySelectorAll('.ds-dot.failure-slot');for(var x=0;x<2&&failIdx<3;x++){if(fDots[failIdx]){fDots[failIdx].classList.add('filled','pulse');dotFilled=true;}
failIdx++;}}else if(roll.success){var sDots2=document.querySelectorAll('.ds-dot.success-slot');if(sDots2[successIdx]){sDots2[successIdx].classList.add('filled','pulse');dotFilled=true;}
successIdx++;}else{var fDots2=document.querySelectorAll('.ds-dot.failure-slot');if(fDots2[failIdx]){fDots2[failIdx].classList.add('filled','pulse');dotFilled=true;}
failIdx++;}
if(dotFilled)vHaptic.medium();if(rollDisplay){rollDisplay.textContent=roll.r;rollDisplay.className='ds-roll-display '+(roll.crit?'crit':roll.crit_fail?'crit-fail':roll.success?'success':'failure');}
rollIdx++;setTimeout(_animateNextRoll,ValdoriaMotion.duration(800,400));},2500);}
setTimeout(_animateNextRoll,ValdoriaMotion.duration(800,400));}
function renderResolution(state){stopAllIntervals();_initDiceAnimated=false;const isVictory=state.phase==='victory';const isFled=state.phase==='fled';if(typeof ValdoriaAudio!=='undefined'){if(isVictory&&!isFled){ValdoriaAudio.play('victory');}else if(!isVictory&&!isFled){ValdoriaAudio.play('defeat');}}
const rawText=state.result_text||state.action_result_text||'';const app=document.getElementById('app');let rewardsHtml='';let narrativeLines=[];const rewards=state.rewards;if(rewards&&isVictory&&!isFled){if(rewards.xp>0){rewardsHtml+=`<div class="res-reward"><span class="res-icon">⭐</span><span>+${rewards.xp} XP</span></div>`;}
if(rewards.gold>0){rewardsHtml+=`<div class="res-reward"><span class="res-icon">🪙</span><span>+${rewards.gold} GP</span></div>`;}
if(rewards.loot){rewards.loot.split('\n').filter(l=>l.trim()).forEach(item=>{rewardsHtml+=`<div class="res-reward"><span class="res-icon">🎁</span><span>${escHtml(item.trim())}</span></div>`;});}}else{const lines=rawText.split('\n').filter(l=>l.trim());lines.forEach(line=>{const trimmed=line.trim();if(/\+\d+\s*(XP|xp|EXP)/i.test(trimmed)){const match=trimmed.match(/\+?(\d+)\s*(XP|xp|EXP)/i);rewardsHtml+=`<div class="res-reward"><span class="res-icon">⭐</span><span>${match[1]} XP</span></div>`;}else if(/\d+\s*(GP|gp|gold|ouro)/i.test(trimmed)){const match=trimmed.match(/(\d+)\s*(GP|gp|gold|ouro)/i);rewardsHtml+=`<div class="res-reward"><span class="res-icon">🪙</span><span>${match[1]} GP</span></div>`;}else if(/nível|level.*up|subiu/i.test(trimmed)){rewardsHtml+=`<div class="res-reward res-levelup"><span class="res-icon">🎉</span><span>${escHtml(trimmed)}</span></div>`;}else if(/ganhou|obteve|recebeu|encontrou|drop/i.test(trimmed)){rewardsHtml+=`<div class="res-reward"><span class="res-icon">🎁</span><span>${escHtml(trimmed)}</span></div>`;}else{narrativeLines.push(trimmed);}});}
if(!narrativeLines.length&&rawText){rawText.split('\n').filter(l=>l.trim()).forEach(line=>{const t=line.trim();if(!/\+\d+\s*(XP|GP)/i.test(t))narrativeLines.push(t);});}
const narrativeHtml=narrativeLines.length>0?`<div class="res-narrative">${narrativeLines.map(l => escHtml(l)).join('<br>')}</div>`:'';let dsTrackerHtml='';if(!isVictory&&!isFled&&state.ds){const _ds=state.ds;const _stab=_ds.s>=3;let _tHtml='<div class="ds-tracker ds-tracker-result">';_tHtml+='<div class="ds-row ds-row-success"><span class="ds-row-label">\u2714</span>';for(let _i=0;_i<3;_i++)_tHtml+='<div class="ds-dot success-slot'+(_i<_ds.s?' filled':'')+'"></div>';_tHtml+='</div><div class="ds-row ds-row-failure"><span class="ds-row-label">\u2718</span>';for(let _i=0;_i<3;_i++)_tHtml+='<div class="ds-dot failure-slot'+(_i<_ds.f?' filled':'')+'"></div>';_tHtml+='</div></div>';const _outcomeText=_stab?'<div class="ds-outcome-inline ds-stabilized">\u2728 Estabilizado! Voc\u00ea acorda com 1 HP.</div>':'<div class="ds-outcome-inline ds-death">\uD83D\uDC80 Sucumbiu aos ferimentos...</div>';dsTrackerHtml='<div class="ds-summary">'+_tHtml+_outcomeText+'</div>';}
const rewardsBlock=rewardsHtml?`<div class="res-rewards">${rewardsHtml}</div>`:(isVictory?'<div class="res-rewards"><div class="res-reward"><span class="res-icon">\u2694\uFE0F</span><span>Combate encerrado</span></div></div>':(narrativeLines.length>0?'':'<div class="res-rewards"><div class="res-reward"><span class="res-icon">\u{1F4AB}</span><span>Você caiu em combate</span></div></div>'));const hasLevelUp=isVictory&&!isFled&&state.leveled_up&&isApiMode;let btnLabel=isVictory?'🏕️ Continuar Aventura':'💫 Continuar';if(isFled)btnLabel='🏕️ Continuar Aventura';const buttonsHtml=hasLevelUp?`<button class="action-btn primary res-continue res-levelup-btn" onclick="transitionToLevelup()">
               ⬆️ Distribuir Pontos!
           </button>
           <button class="action-btn secondary res-continue" onclick="closeCombat('${state.phase}')" style="margin-top:8px;opacity:0.7">
               🏕️ Pular
           </button>`:`<button class="action-btn primary res-continue" onclick="closeCombat('${state.phase}')">
               ${btnLabel}
           </button>`;app.innerHTML=`<div class="resolution-screen">
        <div class="res-header ${isFled ? 'victory' : (isVictory ? 'victory' : 'defeat')}">
            <div class="res-title">${isFled ? '🏃 FUGA!' : (isVictory ? '🏆 VITÓRIA!' : '💀 DERROTA')}</div>
        </div>
        ${dsTrackerHtml}
        ${narrativeHtml}
        ${rewardsBlock}
        ${buttonsHtml}
    </div>`;const rewardEls=app.querySelectorAll('.res-reward');const continueBtn=app.querySelector('.res-continue');if(rewardEls.length>0){rewardEls.forEach((el,i)=>{el.classList.add('reward-hidden');setTimeout(()=>{el.classList.remove('reward-hidden');el.classList.add('reward-reveal');vHaptic.select();},500+i*600);});if(continueBtn){continueBtn.classList.add('reward-hidden');setTimeout(()=>{continueBtn.classList.remove('reward-hidden');continueBtn.classList.add('reward-reveal');},500+rewardEls.length*600+400);}}else if(continueBtn){continueBtn.classList.add('reward-hidden');setTimeout(()=>{continueBtn.classList.remove('reward-hidden');continueBtn.classList.add('reward-reveal');},600);}var _resSkip=document.createElement('button');_resSkip.className='v-skip-btn';_resSkip.textContent='Pular >>';app.querySelector('.resolution-screen').appendChild(_resSkip);setTimeout(function(){_resSkip.classList.add('visible');},500);var _resSkipDone=false;_resSkip.onclick=function(){if(_resSkipDone)return;_resSkipDone=true;_resSkip.style.display='none';app.querySelectorAll('.reward-hidden').forEach(function(el){el.classList.remove('reward-hidden');el.classList.add('reward-reveal');});if(continueBtn){continueBtn.classList.remove('reward-hidden');continueBtn.classList.add('reward-reveal');}};
if(window._combatVfx){const headerEl=app.querySelector('.res-header');if(isVictory||isFled){if(headerEl){window._combatVfx.buff(headerEl);setTimeout(()=>window._combatVfx.buff(headerEl),ValdoriaMotion.duration(400,0));}
window._combatVfx.flash('rgba(255,215,0,0.25)',600);vHaptic.burst('crit');sfxCrit();}else{window._combatVfx.flash('rgba(120,20,20,0.35)',800);setTimeout(()=>window._combatVfx.flash('rgba(80,10,10,0.2)',600),ValdoriaMotion.duration(500,200));vHaptic.heavy();}}}
function renderArena(s){const app=document.getElementById('app');if(typeof ValdoriaAudio!=='undefined'&&!renderArena._musicStarted){renderArena._musicStarted=true;const _hasBoss=s.turn_order&&s.turn_order.some(e=>e.t==='e'&&parseInt(e.leg)>0);ValdoriaAudio.play(_hasBoss?'boss':'combat');}
const newPh=s.ph||s.phase||'intro';if(_lastRenderedPhase&&_lastRenderedPhase!==newPh&&!_cinematicInProgress){app.classList.add('phase-fade-out');setTimeout(()=>{app.classList.remove('phase-fade-out');app.classList.add('phase-fade-in');_lastRenderedPhase=newPh;_renderArenaInner(s);setTimeout(()=>app.classList.remove('phase-fade-in'),ValdoriaMotion.duration(300,0));},ValdoriaMotion.duration(300,0));return;}
_lastRenderedPhase=newPh;_renderArenaInner(s);}
function _renderArenaInner(s){if(_initDice3d&&(s.ph||s.phase||'intro')!=='intro'){_initDice3d.dispose();_initDice3d=null;}
if(!_cinematicInProgress&&!_actionSent){if(_dmgDice3d){_dmgDice3d.dispose();_dmgDice3d=null;}
const existingOverlay=document.getElementById('dmgDice3dOverlay');if(existingOverlay)existingOverlay.style.display='none';}
const app=document.getElementById('app');document.body.className=document.body.className.replace(/\bbiome-\S+/g,'').trim();document.body.classList.add('biome-'+(s.bio||'forest'));const biomeName=BIOME_NAMES[s.bio]||s.bio||'Desconhecido';const wLabel=s.w?s.w.l:'Limpo';const wIco=s.w?s.w.ico:'☀️';const wCls=s.w?_weatherClass(wLabel):'w-clear';const weatherStr=`<span class="weather-badge ${wCls}">${wIco} ${wLabel}</span>`;const activeTurn=s.to&&s.to[0]?s.to[0]:null;_currentPositions=s.positions||null;const ph=s.ph||s.phase||'intro';let html='';const biomeTitle=(ph==='init'||ph==='intro')?'Iniciativa':s.bio==='arena'?'Arena de Combate':s.bio==='dungeon'?'Combate na Masmorra':s.bio==='cave'?'Combate na Caverna':s.bio==='city'?'Combate na Cidade':'Combate';html+=`<div class="arena-header">
        <div class="arena-title">${biomeTitle}</div>
        <div class="arena-subtitle"><span class="round-badge">R${s.rn || 1}</span> ${biomeName} · ${weatherStr}</div>
    </div>`;html+='<div class="zone zone-enemies"><div class="zone-label">Inimigos</div>';if(s.e&&s.e.length>0){s.e.forEach((e,i)=>{const isActive=activeTurn&&activeTurn.t==='e'&&activeTurn.n===e.n;html+=renderEntity(e,'enemy',i,isActive);});}
html+='</div>';const isNarrative=s.vm==='simple';html+='<div class="battlefield">';if(ph==='intro'){html+='<div id="init-hero-area" class="init-hero-area">';html+='<div class="init-dice3d-wrap" id="initDice3dWrap"><div class="init-dice3d-particles" id="initDice3dParticles"></div><div class="init-dice3d-canvas" id="initDice3dCanvas"></div></div>';html+='<div class="init-hero-result" id="initHeroResult"></div>';html+='<button class="init-hero-btn" id="initHeroBtn" data-action="initiative">ROLAR INICIATIVA</button>';html+='<div class="init-hero-subtitle">Toque para determinar a ordem de combate</div>';html+='</div>';}else{html+=renderTurnTimeline(s.to);}
if(s.feed&&s.feed.length>0){const total=s.feed.length;const visibleCount=isNarrative?6:3;const recentFeed=s.feed.slice(-visibleCount);const roundBadge=s.rn&&s.rn>1?'<div class="feed-round-badge">Rodada '+s.rn+'</div>':'';const narrativeCls=isNarrative?' combat-feed-narrative':'';const lastFeedClass=_classifyFeed(s.feed[s.feed.length-1]);const autoExpand=total>visibleCount&&(lastFeedClass==='feed-crit'||lastFeedClass==='feed-kill');html+=`<div class="combat-feed${narrativeCls}${autoExpand ? ' feed-expanded' : ''}" id="combatFeed">${roundBadge}`;if(total>visibleCount){const older=s.feed.slice(0,-visibleCount);older.forEach((f,fi)=>{var fd=s.fd&&fi<(s.fd.length||0)?s.fd[fi]:null;var detailStr=fd?_formatFeedDetail(fd):'';var hasDetail=detailStr.length>0;html+='<div class="feed-entry feed-hidden '+_classifyFeed(f)+(hasDetail?' has-detail':'')+'"'+(hasDetail?' data-detail="'+escHtml(detailStr)+'"':'')+'>'+escHtml(f);if(hasDetail)html+='<span class="feed-expand-icon">\u25b8</span>';html+='</div>';});}
recentFeed.forEach((f,fi)=>{var feedIdx=total-visibleCount+fi;var fd=s.fd&&feedIdx<s.fd.length?s.fd[feedIdx]:null;var detailStr=fd?_formatFeedDetail(fd):'';var hasDetail=detailStr.length>0;html+='<div class="feed-entry '+_classifyFeed(f)+(hasDetail?' has-detail':'')+'"'+(hasDetail?' data-detail="'+escHtml(detailStr)+'"':'')+'>'+escHtml(f);if(hasDetail)html+='<span class="feed-expand-icon">\u25b8</span>';html+='</div>';});if(total>visibleCount){const toggleLabel=autoExpand?'▼ Recolher':`▲ Mostrar +${total - visibleCount} anteriores`;html+=`<div class="feed-toggle" id="feedToggle">${toggleLabel}</div>`;}
html+='</div>';}
html+='</div>';html+='<div class="zone zone-player"><div class="zone-label">Seu Personagem</div>';html+=renderPlayerCard(s.p,ph==='init'||ph==='intro');html+='</div>';if(s.a&&s.a.length>0){html+='<div class="zone zone-allies"><div class="zone-label">Aliados</div>';s.a.forEach((a,i)=>{const isActive=activeTurn&&activeTurn.t==='a'&&activeTurn.n===a.n;html+=renderEntity(a,'ally',i,isActive);});html+='</div>';}
let _actionToastHtml='';if(s.feed&&s.feed.length>0&&ph==='active'){const lastFeed=s.feed[s.feed.length-1];const cls=_classifyFeed(lastFeed);var toastDetail='';if(s.lr&&s.lr.bk&&s.lr.bk.length>0){var bkStr=s.lr.bk.map(function(p){return(p.v>=0?'+':'')+p.v+' '+p.l;}).join(' ');var hitMiss=s.lr.miss?'\u274c':(s.lr.crit?'\u203c\ufe0f':'\u2705');toastDetail='<div class="toast-detail">d20('+(s.lr.r||'?')+') '+bkStr+' = '+(s.lr.total||s.lr.r)+(s.lr.ac?' vs CA '+s.lr.ac:'')+' '+hitMiss+'</div>';}
_actionToastHtml='<div class="action-toast '+cls+'" id="actionToast">'+escHtml(lastFeed)+toastDetail+'</div>';}
const subPh=s.sub_phase||'';if(subPh!=='bonus_action')_bonusHapticFired=false;if(subPh!=='reaction'){_reactionHapticFired=false;if(_reactionAutoTimer){clearTimeout(_reactionAutoTimer);_reactionAutoTimer=null;}}
const isUnconscious=s.unconscious||(s.p&&s.p.hp<=0);if(ph==='active'&&isUnconscious){const ds=s.ds||{s:0,f:0};let dsHtml='<div class="ds-tracker ds-tracker-compact">';dsHtml+='<div class="ds-row ds-row-success"><span class="ds-row-label">\u2714</span>';for(let _si=0;_si<3;_si++)dsHtml+='<div class="ds-dot success-slot'+(_si<ds.s?' filled':'')+'"></div>';dsHtml+='</div><div class="ds-row ds-row-failure"><span class="ds-row-label">\u2718</span>';for(let _fi=0;_fi<3;_fi++)dsHtml+='<div class="ds-dot failure-slot'+(_fi<ds.f?' filled':'')+'"></div>';dsHtml+='</div></div>';const stab=ds.stab?'<div class="spectator-detail">🩹 Estabilizado — aguardando socorro</div>':'';html+=`<div class="action-bar spectator-bar">
            <div class="spectator-msg">💀 <b>Inconsciente</b> — Teste contra a Morte</div>
            ${dsHtml}
            ${stab}
            <button class="action-btn primary full-width" data-action="continue_spectator" style="margin-top:6px">⏭️ Próximo Round</button>
        </div>`;}else if(ph==='active'&&subPh==='bonus_action'){if(!_bonusHapticFired){_bonusHapticFired=true;vHaptic.medium();}
html+=renderTimerBar(s);html+=renderBonusActionBar(s.acts,s.e,s.p,_actionToastHtml);}else if(ph==='active'&&subPh==='reaction'){if(!_reactionHapticFired){_reactionHapticFired=true;vHaptic.warning();if(_reactionAutoTimer)clearTimeout(_reactionAutoTimer);_reactionAutoTimer=setTimeout(()=>{if(currentState&&(currentState.sub_phase||'')==='reaction'){var _rBar=document.querySelector('.reaction-header');if(_rBar&&_rBar.offsetParent!==null){sendAction({type:'reaction_skip'});}else{clearTimeout(_reactionAutoTimer);_reactionAutoTimer=null;}}},10000);}
html+=renderTimerBar(s);html+=renderReactionBar(s.acts,s.p,_actionToastHtml);}else if(ph==='active'){html+=renderTimerBar(s);html+=renderActionBar(s.acts,s.e,s.p,_actionToastHtml);}else if(ph==='intro'&&isApiMode){if(s.can_restore){html+=`<div class="action-bar"><button class="action-btn primary full-width" data-action="restore" style="font-size:14px;padding:12px">🔄 Restaurar Combate</button></div>`;}}else if(ph==='init'){html+='<div id="init-dice-area"></div>';if(isApiMode){html+=`<div class="action-bar" id="init-proceed-bar" style="display:none"><button class="action-btn primary full-width" data-action="proceed" style="font-size:14px;padding:12px">⚔️ Prosseguir para o Combate</button></div>`;}else{html+=`<div class="action-bar"><div style="text-align:center;color:var(--v-text-dim);font-size:12px;padding:8px">⚔️ Aguardando inicio do combate...</div></div>`;}}else{html+=`<div class="action-bar"><div class="action-loading"><div class="loading-d20-icon"></div><span>Definindo iniciativa<span class="loading-dots"></span></span></div></div>`;}
app.classList.remove('fade-in');app.innerHTML=html;void app.offsetWidth;app.classList.add('fade-in');_ensureDiceOverlay();initDice(s.lr);_triggerInitiativeDice(s);const heroBtn=document.getElementById('initHeroBtn');if(heroBtn){const d3dCanvas=document.getElementById('initDice3dCanvas');const d3dPart=document.getElementById('initDice3dParticles');if(d3dCanvas&&typeof Dice3D!=='undefined'){if(_initDice3d){_initDice3d.dispose();_initDice3d=null;}
try{_initDice3d=new Dice3D(d3dCanvas,{size:200,particlesContainer:d3dPart});}
catch(e){console.warn('[COMBAT] Dice3D init failed:',e);}}
heroBtn.addEventListener('click',()=>{_animateInitiativeHero();});}
bindActions(s);if(isOverlayOpen()){document.querySelectorAll('.skill-overlay, .target-overlay, .item-overlay').forEach(o=>o.classList.remove('active'));}
bindExpandCollapse();bindFeedToggle();bindFeedDetail();_scrollTimelineToActive();const _feed=document.getElementById('combatFeed');if(_feed)_feed.scrollTop=_feed.scrollHeight;_animateHpBars(s);_checkPlayerDamage(s);_checkStatusChanges(s);if(activeTurn&&ph!=='init'&&ph!=='intro'){if(activeTurn.t!=='p'){const activeEl=document.querySelector('.entity.active-turn');if(activeEl&&!activeEl.classList.contains('dead'))activeEl.classList.add('expanded');}}
if(ph==='active'&&s.timer>0){startTimer(s.timer);}else{stopTimer();}
if(isApiMode&&(ph==='active'||ph==='init'||ph==='intro')){startPolling();}else{stopPolling();}}
function renderTimerBar(s){if(!s.timer||s.timer<=0)return'';return`<div class="turn-timer">
        <div class="timer-bar" id="timerBar" style="width:100%"></div>
        <span class="timer-text" id="timerText">${Math.ceil(s.timer)}s</span>
    </div>`;}
var _timerDeadline=0;function startTimer(seconds){stopTimer();_timerMax=seconds;_timerRemaining=seconds;_timerDeadline=Date.now()+seconds*1000;_timerInterval=setInterval(()=>{_timerRemaining=Math.max(0,(_timerDeadline-Date.now())/1000);const bar=document.getElementById('timerBar');const text=document.getElementById('timerText');if(!bar||!text){stopTimer();return;}
if(_timerRemaining<=0){bar.style.width='0%';text.textContent='⏳ Turno perdido';bar.classList.add('critical');_showTimerExpiredToast();stopTimer();if(isApiMode&&api){setTimeout(()=>{_pollForTimerResult();},1500);}
return;}
const pct=Math.max(0,(_timerRemaining/_timerMax)*100);bar.style.width=pct+'%';text.textContent=Math.ceil(_timerRemaining)+'s';if(_timerRemaining<=5){bar.classList.remove('warning');bar.classList.add('critical');text.classList.add('critical');}else if(pct<=40){bar.classList.add('warning');}
if(_timerRemaining<=3&&_timerRemaining>0){sfxTimerTick();vHaptic.tap();}},1000);}
function stopTimer(){if(_timerInterval){clearInterval(_timerInterval);_timerInterval=null;}}
function _onVisibilityChange(){if(!document.hidden){if(_cinematicInProgress){_cinematicInProgress=false;if(typeof _cinematicWarnTimer!=='undefined')clearTimeout(_cinematicWarnTimer);}}if(document.hidden||!_timerInterval||!_timerDeadline)return;const remaining=Math.max(0,(_timerDeadline-Date.now())/1000);_timerRemaining=remaining;if(remaining<=0){const bar=document.getElementById('timerBar');const text=document.getElementById('timerText');if(bar){bar.style.width='0%';bar.classList.add('critical');}
if(text){text.textContent='⏳ Turno perdido';}
_showTimerExpiredToast();stopTimer();if(isApiMode&&api){setTimeout(()=>{_pollForTimerResult();},500);}}}
document.addEventListener('visibilitychange',_onVisibilityChange);function _showTimerExpiredToast(){vHaptic.error();_shakeApp('light');const el=document.createElement('div');el.className='timer-toast';const msg='⏳ Tempo esgotado — turno perdido!';el.textContent=msg;document.body.appendChild(el);const dur=(typeof calcReadTime==='function')?calcReadTime(msg,'toast-warn'):3000;setTimeout(()=>el.classList.add('visible'),50);setTimeout(()=>{el.classList.remove('visible');setTimeout(()=>el.remove(),300);},dur);}
async function _pollForTimerResult(){if(!isApiMode||!api)return;const maxRetries=5;const interval=2000;for(let i=0;i<maxRetries;i++){try{const state=await api.getState();if(!state||state.error){if(state&&(state.error==='no_combat'||state.phase==='ended')){showCombatEnded();return;}
await new Promise(r=>setTimeout(r,interval));continue;}
const newPh=state.ph||state.phase||'';const newTc=state.tc||0;const oldTc=currentState?(currentState.tc||0):0;if(newTc!==oldTc||newPh==='victory'||newPh==='defeat'){currentState=state;if(newPh==='victory'||newPh==='defeat'||newPh==='ended'){renderResolution(state);}else{renderArena(state);}
return;}}catch(e){console.warn('[COMBAT] Timer poll retry',i,e.message);}
await new Promise(r=>setTimeout(r,interval));}
startPolling();}
function _getPollInterval(){if(!currentState||!currentState.active_turn)return 5000;if(currentState.unconscious||(currentState.p&&currentState.p.hp<=0))return 2000;return currentState.active_turn.type==='player'?8000:2000;}
var _pollFailures=0;function startPolling(){stopPolling();if(!isApiMode||!api)return;const poll=async()=>{if(document.visibilityState==="hidden"){_pollInterval=setTimeout(poll,_getPollInterval());return;}try{const state=await api.getState();_pollFailures=0;if(!state||state.error){if(state&&state.error==='invalid_session'){showError('Sessão expirada — feche e reabra o combate');stopPolling();return;}
if(state&&(state.error==='no_combat'||state.phase==='ended')){showCombatEnded();}
_pollInterval=setTimeout(poll,_getPollInterval());return;}
if(!state){_pollInterval=setTimeout(poll,8000);return;}
const newPh=state.ph||state.phase||'';const oldPh=currentState?(currentState.ph||currentState.phase||''):'';const newRn=state.rn||0;const oldRn=currentState?(currentState.rn||0):0;const newTc=state.tc||0;const oldTc=currentState?(currentState.tc||0):0;const hpHash=(s)=>{if(!s)return'';const ph=s.p?s.p.hp:0;const eh=(s.e||[]).map(e=>e.hp).join(',');return`${ph}:${eh}`;};const newHp=hpHash(state);const oldHp=hpHash(currentState);if(state.timer_expired&&!currentState?.timer_expired){_showTimerExpiredToast();}
if(newPh!==oldPh||newRn!==oldRn||newTc!==oldTc||newHp!==oldHp){if(_cinematicInProgress||_initAnimationInProgress||_diceAnimating||isOverlayOpen()||_actionSent){_pollInterval=setTimeout(poll,_getPollInterval());return;}
const oldTurn=currentState?.to?.[0];const newTurn=state.to?.[0];const turnChanged=oldTurn&&newTurn&&(oldTurn.n!==newTurn.n||oldTurn.t!==newTurn.t);if(turnChanged){let actionDesc='';if((newTurn.t==='e'||newTurn.t==='a')&&state.lr){const sn=state.lr.sn;if(sn){actionDesc=` usa ${sn}!`;}else{actionDesc=state.lr.t==='skill'||state.lr.t==='save'?' conjura!':' ataca!';}}
const bannerText=newTurn.t==='p'?'⚔️ Seu Turno!':newTurn.t==='e'?`🎯 ${newTurn.n}${actionDesc}`:`🛡️ ${newTurn.n}${actionDesc}`;const bannerType=newTurn.t==='p'?'player':newTurn.t==='e'?'enemy':'ally';_showTurnBanner(bannerText,bannerType);}
if(newRn>oldRn&&newRn>1){setTimeout(()=>_showRoundBanner(newRn),turnChanged?1600:200);}
const hasEnemyRoll=state.lr&&(state.lr.r||state.lr.d)&&newTurn&&newTurn.t!=='p';const rollSig=state.lr?`${state.lr.t||'a'}-${state.lr.r||0}-${state.lr.d||0}-${state.lr.miss||0}-${state.lr.crit||0}-${state.lr.dc||0}-${state.lr.adv||0}-${state.lr.ac||0}`:'';if(hasEnemyRoll&&rollSig!==_lastAnimatedRoll){_cinematicInProgress=true;_cinematicWarnTimer=setTimeout(()=>{if(_cinematicInProgress)vToast('Processando...','ok');},TIMING.CINEMATIC_WARN);const _eLr=state.lr;const _isAllyTurn=newTurn&&newTurn.t==='a';if(!_isAllyTurn&&_eLr.dt)_lastEnemyDmgType=_eLr.dt;initDice(_eLr);if(_eLr.miss||_eLr.d<=0){setTimeout(()=>{const dodgeTarget=_isAllyTurn?document.querySelector('.entity.enemy'):document.querySelector('.entity.player');if(dodgeTarget){dodgeTarget.classList.remove('dodge-flash');void dodgeTarget.offsetWidth;dodgeTarget.classList.add('dodge-flash');setTimeout(()=>dodgeTarget.classList.remove('dodge-flash'),400);}
_showMissFloat(_isAllyTurn?'.entity.enemy':'.entity.player');if(window._combatVfx){const fromEl=_isAllyTurn?(document.querySelector('.entity.ally')||document.querySelector('.entity.player')):document.querySelector('.entity.enemy');if(fromEl&&dodgeTarget)window._combatVfx.miss(fromEl,dodgeTarget,_eLr.dt||'slashing');}
showNarration(_pick(_isAllyTurn?_NARR_ALLY_MISS:_NARR_ENEMY_MISS).replace('{name}',newTurn.n),'miss');if(_isAllyTurn)vHaptic.burst('miss');},1800);}else{const dmgTarget=_isAllyTurn?'.entity.enemy':'.entity.player';setTimeout(()=>_showDamageFloat(_eLr.d,_eLr.dt,dmgTarget,!!_eLr.crit),TIMING.ENEMY_DMG_DELAY);if(_isAllyTurn&&window._combatVfx){setTimeout(()=>{const allyEl=document.querySelector('.entity.ally')||document.querySelector('.entity.player');const enemyEl=document.querySelector('.entity.enemy');if(allyEl&&enemyEl)window._combatVfx.projectile(allyEl,enemyEl,_eLr.dt||'slashing',{crit:!!_eLr.crit});},1600);}
if(!_isAllyTurn&&window._combatVfx){setTimeout(()=>{const enemyEl=document.querySelector('.entity.enemy');const playerEl=document.querySelector('.entity.player');if(enemyEl&&playerEl)window._combatVfx.projectile(enemyEl,playerEl,_eLr.dt||'slashing',{crit:!!_eLr.crit});},1600);}
setTimeout(()=>{if(_isAllyTurn&&_eLr.crit){showNarration(_pick(_NARR_ALLY_CRIT).replace('{name}',newTurn.n),'crit');_shakeApp('heavy');vHaptic.burst('crit');}else if(_isAllyTurn){showNarration(_pick(_NARR_ALLY_HIT).replace('{name}',newTurn.n),'');vHaptic.medium();}else if(_eLr.crit){showNarration(_pick(_NARR_ENEMY_CRIT),'crit');_shakeApp('heavy');vHaptic.heavy();vHaptic.error();}else{showNarration(_pick(_NARR_ENEMY_HIT),'');}},2200);}
const enemyDelay=(_eLr.miss||_eLr.d<=0)?TIMING.ENEMY_RESOLVE_MISS:TIMING.ENEMY_RESOLVE_HIT;setTimeout(()=>{_cinematicInProgress=false;currentState=state;if(newPh==='victory'||newPh==='defeat'||newPh==='ended'){renderResolution(state);}else{renderArena(state);}},enemyDelay);_pollInterval=setTimeout(poll,_getPollInterval());return;}
_showPollUpdateIndicator();if(oldPh==='init'&&newPh!=='init'){_initDiceAnimated=false;_initAnimationInProgress=false;}
currentState=state;if(newPh==='victory'||newPh==='defeat'||newPh==='ended'){renderResolution(state);}else{renderArena(state);}}}catch(e){if(e.status===401||e.status===403||(e.message&&e.message.includes('401'))){showError('Sessão expirada — feche e reabra o combate');stopPolling();return;}
console.warn('[COMBAT] Poll error (silent)',e.message);_pollFailures++;if(_pollFailures>=3){console.warn('[COMBAT] 3+ consecutive poll failures — checking health');try{const health=await api.checkHealth();if(health.api&&health.api!==api.base){console.debug('[COMBAT] Tunnel URL changed, updating apiBase in memory');api.base=health.api;if(window.ApiDiscovery)ApiDiscovery.updateBase(health.api);_pollFailures=0;}
if(health.status==='unreachable'){showError('Servidor indisponível. Tente novamente.');}}catch(he){console.warn('[COMBAT] Health check also failed',he.message);}
_pollFailures=0;}}
_pollInterval=setTimeout(poll,_getPollInterval());};_pollInterval=setTimeout(poll,_getPollInterval());}
function stopPolling(){if(_pollInterval){clearTimeout(_pollInterval);_pollInterval=null;}}
function _showPollUpdateIndicator(){const el=document.createElement('div');el.className='poll-update-indicator';el.textContent='🔄 Estado atualizado';document.body.appendChild(el);setTimeout(()=>el.classList.add('visible'),20);setTimeout(()=>{el.classList.remove('visible');setTimeout(()=>el.remove(),ValdoriaMotion.duration(300,0));},ValdoriaMotion.duration(1500,800));}
function startHeartbeat(){stopHeartbeat();if(!isApiMode||!api)return;_heartbeatInterval=setInterval(async()=>{if(document.visibilityState==="hidden")return;try{const state=await api.getState();if(state&&state.error==='invalid_session'){showError('Sessão expirada — feche e reabra o combate');stopHeartbeat();}}catch(e){if(e.message&&e.message.includes('401')){showError('Sessão expirada — feche e reabra o combate');stopHeartbeat();}}},600000);}
function stopHeartbeat(){if(_heartbeatInterval){clearInterval(_heartbeatInterval);_heartbeatInterval=null;}}
function stopAllIntervals(){stopTimer();stopPolling();stopHeartbeat();if(_reactionAutoTimer){clearTimeout(_reactionAutoTimer);_reactionAutoTimer=null;}
window.addEventListener('pagehide',function(){stopAllIntervals();});
if(_cinematicWarnTimer){clearTimeout(_cinematicWarnTimer);_cinematicWarnTimer=null;}
if(_dmgDice3d){_dmgDice3d.dispose();_dmgDice3d=null;}
if(_initDice3d){_initDice3d.dispose();_initDice3d=null;}
_initAnimationInProgress=false;_cinematicInProgress=false;document.removeEventListener('visibilitychange',_onVisibilityChange);}
function renderTurnTimeline(to){if(!to||to.length===0)return'';let html='<div class="turn-timeline">';to.forEach((entry,i)=>{const isFirst=i===0;const tCls=entry.t==='p'?'t-player':entry.t==='a'?'t-ally':'t-enemy';const isDead=entry.hp!==undefined&&entry.hp<=0;const deadCls=isDead?' dead':'';if(i>0)html+='<div class="turn-arrow">·</div>';const ico=entry.ico||(entry.t==='p'?'⚔️':entry.t==='a'?'🛡️':'👹');if(entry.t!=='e'&&i<to.length-1){const nextE=to[i+1];const _legCount=nextE?(parseInt(nextE.leg)||0):0;if(_legCount>0){for(let li=0;li<Math.min(_legCount,5);li++){html+='<div class="turn-arrow">\u00b7</div>';html+='<div class="turn-entry t-legendary"><span class="turn-ico">\u2B50</span></div>';}}}
html+=`<div class="turn-entry ${isFirst ? 'active' : ''} ${tCls}${deadCls}">
            <span class="turn-ico">${ico}</span>
        </div>`;});html+='</div>';return html;}
function _scrollTimelineToActive(){const timeline=document.querySelector('.turn-timeline');const active=timeline&&timeline.querySelector('.turn-entry.active');if(active&&timeline){const tl=timeline.getBoundingClientRect();const ac=active.getBoundingClientRect();const offset=ac.left-tl.left-(tl.width/2)+(ac.width/2);timeline.scrollBy({left:offset,behavior:'smooth'});}}
function _animateInitiativeHero(){const area=document.getElementById('init-hero-area');if(!area)return;const btn=document.getElementById('initHeroBtn');if(btn)btn.disabled=true;area.classList.add('rolling');const fakeRoll=Math.floor(Math.random()*20)+1;if(_initDice3d){const duration=_initDice3d.roll(fakeRoll,()=>{setTimeout(()=>{sendAction({type:'initiative'});},ValdoriaMotion.duration(600,300));});}else{setTimeout(()=>{sendAction({type:'initiative'});},ValdoriaMotion.duration(1200,600));}}
function _triggerInitiativeDice(s){const area=document.getElementById('init-dice-area');if(!area||!s.to||s.to.length===0)return;const ph=s.ph||s.phase||'';if(ph!=='init')return;const items=s.to.map(entry=>({sides:20,result:entry.v,label:entry.n,type:entry.t==='p'?'player':entry.t==='a'?'ally':'enemy',icon:entry.ico||(entry.t==='p'?'\u{1F464}':entry.t==='a'?'\u{1F6E1}':'\u{1F479}'),formula:entry.f||'',}));const init=s.initiative||{};if(_initDiceAnimated){_showInitiativeStatic(area,items,init);_showProceedBar();return;}
_initDiceAnimated=true;_initAnimationInProgress=true;if(typeof DiceRoller!=='undefined'){DiceRoller.rollSequence(items,{container:area,title:'\u{1F4DC} ORDEM DE COMBATE',onComplete:()=>{_initAnimationInProgress=false;_appendSurpriseInfo(area,init);_showProceedBar();},});setTimeout(()=>{const bar=document.getElementById('init-proceed-bar');const currentArea=document.getElementById('init-dice-area');if(bar&&bar.style.display==='none'&&currentArea){const skipBtn=document.createElement('button');skipBtn.className='v-skip-btn visible';skipBtn.textContent='Pular \u{25B8}';skipBtn.style.cssText='position:relative; z-index:10; margin:8px auto;display:block;padding:6px 16px;font-size:12px;background:rgba(255,255,255,0.08);border:1px solid rgba(255,255,255,0.15);border-radius:6px;color:#aaa;cursor:pointer; clear:both;';skipBtn.onclick=()=>{_initAnimationInProgress=false;_showInitiativeStatic(currentArea,items,init);_showProceedBar();skipBtn.remove();};currentArea.appendChild(skipBtn);}},800);}else{_showInitiativeStatic(area,items,init);_showProceedBar();}}
function _showInitiativeStatic(area,items,init){let html='<div style="padding:4px 10px;font-size:11px;color:var(--v-text-dim)">';html+='<div style="font-weight:700;color:var(--v-gold);font-size:12px;margin-bottom:4px">\u{1F4DC} ORDEM DE COMBATE</div>';items.forEach((entry,i)=>{const tColor=entry.type==='player'?'var(--v-gold)':entry.type==='ally'?'var(--v-silver)':'var(--v-crimson)';const formula=entry.formula?` (${entry.formula})`:'';html+=`<div style="padding:2px 0;color:${tColor}">
            ${i + 1}. ${entry.icon} <b>${escHtml(entry.label)}</b>: ${entry.result}${formula}
        </div>`;});_appendSurpriseHtml(html,init);html+='</div>';area.innerHTML=html;}
function _appendSurpriseInfo(area,init){if(!init.player_surprised&&!init.enemies_surprised)return;const div=document.createElement('div');div.style.cssText='padding:0 10px;font-size:11px';var _surpriseHtml='';if(init.player_surprised)_surpriseHtml+='<div style="color:var(--v-crimson);margin-top:4px">\u2757 Você foi pego desprevenido!</div>';if(init.enemies_surprised)_surpriseHtml+='<div style="color:var(--v-gold);margin-top:4px">\u2728 Inimigos surpreendidos!</div>';if(_surpriseHtml)div.innerHTML+=_surpriseHtml;area.appendChild(div);}
function _appendSurpriseHtml(html,init){if(init.player_surprised)html+='<div style="color:var(--v-crimson);margin-top:4px">\u2757 Você foi pego desprevenido!</div>';if(init.enemies_surprised)html+='<div style="color:var(--v-gold);margin-top:4px">\u2728 Inimigos surpreendidos!</div>';}
function _showProceedBar(){const bar=document.getElementById('init-proceed-bar');if(bar)bar.style.display='';}
var _DMG_FLASH_TYPES=new Set(['fire','cold','lightning','necrotic','radiant','poison','acid','psychic','thunder']);var _origShowError=window.showError;window.showError=function(msg,err){_actionSent=false;document.querySelectorAll('.action-btn').forEach(b=>b.classList.remove('disabled'));if(_origShowError)_origShowError(msg,err);};