var DMG_TYPE_COLORS={fire:'#ff6020',cold:'#80c0ff',lightning:'#ffe040',necrotic:'#9040c0',radiant:'#ffe080',poison:'#60c040',acid:'#60d040',psychic:'#e080ff',thunder:'#a0c0ff',force:'#c0a0ff',slashing:'#ff4444',piercing:'#ff4444',bludgeoning:'#ff6644',magic:'#c060ff'};
var _PARTICLE_COLORS={slashing:['#e0e0e0','#d4c060'],piercing:['#b0c8e0','#d4c060'],bludgeoning:['#c0b080','#e0d080'],fire:[DMG_TYPE_COLORS.fire,'#ff9020','#ffd040'],cold:[DMG_TYPE_COLORS.cold,'#c0e8ff'],lightning:[DMG_TYPE_COLORS.lightning,'#ffffff'],necrotic:[DMG_TYPE_COLORS.necrotic,'#604080'],radiant:[DMG_TYPE_COLORS.radiant,'#ffffff'],psychic:[DMG_TYPE_COLORS.psychic,'#c060d0'],thunder:['#a0a0e0','#ffffff'],poison:[DMG_TYPE_COLORS.poison,'#80e040'],acid:[DMG_TYPE_COLORS.acid,'#c0ff40'],force:['#60c0ff','#a0e0ff'],magic:[DMG_TYPE_COLORS.magic,'#60c0ff'],};function spawnParticles(isCrit,damageType){const colors=_PARTICLE_COLORS[damageType]||_PARTICLE_COLORS['slashing'];const count=isCrit?12:7;const cx=window.innerWidth/2;const cy=window.innerHeight/2;for(let i=0;i<count;i++){const p=document.createElement('div');p.className='hit-particle';const angle=(Math.PI*2*i)/count+(Math.random()-0.5)*0.8;const dist=30+Math.random()*(isCrit?60:40);const tx=Math.cos(angle)*dist;const ty=Math.sin(angle)*dist-20;const dur=0.4+Math.random()*0.3;const color=colors[Math.floor(Math.random()*colors.length)];const size=isCrit?8:5;p.style.cssText=`left:${cx}px;top:${cy}px;background:${color};--p-tx:${tx}px;--p-ty:${ty}px;--p-dur:${dur}s;width:${size}px;height:${size}px;`;document.body.appendChild(p);setTimeout(()=>p.remove(),dur*1000+100);}}
function _pick(arr){return arr[Math.floor(Math.random()*arr.length)];}
function showNarration(text,cssClass){const el=document.getElementById('diceNarration');if(!el)return;if(el.classList.contains('visible')){setTimeout(()=>showNarration(text,cssClass),typeof calcReadTime==='function'?calcReadTime(el.textContent,'combat'):1200);return;}
el.textContent=text;el.className='dice-narration '+(cssClass||'');void el.offsetWidth;el.classList.add('visible');}
function escHtml(str){if(!str)return'';return String(str).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function _weatherClass(label){if(!label)return'w-clear';const l=label.toLowerCase();if(l.includes('chuva')||l.includes('garoa'))return'w-rain';if(l.includes('tempest')||l.includes('raio')||l.includes('trovão'))return'w-storm';if(l.includes('neve')||l.includes('gelo')||l.includes('granizo'))return'w-snow';if(l.includes('névoa')||l.includes('neblina')||l.includes('bruma')||l.includes('nevoeiro'))return'w-fog';if(l.includes('calor')||l.includes('seca')||l.includes('escaldante'))return'w-hot';return'w-clear';}
function _formatFeedDetail(d){if(!d)return'';var lines=[];if(d.d20!==undefined){var modStr=d.mod?(d.mod>=0?'+':'')+d.mod:'';var hitLabel=d.hit?(d.crit?'\u203c\ufe0f CR\u00cdTICO!':'\u2705 Acertou!'):'\u274c Errou';lines.push('\ud83c\udfb2 d20('+d.d20+')'+modStr+' = '+d.tot+' vs CA '+d.ac+' \u2014 '+hitLabel);}
if(d.bk&&d.bk.length>0){var bkStr=d.bk.map(function(p){return(p.v>=0?'+':'')+p.v+' '+p.l;}).join(' ');lines.push('\u2699\ufe0f d20('+(d.d20||'?')+') '+bkStr+' = '+d.tot);}
if(d.dr&&d.dr.length>0){var diceStr=d.dr.join(', ');var dtpLabel=d.dtp||'';var DT_PT={slashing:'Cortante',piercing:'Perfurante',bludgeoning:'Contundente',fire:'Fogo',cold:'Gelo',lightning:'El\u00e9trico',poison:'Veneno',necrotic:'Necr\u00f3tico',radiant:'Radiante',force:'For\u00e7a',psychic:'Ps\u00edquico',acid:'\u00c1cido',thunder:'Trov\u00e3o',magical:'M\u00e1gico'};dtpLabel=DT_PT[dtpLabel]||dtpLabel;lines.push('\ud83d\udca5 '+(d.df||'?')+': ('+diceStr+') = '+d.dt+(dtpLabel?' ['+dtpLabel+']':''));}
return lines.join('\n');}
function _classifyFeed(f){if(!f)return'';const t=f.toLowerCase();if(t.includes('derrotou')||t.includes('abateu')||t.includes('caiu'))return'feed-kill';if(t.includes('crítico')||t.includes('crit'))return'feed-crit';if(t.includes('curou')||t.includes('cura')||t.includes('recuperou'))return'feed-heal';if(t.includes('errou')||t.includes('falhou')||t.includes('resistiu')||t.includes('miss'))return'feed-miss';if(t.includes('acertou')||t.includes('causou')||t.includes('dano'))return'feed-hit';if(t.includes('salvaguarda')||t.includes('teste de'))return'feed-save';if(t.includes('efeito')||t.includes('status')||t.includes('envenenad')||t.includes('atordoad')||t.includes('ceg'))return'feed-status';if(t.includes('usou')||t.includes('ativou')||t.includes('lançou'))return'feed-self';return'';}