var HEX_W=44;var HEX_H=26;var UNIT_PX=7;var ROW_STEP=HEX_H*0.75;var MAP_OFFSET_X=0;var MAP_OFFSET_Y=0;var TILE_HEIGHT={'.':1,'g':1,'p':1,'s':1,'b':1,'m':0.5,'R':2.5,'r':2,'T':3.5,'i':1,'v':1,'w':0,'W':-0.5,'M':8,'#':6,'D':5,'L':0,'C':1.2,'@':1,'E':1,};function calcHexSizeForViewport(viewportW,viewportH,cols,rows){const padX=6;const baseHexW=(viewportW-padX*2)/(cols+0.5);HEX_W=Math.floor(baseHexW*1.85);HEX_H=Math.round(HEX_W*0.86);UNIT_PX=Math.max(3,Math.round(HEX_W*0.07));ROW_STEP=HEX_H*0.75;const maxTileH=Math.max(...Object.values(TILE_HEIGHT))*UNIT_PX;const mapW=cols*HEX_W+HEX_W/2+padX*2;const mapH=(rows-1)*ROW_STEP+HEX_H+maxTileH+20;const canvasW=Math.max(mapW,viewportW);const canvasH=Math.max(mapH,viewportH);MAP_OFFSET_X=Math.max(padX,(canvasW-(cols*HEX_W+HEX_W/2))/2);MAP_OFFSET_Y=Math.max(10,maxTileH+10);return{w:canvasW,h:canvasH};}
function hexToScreen(col,row){const offset=(row%2===1)?HEX_W/2:0;const px=col*HEX_W+offset+MAP_OFFSET_X+HEX_W/2;const py=row*ROW_STEP+MAP_OFFSET_Y+HEX_H/2;return{x:px,y:py};}
function hexTopVertices(cx,cy){const hw=HEX_W/2;const hh=HEX_H/2;return[{x:cx,y:cy-hh},{x:cx+hw,y:cy-hh/2},{x:cx+hw,y:cy+hh/2},{x:cx,y:cy+hh},{x:cx-hw,y:cy+hh/2},{x:cx-hw,y:cy-hh/2},];}
function hexLeftSideVertices(cx,cy,heightPx){const hw=HEX_W/2;const hh=HEX_H/2;return[{x:cx-hw,y:cy-hh/2},{x:cx,y:cy+hh},{x:cx,y:cy+hh+heightPx},{x:cx-hw,y:cy-hh/2+heightPx},];}
function hexRightSideVertices(cx,cy,heightPx){const hw=HEX_W/2;const hh=HEX_H/2;return[{x:cx+hw,y:cy+hh/2},{x:cx,y:cy+hh},{x:cx,y:cy+hh+heightPx},{x:cx+hw,y:cy+hh/2+heightPx},];}
function hexFrontSideVertices(cx,cy,heightPx){const hw=HEX_W/2;const hh=HEX_H/2;return[{x:cx-hw,y:cy+hh/2},{x:cx,y:cy+hh},{x:cx,y:cy+hh+heightPx},{x:cx-hw,y:cy+hh/2+heightPx},];}
function screenToHex(sx,sy,grid,rows,cols){const approxRow=Math.round((sy-MAP_OFFSET_Y-HEX_H/2)/ROW_STEP);const offset=(approxRow%2===1)?HEX_W/2:0;const approxCol=Math.round((sx-MAP_OFFSET_X-HEX_W/2-offset)/HEX_W);let bestDist=Infinity,bestCol=-1,bestRow=-1;const candidates=[[approxCol,approxRow]];const offsets=approxRow%2===0?[[-1,-1],[0,-1],[-1,0],[1,0],[-1,1],[0,1]]:[[0,-1],[1,-1],[-1,0],[1,0],[0,1],[1,1]];for(const[dc,dr]of offsets){candidates.push([approxCol+dc,approxRow+dr]);}
for(const[c,r]of candidates){if(c<0||c>=cols||r<0||r>=rows)continue;const center=hexToScreen(c,r);const tile=grid[r]&&grid[r][c]?grid[r][c]:'.';const h=(TILE_HEIGHT[tile]||1)*UNIT_PX;const dist=Math.hypot(sx-center.x,sy-(center.y-h));if(dist<bestDist){bestDist=dist;bestCol=c;bestRow=r;}}
return{col:bestCol,row:bestRow};}
function fillPoly(ctx,verts,color){ctx.beginPath();ctx.moveTo(verts[0].x,verts[0].y);for(let i=1;i<verts.length;i++){ctx.lineTo(verts[i].x,verts[i].y);}
ctx.closePath();ctx.fillStyle=color;ctx.fill();}
function darken(hex,factor){const r=parseInt(hex.slice(1,3),16);const g=parseInt(hex.slice(3,5),16);const b=parseInt(hex.slice(5,7),16);const nr=Math.round(r*factor);const ng=Math.round(g*factor);const nb=Math.round(b*factor);return`rgb(${nr},${ng},${nb})`;}
function lighten(hex,amount){const r=Math.min(255,parseInt(hex.slice(1,3),16)+amount);const g=Math.min(255,parseInt(hex.slice(3,5),16)+amount);const b=Math.min(255,parseInt(hex.slice(5,7),16)+amount);return`rgb(${r},${g},${b})`;}