function _ensureAudio(){if(_audioCtx)return _audioCtx;try{_audioCtx=new(window.AudioContext||window.webkitAudioContext)();return _audioCtx;}catch(e){console.warn('[COMBAT] AudioContext unavailable',e);return null;}}
function _sfxNoise(dur,vol){const ctx=_ensureAudio();if(!ctx||!_audioUnlocked)return;if(typeof ValdoriaAudio!=='undefined'&&ValdoriaAudio.isSFXMuted())return;if(typeof ValdoriaAudio!=='undefined')vol*=ValdoriaAudio.getSFXVolume();try{const bufSize=ctx.sampleRate*dur;const buf=ctx.createBuffer(1,bufSize,ctx.sampleRate);const data=buf.getChannelData(0);for(let i=0;i<bufSize;i++)data[i]=(Math.random()*2-1);const src=ctx.createBufferSource();src.buffer=buf;const gain=ctx.createGain();gain.gain.setValueAtTime(vol,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(0.001,ctx.currentTime+dur);src.connect(gain);gain.connect(ctx.destination);src.start();src.stop(ctx.currentTime+dur);}catch(e){console.warn('[COMBAT] sfxNoise',e);}}
function _sfxTone(freq,dur,vol,type){const ctx=_ensureAudio();if(!ctx||!_audioUnlocked)return;if(typeof ValdoriaAudio!=='undefined'&&ValdoriaAudio.isSFXMuted())return;if(typeof ValdoriaAudio!=='undefined')vol*=ValdoriaAudio.getSFXVolume();try{const osc=ctx.createOscillator();const gain=ctx.createGain();osc.type=type||'sine';osc.frequency.setValueAtTime(freq,ctx.currentTime);osc.frequency.exponentialRampToValueAtTime(freq*0.5,ctx.currentTime+dur);gain.gain.setValueAtTime(vol,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(0.001,ctx.currentTime+dur);osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+dur);}catch(e){console.warn('[COMBAT] sfxTone',e);}}
function sfxDiceRoll(){_sfxNoise(0.15,0.08);}
function sfxHit(){if(typeof ValdoriaAudio!=='undefined'){ValdoriaAudio.playSFX('sfx_hit');}else{_sfxTone(120,0.25,0.12,'sawtooth');}}
function sfxCrit(){if(typeof ValdoriaAudio!=='undefined'){ValdoriaAudio.playSFX('sfx_crit');}else{_sfxTone(220,0.4,0.18,'sawtooth');setTimeout(()=>_sfxTone(330,0.3,0.12,'sine'),80);}}
function sfxMiss(){if(typeof ValdoriaAudio!=='undefined'){ValdoriaAudio.playSFX('sfx_miss');}else{_sfxTone(300,0.2,0.06,'sine');}}
function sfxPlayerHit(){_sfxTone(80,0.3,0.15,'sawtooth');}
function sfxTimerTick(){_sfxTone(600,0.08,0.1,'square');}
function sfxDamageType(dt){if(typeof ValdoriaAudio!=='undefined'){const sfxMap={fire:'sfx_fire',cold:'sfx_cold',lightning:'sfx_lightning',thunder:'sfx_thunder',necrotic:'sfx_necrotic',radiant:'sfx_radiant',poison:'sfx_poison',acid:'sfx_poison',psychic:'sfx_psychic',force:'sfx_hit',};const key=sfxMap[dt];if(key&&ValdoriaAudio.TRACKS[key]){ValdoriaAudio.playSFX(key);return;}}
const ctx=_ensureAudio();if(!ctx||!_audioUnlocked)return;try{const profiles={fire:{type:'sawtooth',f0:180,f1:80,dur:0.35,vol:0.12},cold:{type:'sine',f0:400,f1:200,dur:0.3,vol:0.10},lightning:{type:'square',f0:800,f1:200,dur:0.15,vol:0.10},thunder:{type:'sawtooth',f0:60,f1:30,dur:0.5,vol:0.14},necrotic:{type:'triangle',f0:60,f1:55,dur:0.5,vol:0.10},radiant:{type:'sine',f0:600,f1:900,dur:0.4,vol:0.09},poison:{type:'triangle',f0:150,f1:100,dur:0.4,vol:0.08},acid:{type:'sawtooth',f0:250,f1:120,dur:0.35,vol:0.10},psychic:{type:'sine',f0:500,f1:700,dur:0.35,vol:0.08},force:{type:'square',f0:300,f1:150,dur:0.25,vol:0.10},};const p=profiles[dt];if(!p)return;const osc=ctx.createOscillator();const gain=ctx.createGain();osc.type=p.type;osc.frequency.setValueAtTime(p.f0,ctx.currentTime);osc.frequency.exponentialRampToValueAtTime(Math.max(p.f1,20),ctx.currentTime+p.dur);gain.gain.setValueAtTime(p.vol,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(0.001,ctx.currentTime+p.dur);osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+p.dur);}catch(e){console.warn('[COMBAT] sfxDamageType',e);}}