// AUTO-GENERATED by scripts/build_exploracao_data.py
// DO NOT EDIT MANUALLY. Edit src/game/exploracao/events/data/*.py e re-run.
// Last build: 2026-04-24T11:50:27.744184

window.__EXPLORACAO_EVENTS = {
  "plains_caravan_01": {
    "id": "plains_caravan_01",
    "biome": "plains",
    "type": "social",
    "title": "Caravana de Comerciantes",
    "text": "Uma pequena caravana de mulas pausa para descansar sob uma árvore. O líder te acena com cautela.",
    "flavor": "O emblema nas caixas é de uma guilda rival — levam mercadorias de contrabando ou legítimas?",
    "choices": [
      {
        "label": "Oferecer escolta até a cidade",
        "skill": "cha",
        "dc": 12,
        "outcome_ok": {
          "text": "O líder aceita com alívio. Pagam +15 Valdoritas pela proteção.",
          "reward_gold": 15,
          "reward_xp": 20
        },
        "outcome_partial": {
          "text": "Aceitam, mas pagam menos. +8 Valdoritas.",
          "reward_gold": 8,
          "reward_xp": 10
        },
        "outcome_fail": {
          "text": "Desconfiam e recusam. Seguem sem você."
        }
      },
      {
        "label": "Inspecionar carga (furtivo)",
        "skill": "dex",
        "dc": 14,
        "only_background": "criminal",
        "outcome_ok": {
          "text": "Você vê contrabando valioso. Aproveita a distração e surrupia 20 Valdoritas.",
          "reward_gold": 20,
          "reward_xp": 15
        },
        "outcome_fail": {
          "text": "Te pegam. Eles fugiram ferindo você.",
          "hp_delta": -3
        }
      },
      {
        "label": "Seguir em frente",
        "outcome_ok": {
          "text": "Você segue sem interagir."
        }
      }
    ]
  },
  "forest_shrine_01": {
    "id": "forest_shrine_01",
    "biome": "forest",
    "type": "discovery",
    "title": "Santuário Esquecido",
    "text": "Um pequeno altar de pedra coberto de musgo. Oferendas antigas de velas queimadas.",
    "flavor": "Uma runa tênue brilha na base.",
    "choices": [
      {
        "label": "Rezar e deixar oferenda",
        "skill": "wis",
        "dc": 10,
        "outcome_ok": {
          "text": "A runa brilha em resposta. Você se sente protegido. +5 HP.",
          "hp_delta": 5,
          "reward_xp": 15
        },
        "outcome_fail": {
          "text": "Reza, mas nada muda. A runa continua tênue."
        }
      },
      {
        "label": "Estudar a runa",
        "skill": "int",
        "dc": 13,
        "outcome_ok": {
          "text": "A runa é de proteção antiga — registrada no seu grimório.",
          "reward_xp": 25
        },
        "outcome_partial": {
          "text": "Você identifica fragmentos, mas o significado escapa.",
          "reward_xp": 10
        },
        "outcome_fail": {
          "text": "Complexa demais. Você desiste."
        }
      },
      {
        "label": "Ignorar",
        "outcome_ok": {
          "text": "Você passa adiante sem perturbar."
        }
      }
    ]
  },
  "mountain_boulder_01": {
    "id": "mountain_boulder_01",
    "biome": "mountain",
    "type": "discovery",
    "title": "Pedregulho na Trilha",
    "text": "Um pedregulho gigante bloqueia parcialmente a passagem. Há espaço para contornar, mas a rota direta exigiria esforço.",
    "flavor": "Marcas frescas — caiu recentemente.",
    "choices": [
      {
        "label": "Empurrar o pedregulho",
        "skill": "str",
        "dc": 15,
        "outcome_ok": {
          "text": "Com esforço hercúleo, a pedra rola pela encosta.",
          "reward_xp": 20
        },
        "outcome_partial": {
          "text": "Move um pouco, mas desliza e machuca o ombro.",
          "hp_delta": -2,
          "reward_xp": 5
        },
        "outcome_fail": {
          "text": "Não cede. Você desiste.",
          "hp_delta": -1
        }
      },
      {
        "label": "Contornar com cuidado",
        "skill": "dex",
        "dc": 10,
        "outcome_ok": {
          "text": "Você passa sem problemas.",
          "reward_xp": 5
        },
        "outcome_fail": {
          "text": "Escorrega um pouco. Arranhões.",
          "hp_delta": -1
        }
      }
    ]
  },
  "forest_poison_trap_01": {
    "id": "forest_poison_trap_01",
    "biome": "forest",
    "type": "hazard",
    "title": "Armadilha de Espinhos Envenenados",
    "text": "Você pisa num gatilho escondido sob folhas secas — espinhos saltam do chão.",
    "flavor": "Caçadores furtivos deixam armadilhas por aqui.",
    "choices": [
      {
        "label": "Reagir",
        "skill": "dex",
        "dc": 13,
        "outcome_ok": {
          "text": "Você salta pra trás no último segundo. Ileso."
        },
        "outcome_fail": {
          "text": "Os espinhos te atingem. Dano mas sem veneno grave.",
          "hp_delta": -4
        }
      }
    ]
  },
  "mountain_rockfall_01": {
    "id": "mountain_rockfall_01",
    "biome": "mountain",
    "type": "hazard",
    "title": "Deslizamento de Pedras",
    "text": "Um estrondo acima — pedras rolam pela encosta em sua direção.",
    "flavor": "Atenção aos sons do vento nas montanhas.",
    "choices": [
      {
        "label": "Esquivar",
        "skill": "dex",
        "dc": 14,
        "outcome_ok": {
          "text": "Você salta pra lateral. Pedras passam rolando.",
          "reward_xp": 5
        },
        "outcome_partial": {
          "text": "Você quase esquiva. Um galho te atinge.",
          "hp_delta": -2
        },
        "outcome_fail": {
          "text": "As pedras te atingem. Ouch.",
          "hp_delta": -6
        }
      }
    ]
  },
  "forest_bandit_ambush_01": {
    "id": "forest_bandit_ambush_01",
    "biome": "forest",
    "type": "combat_optional",
    "title": "Emboscada de Bandidos",
    "text": "Três figuras saltam dos arbustos com facas em punho. \"Suas moedas ou sua vida!\"",
    "flavor": "Pegadas frescas na lama — você devia ter visto.",
    "choices": [
      {
        "label": "Intimidar",
        "skill": "cha",
        "dc": 15,
        "outcome_ok": {
          "text": "Você se ergue com autoridade. Eles fogem.",
          "reward_xp": 30
        },
        "outcome_fail": {
          "text": "Sua voz falha. Eles avançam!",
          "combat": {
            "enemy_id": "bandit_forest_01"
          }
        }
      },
      {
        "label": "Lutar",
        "outcome_ok": {
          "text": "Você saca a arma!",
          "combat": {
            "enemy_id": "bandit_forest_01"
          }
        }
      },
      {
        "label": "Correr",
        "skill": "dex",
        "dc": 12,
        "outcome_ok": {
          "text": "Você escapa pela mata. Fôlego curto.",
          "hp_delta": -2
        },
        "outcome_fail": {
          "text": "Um deles te pega pelo ombro.",
          "combat": {
            "enemy_id": "bandit_forest_01"
          }
        }
      }
    ]
  },
  "plains_orc_raid_01": {
    "id": "plains_orc_raid_01",
    "biome": "plains",
    "type": "combat_forced",
    "title": "Emboscada Orc",
    "text": "Três orcs raiders saltam dos arbustos com machados em punho. Sem tempo de reagir.",
    "flavor": "A bandeira pintada — clã Korthag.",
    "combat": {
      "enemy_id": "orc_raider",
      "enemy_count": 3,
      "surprise": true
    },
    "victory_loot_table": "plains_orc_drop",
    "victory_loot_rolls": 2,
    "victory_xp": 60
  },
  "plains_bandit_ambush_01": {
    "id": "plains_bandit_ambush_01",
    "biome": "plains",
    "type": "combat_forced",
    "title": "Bandidos do Caminho",
    "text": "Dois bandidos pulam de trás de uma carroça abandonada. Lâminas curtas, intenções claras.",
    "flavor": "Marcas no ombro — desertores da guarnição.",
    "combat": {
      "enemy_id": "bandit",
      "enemy_count": 2,
      "surprise": false
    },
    "victory_loot_table": "bandit_combat",
    "victory_loot_rolls": 2,
    "victory_xp": 40
  },
  "plains_bandit_negotiate_01": {
    "id": "plains_bandit_negotiate_01",
    "biome": "plains",
    "type": "combat_optional",
    "title": "Pedágio Improvisado",
    "text": "Dois bandidos bloqueiam a trilha. Olhares calculistas; nem quentes nem frios — só calculadores.",
    "flavor": "Espadas curtas, couro gasto. Não-veteranos.",
    "choices": [
      {
        "label": "Lutar",
        "outcome_ok": {
          "text": "Você saca a arma. Eles avançam!",
          "combat": {
            "enemy_id": "bandit",
            "enemy_count": 2
          }
        }
      },
      {
        "label": "Negociar passagem (-10 Valdoritas)",
        "skill": "cha",
        "dc": 14,
        "outcome_ok": {
          "text": "Eles aceitam ouro pela passagem. Caminho liberado.",
          "reward_gold": -10,
          "reward_xp": 10
        },
        "outcome_fail": {
          "text": "Riem da sua oferta. Sacam armas.",
          "combat": {
            "enemy_id": "bandit",
            "enemy_count": 2
          }
        }
      },
      {
        "label": "Intimidar",
        "skill": "cha",
        "dc": 16,
        "outcome_ok": {
          "text_by_alignment": {
            "evil": "Vossa presença gélida os congela. Fogem aos tropeções.",
            "good": "Vossa firmeza moral os faz hesitar. Recuam, envergonhados."
          },
          "text": "Sua bravata os intimida. Fogem.",
          "reward_xp": 30
        },
        "outcome_fail": {
          "text": "Sua bravata falha — eles riem. E avançam.",
          "combat": {
            "enemy_id": "bandit",
            "enemy_count": 2
          }
        }
      }
    ]
  },
  "plains_lone_wolf_01": {
    "id": "plains_lone_wolf_01",
    "biome": "plains",
    "type": "combat_optional",
    "title": "Lobo Solitário",
    "text": "Um lobo magro rosna baixo, costas arqueadas. Faminto, mas ainda pesando se você vale o esforço.",
    "flavor": "A pelagem rala denuncia falta de presa nesta estação.",
    "choices": [
      {
        "label": "Atacar",
        "outcome_ok": {
          "text": "Você avança primeiro. Ele responde.",
          "combat": {
            "enemy_id": "gray_wolf",
            "enemy_count": 1
          }
        }
      },
      {
        "label": "Acalmar com voz baixa",
        "skill": "wis",
        "dc": 10,
        "outcome_ok": {
          "text_by_class": {
            "patrulheiro": "Você reconhece os sinais — postura, olhar. Sussurra a palavra antiga. Ele baixa a cabeça e some na vegetação."
          },
          "text": "Tom calmo, postura aberta. Ele observa, calcula, e desaparece pelas grama.",
          "reward_xp": 15
        },
        "outcome_fail": {
          "text": "Sua voz tremeu. Ele leu medo.",
          "combat": {
            "enemy_id": "gray_wolf",
            "enemy_count": 1
          }
        }
      },
      {
        "label": "Oferecer comida",
        "skill": "wis",
        "dc": 12,
        "outcome_ok": {
          "text": "Você joga ração no chão. Ele come, observa, e parte. Olhar menos hostil agora.",
          "reward_xp": 10,
          "loot_table": "plains_pilgrim_blessing",
          "loot_rolls": 1
        },
        "outcome_fail": {
          "text": "Ele toma a ração mas não satisfaz a fome. Ataca.",
          "combat": {
            "enemy_id": "gray_wolf",
            "enemy_count": 1
          }
        }
      }
    ]
  },
  "plains_pit_trap_01": {
    "id": "plains_pit_trap_01",
    "biome": "plains",
    "type": "hazard",
    "title": "Cova Oculta",
    "text": "Você pisa em algo macio demais — uma camada de gravetos sobre vazio.",
    "flavor": "Caçadores deixam armadilhas pra javalis. Você não é um.",
    "choices": [
      {
        "label": "Reagir",
        "skill": "dex",
        "dc": 13,
        "outcome_ok": {
          "text": "Você pula pra trás no último momento. Os gravetos caem no buraco que se forma sob o pé.",
          "reward_xp": 5
        },
        "outcome_partial": {
          "text": "Quase escapa — torce o tornozelo na borda.",
          "hp_delta": -2
        },
        "outcome_fail": {
          "text": "Você cai. Estacas no fundo. Sangra ao subir.",
          "hp_delta": -6
        }
      }
    ]
  },
  "plains_brushfire_01": {
    "id": "plains_brushfire_01",
    "biome": "plains",
    "type": "hazard",
    "title": "Incêndio no Mato",
    "text": "Fumaça densa à frente. O fogo atravessa a trilha — pequeno mas rápido. Atravessar é a saída mais curta.",
    "flavor": "Verão seco. Um único raio mata uma planície.",
    "choices": [
      {
        "label": "Atravessar correndo",
        "skill": "con",
        "dc": 12,
        "outcome_ok": {
          "text": "Você passa rápido, abafando a tosse. Roupas chamuscam mas você sobrevive.",
          "reward_xp": 10
        },
        "outcome_partial": {
          "text": "A fumaça toma seus pulmões. Atravessa, mas fraco.",
          "hp_delta": -2
        },
        "outcome_fail": {
          "text": "Você inala demais e cai. Acorda na borda do incêndio, queimado.",
          "hp_delta": -5
        }
      }
    ]
  },
  "plains_caravan_merchant_01": {
    "id": "plains_caravan_merchant_01",
    "biome": "plains",
    "type": "social",
    "title": "Caravana de Mercadores",
    "text": "Uma pequena caravana de mulas pausa para descansar sob uma árvore. O líder te acena com cautela.",
    "flavor": "O emblema nas caixas é de uma guilda rival — levam mercadorias de contrabando ou legítimas?",
    "choices": [
      {
        "label": "Oferecer escolta até a cidade",
        "skill": "cha",
        "dc": 12,
        "outcome_ok": {
          "text": "O líder aceita com alívio. Pagam +15 Valdoritas pela proteção.",
          "reward_gold": 15,
          "reward_xp": 20
        },
        "outcome_partial": {
          "text": "Aceitam, mas pagam menos. +8 Valdoritas.",
          "reward_gold": 8,
          "reward_xp": 10
        },
        "outcome_fail": {
          "text": "Desconfiam e recusam. Seguem sem você."
        }
      },
      {
        "label": "Inspecionar carga (furtivo)",
        "skill": "dex",
        "dc": 14,
        "only_background": "criminal",
        "outcome_ok": {
          "text": "Você vê contrabando valioso. Aproveita a distração e surrupia 20 Valdoritas.",
          "reward_gold": 20,
          "reward_xp": 15
        },
        "outcome_fail": {
          "text": "Te pegam. Eles fugiram ferindo você.",
          "hp_delta": -3
        }
      },
      {
        "label": "Seguir em frente",
        "outcome_ok": {
          "text": "Você segue sem interagir."
        }
      }
    ]
  },
  "plains_farmer_distress_01": {
    "id": "plains_farmer_distress_01",
    "biome": "plains",
    "type": "social",
    "title": "Camponês em Apuros",
    "text": "Um camponês magro vem correndo, abano na mão. \"Senhor(a)! Ratos gigantes no celeiro! Comem tudo!\"",
    "flavor": "Sua única boia. Sem grão, a família não passa do inverno.",
    "choices": [
      {
        "label": "Ouvir a história",
        "skill": "cha",
        "dc": 10,
        "outcome_ok": {
          "text": "Ele explica entre lágrimas. Três ratos enormes, tamanho de cães. Pergunta se você ajuda.",
          "reward_xp": 5,
          "starts_quest": "plains_rat_infestation"
        },
        "outcome_fail": {
          "text": "Ele se confunde, agitado demais. Você não entende direito."
        }
      },
      {
        "label": "Ir agora matar os ratos",
        "outcome_ok": {
          "text": "Vocês correm pro celeiro. Os ratos te atacam!",
          "combat": {
            "enemy_id": "rat_swarm",
            "enemy_count": 1
          }
        }
      },
      {
        "label": "Voltar pra confirmar quest concluída",
        "outcome_ok": {
          "text": "O camponês te recebe ajoelhado. Oferece o pouco que tem.",
          "reward_gold": 20,
          "reward_xp": 30
        }
      }
    ]
  },
  "plains_pilgrim_blessing_01": {
    "id": "plains_pilgrim_blessing_01",
    "biome": "plains",
    "type": "social",
    "title": "Peregrino na Estrada",
    "text": "Uma figura encapuzada caminha lenta, cajado em mão. Te saúda com voz cansada. \"Posso oferecer uma bênção, viajante?\"",
    "flavor": "Símbolos religiosos pendem do cajado — uma ordem antiga.",
    "choices": [
      {
        "label": "Aceitar humildemente",
        "skill": "wis",
        "dc": 10,
        "outcome_ok": {
          "text_by_alignment": {
            "good": "Você se ajoelha. Ele toca sua testa — você sente uma energia quente fluir. +5 HP."
          },
          "text": "Você aceita. Ele recita versos antigos. Sente-se mais forte.",
          "hp_delta": 5,
          "reward_xp": 10,
          "loot_table": "plains_pilgrim_blessing",
          "loot_rolls": 1
        },
        "outcome_fail": {
          "text": "Você aceita por cortesia, mas não sente nada. O peregrino sorri tristemente e segue."
        }
      },
      {
        "label": "Recusar educadamente",
        "outcome_ok": {
          "text": "Ele assente. \"Que os ventos te guiem.\" Segue caminho.",
          "reward_xp": 3
        }
      },
      {
        "label": "Roubar o cajado",
        "skill": "dex",
        "dc": 16,
        "only_alignment": "evil",
        "outcome_ok": {
          "text": "Você arranca o cajado. Ele cai surpreso, mas não revida. Você foge com o tesouro.",
          "reward_gold": 25,
          "reward_xp": -10
        },
        "outcome_fail": {
          "text": "Ele se revela mais forte do que parecia. Te derruba e foge.",
          "hp_delta": -4
        }
      }
    ]
  },
  "plains_old_battlefield_01": {
    "id": "plains_old_battlefield_01",
    "biome": "plains",
    "type": "discovery",
    "title": "Campo de Batalha Antigo",
    "text": "Ossos branqueados sob a grama. Armas enferrujadas saem da terra. Aqui morreram muitos.",
    "flavor": "A vegetação cresce diferente onde sangue se misturou ao solo.",
    "choices": [
      {
        "label": "Cavar ao redor",
        "skill": "int",
        "dc": 12,
        "outcome_ok": {
          "text_by_background": {
            "sage": "Você reconhece marcas em escudos quebrados — Batalha do Vau, há cem anos. Encontra relíquias intactas.",
            "soldier": "Olhos militares: você identifica posições. Dois exércitos. O lado vencedor deixou itens valiosos."
          },
          "text": "Você cava com cuidado. Encontra alguns objetos preservados.",
          "reward_xp": 25,
          "loot_table": "plains_battlefield_dig",
          "loot_rolls": 2
        },
        "outcome_partial": {
          "text": "Acha um item pequeno. Não vale o esforço todo.",
          "reward_xp": 10,
          "loot_table": "plains_battlefield_dig",
          "loot_rolls": 1
        },
        "outcome_fail": {
          "text": "A terra está dura. Você cava por horas e acha apenas pedras."
        }
      },
      {
        "label": "Respeitar e seguir",
        "outcome_ok": {
          "text": "Você inclina a cabeça e segue caminho. Sente que fez o certo.",
          "reward_xp": 5
        }
      }
    ]
  },
  "plains_abandoned_cart_01": {
    "id": "plains_abandoned_cart_01",
    "biome": "plains",
    "type": "discovery",
    "title": "Carroça Abandonada",
    "text": "Uma carroça à beira da estrada. Roda quebrada. Carga ainda amarrada. Sem dono à vista.",
    "flavor": "Pegadas afastam-se rapidamente — alguém fugiu apressado.",
    "choices": [
      {
        "label": "Vasculhar a carga",
        "skill": "dex",
        "dc": 10,
        "outcome_ok": {
          "text": "Você desfaz os nós. Encontra mantimentos e algo de valor.",
          "reward_xp": 10,
          "loot_table": "forest_basic",
          "loot_rolls": 2
        },
        "outcome_fail": {
          "text": "Os nós são complexos. Você cede, frustrado."
        }
      },
      {
        "label": "Deixar como está",
        "outcome_ok": {
          "text": "Não é seu. Você passa adiante.",
          "reward_xp": 3
        }
      }
    ]
  },
  "plains_missing_caravan_hook_01": {
    "id": "plains_missing_caravan_hook_01",
    "biome": "plains",
    "type": "quest_hook",
    "title": "Mensageiro Aflito",
    "text": "Um mensageiro real puxa rédeas ao te ver. \"Viajante! Uma caravana sumiu na estrada pra Floresta Sussurrante. Sabe algo?\"",
    "flavor": "Botões dourados, espada de oficial. Mensagem urgente.",
    "choices": [
      {
        "label": "Aceitar investigar",
        "skill": "cha",
        "dc": 8,
        "outcome_ok": {
          "text": "\"Excelente. Sigam pra a floresta — busquem a caravana. Recompensa garantida na volta.\"",
          "reward_xp": 15,
          "starts_quest": "plains_missing_caravan"
        },
        "outcome_fail": {
          "text": "Ele desconfia da sua hesitação. \"Talvez outro.\" Parte galopando."
        }
      },
      {
        "label": "Recusar",
        "outcome_ok": {
          "text": "Você nega com tato. Ele assente, decepcionado, e segue em busca de outro."
        }
      }
    ]
  },
  "forest_goblin_warband_01": {
    "id": "forest_goblin_warband_01",
    "biome": "forest",
    "type": "combat_forced",
    "title": "Bando Goblin",
    "text": "Quatro goblins saltam de galhos baixos. Gritos agudos, lâminas sujas — sem hesitação.",
    "flavor": "A pintura de guerra é recente. Saem de uma caçada fracassada.",
    "combat": {
      "enemy_id": "goblin",
      "enemy_count": 4,
      "surprise": true
    },
    "victory_loot_table": "forest_goblin_drop",
    "victory_loot_rolls": 2,
    "victory_xp": 70
  },
  "forest_dire_wolf_01": {
    "id": "forest_dire_wolf_01",
    "biome": "forest",
    "type": "combat_forced",
    "title": "Lobo Terrível",
    "text": "Um lobo do tamanho de um cavalo irrompe da mata, focinho ensanguentado, olhos amarelos cravados em você.",
    "flavor": "Cicatrizes recentes no pelo — brigou hoje, e venceu.",
    "combat": {
      "enemy_id": "dire_wolf",
      "enemy_count": 1,
      "surprise": false
    },
    "victory_loot_table": "forest_basic",
    "victory_loot_rolls": 2,
    "victory_xp": 80
  },
  "forest_elven_ranger_01": {
    "id": "forest_elven_ranger_01",
    "biome": "forest",
    "type": "combat_optional",
    "title": "Patrulheiro Élfico Desconfiado",
    "text": "Uma figura esguia surge silenciosamente da vegetação, arco tensionado. \"Identifique-se, forasteiro.\"",
    "flavor": "Vestes verdes, brasão da Casa Ennaiel. Guardião territorial.",
    "choices": [
      {
        "label": "Atacar imediatamente",
        "outcome_ok": {
          "text": "Você saca a arma. Ele dispara antes de você dar um passo.",
          "combat": {
            "enemy_id": "elven_ranger",
            "enemy_count": 1
          }
        }
      },
      {
        "label": "Explicar sua presença",
        "skill": "cha",
        "dc": 13,
        "outcome_ok": {
          "text_by_class": {
            "patrulheiro": "Você usa os sinais de mão dos patrulheiros. Ele baixa o arco, assente, e some na vegetação."
          },
          "text_by_alignment": {
            "good": "Sua sinceridade o convence. Ele aponta a direção segura."
          },
          "text": "Você fala com calma. Ele escuta, assente, e permite passagem.",
          "reward_xp": 20
        },
        "outcome_fail": {
          "text": "Sua história não convence. Ele interpreta como ameaça.",
          "combat": {
            "enemy_id": "elven_ranger",
            "enemy_count": 1
          }
        }
      },
      {
        "label": "Fugir pela vegetação",
        "skill": "dex",
        "dc": 15,
        "outcome_ok": {
          "text": "Você some entre os arbustos. Ele desiste de perseguir.",
          "reward_xp": 10
        },
        "outcome_fail": {
          "text": "Uma flecha crava no tronco ao seu lado. Você tropeça e ele chega.",
          "combat": {
            "enemy_id": "elven_ranger",
            "enemy_count": 1
          }
        }
      }
    ]
  },
  "forest_giant_spider_01": {
    "id": "forest_giant_spider_01",
    "biome": "forest",
    "type": "combat_optional",
    "title": "Aranha Gigante na Teia",
    "text": "Uma teia massiva bloqueia a trilha. No centro, uma aranha do tamanho de um cão observa imóvel — talvez esperando se você é presa.",
    "flavor": "Sedas prateadas. Antigas demais pra serem de uma única aranha.",
    "choices": [
      {
        "label": "Atacar a aranha",
        "outcome_ok": {
          "text": "Você avança com arma pronta. Ela salta da teia!",
          "combat": {
            "enemy_id": "giant_spider",
            "enemy_count": 1
          }
        }
      },
      {
        "label": "Rodear silenciosamente",
        "skill": "dex",
        "dc": 14,
        "outcome_ok": {
          "text": "Passo a passo, você dá a volta pela mata. Ela não se move.",
          "reward_xp": 15
        },
        "outcome_fail": {
          "text": "Um galho estala sob seu pé. A aranha ataca!",
          "combat": {
            "enemy_id": "giant_spider",
            "enemy_count": 1
          }
        }
      },
      {
        "label": "Queimar a teia",
        "skill": "int",
        "dc": 12,
        "outcome_ok": {
          "text": "Você usa uma tocha. O fogo espalha e a aranha foge entre as chamas.",
          "reward_xp": 25
        },
        "outcome_fail": {
          "text": "A seda não pega fogo como esperado. A aranha detecta o calor e ataca.",
          "combat": {
            "enemy_id": "giant_spider",
            "enemy_count": 1
          }
        }
      }
    ]
  },
  "forest_will_o_wisp_01": {
    "id": "forest_will_o_wisp_01",
    "biome": "forest",
    "type": "hazard",
    "title": "Luz Fátua",
    "text": "Uma luz azulada dança entre as árvores, chamando você pra uma clareira que não devia existir. O chão fica mole, pantanoso.",
    "flavor": "Pegadas de viajantes afundam no lodo — alguns nunca saíram.",
    "choices": [
      {
        "label": "Resistir à atração",
        "skill": "wis",
        "dc": 13,
        "outcome_ok": {
          "text": "Você firma o olhar no chão e ignora a luz. Ela some, irritada.",
          "reward_xp": 15
        },
        "outcome_partial": {
          "text": "Você hesita e afunda até os joelhos. Sai exausto.",
          "hp_delta": -3
        },
        "outcome_fail": {
          "text": "A luz te hipnotiza. Você caminha em círculos até cair no pântano.",
          "hp_delta": -7
        }
      }
    ]
  },
  "forest_falling_branch_01": {
    "id": "forest_falling_branch_01",
    "biome": "forest",
    "type": "hazard",
    "title": "Galho Traiçoeiro",
    "text": "Um estalo seco vem de cima. Um galho enorme cai diretamente na sua trajetória.",
    "flavor": "Árvores antigas perdem membros sem aviso. A floresta cobra seu pedágio.",
    "choices": [
      {
        "label": "Reagir",
        "skill": "dex",
        "dc": 12,
        "outcome_ok": {
          "text": "Você rola pro lado. O galho crava no chão onde você estava.",
          "reward_xp": 5
        },
        "outcome_partial": {
          "text": "Raspa no ombro. Dói, mas você está de pé.",
          "hp_delta": -2
        },
        "outcome_fail": {
          "text": "Atinge suas costas em cheio. Você cai, tonto.",
          "hp_delta": -6
        }
      }
    ]
  },
  "forest_druid_meeting_01": {
    "id": "forest_druid_meeting_01",
    "biome": "forest",
    "type": "social",
    "title": "Encontro com Druida",
    "text": "Uma figura com vestes de folhas emerge da mata, cajado coroado de musgo. \"A floresta permite sua passagem. Mas a um preço.\"",
    "flavor": "O olhar é antigo, mais velho que as árvores ao redor.",
    "choices": [
      {
        "label": "Oferecer proteção em troca de bênção",
        "skill": "cha",
        "dc": 12,
        "outcome_ok": {
          "text_by_class": {
            "druida": "Ele reconhece um irmão de ordem. Compartilha folha sagrada e bênção."
          },
          "text": "Ele sorri serenamente. Toca seu ombro — você sente a floresta em paz.",
          "hp_delta": 8,
          "reward_xp": 20,
          "loot_table": "forest_druid_blessing",
          "loot_rolls": 1
        },
        "outcome_fail": {
          "text": "Ele percebe falsidade no seu gesto. \"A floresta sabe.\" Desaparece."
        }
      },
      {
        "label": "Perguntar sobre perigos locais",
        "skill": "wis",
        "dc": 10,
        "outcome_ok": {
          "text": "Ele aponta norte. \"Bandidos. Acampamento próximo. Cuidado.\"",
          "reward_xp": 15
        },
        "outcome_fail": {
          "text": "Ele responde em rima, linguagem obscura. Você não entende nada útil."
        }
      },
      {
        "label": "Seguir caminho",
        "outcome_ok": {
          "text": "Você assente com respeito e passa. Ele fica imóvel, observando."
        }
      }
    ]
  },
  "forest_lost_child_01": {
    "id": "forest_lost_child_01",
    "biome": "forest",
    "type": "social",
    "title": "Criança Perdida",
    "text": "Você ouve choro. Um garoto pequeno, todo sujo, abraça um urso de pelúcia. \"Mamãe... cadê a mamãe?\"",
    "flavor": "Longe demais de vila. Alguém o trouxe — ou ele fugiu.",
    "choices": [
      {
        "label": "Aceitar acompanhar de volta",
        "skill": "wis",
        "dc": 10,
        "outcome_ok": {
          "text_by_alignment": {
            "good": "Você se ajoelha, estende a mão com ternura. Ele confia."
          },
          "text": "Você acalma a criança. Ela aponta pra direção de onde veio. A floresta é perigosa — você promete protegê-la.",
          "reward_xp": 10,
          "starts_quest": "forest_lost_child"
        },
        "outcome_fail": {
          "text": "A criança se assusta com sua abordagem e foge pra mata."
        }
      },
      {
        "label": "Interrogar sobre como chegou ali",
        "skill": "int",
        "dc": 14,
        "outcome_ok": {
          "text": "Entre soluços, ele descreve homens de manto negro. Cultistas, talvez. Você guarda a informação.",
          "reward_xp": 15
        },
        "outcome_fail": {
          "text": "Ele chora mais forte. Não consegue articular nada coerente."
        }
      },
      {
        "label": "Voltar à vila para avisar",
        "outcome_ok": {
          "text": "Você o carrega até a borda da floresta. A mãe te abraça chorando.",
          "reward_gold": 25,
          "reward_xp": 30
        }
      }
    ]
  },
  "forest_traveling_bard_01": {
    "id": "forest_traveling_bard_01",
    "biome": "forest",
    "type": "social",
    "title": "Bardo Itinerante",
    "text": "Um homem de manto colorido está sentado numa pedra, afinando um alaúde. Ele te saúda com um sorriso. \"Senta um pouco, viajante!\"",
    "flavor": "Os dedos dele têm calos antigos — músico profissional há décadas.",
    "choices": [
      {
        "label": "Ouvir uma história",
        "skill": "cha",
        "dc": 8,
        "outcome_ok": {
          "text_by_background": {
            "sage": "Ele cita fontes que você conhece. A história é verídica — detalhes preciosos sobre as ruínas élficas próximas."
          },
          "text": "Ele canta sobre heróis antigos. A melodia fica com você. Você se sente inspirado.",
          "reward_xp": 15,
          "hp_delta": 3
        },
        "outcome_fail": {
          "text": "Ele se perde no enredo. Você agradece educadamente e segue."
        }
      },
      {
        "label": "Tocar música juntos",
        "skill": "cha",
        "dc": 14,
        "only_class": "bardo",
        "outcome_ok": {
          "text": "Vocês improvisam um dueto. Ele te presenteia com uma partitura rara.",
          "reward_xp": 30,
          "loot_table": "forest_druid_blessing",
          "loot_rolls": 1
        },
        "outcome_fail": {
          "text": "Sua performance é decente, mas não o impressiona. Ele sorri cortês.",
          "reward_xp": 5
        }
      },
      {
        "label": "Seguir caminho",
        "outcome_ok": {
          "text": "Você acena e segue. A melodia te acompanha até se perder no vento.",
          "reward_xp": 3
        }
      }
    ]
  },
  "forest_elven_ruins_01": {
    "id": "forest_elven_ruins_01",
    "biome": "forest",
    "type": "discovery",
    "title": "Ruínas Élficas",
    "text": "Colunas de pedra branca, cobertas de musgo, emergem entre as raízes. Runas antigas ainda brilham fracamente.",
    "flavor": "Arquitetura anterior à queda das casas maiores — três mil anos, talvez mais.",
    "choices": [
      {
        "label": "Estudar as runas",
        "skill": "int",
        "dc": 13,
        "outcome_ok": {
          "text_by_background": {
            "sage": "Você reconhece o dialeto do Alto-Élfico. As runas narram a morte de uma rainha. Há um tesouro escondido."
          },
          "text_by_class": {
            "mago": "A magia arcana ainda pulsa nas runas. Você absorve conhecimento."
          },
          "text": "Você decifra fragmentos. Menção a um \"salão selado\" nas profundezas.",
          "reward_xp": 30
        },
        "outcome_fail": {
          "text": "As runas são indecifráveis pra você. Apenas musgo e pedra velha.",
          "reward_xp": 5
        }
      },
      {
        "label": "Escavar entre as raízes",
        "skill": "str",
        "dc": 12,
        "outcome_ok": {
          "text": "Você move pedras pesadas. Encontra relíquias preservadas pelo tempo.",
          "reward_xp": 20,
          "loot_table": "forest_elven_ruins_dig",
          "loot_rolls": 2
        },
        "outcome_partial": {
          "text": "Cava um pouco e encontra um único objeto antes de exaustão.",
          "loot_table": "forest_elven_ruins_dig",
          "loot_rolls": 1
        },
        "outcome_fail": {
          "text": "As raízes são grossas demais. Você desiste, suado."
        }
      },
      {
        "label": "Respeitar o local e partir",
        "outcome_ok": {
          "text_by_alignment": {
            "good": "Você inclina a cabeça em respeito aos antigos. Sente paz."
          },
          "text": "Você toca uma coluna levemente e segue caminho.",
          "reward_xp": 8
        }
      }
    ]
  },
  "forest_caravan_remains_01": {
    "id": "forest_caravan_remains_01",
    "biome": "forest",
    "type": "discovery",
    "title": "Restos da Caravana",
    "text": "Carroças quebradas, mantimentos espalhados. Pegadas seguem norte — bandidos.",
    "flavor": "Esta é a caravana que o mensageiro mencionava.",
    "choices": [
      {
        "label": "Investigar e seguir as pegadas",
        "skill": "wis",
        "dc": 12,
        "outcome_ok": {
          "text": "As pegadas levam pro norte. Bandidos liderados por Grog — você identifica o emblema gravado numa lâmina quebrada.",
          "reward_xp": 30
        },
        "outcome_partial": {
          "text": "Você segue a trilha parcialmente. Sabe a direção geral.",
          "reward_xp": 15
        },
        "outcome_fail": {
          "text": "Você perde a trilha entre folhas mortas. Apenas destroços restam."
        }
      },
      {
        "label": "Saquear o que sobrou",
        "skill": "dex",
        "dc": 10,
        "outcome_ok": {
          "text": "Você acha mantimentos úteis nos destroços.",
          "reward_gold": 15,
          "loot_table": "forest_basic",
          "loot_rolls": 2
        },
        "outcome_fail": {
          "text": "Tudo já foi levado. Resta a sucata."
        }
      },
      {
        "label": "Deixar em paz por respeito",
        "outcome_ok": {
          "text_by_alignment": {
            "good": "Você assente com a cabeça e segue. Os mortos merecem paz."
          },
          "text": "Você assente com a cabeça e segue.",
          "reward_xp": 5
        }
      }
    ]
  },
  "forest_ancient_tree_quest_01": {
    "id": "forest_ancient_tree_quest_01",
    "biome": "forest",
    "type": "quest_hook",
    "title": "Árvore Antiga",
    "text": "Uma árvore monumental, tronco largo como torre, pulsa levemente. Uma voz ressoa na sua mente. \"Viajante... a mata sofre. Ajude-nos.\"",
    "flavor": "Senciente. Antiga. E claramente em apuros.",
    "choices": [
      {
        "label": "Aceitar a missão",
        "skill": "wis",
        "dc": 10,
        "outcome_ok": {
          "text_by_class": {
            "druida": "Você sente a dor dela como sua. A corrupção vem fundo. Aceita sem hesitação."
          },
          "text": "\"Nas profundezas da Mata Sussurrante, um dos nossos foi corrompido. Purifique-o.\" Você sente o chamado.",
          "reward_xp": 20,
          "starts_quest": "forest_ancient_grove"
        },
        "outcome_fail": {
          "text": "A voz se cala. Você hesita demais. A árvore não insiste."
        }
      },
      {
        "label": "Recusar",
        "outcome_ok": {
          "text": "\"Entendo, viajante. Que a mata te guie de qualquer forma.\" A voz some."
        }
      }
    ]
  },
  "mountain_giant_attack_01": {
    "id": "mountain_giant_attack_01",
    "biome": "mountain",
    "type": "combat_forced",
    "title": "Gigante das Pedras",
    "text": "A terra treme. Um gigante das pedras emerge de trás de um paredão, lasca de granito na mão como se fosse lâmina.",
    "flavor": "Musgo antigo cobre sua pele — dorme aqui há décadas, talvez séculos.",
    "combat": {
      "enemy_id": "stone_giant",
      "enemy_count": 1,
      "surprise": true
    },
    "victory_loot_table": "mountain_giant_drop",
    "victory_loot_rolls": 2,
    "victory_xp": 90
  },
  "mountain_troll_ambush_01": {
    "id": "mountain_troll_ambush_01",
    "biome": "mountain",
    "type": "combat_forced",
    "title": "Troll na Ravina",
    "text": "A ravina estreita te força a um desfiladeiro apertado. Um troll surge de debaixo de uma pedra saliente, saliva escorrendo.",
    "flavor": "Ossos espalhados denunciam que não é o primeiro viajante — nem será o último.",
    "combat": {
      "enemy_id": "mountain_troll",
      "enemy_count": 1,
      "surprise": false
    },
    "victory_loot_table": "mountain_giant_drop",
    "victory_loot_rolls": 2,
    "victory_xp": 75
  },
  "mountain_dwarven_patrol_01": {
    "id": "mountain_dwarven_patrol_01",
    "biome": "mountain",
    "type": "combat_optional",
    "title": "Patrulha Anã Desconfiada",
    "text": "Três anões armados de machados bloqueiam a trilha. O líder cofia a barba grisalha. \"Identifique-se, forasteiro. Estes caminhos são território do Clã Thorak.\"",
    "flavor": "Armaduras de placas com runas de família. Não são bandidos — são guardiões.",
    "choices": [
      {
        "label": "Atacar imediatamente",
        "outcome_ok": {
          "text": "Você saca a arma. Os machados anões respondem em sincronia.",
          "combat": {
            "enemy_id": "dwarf_patrol",
            "enemy_count": 3
          }
        }
      },
      {
        "label": "Explicar com cortesia anã",
        "skill": "cha",
        "dc": 13,
        "outcome_ok": {
          "text_by_class": {
            "guerreiro": "Você aperta o antebraço — saudação marcial anã. O líder assente, impressionado. \"Forasteiro honrado. Passe.\""
          },
          "text_by_background": {
            "soldier": "Sua postura militar os convence de que é pago, não ladino. Liberam passagem com gruñidos aprovadores."
          },
          "text": "Você fala devagar, mostra palmas vazias. O líder baixa o machado. \"Passe. Mas não toque nada das rochas sagradas.\"",
          "reward_xp": 20
        },
        "outcome_fail": {
          "text": "Suas palavras soam falsas aos ouvidos deles. \"Forasteiro mentiroso.\" Avançam.",
          "combat": {
            "enemy_id": "dwarf_patrol",
            "enemy_count": 3
          }
        }
      },
      {
        "label": "Subornar com Valdoritas (-20)",
        "skill": "cha",
        "dc": 12,
        "outcome_ok": {
          "text": "O líder pega as moedas com relutância. \"Isto não é suborno. É pedágio. Nunca mais passe aqui.\"",
          "reward_gold": -20,
          "reward_xp": 10
        },
        "outcome_fail": {
          "text": "\"Anões não vendem honra.\" Cospe no chão. Avançam ofendidos.",
          "reward_gold": -20,
          "combat": {
            "enemy_id": "dwarf_patrol",
            "enemy_count": 3
          }
        }
      }
    ]
  },
  "mountain_eagle_nest_01": {
    "id": "mountain_eagle_nest_01",
    "biome": "mountain",
    "type": "combat_optional",
    "title": "Águia Gigante Defende Ninho",
    "text": "Uma sombra enorme passa sobre você. Uma águia do tamanho de cavalo pousa entre você e seu ninho num pináculo rochoso. Asas abertas, grito estridente.",
    "flavor": "Filhotes cheiam no ninho. A mãe não vai recuar.",
    "choices": [
      {
        "label": "Lutar",
        "outcome_ok": {
          "text": "Você se prepara. Ela mergulha com garras em riste.",
          "combat": {
            "enemy_id": "giant_eagle",
            "enemy_count": 1
          }
        }
      },
      {
        "label": "Recuar lentamente",
        "skill": "wis",
        "dc": 12,
        "outcome_ok": {
          "text_by_class": {
            "patrulheiro": "Você reconhece os sinais de ameaça iminente. Desce de costas, sem virar. Ela observa, tensa, mas não ataca."
          },
          "text": "Você dá passos lentos pra trás, olhos baixos. Ela mantém posição até você sumir na curva.",
          "reward_xp": 15
        },
        "outcome_fail": {
          "text": "Seu movimento errado a provoca. Ela ataca!",
          "combat": {
            "enemy_id": "giant_eagle",
            "enemy_count": 1
          }
        }
      },
      {
        "label": "Oferecer carne (rações)",
        "skill": "wis",
        "dc": 14,
        "outcome_ok": {
          "text": "Você joga as rações longe do ninho. Ela avalia, pega a oferenda e voa pros filhotes. Caminho liberado.",
          "reward_xp": 20
        },
        "outcome_fail": {
          "text": "Ela interpreta como ameaça aos filhotes. Ataca!",
          "combat": {
            "enemy_id": "giant_eagle",
            "enemy_count": 1
          }
        }
      }
    ]
  },
  "mountain_avalanche_01": {
    "id": "mountain_avalanche_01",
    "biome": "mountain",
    "type": "hazard",
    "title": "Avalanche Iminente",
    "text": "Um estrondo surdo vem do alto. Neve e pedras soltas descem em cascata pela encosta — direto sobre a trilha.",
    "flavor": "Primavera derrete o que o inverno acumula. A montanha cobra.",
    "choices": [
      {
        "label": "Correr pra abrigo",
        "skill": "dex",
        "dc": 14,
        "outcome_ok": {
          "text": "Você mergulha atrás de um paredão rochoso. A avalanche passa a metros de você, cobrindo a trilha onde estava.",
          "reward_xp": 15
        },
        "outcome_partial": {
          "text": "Você chega ao abrigo, mas uma rocha te atinge de raspão.",
          "hp_delta": -4
        },
        "outcome_fail": {
          "text": "Você tropeça no cascalho solto. A avalanche te pega de cheio. Acorda enterrado até o peito, ferido.",
          "hp_delta": -8
        }
      }
    ]
  },
  "mountain_thin_air_01": {
    "id": "mountain_thin_air_01",
    "biome": "mountain",
    "type": "hazard",
    "title": "Ar Rarefeito",
    "text": "A altitude cresce. Seu peito aperta. Cada passo vira esforço. Tontura, visão embaçada — os pulmões clamam por ar que não vem.",
    "flavor": "Picos proibitivos. O sangue não obedece as ordens.",
    "choices": [
      {
        "label": "Aguentar e continuar",
        "skill": "con",
        "dc": 13,
        "outcome_ok": {
          "text": "Você respira fundo, pausa, segue. Corpo se ajusta. Lenta, mas firmemente, progride.",
          "reward_xp": 10
        },
        "outcome_partial": {
          "text": "Você consegue — mas os pulmões queimam. Chega ao topo esgotado.",
          "hp_delta": -3
        },
        "outcome_fail": {
          "text": "Você desmaia brevemente. Acorda na encosta, cabeça latejando.",
          "hp_delta": -6
        }
      }
    ]
  },
  "mountain_dwarf_smith_01": {
    "id": "mountain_dwarf_smith_01",
    "biome": "mountain",
    "type": "social",
    "title": "Ferreiro Anão na Estrada",
    "text": "Um anão barbudo descansa sob um penedo, bigorna portátil e fole de couro ao lado. Ele te saúda. \"Ah, um viajante! Preciso de ajuda — ou estou disposto a negociar.\"",
    "flavor": "As mãos calosas e as queimaduras antigas denunciam décadas de forja.",
    "choices": [
      {
        "label": "Negociar ferramentas",
        "skill": "cha",
        "dc": 13,
        "outcome_ok": {
          "text_by_class": {
            "guerreiro": "Ele reconhece um guerreiro de verdade pelos calos nas mãos. \"Pra ti, preço de camarada.\" Oferece desconto.",
            "ladino": "\"Hm. Mãos leves, olhos espertos.\" Ele negocia com cautela, mas fecha negócio."
          },
          "text": "Você barganha com cordialidade. Ele oferece um item de seu estoque.",
          "reward_xp": 15,
          "loot_table": "mountain_dwarven_smith_offer",
          "loot_rolls": 1
        },
        "outcome_fail": {
          "text": "Ele ri da sua oferta. \"Forasteiro, nem em sonho.\" Segue sem vender."
        }
      },
      {
        "label": "Oferecer ajuda com fole",
        "skill": "str",
        "dc": 11,
        "outcome_ok": {
          "text": "Você bombeia o fole por uma hora. Ele aquece o metal, bate, forja. Em gratidão, te dá um item pequeno mas útil.",
          "reward_xp": 20,
          "loot_table": "mountain_dwarven_smith_offer",
          "loot_rolls": 1
        },
        "outcome_fail": {
          "text": "Você cansa antes do necessário. Ele agradece a intenção, nada dá.",
          "reward_xp": 5
        }
      },
      {
        "label": "Seguir caminho",
        "outcome_ok": {
          "text": "Você acena. Ele volta a atiçar o fogo, resmungando."
        }
      }
    ]
  },
  "mountain_lost_climber_01": {
    "id": "mountain_lost_climber_01",
    "biome": "mountain",
    "type": "social",
    "title": "Alpinista Preso em Fenda",
    "text": "Você ouve gritos abafados. Um alpinista está preso em uma fenda profunda, perna torta num ângulo errado. \"Por favor! Um troll me empurrou aqui... ainda deve estar por perto.\"",
    "flavor": "Corda cortada, picareta quebrada. Não caiu — foi empurrado.",
    "choices": [
      {
        "label": "Ajudar — caçar o troll",
        "skill": "wis",
        "dc": 10,
        "outcome_ok": {
          "text_by_alignment": {
            "good": "Você jura ao alpinista: \"Vou voltar com sua segurança.\" Ele chora de alívio.",
            "evil": "Você avalia: o troll pagará pelo inconveniente. Aceita com motivos próprios."
          },
          "text": "Você aceita. Promete voltar após eliminar a ameaça.",
          "reward_xp": 10,
          "starts_quest": "mountain_lost_climber_quest"
        },
        "outcome_fail": {
          "text": "Você hesita demais. Ele interpreta como recusa. \"Então me deixe morrer em paz.\" Você se afasta, incômodo."
        }
      },
      {
        "label": "Puxar ele agora (arriscado)",
        "skill": "str",
        "dc": 15,
        "outcome_ok": {
          "text": "Com esforço imenso, você o iça. Ele grita de dor mas chega à superfície. Ofega, agradece, manca pro acampamento mais próximo.",
          "reward_xp": 25,
          "reward_gold": 30
        },
        "outcome_fail": {
          "text": "A corda escapa. Ele cai de volta gritando. Você precisa achar outra forma.",
          "hp_delta": -2
        }
      },
      {
        "label": "Voltar com ajuda (quest stage_2)",
        "outcome_ok": {
          "text": "Você volta após lidar com o troll. Içam ele juntos. Em gratidão, ele te dá a bolsa de Valdoritas que carregava.",
          "reward_gold": 40,
          "reward_xp": 30
        }
      }
    ]
  },
  "mountain_hermit_sage_01": {
    "id": "mountain_hermit_sage_01",
    "biome": "mountain",
    "type": "social",
    "title": "Eremita Sábio",
    "text": "Uma cabana de pedra no alto do penhasco. Um velho de barba branca te observa aproximar, olhos claros apesar da idade. \"Pouco sobe até aqui. O que procura, viajante?\"",
    "flavor": "Pergaminhos antigos secam ao sol. Ele passou a vida fugindo do mundo — ou estudando-o de longe.",
    "choices": [
      {
        "label": "Pedir conhecimento",
        "skill": "int",
        "dc": 13,
        "outcome_ok": {
          "text_by_alignment": {
            "good": "Ele sente pureza na sua intenção. Compartilha uma profecia há muito escondida. \"O caminho que escolhe o homem, nenhuma estrela traça por ele.\"",
            "evil": "Seus olhos endurecem. \"Sabedoria não é pra ser usada assim.\" Fala pouco, mas preciso o suficiente pra ser útil."
          },
          "text_by_class": {
            "mago": "Ele reconhece um colega de estudos. Abre tomos antigos. Você absorve magia perdida."
          },
          "text": "Ele partilha o que sabe sobre os ventos, rotas seguras e o que habita os picos. Você parte mais sábio.",
          "reward_xp": 30
        },
        "outcome_fail": {
          "text": "Ele responde em enigmas. \"Se o jovem não pergunta certo, o velho não responde claro.\" Você sai mais confuso.",
          "reward_xp": 5
        }
      },
      {
        "label": "Oferecer comida/companhia",
        "skill": "cha",
        "dc": 10,
        "outcome_ok": {
          "text": "Ele aceita o pão e o vinho. Conversam até o pôr do sol. Em gratidão, ele te benze — você sente o peso da jornada diminuir.",
          "hp_delta": 10,
          "reward_xp": 20
        },
        "outcome_fail": {
          "text": "Ele recusa com gentileza. \"Não preciso. Mas obrigado.\" Segue olhando o horizonte."
        }
      },
      {
        "label": "Partir sem incomodar",
        "outcome_ok": {
          "text_by_alignment": {
            "good": "Você deixa um gesto de respeito — um galho arranjado no chão como oferenda silenciosa. Ele sorri ao ver."
          },
          "text": "Você assente e desce. Ele continua imóvel, parte da paisagem.",
          "reward_xp": 5
        }
      }
    ]
  },
  "mountain_ancient_inscription_01": {
    "id": "mountain_ancient_inscription_01",
    "biome": "mountain",
    "type": "discovery",
    "title": "Inscrição Antiga em Pedra",
    "text": "Uma parede rochosa tem símbolos entalhados — não é rúnico anão nem élfico. Algo mais antigo. Os contornos sugerem uma linguagem esquecida.",
    "flavor": "As ranhuras são fundas. Quem entalhou tinha tempo — e motivo.",
    "choices": [
      {
        "label": "Decifrar os símbolos",
        "skill": "int",
        "dc": 14,
        "outcome_ok": {
          "text_by_background": {
            "sage": "Você reconhece: proto-gigante. Um aviso — \"abaixo dorme o que não deve acordar.\" Você anota meticulosamente cada traço."
          },
          "text_by_class": {
            "mago": "A escrita pulsa com magia latente. Você absorve fragmentos de conhecimento arcano perdido."
          },
          "text": "Você identifica padrões. É uma advertência — mas também um mapa. Há algo oculto aqui perto.",
          "reward_xp": 35
        },
        "outcome_partial": {
          "text": "Você pega o sentido geral. Perigo. Mas detalhes escapam.",
          "reward_xp": 15
        },
        "outcome_fail": {
          "text": "Os símbolos permanecem indecifráveis. Apenas pedra riscada."
        }
      },
      {
        "label": "Copiar pra estudar depois",
        "skill": "dex",
        "dc": 10,
        "outcome_ok": {
          "text": "Você gasta tempo copiando cada marca. Em algum dia, algum sábio decifrará. Sente que fez o certo.",
          "reward_xp": 15
        },
        "outcome_fail": {
          "text": "Sua cópia fica imprecisa. Inútil pra qualquer estudioso.",
          "reward_xp": 3
        }
      },
      {
        "label": "Ignorar e seguir",
        "outcome_ok": {
          "text": "Você passa. Pedras têm muitos segredos; nem todos são seus.",
          "reward_xp": 3
        }
      }
    ]
  },
  "mountain_abandoned_mine_01": {
    "id": "mountain_abandoned_mine_01",
    "biome": "mountain",
    "type": "discovery",
    "title": "Mina Abandonada",
    "text": "Uma entrada escorada com vigas apodrecidas. Letras rúnicas anãs pálidas sobre a lintel. Parece abandonada há décadas.",
    "flavor": "Pó assentou onde antes pés andaram. Mas algo brilha no fundo, talvez.",
    "choices": [
      {
        "label": "Explorar as galerias",
        "skill": "int",
        "dc": 12,
        "outcome_ok": {
          "text_by_background": {
            "soldier": "Olhos treinados: você identifica pontos de colapso, passa seguro e acha o filão rico que os anões abandonaram."
          },
          "text": "Você avança com cuidado, testando o chão. Encontra veios de minério e ferramentas esquecidas.",
          "reward_xp": 25,
          "loot_table": "mountain_abandoned_mine_dig",
          "loot_rolls": 2
        },
        "outcome_partial": {
          "text": "Você acha algumas coisas úteis antes do medo de desabamento te expulsar.",
          "reward_xp": 10,
          "loot_table": "mountain_abandoned_mine_dig",
          "loot_rolls": 1
        },
        "outcome_fail": {
          "text": "Uma viga range. Você bate em retirada sem nada. Melhor vivo que rico enterrado."
        }
      },
      {
        "label": "Escavar na entrada apenas",
        "skill": "str",
        "dc": 10,
        "outcome_ok": {
          "text": "Você mexe em pilhas de detritos próximas à boca da mina. Acha resquícios sem riscar a vida.",
          "reward_xp": 10,
          "loot_table": "mountain_abandoned_mine_dig",
          "loot_rolls": 1
        },
        "outcome_fail": {
          "text": "Os destroços são pesados demais pra mover sozinho. Desiste, suado."
        }
      },
      {
        "label": "Selar e partir (lacrar entrada)",
        "outcome_ok": {
          "text_by_alignment": {
            "good": "Você sela a entrada com pedras. Se algo dorme lá dentro, não será seu despertar. Sente paz."
          },
          "text": "Você empurra pedras sobre a entrada. Alguns segredos ficam melhor fechados.",
          "reward_xp": 10
        }
      }
    ]
  },
  "mountain_dragon_egg_quest_01": {
    "id": "mountain_dragon_egg_quest_01",
    "biome": "mountain",
    "type": "quest_hook",
    "title": "Caçador e o Ovo de Dragão",
    "text": "Um caçador grisalho conta, ao redor de fogueira baixa: \"Vi um ovo enorme. Dragão jovem. No Passo do Dragão. Vale uma fortuna — ou a vida de quem tentar.\"",
    "flavor": "O olhar dele mede o seu: é coragem, ou ganância, que te move?",
    "choices": [
      {
        "label": "Aceitar a caçada",
        "skill": "cha",
        "dc": 10,
        "outcome_ok": {
          "text_by_alignment": {
            "evil": "Seus olhos brilham. Um ovo, um filhote, uma fortuna. O caçador sorri torto: \"Pensei que ia topar.\"",
            "good": "Você aceita com reservas — se há mãe, é justo? Mas a ganância do caçador precisa de alguém pra conter."
          },
          "text": "Você concorda. O caçador aponta a direção do Passo do Dragão. \"Boa sorte. Vai precisar.\"",
          "reward_xp": 20,
          "starts_quest": "mountain_dragon_egg"
        },
        "outcome_fail": {
          "text": "Ele percebe sua hesitação. \"Sábio. Esquece o que te disse.\" Vira-se pro fogo."
        }
      },
      {
        "label": "Recusar — perigoso demais",
        "outcome_ok": {
          "text": "Você declina. Ele assente sem surpresa. \"Poucos têm estômago. Boa jornada.\""
        }
      }
    ]
  }
};

window.__EXPLORACAO_LOOT_TABLES = {
  "forest_basic": [
    {
      "item_id": "Poção de Cura",
      "weight": 30,
      "qty": [
        1,
        1
      ]
    },
    {
      "item_id": "Corda de Cânhamo (15m)",
      "weight": 30,
      "qty": [
        1,
        2
      ]
    },
    {
      "item_id": "Pele de Lobo",
      "weight": 25,
      "qty": [
        1,
        1
      ]
    },
    {
      "item_id": "Anel de Prata",
      "weight": 15,
      "qty": [
        1,
        1
      ]
    }
  ],
  "bandit_combat": [
    {
      "item_id": "Adaga Enferrujada",
      "weight": 40,
      "qty": [
        1,
        1
      ]
    },
    {
      "item_id": "Armadura de Couro",
      "weight": 30,
      "qty": [
        1,
        1
      ]
    },
    {
      "item_id": "Corda de Cânhamo (15m)",
      "weight": 30,
      "qty": [
        1,
        1
      ]
    }
  ],
  "shrine_blessing": [
    {
      "item_id": "Poção de Cura",
      "weight": 60,
      "qty": [
        1,
        2
      ]
    },
    {
      "item_id": "Anel de Prata",
      "weight": 40,
      "qty": [
        1,
        1
      ]
    }
  ],
  "plains_orc_drop": [
    {
      "item_id": "Adaga Enferrujada",
      "weight": 50,
      "qty": [
        1,
        1
      ]
    },
    {
      "item_id": "Pele de Lobo",
      "weight": 30,
      "qty": [
        1,
        1
      ]
    },
    {
      "item_id": "Armadura de Couro",
      "weight": 20,
      "qty": [
        1,
        1
      ]
    }
  ],
  "plains_pilgrim_blessing": [
    {
      "item_id": "Poção de Cura",
      "weight": 100,
      "qty": [
        1,
        2
      ]
    }
  ],
  "plains_battlefield_dig": [
    {
      "item_id": "Adaga Enferrujada",
      "weight": 40,
      "qty": [
        1,
        1
      ]
    },
    {
      "item_id": "Anel de Prata",
      "weight": 20,
      "qty": [
        1,
        1
      ]
    },
    {
      "item_id": "Corda de Cânhamo (15m)",
      "weight": 40,
      "qty": [
        1,
        1
      ]
    }
  ],
  "forest_goblin_drop": [
    {
      "item_id": "Adaga Enferrujada",
      "weight": 60,
      "qty": [
        1,
        1
      ]
    },
    {
      "item_id": "Pele de Lobo",
      "weight": 25,
      "qty": [
        1,
        1
      ]
    },
    {
      "item_id": "Anel de Prata",
      "weight": 15,
      "qty": [
        1,
        1
      ]
    }
  ],
  "forest_druid_blessing": [
    {
      "item_id": "Poção de Cura",
      "weight": 80,
      "qty": [
        1,
        2
      ]
    },
    {
      "item_id": "Anel de Prata",
      "weight": 20,
      "qty": [
        1,
        1
      ]
    }
  ],
  "forest_elven_ruins_dig": [
    {
      "item_id": "Anel de Prata",
      "weight": 50,
      "qty": [
        1,
        1
      ]
    },
    {
      "item_id": "Adaga Enferrujada",
      "weight": 30,
      "qty": [
        1,
        1
      ]
    },
    {
      "item_id": "Corda de Cânhamo (15m)",
      "weight": 20,
      "qty": [
        1,
        1
      ]
    }
  ],
  "mountain_giant_drop": [
    {
      "item_id": "Adaga Enferrujada",
      "weight": 40,
      "qty": [
        1,
        1
      ]
    },
    {
      "item_id": "Armadura de Couro",
      "weight": 35,
      "qty": [
        1,
        1
      ]
    },
    {
      "item_id": "Anel de Prata",
      "weight": 25,
      "qty": [
        1,
        1
      ]
    }
  ],
  "mountain_dwarven_smith_offer": [
    {
      "item_id": "Adaga Enferrujada",
      "weight": 60,
      "qty": [
        1,
        1
      ]
    },
    {
      "item_id": "Armadura de Couro",
      "weight": 40,
      "qty": [
        1,
        1
      ]
    }
  ],
  "mountain_abandoned_mine_dig": [
    {
      "item_id": "Anel de Prata",
      "weight": 50,
      "qty": [
        1,
        2
      ]
    },
    {
      "item_id": "Adaga Enferrujada",
      "weight": 30,
      "qty": [
        1,
        1
      ]
    },
    {
      "item_id": "Corda de Cânhamo (15m)",
      "weight": 20,
      "qty": [
        1,
        1
      ]
    }
  ]
};

window.__EXPLORACAO_QUESTS = {
  "missing_caravan": {
    "id": "missing_caravan",
    "title": "A Caravana Desaparecida",
    "desc": "Uma caravana sumiu na trilha pra Valdoria. Encontre o que aconteceu.",
    "stages": [
      {
        "id": "stage_1",
        "narrative": "Em algum lugar entre os Portões e a Floresta Sussurrante, a caravana parou de se reportar.",
        "trigger": {
          "type": "enter_map",
          "map_id": "whispering_woods"
        }
      },
      {
        "id": "stage_2",
        "narrative": "Você encontra os restos. Pegadas seguem norte. Bandidos.",
        "trigger": {
          "type": "event_outcome",
          "event_id": "forest_caravan_remains_01",
          "choice_idx": 0
        }
      },
      {
        "id": "stage_3",
        "narrative": "O líder dos bandidos cai. Documentos revelam quem orquestrou.",
        "trigger": {
          "type": "combat_victory",
          "enemy_id": "bandit_leader_grog"
        },
        "completes_quest": true
      }
    ]
  },
  "plains_missing_caravan": {
    "id": "plains_missing_caravan",
    "title": "A Caravana Desaparecida (Plains)",
    "desc": "Mensageiro real pediu pra investigar uma caravana sumida.",
    "stages": [
      {
        "id": "stage_1",
        "narrative": "Sigam pra a Floresta Sussurrante.",
        "trigger": {
          "type": "enter_map",
          "map_id": "whispering_woods"
        }
      },
      {
        "id": "stage_2",
        "narrative": "Você encontra os restos da caravana — bandidos.",
        "trigger": {
          "type": "event_outcome",
          "event_id": "forest_caravan_remains_01",
          "choice_idx": 0
        }
      },
      {
        "id": "stage_3",
        "narrative": "Derrote o líder dos bandidos.",
        "trigger": {
          "type": "combat_victory",
          "enemy_id": "bandit_leader_grog"
        },
        "completes_quest": true
      }
    ]
  },
  "plains_rat_infestation": {
    "id": "plains_rat_infestation",
    "title": "Praga de Ratos",
    "desc": "Um camponês precisa de ajuda contra ratos gigantes.",
    "stages": [
      {
        "id": "stage_1",
        "narrative": "Mate o enxame de ratos no celeiro.",
        "trigger": {
          "type": "combat_victory",
          "enemy_id": "rat_swarm"
        }
      },
      {
        "id": "stage_2",
        "narrative": "Volte pra avisar o camponês.",
        "trigger": {
          "type": "event_outcome",
          "event_id": "plains_farmer_distress_01",
          "choice_idx": 2
        },
        "completes_quest": true
      }
    ]
  },
  "forest_lost_child": {
    "id": "forest_lost_child",
    "title": "A Criança Perdida",
    "desc": "Uma criança perdida na floresta precisa de escolta segura.",
    "stages": [
      {
        "id": "stage_1",
        "narrative": "Proteja a criança — um lobo terrível ronda a trilha.",
        "trigger": {
          "type": "combat_victory",
          "enemy_id": "dire_wolf"
        }
      },
      {
        "id": "stage_2",
        "narrative": "Volte com a criança à vila.",
        "trigger": {
          "type": "event_outcome",
          "event_id": "forest_lost_child_01",
          "choice_idx": 2
        },
        "completes_quest": true
      }
    ]
  },
  "forest_ancient_grove": {
    "id": "forest_ancient_grove",
    "title": "O Bosque Ancestral",
    "desc": "Uma árvore antiga pediu ajuda contra corrupção na mata profunda.",
    "stages": [
      {
        "id": "stage_1",
        "narrative": "Adentre a Mata Sussurrante profunda.",
        "trigger": {
          "type": "enter_map",
          "map_id": "whispering_woods_deep"
        }
      },
      {
        "id": "stage_2",
        "narrative": "Derrote o ente corrompido que profana o bosque.",
        "trigger": {
          "type": "combat_victory",
          "enemy_id": "corrupted_treant"
        },
        "completes_quest": true
      }
    ]
  },
  "mountain_lost_climber_quest": {
    "id": "mountain_lost_climber_quest",
    "title": "O Alpinista Preso",
    "desc": "Um troll empurrou um alpinista em uma fenda. Elimine a ameaça e volte.",
    "stages": [
      {
        "id": "stage_1",
        "narrative": "Caçe o troll que empurrou o alpinista na fenda.",
        "trigger": {
          "type": "combat_victory",
          "enemy_id": "mountain_troll"
        }
      },
      {
        "id": "stage_2",
        "narrative": "Volte à fenda para içar o alpinista.",
        "trigger": {
          "type": "event_outcome",
          "event_id": "mountain_lost_climber_01",
          "choice_idx": 2
        },
        "completes_quest": true
      }
    ]
  },
  "mountain_dragon_egg": {
    "id": "mountain_dragon_egg",
    "title": "O Ovo de Dragão",
    "desc": "Um caçador te falou de um ovo de dragão no Passo do Dragão.",
    "stages": [
      {
        "id": "stage_1",
        "narrative": "Adentre o Passo do Dragão.",
        "trigger": {
          "type": "enter_map",
          "map_id": "dragon_pass"
        }
      },
      {
        "id": "stage_2",
        "narrative": "Derrote o dragão jovem que protege o ovo.",
        "trigger": {
          "type": "combat_victory",
          "enemy_id": "young_dragon"
        },
        "completes_quest": true
      }
    ]
  }
};

window.__EXPLORACAO_BUILD = {
    timestamp: '2026-04-24T11:50:27.744184',
    event_count: 42,
    loot_table_count: 12,
    quest_count: 7
};
