// AUTO-GENERATED by scripts/build_exploracao_data.py
// DO NOT EDIT MANUALLY. Edit src/game/exploracao/events/data/*.py e re-run.
// Last build: 2026-04-24T11:29:55.457657

window.__EXPLORACAO_EVENTS = {
  "plains_caravan_01": {
    "id": "plains_caravan_01",
    "biome": "plains",
    "type": "social",
    "title": "Caravana de Comerciantes",
    "text": "Uma pequena caravana de mulas pausa para descansar sob uma árvore. O líder te acena com cautela.",
    "flavor": "O emblema nas caixas é de uma guilda rival — levam mercadorias de contrabando ou legítimas?",
    "choices": [
      {
        "label": "Oferecer escolta até a cidade",
        "skill": "cha",
        "dc": 12,
        "outcome_ok": {
          "text": "O líder aceita com alívio. Pagam +15 Valdoritas pela proteção.",
          "reward_gold": 15,
          "reward_xp": 20
        },
        "outcome_partial": {
          "text": "Aceitam, mas pagam menos. +8 Valdoritas.",
          "reward_gold": 8,
          "reward_xp": 10
        },
        "outcome_fail": {
          "text": "Desconfiam e recusam. Seguem sem você."
        }
      },
      {
        "label": "Inspecionar carga (furtivo)",
        "skill": "dex",
        "dc": 14,
        "only_background": "criminal",
        "outcome_ok": {
          "text": "Você vê contrabando valioso. Aproveita a distração e surrupia 20 Valdoritas.",
          "reward_gold": 20,
          "reward_xp": 15
        },
        "outcome_fail": {
          "text": "Te pegam. Eles fugiram ferindo você.",
          "hp_delta": -3
        }
      },
      {
        "label": "Seguir em frente",
        "outcome_ok": {
          "text": "Você segue sem interagir."
        }
      }
    ]
  },
  "forest_shrine_01": {
    "id": "forest_shrine_01",
    "biome": "forest",
    "type": "discovery",
    "title": "Santuário Esquecido",
    "text": "Um pequeno altar de pedra coberto de musgo. Oferendas antigas de velas queimadas.",
    "flavor": "Uma runa tênue brilha na base.",
    "choices": [
      {
        "label": "Rezar e deixar oferenda",
        "skill": "wis",
        "dc": 10,
        "outcome_ok": {
          "text": "A runa brilha em resposta. Você se sente protegido. +5 HP.",
          "hp_delta": 5,
          "reward_xp": 15
        },
        "outcome_fail": {
          "text": "Reza, mas nada muda. A runa continua tênue."
        }
      },
      {
        "label": "Estudar a runa",
        "skill": "int",
        "dc": 13,
        "outcome_ok": {
          "text": "A runa é de proteção antiga — registrada no seu grimório.",
          "reward_xp": 25
        },
        "outcome_partial": {
          "text": "Você identifica fragmentos, mas o significado escapa.",
          "reward_xp": 10
        },
        "outcome_fail": {
          "text": "Complexa demais. Você desiste."
        }
      },
      {
        "label": "Ignorar",
        "outcome_ok": {
          "text": "Você passa adiante sem perturbar."
        }
      }
    ]
  },
  "mountain_boulder_01": {
    "id": "mountain_boulder_01",
    "biome": "mountain",
    "type": "discovery",
    "title": "Pedregulho na Trilha",
    "text": "Um pedregulho gigante bloqueia parcialmente a passagem. Há espaço para contornar, mas a rota direta exigiria esforço.",
    "flavor": "Marcas frescas — caiu recentemente.",
    "choices": [
      {
        "label": "Empurrar o pedregulho",
        "skill": "str",
        "dc": 15,
        "outcome_ok": {
          "text": "Com esforço hercúleo, a pedra rola pela encosta.",
          "reward_xp": 20
        },
        "outcome_partial": {
          "text": "Move um pouco, mas desliza e machuca o ombro.",
          "hp_delta": -2,
          "reward_xp": 5
        },
        "outcome_fail": {
          "text": "Não cede. Você desiste.",
          "hp_delta": -1
        }
      },
      {
        "label": "Contornar com cuidado",
        "skill": "dex",
        "dc": 10,
        "outcome_ok": {
          "text": "Você passa sem problemas.",
          "reward_xp": 5
        },
        "outcome_fail": {
          "text": "Escorrega um pouco. Arranhões.",
          "hp_delta": -1
        }
      }
    ]
  },
  "forest_poison_trap_01": {
    "id": "forest_poison_trap_01",
    "biome": "forest",
    "type": "hazard",
    "title": "Armadilha de Espinhos Envenenados",
    "text": "Você pisa num gatilho escondido sob folhas secas — espinhos saltam do chão.",
    "flavor": "Caçadores furtivos deixam armadilhas por aqui.",
    "choices": [
      {
        "label": "Reagir",
        "skill": "dex",
        "dc": 13,
        "outcome_ok": {
          "text": "Você salta pra trás no último segundo. Ileso."
        },
        "outcome_fail": {
          "text": "Os espinhos te atingem. Dano mas sem veneno grave.",
          "hp_delta": -4
        }
      }
    ]
  },
  "mountain_rockfall_01": {
    "id": "mountain_rockfall_01",
    "biome": "mountain",
    "type": "hazard",
    "title": "Deslizamento de Pedras",
    "text": "Um estrondo acima — pedras rolam pela encosta em sua direção.",
    "flavor": "Atenção aos sons do vento nas montanhas.",
    "choices": [
      {
        "label": "Esquivar",
        "skill": "dex",
        "dc": 14,
        "outcome_ok": {
          "text": "Você salta pra lateral. Pedras passam rolando.",
          "reward_xp": 5
        },
        "outcome_partial": {
          "text": "Você quase esquiva. Um galho te atinge.",
          "hp_delta": -2
        },
        "outcome_fail": {
          "text": "As pedras te atingem. Ouch.",
          "hp_delta": -6
        }
      }
    ]
  },
  "forest_bandit_ambush_01": {
    "id": "forest_bandit_ambush_01",
    "biome": "forest",
    "type": "combat_optional",
    "title": "Emboscada de Bandidos",
    "text": "Três figuras saltam dos arbustos com facas em punho. \"Suas moedas ou sua vida!\"",
    "flavor": "Pegadas frescas na lama — você devia ter visto.",
    "choices": [
      {
        "label": "Intimidar",
        "skill": "cha",
        "dc": 15,
        "outcome_ok": {
          "text": "Você se ergue com autoridade. Eles fogem.",
          "reward_xp": 30
        },
        "outcome_fail": {
          "text": "Sua voz falha. Eles avançam!",
          "combat": {
            "enemy_id": "bandit_forest_01"
          }
        }
      },
      {
        "label": "Lutar",
        "outcome_ok": {
          "text": "Você saca a arma!",
          "combat": {
            "enemy_id": "bandit_forest_01"
          }
        }
      },
      {
        "label": "Correr",
        "skill": "dex",
        "dc": 12,
        "outcome_ok": {
          "text": "Você escapa pela mata. Fôlego curto.",
          "hp_delta": -2
        },
        "outcome_fail": {
          "text": "Um deles te pega pelo ombro.",
          "combat": {
            "enemy_id": "bandit_forest_01"
          }
        }
      }
    ]
  },
  "plains_orc_raid_01": {
    "id": "plains_orc_raid_01",
    "biome": "plains",
    "type": "combat_forced",
    "title": "Emboscada Orc",
    "text": "Três orcs raiders saltam dos arbustos com machados em punho. Sem tempo de reagir.",
    "flavor": "A bandeira pintada — clã Korthag.",
    "combat": {
      "enemy_id": "orc_raider",
      "enemy_count": 3,
      "surprise": true
    },
    "victory_loot_table": "plains_orc_drop",
    "victory_loot_rolls": 2,
    "victory_xp": 60
  },
  "plains_bandit_ambush_01": {
    "id": "plains_bandit_ambush_01",
    "biome": "plains",
    "type": "combat_forced",
    "title": "Bandidos do Caminho",
    "text": "Dois bandidos pulam de trás de uma carroça abandonada. Lâminas curtas, intenções claras.",
    "flavor": "Marcas no ombro — desertores da guarnição.",
    "combat": {
      "enemy_id": "bandit",
      "enemy_count": 2,
      "surprise": false
    },
    "victory_loot_table": "bandit_combat",
    "victory_loot_rolls": 2,
    "victory_xp": 40
  },
  "plains_bandit_negotiate_01": {
    "id": "plains_bandit_negotiate_01",
    "biome": "plains",
    "type": "combat_optional",
    "title": "Pedágio Improvisado",
    "text": "Dois bandidos bloqueiam a trilha. Olhares calculistas; nem quentes nem frios — só calculadores.",
    "flavor": "Espadas curtas, couro gasto. Não-veteranos.",
    "choices": [
      {
        "label": "Lutar",
        "outcome_ok": {
          "text": "Você saca a arma. Eles avançam!",
          "combat": {
            "enemy_id": "bandit",
            "enemy_count": 2
          }
        }
      },
      {
        "label": "Negociar passagem (-10 Valdoritas)",
        "skill": "cha",
        "dc": 14,
        "outcome_ok": {
          "text": "Eles aceitam ouro pela passagem. Caminho liberado.",
          "reward_gold": -10,
          "reward_xp": 10
        },
        "outcome_fail": {
          "text": "Riem da sua oferta. Sacam armas.",
          "combat": {
            "enemy_id": "bandit",
            "enemy_count": 2
          }
        }
      },
      {
        "label": "Intimidar",
        "skill": "cha",
        "dc": 16,
        "outcome_ok": {
          "text_by_alignment": {
            "evil": "Vossa presença gélida os congela. Fogem aos tropeções.",
            "good": "Vossa firmeza moral os faz hesitar. Recuam, envergonhados."
          },
          "text": "Sua bravata os intimida. Fogem.",
          "reward_xp": 30
        },
        "outcome_fail": {
          "text": "Sua bravata falha — eles riem. E avançam.",
          "combat": {
            "enemy_id": "bandit",
            "enemy_count": 2
          }
        }
      }
    ]
  },
  "plains_lone_wolf_01": {
    "id": "plains_lone_wolf_01",
    "biome": "plains",
    "type": "combat_optional",
    "title": "Lobo Solitário",
    "text": "Um lobo magro rosna baixo, costas arqueadas. Faminto, mas ainda pesando se você vale o esforço.",
    "flavor": "A pelagem rala denuncia falta de presa nesta estação.",
    "choices": [
      {
        "label": "Atacar",
        "outcome_ok": {
          "text": "Você avança primeiro. Ele responde.",
          "combat": {
            "enemy_id": "gray_wolf",
            "enemy_count": 1
          }
        }
      },
      {
        "label": "Acalmar com voz baixa",
        "skill": "wis",
        "dc": 10,
        "outcome_ok": {
          "text_by_class": {
            "patrulheiro": "Você reconhece os sinais — postura, olhar. Sussurra a palavra antiga. Ele baixa a cabeça e some na vegetação."
          },
          "text": "Tom calmo, postura aberta. Ele observa, calcula, e desaparece pelas grama.",
          "reward_xp": 15
        },
        "outcome_fail": {
          "text": "Sua voz tremeu. Ele leu medo.",
          "combat": {
            "enemy_id": "gray_wolf",
            "enemy_count": 1
          }
        }
      },
      {
        "label": "Oferecer comida",
        "skill": "wis",
        "dc": 12,
        "outcome_ok": {
          "text": "Você joga ração no chão. Ele come, observa, e parte. Olhar menos hostil agora.",
          "reward_xp": 10,
          "loot_table": "plains_pilgrim_blessing",
          "loot_rolls": 1
        },
        "outcome_fail": {
          "text": "Ele toma a ração mas não satisfaz a fome. Ataca.",
          "combat": {
            "enemy_id": "gray_wolf",
            "enemy_count": 1
          }
        }
      }
    ]
  },
  "plains_pit_trap_01": {
    "id": "plains_pit_trap_01",
    "biome": "plains",
    "type": "hazard",
    "title": "Cova Oculta",
    "text": "Você pisa em algo macio demais — uma camada de gravetos sobre vazio.",
    "flavor": "Caçadores deixam armadilhas pra javalis. Você não é um.",
    "choices": [
      {
        "label": "Reagir",
        "skill": "dex",
        "dc": 13,
        "outcome_ok": {
          "text": "Você pula pra trás no último momento. Os gravetos caem no buraco que se forma sob o pé.",
          "reward_xp": 5
        },
        "outcome_partial": {
          "text": "Quase escapa — torce o tornozelo na borda.",
          "hp_delta": -2
        },
        "outcome_fail": {
          "text": "Você cai. Estacas no fundo. Sangra ao subir.",
          "hp_delta": -6
        }
      }
    ]
  },
  "plains_brushfire_01": {
    "id": "plains_brushfire_01",
    "biome": "plains",
    "type": "hazard",
    "title": "Incêndio no Mato",
    "text": "Fumaça densa à frente. O fogo atravessa a trilha — pequeno mas rápido. Atravessar é a saída mais curta.",
    "flavor": "Verão seco. Um único raio mata uma planície.",
    "choices": [
      {
        "label": "Atravessar correndo",
        "skill": "con",
        "dc": 12,
        "outcome_ok": {
          "text": "Você passa rápido, abafando a tosse. Roupas chamuscam mas você sobrevive.",
          "reward_xp": 10
        },
        "outcome_partial": {
          "text": "A fumaça toma seus pulmões. Atravessa, mas fraco.",
          "hp_delta": -2
        },
        "outcome_fail": {
          "text": "Você inala demais e cai. Acorda na borda do incêndio, queimado.",
          "hp_delta": -5
        }
      }
    ]
  },
  "plains_caravan_merchant_01": {
    "id": "plains_caravan_merchant_01",
    "biome": "plains",
    "type": "social",
    "title": "Caravana de Mercadores",
    "text": "Uma pequena caravana de mulas pausa para descansar sob uma árvore. O líder te acena com cautela.",
    "flavor": "O emblema nas caixas é de uma guilda rival — levam mercadorias de contrabando ou legítimas?",
    "choices": [
      {
        "label": "Oferecer escolta até a cidade",
        "skill": "cha",
        "dc": 12,
        "outcome_ok": {
          "text": "O líder aceita com alívio. Pagam +15 Valdoritas pela proteção.",
          "reward_gold": 15,
          "reward_xp": 20
        },
        "outcome_partial": {
          "text": "Aceitam, mas pagam menos. +8 Valdoritas.",
          "reward_gold": 8,
          "reward_xp": 10
        },
        "outcome_fail": {
          "text": "Desconfiam e recusam. Seguem sem você."
        }
      },
      {
        "label": "Inspecionar carga (furtivo)",
        "skill": "dex",
        "dc": 14,
        "only_background": "criminal",
        "outcome_ok": {
          "text": "Você vê contrabando valioso. Aproveita a distração e surrupia 20 Valdoritas.",
          "reward_gold": 20,
          "reward_xp": 15
        },
        "outcome_fail": {
          "text": "Te pegam. Eles fugiram ferindo você.",
          "hp_delta": -3
        }
      },
      {
        "label": "Seguir em frente",
        "outcome_ok": {
          "text": "Você segue sem interagir."
        }
      }
    ]
  },
  "plains_farmer_distress_01": {
    "id": "plains_farmer_distress_01",
    "biome": "plains",
    "type": "social",
    "title": "Camponês em Apuros",
    "text": "Um camponês magro vem correndo, abano na mão. \"Senhor(a)! Ratos gigantes no celeiro! Comem tudo!\"",
    "flavor": "Sua única boia. Sem grão, a família não passa do inverno.",
    "choices": [
      {
        "label": "Ouvir a história",
        "skill": "cha",
        "dc": 10,
        "outcome_ok": {
          "text": "Ele explica entre lágrimas. Três ratos enormes, tamanho de cães. Pergunta se você ajuda.",
          "reward_xp": 5,
          "starts_quest": "plains_rat_infestation"
        },
        "outcome_fail": {
          "text": "Ele se confunde, agitado demais. Você não entende direito."
        }
      },
      {
        "label": "Ir agora matar os ratos",
        "outcome_ok": {
          "text": "Vocês correm pro celeiro. Os ratos te atacam!",
          "combat": {
            "enemy_id": "rat_swarm",
            "enemy_count": 1
          }
        }
      },
      {
        "label": "Voltar pra confirmar quest concluída",
        "outcome_ok": {
          "text": "O camponês te recebe ajoelhado. Oferece o pouco que tem.",
          "reward_gold": 20,
          "reward_xp": 30
        }
      }
    ]
  },
  "plains_pilgrim_blessing_01": {
    "id": "plains_pilgrim_blessing_01",
    "biome": "plains",
    "type": "social",
    "title": "Peregrino na Estrada",
    "text": "Uma figura encapuzada caminha lenta, cajado em mão. Te saúda com voz cansada. \"Posso oferecer uma bênção, viajante?\"",
    "flavor": "Símbolos religiosos pendem do cajado — uma ordem antiga.",
    "choices": [
      {
        "label": "Aceitar humildemente",
        "skill": "wis",
        "dc": 10,
        "outcome_ok": {
          "text_by_alignment": {
            "good": "Você se ajoelha. Ele toca sua testa — você sente uma energia quente fluir. +5 HP."
          },
          "text": "Você aceita. Ele recita versos antigos. Sente-se mais forte.",
          "hp_delta": 5,
          "reward_xp": 10,
          "loot_table": "plains_pilgrim_blessing",
          "loot_rolls": 1
        },
        "outcome_fail": {
          "text": "Você aceita por cortesia, mas não sente nada. O peregrino sorri tristemente e segue."
        }
      },
      {
        "label": "Recusar educadamente",
        "outcome_ok": {
          "text": "Ele assente. \"Que os ventos te guiem.\" Segue caminho.",
          "reward_xp": 3
        }
      },
      {
        "label": "Roubar o cajado",
        "skill": "dex",
        "dc": 16,
        "only_alignment": "evil",
        "outcome_ok": {
          "text": "Você arranca o cajado. Ele cai surpreso, mas não revida. Você foge com o tesouro.",
          "reward_gold": 25,
          "reward_xp": -10
        },
        "outcome_fail": {
          "text": "Ele se revela mais forte do que parecia. Te derruba e foge.",
          "hp_delta": -4
        }
      }
    ]
  },
  "plains_old_battlefield_01": {
    "id": "plains_old_battlefield_01",
    "biome": "plains",
    "type": "discovery",
    "title": "Campo de Batalha Antigo",
    "text": "Ossos branqueados sob a grama. Armas enferrujadas saem da terra. Aqui morreram muitos.",
    "flavor": "A vegetação cresce diferente onde sangue se misturou ao solo.",
    "choices": [
      {
        "label": "Cavar ao redor",
        "skill": "int",
        "dc": 12,
        "outcome_ok": {
          "text_by_background": {
            "sage": "Você reconhece marcas em escudos quebrados — Batalha do Vau, há cem anos. Encontra relíquias intactas.",
            "soldier": "Olhos militares: você identifica posições. Dois exércitos. O lado vencedor deixou itens valiosos."
          },
          "text": "Você cava com cuidado. Encontra alguns objetos preservados.",
          "reward_xp": 25,
          "loot_table": "plains_battlefield_dig",
          "loot_rolls": 2
        },
        "outcome_partial": {
          "text": "Acha um item pequeno. Não vale o esforço todo.",
          "reward_xp": 10,
          "loot_table": "plains_battlefield_dig",
          "loot_rolls": 1
        },
        "outcome_fail": {
          "text": "A terra está dura. Você cava por horas e acha apenas pedras."
        }
      },
      {
        "label": "Respeitar e seguir",
        "outcome_ok": {
          "text": "Você inclina a cabeça e segue caminho. Sente que fez o certo.",
          "reward_xp": 5
        }
      }
    ]
  },
  "plains_abandoned_cart_01": {
    "id": "plains_abandoned_cart_01",
    "biome": "plains",
    "type": "discovery",
    "title": "Carroça Abandonada",
    "text": "Uma carroça à beira da estrada. Roda quebrada. Carga ainda amarrada. Sem dono à vista.",
    "flavor": "Pegadas afastam-se rapidamente — alguém fugiu apressado.",
    "choices": [
      {
        "label": "Vasculhar a carga",
        "skill": "dex",
        "dc": 10,
        "outcome_ok": {
          "text": "Você desfaz os nós. Encontra mantimentos e algo de valor.",
          "reward_xp": 10,
          "loot_table": "forest_basic",
          "loot_rolls": 2
        },
        "outcome_fail": {
          "text": "Os nós são complexos. Você cede, frustrado."
        }
      },
      {
        "label": "Deixar como está",
        "outcome_ok": {
          "text": "Não é seu. Você passa adiante.",
          "reward_xp": 3
        }
      }
    ]
  },
  "plains_missing_caravan_hook_01": {
    "id": "plains_missing_caravan_hook_01",
    "biome": "plains",
    "type": "quest_hook",
    "title": "Mensageiro Aflito",
    "text": "Um mensageiro real puxa rédeas ao te ver. \"Viajante! Uma caravana sumiu na estrada pra Floresta Sussurrante. Sabe algo?\"",
    "flavor": "Botões dourados, espada de oficial. Mensagem urgente.",
    "choices": [
      {
        "label": "Aceitar investigar",
        "skill": "cha",
        "dc": 8,
        "outcome_ok": {
          "text": "\"Excelente. Sigam pra a floresta — busquem a caravana. Recompensa garantida na volta.\"",
          "reward_xp": 15,
          "starts_quest": "plains_missing_caravan"
        },
        "outcome_fail": {
          "text": "Ele desconfia da sua hesitação. \"Talvez outro.\" Parte galopando."
        }
      },
      {
        "label": "Recusar",
        "outcome_ok": {
          "text": "Você nega com tato. Ele assente, decepcionado, e segue em busca de outro."
        }
      }
    ]
  }
};

window.__EXPLORACAO_LOOT_TABLES = {
  "forest_basic": [
    {
      "item_id": "Poção de Cura",
      "weight": 30,
      "qty": [
        1,
        1
      ]
    },
    {
      "item_id": "Corda de Cânhamo (15m)",
      "weight": 30,
      "qty": [
        1,
        2
      ]
    },
    {
      "item_id": "Pele de Lobo",
      "weight": 25,
      "qty": [
        1,
        1
      ]
    },
    {
      "item_id": "Anel de Prata",
      "weight": 15,
      "qty": [
        1,
        1
      ]
    }
  ],
  "bandit_combat": [
    {
      "item_id": "Adaga Enferrujada",
      "weight": 40,
      "qty": [
        1,
        1
      ]
    },
    {
      "item_id": "Armadura de Couro",
      "weight": 30,
      "qty": [
        1,
        1
      ]
    },
    {
      "item_id": "Corda de Cânhamo (15m)",
      "weight": 30,
      "qty": [
        1,
        1
      ]
    }
  ],
  "shrine_blessing": [
    {
      "item_id": "Poção de Cura",
      "weight": 60,
      "qty": [
        1,
        2
      ]
    },
    {
      "item_id": "Anel de Prata",
      "weight": 40,
      "qty": [
        1,
        1
      ]
    }
  ],
  "plains_orc_drop": [
    {
      "item_id": "Adaga Enferrujada",
      "weight": 50,
      "qty": [
        1,
        1
      ]
    },
    {
      "item_id": "Pele de Lobo",
      "weight": 30,
      "qty": [
        1,
        1
      ]
    },
    {
      "item_id": "Armadura de Couro",
      "weight": 20,
      "qty": [
        1,
        1
      ]
    }
  ],
  "plains_pilgrim_blessing": [
    {
      "item_id": "Poção de Cura",
      "weight": 100,
      "qty": [
        1,
        2
      ]
    }
  ],
  "plains_battlefield_dig": [
    {
      "item_id": "Adaga Enferrujada",
      "weight": 40,
      "qty": [
        1,
        1
      ]
    },
    {
      "item_id": "Anel de Prata",
      "weight": 20,
      "qty": [
        1,
        1
      ]
    },
    {
      "item_id": "Corda de Cânhamo (15m)",
      "weight": 40,
      "qty": [
        1,
        1
      ]
    }
  ]
};

window.__EXPLORACAO_QUESTS = {
  "missing_caravan": {
    "id": "missing_caravan",
    "title": "A Caravana Desaparecida",
    "desc": "Uma caravana sumiu na trilha pra Valdoria. Encontre o que aconteceu.",
    "stages": [
      {
        "id": "stage_1",
        "narrative": "Em algum lugar entre os Portões e a Floresta Sussurrante, a caravana parou de se reportar.",
        "trigger": {
          "type": "enter_map",
          "map_id": "whispering_woods"
        }
      },
      {
        "id": "stage_2",
        "narrative": "Você encontra os restos. Pegadas seguem norte. Bandidos.",
        "trigger": {
          "type": "event_outcome",
          "event_id": "forest_caravan_remains_01",
          "choice_idx": 0
        }
      },
      {
        "id": "stage_3",
        "narrative": "O líder dos bandidos cai. Documentos revelam quem orquestrou.",
        "trigger": {
          "type": "combat_victory",
          "enemy_id": "bandit_leader_grog"
        },
        "completes_quest": true
      }
    ]
  },
  "plains_missing_caravan": {
    "id": "plains_missing_caravan",
    "title": "A Caravana Desaparecida (Plains)",
    "desc": "Mensageiro real pediu pra investigar uma caravana sumida.",
    "stages": [
      {
        "id": "stage_1",
        "narrative": "Sigam pra a Floresta Sussurrante.",
        "trigger": {
          "type": "enter_map",
          "map_id": "whispering_woods"
        }
      },
      {
        "id": "stage_2",
        "narrative": "Você encontra os restos da caravana — bandidos.",
        "trigger": {
          "type": "event_outcome",
          "event_id": "forest_caravan_remains_01",
          "choice_idx": 0
        }
      },
      {
        "id": "stage_3",
        "narrative": "Derrote o líder dos bandidos.",
        "trigger": {
          "type": "combat_victory",
          "enemy_id": "bandit_leader_grog"
        },
        "completes_quest": true
      }
    ]
  },
  "plains_rat_infestation": {
    "id": "plains_rat_infestation",
    "title": "Praga de Ratos",
    "desc": "Um camponês precisa de ajuda contra ratos gigantes.",
    "stages": [
      {
        "id": "stage_1",
        "narrative": "Mate o enxame de ratos no celeiro.",
        "trigger": {
          "type": "combat_victory",
          "enemy_id": "rat_swarm"
        }
      },
      {
        "id": "stage_2",
        "narrative": "Volte pra avisar o camponês.",
        "trigger": {
          "type": "event_outcome",
          "event_id": "plains_farmer_distress_01",
          "choice_idx": 2
        },
        "completes_quest": true
      }
    ]
  }
};

window.__EXPLORACAO_BUILD = {
    timestamp: '2026-04-24T11:29:55.457657',
    event_count: 18,
    loot_table_count: 6,
    quest_count: 3
};
