var Dice3D=(()=>{'use strict';if(typeof THREE==='undefined'){console.warn('[DICE3D] THREE.js not loaded — Dice3D disabled (fallback to emoji)');return null;}
var _perfTier=window._valdoriaPerformanceTier||'full';var _isLite=_perfTier==='lite';var _isMedium=_perfTier==='medium';var _labelRes=_isLite?128:256;
const EDGE_COLOR=0xc4953a;const V_GOLD_HEX='#c4953a';const V_SUCCESS_HEX='#4caf50';const V_DANGER_HEX='#e74c3c';const ROLL_MS_DEFAULT=2000;function haptic(style){try{var tg=window.Telegram&&window.Telegram.WebApp;if(tg&&tg.HapticFeedback)tg.HapticFeedback.impactOccurred(style);}catch(e){console.warn('[DICE_3D]',e);}}
function makeLabelTexture(num,size){size=size||_labelRes;var c=document.createElement('canvas');c.width=size;c.height=size;var ctx=c.getContext('2d');ctx.clearRect(0,0,size,size);var text=String(num);var fontSize=text.length>1?size*0.62:size*0.74;ctx.font='bold '+fontSize+'px "Cinzel", Georgia, serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.strokeStyle='rgba(0,0,0,0.8)';ctx.lineWidth=12;ctx.lineJoin='round';ctx.strokeText(text,size/2,size/2);ctx.shadowColor='rgba(212,175,55,0.6)';ctx.shadowBlur=size*0.08;ctx.fillStyle='#fff8e0';ctx.fillText(text,size/2,size/2);if(num===6||num===9){ctx.shadowBlur=0;var w=ctx.measureText(text).width;ctx.fillRect(size/2-w/2,size/2+fontSize*0.36,w,fontSize*0.07);}
var tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;return tex;}
function applyGradient(geo){var pos=geo.attributes.position;if(_isLite){var colors=new Float32Array(pos.count*3);var flat=new THREE.Color(0x7a5a2a);for(var i=0;i<pos.count;i++){colors[i*3]=flat.r;colors[i*3+1]=flat.g;colors[i*3+2]=flat.b;}geo.setAttribute("color",new THREE.BufferAttribute(colors,3));return;}var yMin=Infinity,yMax=-Infinity;for(var i=0;i<pos.count;i++){var y=pos.getY(i);if(y<yMin)yMin=y;if(y>yMax)yMax=y;}
var range=yMax-yMin||1;var colors=new Float32Array(pos.count*3);var cLow=new THREE.Color(0x2a1e10);var cHigh=new THREE.Color(0xc4953a);var tmp=new THREE.Color();for(var i=0;i<pos.count;i++){var t=(pos.getY(i)-yMin)/range;tmp.copy(cLow).lerp(cHigh,t);colors[i*3]=tmp.r;colors[i*3+1]=tmp.g;colors[i*3+2]=tmp.b;}
geo.setAttribute('color',new THREE.BufferAttribute(colors,3));}
function makeBodyMat(){return new THREE.MeshPhongMaterial({vertexColors:true,shininess:100,specular:new THREE.Color(0x554433),flatShading:true,});}
function addEdgeWire(mesh,geo,threshold){if(_isLite)return;var edges=new THREE.EdgesGeometry(geo,threshold||15);mesh.add(new THREE.LineSegments(edges,new THREE.LineBasicMaterial({color:EDGE_COLOR,transparent:true,opacity:0.5})));}
function computeLabelUp(n){var worldUp=new THREE.Vector3(0,1,0);var faceUp=worldUp.clone().addScaledVector(n,-worldUp.dot(n));if(faceUp.lengthSq()<0.001){faceUp=new THREE.Vector3(1,0,0).addScaledVector(n,-new THREE.Vector3(1,0,0).dot(n));}
return faceUp.normalize();}
function addLabels(mesh,numbers,centers,normals,labelSize){var labelUps=[];for(var i=0;i<numbers.length;i++){var tex=makeLabelTexture(numbers[i],_labelRes);var mat=new THREE.MeshBasicMaterial({map:tex,transparent:true,depthWrite:false,side:THREE.DoubleSide,});var plane=new THREE.Mesh(new THREE.PlaneGeometry(labelSize,labelSize),mat);var n=normals[i];plane.position.copy(centers[i].clone().add(n.clone().multiplyScalar(0.01)));var faceUp=computeLabelUp(n);labelUps.push(faceUp.clone());var faceRight=new THREE.Vector3().crossVectors(faceUp,n).normalize();plane.rotation.setFromRotationMatrix(new THREE.Matrix4().makeBasis(faceRight,faceUp,n));mesh.add(plane);}
if(!mesh.userData.labelUps)mesh.userData.labelUps=labelUps;}
function facesFromTris(geo,count){var pos=geo.attributes.position;var centers=[],normals=[];for(var f=0;f<count;f++){var i=f*3;var a=new THREE.Vector3().fromBufferAttribute(pos,i);var b=new THREE.Vector3().fromBufferAttribute(pos,i+1);var c=new THREE.Vector3().fromBufferAttribute(pos,i+2);var center=a.clone().add(b).add(c).divideScalar(3);var normal=new THREE.Vector3().crossVectors(b.clone().sub(a),c.clone().sub(a)).normalize();if(normal.dot(center)<0)normal.negate();centers.push(center);normals.push(normal);}
return{centers:centers,normals:normals};}
function facesFromClusters(geo){var pos=geo.attributes.position;var triCount=pos.count/3;var tN=[],tC=[];for(var t=0;t<triCount;t++){var i=t*3;var a=new THREE.Vector3().fromBufferAttribute(pos,i);var b=new THREE.Vector3().fromBufferAttribute(pos,i+1);var c=new THREE.Vector3().fromBufferAttribute(pos,i+2);tC.push(a.clone().add(b).add(c).divideScalar(3));var n=new THREE.Vector3().crossVectors(b.clone().sub(a),c.clone().sub(a)).normalize();if(n.dot(tC[t])<0)n.negate();tN.push(n);}
var used=[];for(var t=0;t<triCount;t++)used.push(false);var centers=[],normals=[];for(var t=0;t<triCount;t++){if(used[t])continue;used[t]=true;var cluster=[t];for(var u=t+1;u<triCount;u++){if(!used[u]&&tN[t].dot(tN[u])>0.999){used[u]=true;cluster.push(u);}}
var center=new THREE.Vector3();for(var j=0;j<cluster.length;j++)center.add(tC[cluster[j]]);center.divideScalar(cluster.length);centers.push(center);normals.push(tN[t]);}
return{centers:centers,normals:normals};}
function buildD4(){var base=new THREE.TetrahedronGeometry(1.1);var geo=base.toNonIndexed();applyGradient(geo);var mesh=new THREE.Mesh(geo,makeBodyMat());addEdgeWire(mesh,base);var numbers=[1,2,3,4];var faces=facesFromTris(geo,4);mesh.userData={type:'d4',numbers:numbers,normals:faces.normals};addLabels(mesh,numbers,faces.centers,faces.normals,0.85);mesh.castShadow=true;return mesh;}
function buildD6(){var base=new THREE.BoxGeometry(1.2,1.2,1.2);var geo=base.toNonIndexed();applyGradient(geo);var mesh=new THREE.Mesh(geo,makeBodyMat());addEdgeWire(mesh,base);var D6_NUMS=[3,4,1,6,2,5];var pos=geo.attributes.position;var centers=[],normals=[];for(var f=0;f<6;f++){var bi=f*6;var center=new THREE.Vector3();for(var v=0;v<6;v++)center.add(new THREE.Vector3().fromBufferAttribute(pos,bi+v));center.divideScalar(6);var a=new THREE.Vector3().fromBufferAttribute(pos,bi);var b=new THREE.Vector3().fromBufferAttribute(pos,bi+1);var c=new THREE.Vector3().fromBufferAttribute(pos,bi+2);var n=new THREE.Vector3().crossVectors(b.clone().sub(a),c.clone().sub(a)).normalize();if(n.dot(center)<0)n.negate();centers.push(center);normals.push(n);}
mesh.userData={type:'d6',numbers:D6_NUMS,normals:normals};addLabels(mesh,D6_NUMS,centers,normals,0.92);mesh.castShadow=true;return mesh;}
function buildD8(){var base=new THREE.OctahedronGeometry(1.05);var geo=base.toNonIndexed();applyGradient(geo);var mesh=new THREE.Mesh(geo,makeBodyMat());addEdgeWire(mesh,base);var numbers=[1,2,3,4,5,6,7,8];var faces=facesFromTris(geo,8);mesh.userData={type:'d8',numbers:numbers,normals:faces.normals};addLabels(mesh,numbers,faces.centers,faces.normals,0.55);mesh.castShadow=true;return mesh;}
function buildD10(){var scale=1.15;var step=Math.PI*2/10;var hOff=0.105;var rawVerts=[];for(var i=0;i<10;i++){var angle=i*step;rawVerts.push(new THREE.Vector3(Math.cos(angle),Math.sin(angle),hOff*(i%2?1:-1)).normalize().multiplyScalar(scale));}
rawVerts.push(new THREE.Vector3(0,0,-1).multiplyScalar(scale));rawVerts.push(new THREE.Vector3(0,0,1).multiplyScalar(scale));var kiteFaces=[[5,7,11,0],[4,2,10,1],[1,3,11,2],[0,8,10,3],[7,9,11,4],[8,6,10,5],[9,1,11,6],[2,0,10,7],[3,5,11,8],[6,4,10,9],];var equatTris=[[1,0,2],[1,2,3],[3,2,4],[3,4,5],[5,4,6],[5,6,7],[7,6,8],[7,8,9],[9,8,0],[9,0,1],];var positions=[],normArr=[];var faceNormals=[],faceCenters=[],faceNumbers=[];kiteFaces.forEach(function(face){var a=face[0],b=face[1],pole=face[2],num=face[3];var va=rawVerts[a],vb=rawVerts[b],vc=rawVerts[pole];positions.push(va.x,va.y,va.z,vb.x,vb.y,vb.z,vc.x,vc.y,vc.z);var e1=new THREE.Vector3().subVectors(vb,va);var e2=new THREE.Vector3().subVectors(vc,va);var n=new THREE.Vector3().crossVectors(e1,e2).normalize();var center=new THREE.Vector3().addVectors(va,vb).add(vc).divideScalar(3);if(n.dot(center)<0)n.negate();normArr.push(n.x,n.y,n.z,n.x,n.y,n.z,n.x,n.y,n.z);faceNormals.push(n);faceCenters.push(center);faceNumbers.push(num);});equatTris.forEach(function(tri){var a=tri[0],b=tri[1],c=tri[2];var va=rawVerts[a],vb=rawVerts[b],vc=rawVerts[c];positions.push(va.x,va.y,va.z,vb.x,vb.y,vb.z,vc.x,vc.y,vc.z);var e1=new THREE.Vector3().subVectors(vb,va);var e2=new THREE.Vector3().subVectors(vc,va);var n=new THREE.Vector3().crossVectors(e1,e2).normalize();var center=new THREE.Vector3().addVectors(va,vb).add(vc).divideScalar(3);if(n.dot(center)<0)n.negate();normArr.push(n.x,n.y,n.z,n.x,n.y,n.z,n.x,n.y,n.z);});var geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geo.setAttribute('normal',new THREE.Float32BufferAttribute(normArr,3));applyGradient(geo);var mesh=new THREE.Mesh(geo,makeBodyMat());addEdgeWire(mesh,geo,20);mesh.userData={type:'d10',numbers:faceNumbers,normals:faceNormals};addLabels(mesh,faceNumbers,faceCenters,faceNormals,0.52);mesh.castShadow=true;return mesh;}
function buildD12(){var base=new THREE.DodecahedronGeometry(1.0);var geo=base.toNonIndexed();applyGradient(geo);var mesh=new THREE.Mesh(geo,makeBodyMat());addEdgeWire(mesh,base);var faces=facesFromClusters(geo);var numbers=[];for(var i=1;i<=faces.centers.length;i++)numbers.push(i);mesh.userData={type:'d12',numbers:numbers,normals:faces.normals};addLabels(mesh,numbers,faces.centers,faces.normals,0.62);mesh.castShadow=true;return mesh;}
function buildD20(){var R=1.0;var baseGeo=new THREE.IcosahedronGeometry(R,0);var geo=baseGeo.toNonIndexed();applyGradient(geo);var faces=facesFromTris(geo,20);var mesh=new THREE.Mesh(geo,makeBodyMat());var edgeGeo=new THREE.EdgesGeometry(new THREE.IcosahedronGeometry(R*1.003,0));mesh.add(new THREE.LineSegments(edgeGeo,new THREE.LineBasicMaterial({color:EDGE_COLOR,transparent:true,opacity:0.5})));var numbers=[];for(var i=1;i<=20;i++)numbers.push(i);mesh.userData={type:'d20',numbers:numbers,normals:faces.normals};addLabels(mesh,numbers,faces.centers,faces.normals,0.56);mesh.castShadow=true;return mesh;}
function buildResultDie(total,dieType){if(dieType==='d10'){var baseMesh=buildD10();var labelsToRemove=[];baseMesh.traverse(function(child){if(child!==baseMesh&&child.isMesh&&child.material&&child.material.map&&child.material.transparent)labelsToRemove.push(child);});for(var ri=0;ri<labelsToRemove.length;ri++){if(labelsToRemove[ri].material.map)labelsToRemove[ri].material.map.dispose();labelsToRemove[ri].material.dispose();labelsToRemove[ri].geometry.dispose();baseMesh.remove(labelsToRemove[ri]);}
var origNormals=baseMesh.userData.normals;var fCount=origNormals.length;var nums=[];for(var fi=0;fi<fCount;fi++)nums.push(total);var origCenters=[];var pos=baseMesh.geometry.attributes.position;var triCount=pos.count/3;var tC=[],tN=[];for(var t=0;t<triCount;t++){var ti=t*3;var va=new THREE.Vector3().fromBufferAttribute(pos,ti);var vb=new THREE.Vector3().fromBufferAttribute(pos,ti+1);var vc=new THREE.Vector3().fromBufferAttribute(pos,ti+2);tC.push(va.clone().add(vb).add(vc).divideScalar(3));var n=new THREE.Vector3().crossVectors(vb.clone().sub(va),vc.clone().sub(va)).normalize();if(n.dot(tC[t])<0)n.negate();tN.push(n);}
for(var fi=0;fi<fCount;fi++){var bestDist=Infinity;var bestCenter=tC[0];for(var ti=0;ti<tC.length;ti++){var ang=1-origNormals[fi].dot(tN[ti]);if(ang<bestDist){bestDist=ang;bestCenter=tC[ti];}}
origCenters.push(bestCenter);}
addLabels(baseMesh,nums,origCenters,origNormals,0.52);baseMesh.userData={type:'result',shape:'d10',numbers:nums,normals:origNormals,labelUps:baseMesh.userData.labelUps};return baseMesh;}
var RESULT_CONFIGS={d4:{build:function(){return new THREE.TetrahedronGeometry(1.1);},faceCount:4,labelSize:0.85,faceFn:'tris'},d6:{build:function(){return new THREE.BoxGeometry(1.2,1.2,1.2);},faceCount:6,labelSize:0.92,faceFn:'box'},d8:{build:function(){return new THREE.OctahedronGeometry(1.05);},faceCount:8,labelSize:0.55,faceFn:'tris'},d12:{build:function(){return new THREE.DodecahedronGeometry(1.0);},faceCount:12,labelSize:0.62,faceFn:'clusters'},d20:{build:function(){return new THREE.IcosahedronGeometry(1.0,0);},faceCount:20,labelSize:0.56,faceFn:'tris'},};var cfg=dieType?RESULT_CONFIGS[dieType]:null;if(!cfg)cfg=RESULT_CONFIGS.d6;var base=cfg.build();var geo=base.toNonIndexed();applyGradient(geo);var mesh=new THREE.Mesh(geo,makeBodyMat());addEdgeWire(mesh,base);var faces;if(cfg.faceFn==='box'){var pos=geo.attributes.position;var centers=[],normals=[];for(var f=0;f<6;f++){var bi=f*6;var center=new THREE.Vector3();for(var v=0;v<6;v++)center.add(new THREE.Vector3().fromBufferAttribute(pos,bi+v));center.divideScalar(6);var a=new THREE.Vector3().fromBufferAttribute(pos,bi);var b=new THREE.Vector3().fromBufferAttribute(pos,bi+1);var c=new THREE.Vector3().fromBufferAttribute(pos,bi+2);var n=new THREE.Vector3().crossVectors(b.clone().sub(a),c.clone().sub(a)).normalize();if(n.dot(center)<0)n.negate();centers.push(center);normals.push(n);}faces={centers:centers,normals:normals};}else if(cfg.faceFn==='clusters'){faces=facesFromClusters(geo);}else{faces=facesFromTris(geo,cfg.faceCount);}
var fCount=faces.centers.length;var nums=[];for(var i=0;i<fCount;i++)nums.push(total);mesh.userData={type:'result',shape:dieType||'d6',numbers:nums,normals:faces.normals};addLabels(mesh,nums,faces.centers,faces.normals,cfg.labelSize);mesh.castShadow=true;return mesh;}
var BUILDERS={d4:buildD4,d6:buildD6,d8:buildD8,d10:buildD10,d12:buildD12,d20:buildD20};function getTargetQuaternion(mesh,resultValue){var numbers=mesh.userData.numbers;var normals=mesh.userData.normals;var dieType=mesh.userData.type;var faceIdx=numbers.indexOf(resultValue);if(faceIdx===-1)faceIdx=0;var alignQ=new THREE.Quaternion().setFromUnitVectors(normals[faceIdx].clone(),new THREE.Vector3(0,0,1));var twistAngle;var resultShape=mesh.userData.shape;if(dieType==='d6'||(dieType==='result'&&(!resultShape||resultShape==='d6'))){var screenUp=new THREE.Vector3(0,1,0);var labelUps=mesh.userData.labelUps;var labelUp=labelUps?labelUps[faceIdx].clone():new THREE.Vector3(0,1,0);var bestAngle=0;var bestDot=-2;for(var ci=0;ci<4;ci++){var angle=ci*(Math.PI/2);var testQ=new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,0,1),angle).multiply(alignQ.clone());var upDir=labelUp.clone().applyQuaternion(testQ);var dot=upDir.dot(screenUp);if(dot>bestDot){bestDot=dot;bestAngle=angle;}}
twistAngle=bestAngle;}else{twistAngle=Math.random()*Math.PI*2;}
var twistQ=new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,0,1),twistAngle);return twistQ.multiply(alignQ);}
class Dice3DInstance{constructor(container,opts){opts=opts||{};this._container=container;this._size=opts.size||200;this._dieType=opts.dieType||'d20';this._rollMs=opts.duration||ROLL_MS_DEFAULT;this._disposed=false;this._animFrame=null;this._rolling=false;this._rollStart=0;this._rollDuration=this._rollMs;this._startEuler={x:0,y:0,z:0};this._endEuler={x:0,y:0,z:0};this._finalQuat=new THREE.Quaternion();this._rollCallback=null;this._showingResult=false;this._resultTime=0;this._idleTime=0;this._dieMesh=null;this._particlesEl=opts.particlesContainer||null;this._timers=[];this._multiMode=false;this._multiMeshes=[];this._multiStates=[];this._multiLanded=0;this._multiCallback=null;this._fusionActive=false;this._fusionStart=0;this._fusionDuration=500;this._fusionCallback=null;this._fusionMesh=null;var W=this._size,H=this._size;this._scene=new THREE.Scene();this._camera=new THREE.PerspectiveCamera(40,W/H,0.1,100);this._camera.position.set(0,0,4.5);this._renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});this._renderer.setSize(W,H);this._renderer.setPixelRatio(_isLite?1:Math.min(window.devicePixelRatio,2));this._renderer.shadowMap.enabled=!_isLite;if(!_isLite)this._renderer.shadowMap.type=THREE.PCFSoftShadowMap;container.appendChild(this._renderer.domElement);this._ambient=new THREE.AmbientLight(0xffffff,0.5);this._scene.add(this._ambient);this._keyLight=new THREE.DirectionalLight(0xfff5e0,1.2);this._keyLight.position.set(3,5,5);this._keyLight.castShadow=true;this._keyLight.shadow.mapSize.set(512,512);this._scene.add(this._keyLight);var fillLight=new THREE.DirectionalLight(0xd4af37,0.4);fillLight.position.set(-4,-1,3);this._scene.add(fillLight);var rimLight=new THREE.DirectionalLight(0x8b6914,0.3);rimLight.position.set(0,-4,-3);this._scene.add(rimLight);this._orbitLight=new THREE.PointLight(0xd4af37,0,6);this._scene.add(this._orbitLight);this._resultGlow=new THREE.PointLight(0xd4af37,0,5);this._resultGlow.position.set(0,0,2);this._scene.add(this._resultGlow);this._createMesh();this._animate=this._animate.bind(this);this._animate(performance.now());}
_trackTimeout(fn,ms){var self=this;var id=setTimeout(function(){self._timers=self._timers.filter(function(t){return t.id!==id;});if(!self._disposed)fn();},ms);this._timers.push({id:id,type:'timeout'});return id;}
_trackInterval(fn,ms){var id=setInterval(fn,ms);this._timers.push({id:id,type:'interval'});return id;}
_clearTimers(){for(var i=0;i<this._timers.length;i++){var t=this._timers[i];if(t.type==='interval')clearInterval(t.id);else clearTimeout(t.id);}
this._timers=[];}
_createMesh(){if(this._dieMesh){this._scene.remove(this._dieMesh);this._dieMesh=null;}
var builder=BUILDERS[this._dieType]||BUILDERS.d20;this._dieMesh=builder();this._dieMesh.position.set(0,0,0);this._scene.add(this._dieMesh);}
_animate(time){if(this._disposed)return;this._animFrame=requestAnimationFrame(this._animate);if(this._fusionActive){this._updateFusion(time);}else if(this._multiMode&&this._rolling){this._updateMultiRoll(time);}else if(this._rolling){this._updateRoll(time);}else if(this._showingResult){this._resultTime+=0.02;var pulse=0.3+0.2*Math.sin(this._resultTime*2.5);this._resultGlow.intensity=pulse;var target=this._fusionMesh||this._dieMesh;if(target){var s=1.0+0.008*Math.sin(this._resultTime*2.0);target.scale.setScalar(s);}
if(this._multiMode&&this._multiMeshes.length>0){for(var i=0;i<this._multiMeshes.length;i++){var ms=1.0+0.006*Math.sin(this._resultTime*2.0+i*0.5);this._multiMeshes[i].scale.setScalar(this._multiStates[i].baseScale*ms);}}}else if(this._dieMesh){this._idleTime+=0.012;this._dieMesh.rotation.y+=0.003;this._dieMesh.rotation.x+=0.001;this._orbitLight.intensity=0;this._resultGlow.intensity=0;}
this._renderer.render(this._scene,this._camera);}
_updateRoll(time){var elapsed=time-this._rollStart;var t=Math.min(elapsed/this._rollDuration,1);var eased=1-Math.pow(1-t,4);var mesh=this._dieMesh;mesh.rotation.x=this._startEuler.x+(this._endEuler.x-this._startEuler.x)*eased;mesh.rotation.y=this._startEuler.y+(this._endEuler.y-this._startEuler.y)*eased;mesh.rotation.z=this._startEuler.z+(this._endEuler.z-this._startEuler.z)*eased;var speed=1-eased;var orbitAngle=elapsed*0.008;this._orbitLight.position.set(Math.cos(orbitAngle)*2.5,Math.sin(orbitAngle)*2.5,1.5);this._orbitLight.intensity=speed*1.8;var scalePulse=1.0+speed*0.04*Math.sin(elapsed*0.015);mesh.scale.setScalar(scalePulse);if(mesh.material){mesh.material.shininess=100+speed*150;}
if(elapsed>=this._rollDuration){mesh.quaternion.copy(this._finalQuat);mesh.scale.setScalar(1.0);if(mesh.material)mesh.material.shininess=100;this._orbitLight.intensity=0;this._keyLight.intensity=3.0;var self=this;var flashI=3.0;var flashFade=self._trackInterval(function(){flashI-=0.15;if(flashI<=1.2){self._keyLight.intensity=1.2;clearInterval(flashFade);}else{self._keyLight.intensity=flashI;}},20);mesh.scale.setScalar(1.12);self._trackTimeout(function(){if(self._dieMesh)self._dieMesh.scale.setScalar(1.0);},120);var el=self._container;if(el){el.style.transition='transform 0.06s ease-out';el.style.transform='translate('+(Math.random()-0.5)*4+'px,'+(Math.random()-0.5)*4+'px)';self._trackTimeout(function(){el.style.transform='translate('+(Math.random()-0.5)*2+'px,'+(Math.random()-0.5)*2+'px)';},60);self._trackTimeout(function(){el.style.transition='transform 0.1s ease-out';el.style.transform='';},140);}
this._rolling=false;this._showingResult=true;this._resultTime=0;this._resultGlow.intensity=0.6;if(this._rollCallback)this._rollCallback();}}
_spawnRing(color){if(_isLite)return;var c=this._particlesEl;if(!c)return;var cx=c.offsetWidth/2,cy=c.offsetHeight/2;var r=document.createElement('div');r.style.cssText='position:absolute;border-radius:50%;border:2px solid '+color+';pointer-events:none;opacity:0;left:'+cx+'px;top:'+cy+'px';r.animate([{width:'0',height:'0',marginLeft:'0',marginTop:'0',opacity:0.8,borderWidth:'3px'},{width:'180px',height:'180px',marginLeft:'-90px',marginTop:'-90px',opacity:0,borderWidth:'1px'}],{duration:550,easing:'ease-out'});c.appendChild(r);setTimeout(function(){r.remove();},550);}
_spawnParticles(color,n){var c=this._particlesEl;if(!c)return;if(_isLite)n=Math.max(3,Math.floor(n/3));else if(_isMedium)n=Math.max(5,Math.floor(n*0.7));var cx=c.offsetWidth/2,cy=c.offsetHeight/2;for(var i=0;i<n;i++){var p=document.createElement('div');var s=2+Math.random()*5;p.style.cssText='position:absolute;border-radius:50%;background:'+color+';opacity:0;width:'+s+'px;height:'+s+'px;left:'+cx+'px;top:'+cy+'px';var a=(Math.PI*2*i)/n+(Math.random()-0.5)*0.6;var dist=40+Math.random()*100;var dx=Math.cos(a)*dist,dy=Math.sin(a)*dist;var dur=450+Math.random()*550;p.animate([{opacity:0.9,transform:'translate(0,0) scale(1)'},{opacity:0,transform:'translate('+dx+'px,'+dy+'px) scale(0)'}],{duration:dur,easing:'cubic-bezier(0,0.3,0.5,1)'});c.appendChild(p);(function(el,d){setTimeout(function(){el.remove();},d);})(p,dur);}}
roll(resultValue,onDone){var self=this;this._showingResult=false;this._rolling=false;this._createMesh();haptic('medium');var mesh=this._dieMesh;var dieType=this._dieType;this._finalQuat=getTargetQuaternion(mesh,resultValue);this._startEuler={x:mesh.rotation.x,y:mesh.rotation.y,z:mesh.rotation.z,};var targetEuler=new THREE.Euler().setFromQuaternion(this._finalQuat);var spins=3+Math.floor(Math.random()*3);var dir=function(){return Math.random()>0.5?1:-1;};this._endEuler={x:targetEuler.x+Math.PI*2*spins*dir(),y:targetEuler.y+Math.PI*2*spins*dir(),z:targetEuler.z+Math.PI*2*spins*dir(),};var maxVal={d4:4,d6:6,d8:8,d10:9,d12:12,d20:20}[dieType]||20;var minVal=dieType==='d10'?0:1;var isCrit=resultValue===maxVal;var isFail=resultValue===minVal;this._rollDuration=this._rollMs;this._rollStart=performance.now();this._rolling=true;this._rollCallback=function(){if(isCrit||isFail){haptic('heavy');self._spawnRing(isCrit?V_SUCCESS_HEX:V_DANGER_HEX);self._spawnParticles(isCrit?V_SUCCESS_HEX:V_DANGER_HEX,30);if(self._dieMesh){var glowColor=parseInt((isCrit?V_SUCCESS_HEX:V_DANGER_HEX).replace('#',''),16);var glow=new THREE.PointLight(glowColor,1.5,4);glow.position.set(0,0.5,1);self._dieMesh.add(glow);var intensity=1.5;var fadeGlow=self._trackInterval(function(){intensity-=0.05;if(intensity<=0){if(self._dieMesh)self._dieMesh.remove(glow);clearInterval(fadeGlow);}
else glow.intensity=intensity;},50);}}else{haptic('heavy');self._spawnParticles(V_GOLD_HEX,15);}
if(onDone)onDone();};return this._rollDuration;}
rollMultiple(configs,onDone){if(!configs||configs.length<=1){return this.roll(configs&&configs[0]?configs[0].value:1,onDone);}
var self=this;var count=Math.min(configs.length,5);this._showingResult=false;this._rolling=true;this._multiMode=true;this._multiLanded=0;this._multiCallback=onDone;this._fusionActive=false;this._fusionMesh=null;haptic('medium');if(this._dieMesh){this._scene.remove(this._dieMesh);this._dieMesh=null;}
for(var k=0;k<this._multiMeshes.length;k++)this._scene.remove(this._multiMeshes[k]);this._multiMeshes=[];this._multiStates=[];var layouts={2:[[-0.8,0],[0.8,0]],3:[[-0.9,-0.45],[0.9,-0.45],[0,0.6]],4:[[-0.8,-0.55],[0.8,-0.55],[-0.8,0.55],[0.8,0.55]],5:[[-1.0,-0.55],[0,-0.55],[1.0,-0.55],[-0.55,0.55],[0.55,0.55]],};var positions=layouts[count]||layouts[5];this._camera.position.z=count<=2?4.5:count===3?4.8:count===4?5.0:5.4;var baseScale=count<=2?0.85:count===3?0.78:count===4?0.72:0.65;var builder=BUILDERS[this._dieType]||BUILDERS.d20;var staggerMs=80;for(var i=0;i<count;i++){var mesh=builder();var pos=positions[i]||[0,0];var xPos=pos[0];mesh.position.set(pos[0],pos[1],0);mesh.scale.setScalar(baseScale);this._scene.add(mesh);this._multiMeshes.push(mesh);var val=configs[i].value;var finalQuat=getTargetQuaternion(mesh,val);var startE={x:mesh.rotation.x,y:mesh.rotation.y,z:mesh.rotation.z};var targetE=new THREE.Euler().setFromQuaternion(finalQuat);var spins=3+Math.floor(Math.random()*3);var dir=function(){return Math.random()>0.5?1:-1;};var endE={x:targetE.x+Math.PI*2*spins*dir(),y:targetE.y+Math.PI*2*spins*dir(),z:targetE.z+Math.PI*2*spins*dir(),};this._multiStates.push({startEuler:startE,endEuler:endE,finalQuat:finalQuat,startTime:performance.now()+i*staggerMs,landed:false,baseScale:baseScale,originX:pos[0],originY:pos[1],value:val,});}
this._rollStart=performance.now();return this._rollMs+(count-1)*staggerMs;}
_updateMultiRoll(time){var allLanded=true;var self=this;for(var i=0;i<this._multiMeshes.length;i++){var st=this._multiStates[i];if(st.landed)continue;var elapsed=time-st.startTime;if(elapsed<0){allLanded=false;continue;}
var t=Math.min(elapsed/this._rollMs,1);var eased=1-Math.pow(1-t,4);var mesh=this._multiMeshes[i];mesh.rotation.x=st.startEuler.x+(st.endEuler.x-st.startEuler.x)*eased;mesh.rotation.y=st.startEuler.y+(st.endEuler.y-st.startEuler.y)*eased;mesh.rotation.z=st.startEuler.z+(st.endEuler.z-st.startEuler.z)*eased;var speed=1-eased;var scalePulse=st.baseScale*(1.0+speed*0.04*Math.sin(elapsed*0.015));mesh.scale.setScalar(scalePulse);if(mesh.material)mesh.material.shininess=100+speed*150;if(elapsed>=this._rollMs){mesh.quaternion.copy(st.finalQuat);mesh.scale.setScalar(st.baseScale*1.1);if(mesh.material)mesh.material.shininess=100;st.landed=true;self._multiLanded++;haptic('light');(function(m,bs,inst){inst._trackTimeout(function(){m.scale.setScalar(bs);},100);})(mesh,st.baseScale,self);}else{allLanded=false;}}
if(this._multiMeshes.length>0&&!this._multiStates[0].landed){var e0=time-this._multiStates[0].startTime;var sp0=1-Math.min(e0/this._rollMs,1);var angle=e0*0.008;this._orbitLight.position.set(Math.cos(angle)*2.5,Math.sin(angle)*2.5,1.5);this._orbitLight.intensity=sp0*1.5;}else{this._orbitLight.intensity=0;}
if(allLanded&&this._multiLanded>=this._multiMeshes.length){this._rolling=false;this._showingResult=true;this._resultTime=0;this._keyLight.intensity=2.5;var flashI=2.5;var flashFade=self._trackInterval(function(){flashI-=0.12;if(flashI<=1.2){self._keyLight.intensity=1.2;clearInterval(flashFade);}
else self._keyLight.intensity=flashI;},20);var el=this._container;if(el){el.style.transition='transform 0.06s ease-out';el.style.transform='translate('+(Math.random()-0.5)*3+'px,'+(Math.random()-0.5)*3+'px)';self._trackTimeout(function(){el.style.transform='';el.style.transition='';},120);}
this._spawnParticles(V_GOLD_HEX,12);this._resultGlow.intensity=0.5;if(this._multiCallback)this._multiCallback();}}
fusionTo(totalValue,onDone){if(!this._multiMode||this._multiMeshes.length<2){if(onDone)onDone();return;}
this._showingResult=false;this._fusionActive=true;this._fusionStart=performance.now();this._fusionDuration=500;this._fusionCallback=onDone;this._fusionTotal=totalValue;this._resultGlow.intensity=0;haptic('medium');}
_updateFusion(time){var elapsed=time-this._fusionStart;var t=Math.min(elapsed/this._fusionDuration,1);var eased=t<0.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;var self=this;for(var i=0;i<this._multiMeshes.length;i++){var mesh=this._multiMeshes[i];var st=this._multiStates[i];var targetScale=st.baseScale*(1-eased*0.7);mesh.scale.setScalar(targetScale);mesh.position.x=st.originX*(1-eased);mesh.position.y=(st.originY||0)*(1-eased);mesh.rotation.y+=0.02*(1+eased*3);}
var angle=elapsed*0.015;this._orbitLight.position.set(Math.cos(angle)*1.5,Math.sin(angle)*1.5,1.5);this._orbitLight.intensity=eased*2.0;if(elapsed>=this._fusionDuration){for(var j=0;j<this._multiMeshes.length;j++){this._scene.remove(this._multiMeshes[j]);}
this._multiMeshes=[];this._multiStates=[];this._multiMode=false;this._fusionMesh=buildResultDie(this._fusionTotal,this._dieType);this._fusionMesh.position.set(0,0,0);this._fusionMesh.scale.setScalar(0.01);var normals=this._fusionMesh.userData.normals;var faceIdx=0;for(var fi=0;fi<normals.length;fi++){if(normals[fi].z>normals[faceIdx].z)faceIdx=fi;}
var alignQ=new THREE.Quaternion().setFromUnitVectors(normals[faceIdx].clone(),new THREE.Vector3(0,0,1));this._fusionMesh.quaternion.copy(alignQ);this._scene.add(this._fusionMesh);this._camera.position.z=4.5;this._keyLight.intensity=4.0;var flashI=4.0;var flashFade=self._trackInterval(function(){flashI-=0.2;if(flashI<=1.2){self._keyLight.intensity=1.2;clearInterval(flashFade);}
else self._keyLight.intensity=flashI;},20);this._orbitLight.intensity=0;haptic('heavy');this._spawnRing(V_GOLD_HEX);this._spawnParticles(V_GOLD_HEX,25);var fm=this._fusionMesh;fm.scale.setScalar(1.2);self._trackTimeout(function(){if(fm)fm.scale.setScalar(1.0);},150);var el=this._container;if(el){el.style.transition='transform 0.06s ease-out';el.style.transform='translate('+(Math.random()-0.5)*5+'px,'+(Math.random()-0.5)*5+'px)';self._trackTimeout(function(){el.style.transform='translate('+(Math.random()-0.5)*2+'px,'+(Math.random()-0.5)*2+'px)';},60);self._trackTimeout(function(){el.style.transition='';el.style.transform='';},140);}
this._fusionActive=false;this._showingResult=true;this._resultTime=0;this._resultGlow.intensity=0.7;if(this._fusionCallback)this._fusionCallback();}}
dispose(){this._disposed=true;this._clearTimers();if(this._animFrame)cancelAnimationFrame(this._animFrame);var self=this;function disposeMesh(mesh){if(!mesh)return;self._scene.remove(mesh);mesh.traverse(function(child){if(child.geometry)child.geometry.dispose();if(child.material){if(child.material.map)child.material.map.dispose();child.material.dispose();}});}
disposeMesh(this._dieMesh);disposeMesh(this._fusionMesh);for(var i=0;i<this._multiMeshes.length;i++)disposeMesh(this._multiMeshes[i]);this._multiMeshes=[];this._dieMesh=null;this._fusionMesh=null;this._renderer.dispose();if(this._renderer.domElement.parentNode){this._renderer.domElement.parentNode.removeChild(this._renderer.domElement);}}}
return Dice3DInstance;})();