(function(){'use strict';window.addEventListener('error',function(e){if(e.target&&e.target.tagName==='SCRIPT'&&e.target.src){var src=e.target.src.split('/').pop().split('?')[0];if(window._loadDbg)_loadDbg('SCRIPT FAIL: '+src);else console.error('[LOAD-DBG] SCRIPT FAIL: '+src);}if(e.target&&e.target.tagName==='LINK'&&e.target.rel==='stylesheet'){var href=e.target.href.split('/').pop().split('?')[0];if(window._loadDbg)_loadDbg('CSS FAIL: '+href);else console.error('[LOAD-DBG] CSS FAIL: '+href);}},true);})();
(function(){'use strict';var CANONICAL={'.mc-outer':{prop:'animationDuration',min:25,canonical:60},'.mc-mid':{prop:'animationDuration',min:15,canonical:35},'.mc-inner':{prop:'animationDuration',min:20,canonical:45},};var VAR_MINIMUMS={'--ring-outer':25,'--ring-mid':15,'--ring-inner':20,};function parseDuration(val){if(!val)return 0;val=String(val).trim();if(val.endsWith('ms'))return parseFloat(val)/1000;if(val.endsWith('s'))return parseFloat(val);return parseFloat(val);}
function validateElement(selector,rule){var el=document.querySelector(selector);if(!el)return;var computed=getComputedStyle(el);var duration=parseDuration(computed.animationDuration);if(duration>0&&duration<rule.min){console.warn('[LOADING-GUARD] '+selector+' animation too fast: '+
duration.toFixed(1)+'s (min: '+rule.min+'s). Forcing to '+
rule.canonical+'s.');el.style.animationDuration=rule.canonical+'s';return true;}
return false;}
function validateCSSVariables(){var circle=document.querySelector('.magic-circle');if(!circle)return;var style=circle.style;var corrected=false;for(var varName in VAR_MINIMUMS){var val=style.getPropertyValue(varName);if(val){var seconds=parseDuration(val);if(seconds>0&&seconds<VAR_MINIMUMS[varName]){console.warn('[LOADING-GUARD] CSS var '+varName+' too fast: '+
seconds.toFixed(1)+'s (min: '+VAR_MINIMUMS[varName]+'s). Removing override.');style.removeProperty(varName);corrected=true;}}}
return corrected;}
function validateAll(){return false;/* Animation speed validation disabled — loading controller manages speeds intentionally */var overlay=document.getElementById("loading")||document.querySelector(".loading-overlay");if(!overlay||overlay.style.display==="none"||overlay.classList.contains("hidden")){if(_guardInterval){clearInterval(_guardInterval);_guardInterval=null;}return false;}var corrected=false;for(var selector in CANONICAL){if(validateElement(selector,CANONICAL[selector]))corrected=true;}
if(validateCSSVariables())corrected=true;return corrected;}
function observeCircle(){var circle=document.querySelector('.magic-circle');if(!circle)return;var observer=window._valdoriaPerfObserver=new MutationObserver(function(mutations){var needsCheck=false;for(var i=0;i<mutations.length;i++){var m=mutations[i];if(m.type==='attributes'&&(m.attributeName==='style'||m.attributeName==='class')){needsCheck=true;break;}}
if(needsCheck){validateAll();}});observer.observe(circle,{attributes:true,attributeFilter:['style','class'],subtree:false,});}
function init(){validateAll();observeCircle();}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',init);}else{init();}
var _guardInterval=null;var _origShowLoading=window.showLoading;Object.defineProperty(window,'_loadingGuardActive',{get:function(){return!!_guardInterval;},});function patchShowHide(){if(typeof window.showLoading==='function'&&!window.showLoading._guarded){var orig=window.showLoading;window.showLoading=function(){orig.apply(this,arguments);validateAll();if(_guardInterval)clearInterval(_guardInterval);_guardInterval=setInterval(validateAll,2000);};window.showLoading._guarded=true;}
if(typeof window.hideLoading==='function'&&!window.hideLoading._guarded){var origHide=window.hideLoading;window.hideLoading=function(){origHide.apply(this,arguments);if(_guardInterval){clearInterval(_guardInterval);_guardInterval=null;}if(window._perfModeObserver){window._perfModeObserver.disconnect();window._perfModeObserver=null;}};window.hideLoading._guarded=true;}}
patchShowHide();setTimeout(patchShowHide,100);setTimeout(patchShowHide,500);})();(function(){'use strict';var LITE_KEY='valdoria_loading_lite';function detectPerformanceTier(){var cores=navigator.hardwareConcurrency||8;var mem=navigator.deviceMemory||8;if(cores<=2||mem<=2)return'lite';if(cores<=4&&mem<=4)return'lite';if(cores<=8&&mem<=8)return'medium';return'full';}
function isLowEndDevice(){return detectPerformanceTier()==='lite';}
function applyPerformanceMode(tier){var overlays=document.querySelectorAll('.loading-overlay');for(var i=0;i<overlays.length;i++){if(tier==='lite'){overlays[i].classList.add('loading-lite');}else if(tier==='medium'){overlays[i].classList.add('loading-medium');}}
if(tier!=='full'){}}
function getEffectiveTier(){try{var pref=localStorage.getItem(LITE_KEY);if(pref==='1')return'lite';if(pref==='0')return'full';}catch(e){console.warn('[LOADING_GUARD]',e);}
return detectPerformanceTier();}
function initPerformanceMode(){var tier=getEffectiveTier();if(tier!=='full'){applyPerformanceMode(tier);var observer=new MutationObserver(function(mutations){for(var i=0;i<mutations.length;i++){var nodes=mutations[i].addedNodes;for(var j=0;j<nodes.length;j++){var node=nodes[j];if(node.nodeType===1&&node.classList&&node.classList.contains('loading-overlay')){if(tier==='lite')node.classList.add('loading-lite');else if(tier==='medium')node.classList.add('loading-medium');}}}});var _lo=document.getElementById("loading")||document.body;observer.observe(_lo,{childList:true,subtree:false});window._perfModeObserver=observer;}}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',initPerformanceMode);}else{initPerformanceMode();}
window.ValdoriaLoadingLite={isLowEnd:isLowEndDevice,isMedium:function(){return detectPerformanceTier()==='medium';},getTier:getEffectiveTier,enable:function(){try{localStorage.setItem(LITE_KEY,'1');}catch(e){console.warn('[LOADING_GUARD]',e);}applyPerformanceMode('lite');},disable:function(){try{localStorage.setItem(LITE_KEY,'0');}catch(e){console.warn('[LOADING_GUARD]',e);}},auto:function(){try{localStorage.removeItem(LITE_KEY);}catch(e){console.warn('[LOADING_GUARD]',e);}},};})();/* Loading overlay reveal */
/* Reveal handled by loading.css animation + visibility cascade */
window.VALDORIA_MIN_LOAD_MS=2500;window.VALDORIA_SPA_RETURN_MS=1500;window.VALDORIA_MIN_ERROR_DELAY=2500;(function(){'use strict';var _lsBase='';try{var _qp=new URLSearchParams(window.location.search);var _qApi=_qp.get('api');if(_qApi)_lsBase=_qApi;}catch(e){/* intentionally silent */}if(!_lsBase){try{var h=window.location.hash;if(h&&h.length>2){var decoded=atob(h.substring(1).split('.')[0]||'');var m=decoded.match(/"api(?:Base)?"\s*:\s*"([^"]+)"/);if(m&&m[1])_lsBase=m[1];}}catch(e){/* legacy hash decode — intentionally silent */}}
if(!_lsBase){try{_lsBase=localStorage.getItem(ValdoriaEnv.getEnvKey('valdoria_api_base'))||'';}catch(e){console.warn('[LOADING_GUARD]',e);}}
if(_lsBase){try{var u=new URL(_lsBase);var link=document.createElement('link');link.rel='preconnect';link.href=u.origin;link.crossOrigin='anonymous';document.head.appendChild(link);var dnsPre=document.createElement('link');dnsPre.rel='dns-prefetch';dnsPre.href=u.origin;document.head.appendChild(dnsPre);if(window._loadDbg)_loadDbg('preconnect: '+u.origin);}catch(e){console.warn('[LOADING_GUARD]',e);}}})();(function(){'use strict';function _setupGemTap(){var gemEl=document.getElementById('mc-gem');if(!gemEl)return;if(gemEl.__valdoriaGemTap){if(typeof _gemObserver!=='undefined'&&_gemObserver){try{_gemObserver.disconnect();}catch(e){console.warn('[LOADING_GUARD]',e);}}return;}gemEl.__valdoriaGemTap=true;var _gemTapCount=0;if(typeof _gemObserver!=='undefined'&&_gemObserver){try{_gemObserver.disconnect();}catch(e){console.warn('[LOADING_GUARD]',e);}}var cooldown=false;gemEl.addEventListener('click',function(){if(cooldown)return;cooldown=true;if(typeof ValdoriaAudio!=='undefined'&&ValdoriaAudio._warmUp)ValdoriaAudio._warmUp();gemEl.classList.add('tapped');_gemTapCount++;if(_gemTapCount===5){gemEl.style.filter='hue-rotate(180deg) brightness(1.3)';setTimeout(function(){gemEl.style.filter='';},600);}else if(_gemTapCount===10){for(var _pi=0;_pi<8;_pi++){var _sp=document.createElement('div');_sp.style.cssText='position:absolute;width:4px;height:4px;background:#c4953a;border-radius:50%;pointer-events:none';var _a=Math.PI*2*_pi/8;var _dx=Math.cos(_a)*30;var _dy=Math.sin(_a)*30;_sp.animate([{transform:'translate(0,0) scale(1)',opacity:1},{transform:'translate('+_dx+'px,'+_dy+'px) scale(0)',opacity:0}],{duration:500,easing:'ease-out'});gemEl.appendChild(_sp);setTimeout((function(_s){return function(){if(_s.parentNode)_s.remove();}})(_sp),500);}}else if(_gemTapCount>=20&&typeof showToast==='function'){showToast('O cristal responde à sua persistência...',3000);_gemTapCount=0;}var burst=document.createElement('div');burst.className='mc-gem-burst';gemEl.appendChild(burst);try{if(window.Telegram&&Telegram.WebApp&&Telegram.WebApp.HapticFeedback){Telegram.WebApp.HapticFeedback.impactOccurred('light');}}catch(_){console.warn('[LOADING_GUARD]',_);}
setTimeout(function(){gemEl.classList.remove('tapped');if(burst.parentNode)burst.parentNode.removeChild(burst);cooldown=false;},600);});}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',_setupGemTap);}else{_setupGemTap();}
var _gemObserver=new MutationObserver(function(){_setupGemTap();});if(document.body){var _gemTarget=document.getElementById("loading")||document.body;_gemObserver.observe(_gemTarget,{childList:true,subtree:false});}else{document.addEventListener('DOMContentLoaded',function(){var _gemTarget2=document.getElementById("loading")||document.body;_gemObserver.observe(_gemTarget2,{childList:true,subtree:false});});}window.addEventListener('pagehide',function(){if(_gemObserver){try{_gemObserver.disconnect();}catch(e){console.warn('[LOADING_GUARD]',e);}}});})();(function(){'use strict';var tier='full';try{var pref=localStorage.getItem('valdoria_loading_lite');if(pref==='1')tier='lite';else if(pref!=='0'){var cores=navigator.hardwareConcurrency||8;var mem=navigator.deviceMemory||8;if(cores<=2||mem<=2||(cores<=4&&mem<=4))tier='lite';else if(cores<=8&&mem<=8)tier='medium';}}catch(e){console.warn('[LOADING_GUARD]',e);}
window._valdoriaMinLoadFactor=tier==='lite'?0.4:tier==='medium'?0.7:1.0;window._valdoriaPerformanceTier=tier;if(window._loadDbg)_loadDbg('perf tier='+tier+' cores='+(navigator.hardwareConcurrency||'?')+' mem='+(navigator.deviceMemory||'?')+' factor='+window._valdoriaMinLoadFactor);window.addEventListener('pagehide',function(){if(window._valdoriaPerfObserver){try{window._valdoriaPerfObserver.disconnect();}catch(e){console.warn('[LOADING_GUARD]',e);}}});if(tier!=='full'){var _applyPerfClass=function(){if(document.body)document.body.classList.add('perf-'+tier);else document.addEventListener('DOMContentLoaded',function(){document.body.classList.add('perf-'+tier);});};_applyPerfClass();}})();
setTimeout(function(){try{if(getComputedStyle(document.documentElement).opacity==='0'){document.documentElement.style.opacity='1';console.warn('[GAME] FOUC safety: forced opacity after 10s');if(window._loadDbg)_loadDbg('FOUC safety: opacity forced');}var _lo=document.querySelector('.loading-overlay');if(_lo&&window._loadingGuardBypass){if(window._loadDbg)_loadDbg('FOUC safety: skipped (_loadingGuardBypass=true)');}else if(_lo&&(getComputedStyle(_lo).display==='none'||getComputedStyle(_lo).visibility==='hidden')){_lo.style.display='';_lo.style.visibility='visible';_lo.style.opacity='1';console.warn('[GAME] FOUC safety: forced loading overlay visible after 10s');if(window._loadDbg)_loadDbg('FOUC safety: forced loading visible');}}catch(e){/* getComputedStyle may fail in some envs - intentionally silent */}},10000);(function(){var i,s=document.getElementsByTagName('script');for(i=s.length-1;i>=0;i--){var x=s[i].src;if(x&&x.indexOf('loading-guard.js')!==-1){var b=x.split('loading-guard.js')[0]+'orientation-gate.js?v='+Date.now();var n=document.createElement('script');n.src=b;n.async=true;document.head.appendChild(n);break;}}})();