(function(){'use strict';var CANONICAL={'.mc-outer':{prop:'animationDuration',min:25,canonical:60},'.mc-mid':{prop:'animationDuration',min:15,canonical:35},'.mc-inner':{prop:'animationDuration',min:20,canonical:45},};var VAR_MINIMUMS={'--ring-outer':25,'--ring-mid':15,'--ring-inner':20,};function parseDuration(val){if(!val)return 0;val=String(val).trim();if(val.endsWith('ms'))return parseFloat(val)/1000;if(val.endsWith('s'))return parseFloat(val);return parseFloat(val);}
function validateElement(selector,rule){var el=document.querySelector(selector);if(!el)return;var computed=getComputedStyle(el);var duration=parseDuration(computed.animationDuration);if(duration>0&&duration<rule.min){console.warn('[LOADING-GUARD] '+selector+' animation too fast: '+
duration.toFixed(1)+'s (min: '+rule.min+'s). Forcing to '+
rule.canonical+'s.');el.style.animationDuration=rule.canonical+'s';return true;}
return false;}
function validateCSSVariables(){var circle=document.querySelector('.magic-circle');if(!circle)return;var style=circle.style;var corrected=false;for(var varName in VAR_MINIMUMS){var val=style.getPropertyValue(varName);if(val){var seconds=parseDuration(val);if(seconds>0&&seconds<VAR_MINIMUMS[varName]){console.warn('[LOADING-GUARD] CSS var '+varName+' too fast: '+
seconds.toFixed(1)+'s (min: '+VAR_MINIMUMS[varName]+'s). Removing override.');style.removeProperty(varName);corrected=true;}}}
return corrected;}
function validateAll(){var corrected=false;for(var selector in CANONICAL){if(validateElement(selector,CANONICAL[selector]))corrected=true;}
if(validateCSSVariables())corrected=true;return corrected;}
function observeCircle(){var circle=document.querySelector('.magic-circle');if(!circle)return;var observer=window._valdoriaPerfObserver=new MutationObserver(function(mutations){var needsCheck=false;for(var i=0;i<mutations.length;i++){var m=mutations[i];if(m.type==='attributes'&&(m.attributeName==='style'||m.attributeName==='class')){needsCheck=true;break;}}
if(needsCheck){validateAll();}});observer.observe(circle,{attributes:true,attributeFilter:['style','class'],subtree:true,});}
function init(){validateAll();observeCircle();}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',init);}else{init();}
var _guardInterval=null;var _origShowLoading=window.showLoading;Object.defineProperty(window,'_loadingGuardActive',{get:function(){return!!_guardInterval;},});function patchShowHide(){if(typeof window.showLoading==='function'&&!window.showLoading._guarded){var orig=window.showLoading;window.showLoading=function(){orig.apply(this,arguments);validateAll();if(_guardInterval)clearInterval(_guardInterval);_guardInterval=setInterval(validateAll,2000);};window.showLoading._guarded=true;}
if(typeof window.hideLoading==='function'&&!window.hideLoading._guarded){var origHide=window.hideLoading;window.hideLoading=function(){origHide.apply(this,arguments);if(_guardInterval){clearInterval(_guardInterval);_guardInterval=null;}if(window._perfModeObserver){window._perfModeObserver.disconnect();window._perfModeObserver=null;}};window.hideLoading._guarded=true;}}
patchShowHide();setTimeout(patchShowHide,100);setTimeout(patchShowHide,500);})();(function(){'use strict';var LITE_KEY='valdoria_loading_lite';function detectPerformanceTier(){var cores=navigator.hardwareConcurrency||8;var mem=navigator.deviceMemory||8;if(cores<=2||mem<=2)return'lite';if(cores<=4&&mem<=4)return'lite';if(cores<=8&&mem<=8)return'medium';return'full';}
function isLowEndDevice(){return detectPerformanceTier()==='lite';}
function applyPerformanceMode(tier){var overlays=document.querySelectorAll('.loading-overlay');for(var i=0;i<overlays.length;i++){if(tier==='lite'){overlays[i].classList.add('loading-lite');}else if(tier==='medium'){overlays[i].classList.add('loading-medium');}}
if(tier!=='full'){console.debug('[LOADING] '+tier+' mode active');}}
function getEffectiveTier(){try{var pref=localStorage.getItem(LITE_KEY);if(pref==='1')return'lite';if(pref==='0')return'full';}catch(e){}
return detectPerformanceTier();}
function initPerformanceMode(){var tier=getEffectiveTier();if(tier!=='full'){applyPerformanceMode(tier);var observer=new MutationObserver(function(mutations){for(var i=0;i<mutations.length;i++){var nodes=mutations[i].addedNodes;for(var j=0;j<nodes.length;j++){var node=nodes[j];if(node.nodeType===1&&node.classList&&node.classList.contains('loading-overlay')){if(tier==='lite')node.classList.add('loading-lite');else if(tier==='medium')node.classList.add('loading-medium');}}}});observer.observe(document.body||document.documentElement,{childList:true,subtree:true});window._perfModeObserver=observer;}}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',initPerformanceMode);}else{initPerformanceMode();}
window.ValdoriaLoadingLite={isLowEnd:isLowEndDevice,isMedium:function(){return detectPerformanceTier()==='medium';},getTier:getEffectiveTier,enable:function(){try{localStorage.setItem(LITE_KEY,'1');}catch(e){}applyPerformanceMode('lite');},disable:function(){try{localStorage.setItem(LITE_KEY,'0');}catch(e){}},auto:function(){try{localStorage.removeItem(LITE_KEY);}catch(e){}},};})();/* FOUC fix: reveal loading overlay */
(function(){document.documentElement.classList.add('v-ready');var lo=document.querySelector('.loading-overlay');if(lo){lo.style.transition='opacity 0.15s ease';lo.style.opacity='1';}})();
window.VALDORIA_MIN_LOAD_MS=5000;window.VALDORIA_SPA_RETURN_MS=1500;window.VALDORIA_MIN_ERROR_DELAY=2500;(function(){'use strict';var _lsBase='';try{var h=window.location.hash;if(h&&h.length>2){var decoded=atob(h.substring(1).split('.')[0]||'');var m=decoded.match(/"api(?:Base)?"\s*:\s*"([^"]+)"/);if(m&&m[1])_lsBase=m[1];}}catch(e){}
if(!_lsBase){try{_lsBase=localStorage.getItem('valdoria_api_base')||'';}catch(e){}}
if(_lsBase){try{var u=new URL(_lsBase);var link=document.createElement('link');link.rel='preconnect';link.href=u.origin;link.crossOrigin='anonymous';document.head.appendChild(link);var dnsPre=document.createElement('link');dnsPre.rel='dns-prefetch';dnsPre.href=u.origin;document.head.appendChild(dnsPre);}catch(e){}}})();(function(){'use strict';function _setupGemTap(){var gemEl=document.getElementById('mc-gem');if(!gemEl)return;if(gemEl.__valdoriaGemTap){if(typeof _gemObserver!=='undefined'&&_gemObserver){try{_gemObserver.disconnect();}catch(e){}}return;}gemEl.__valdoriaGemTap=true;if(typeof _gemObserver!=='undefined'&&_gemObserver){try{_gemObserver.disconnect();}catch(e){}}var cooldown=false;gemEl.addEventListener('click',function(){if(cooldown)return;cooldown=true;if(typeof ValdoriaAudio!=='undefined'&&ValdoriaAudio._warmUp)ValdoriaAudio._warmUp();gemEl.classList.add('tapped');var burst=document.createElement('div');burst.className='mc-gem-burst';gemEl.appendChild(burst);try{if(window.Telegram&&Telegram.WebApp&&Telegram.WebApp.HapticFeedback){Telegram.WebApp.HapticFeedback.impactOccurred('light');}}catch(_){}
setTimeout(function(){gemEl.classList.remove('tapped');if(burst.parentNode)burst.parentNode.removeChild(burst);cooldown=false;},600);});}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',_setupGemTap);}else{_setupGemTap();}
var _gemObserver=new MutationObserver(function(){_setupGemTap();});if(document.body)_gemObserver.observe(document.body,{childList:true,subtree:true});else document.addEventListener('DOMContentLoaded',function(){_gemObserver.observe(document.body,{childList:true,subtree:true});});window.addEventListener('pagehide',function(){if(_gemObserver){try{_gemObserver.disconnect();}catch(e){}}});})();(function(){'use strict';var tier='full';try{var pref=localStorage.getItem('valdoria_loading_lite');if(pref==='1')tier='lite';else if(pref!=='0'){var cores=navigator.hardwareConcurrency||8;var mem=navigator.deviceMemory||8;if(cores<=2||mem<=2||(cores<=4&&mem<=4))tier='lite';else if(cores<=8&&mem<=8)tier='medium';}}catch(e){}
window._valdoriaMinLoadFactor=tier==='lite'?0.4:tier==='medium'?0.7:1.0;window._valdoriaPerformanceTier=tier;window.addEventListener('pagehide',function(){if(window._valdoriaPerfObserver){try{window._valdoriaPerfObserver.disconnect();}catch(e){}}});if(tier!=='full'){var _applyPerfClass=function(){if(document.body)document.body.classList.add('perf-'+tier);else document.addEventListener('DOMContentLoaded',function(){document.body.classList.add('perf-'+tier);});};_applyPerfClass();}})();