(function(){'use strict';var _overlay=null;var _busy=false;var _onHide=null;var _zBase=1000;var _stack=[];function _el(id){return document.getElementById(id);}
function show(opts){if(!opts)return;var overlayId=opts.id||'v-popup-overlay';_overlay=_el(overlayId);if(!_overlay){console.warn('[POPUP] overlay not found:',overlayId);return;}
_onHide=opts.onHide||null;var headerEl=_overlay.querySelector('.v-popup-header');if(headerEl){headerEl.innerHTML=opts.header||'';headerEl.className='v-popup-header'+(opts.headerClass?' '+opts.headerClass:'');}
var bodyEl=_overlay.querySelector('.v-popup-body');if(bodyEl)bodyEl.innerHTML=opts.body||'';var actionsEl=_overlay.querySelector('.v-popup-actions');if(actionsEl){actionsEl.innerHTML=opts.actions||'';var btns=actionsEl.querySelectorAll('[data-action]');for(var i=0;i<btns.length;i++){btns[i].addEventListener('click',_makeHandler(opts.onAction));}}
if(bodyEl){var bodyBtns=bodyEl.querySelectorAll('[data-action]');for(var j=0;j<bodyBtns.length;j++){bodyBtns[j].addEventListener('click',_makeHandler(opts.onAction));}}
_zBase+=10;_overlay.style.zIndex=_zBase;_stack.push(_overlay);_overlay.style.display='flex';_overlay.classList.remove('hiding');void _overlay.offsetWidth;_overlay.classList.add('active');_busy=false;if(opts.closeOnOutside!==false){_overlay.onclick=function(e){if(e.target===_overlay)hide();};}}
function hide(){if(!_overlay)return;_overlay.classList.add('hiding');_overlay.classList.remove('active');var ov=_overlay;var cb=_onHide;setTimeout(function(){if(ov)ov.style.display='none';var idx=_stack.indexOf(ov);if(idx>=0)_stack.splice(idx,1);_zBase=Math.max(1000,_zBase-10);_overlay=_stack.length>0?_stack[_stack.length-1]:null;_onHide=null;_busy=false;if(cb)cb();},300);}
function isOpen(){return _overlay!==null&&_overlay.classList.contains('active');}
function _makeHandler(customHandler){return function(e){if(_busy)return;var action=e.currentTarget.getAttribute('data-action');if(!action)return;if(typeof haptic==='function')haptic('light');if(action==='cancel'||action==='v-popup-close'){hide();return;}
if(customHandler){var handled=customHandler(action,e.currentTarget);if(handled)return;}
_busy=true;hide();setTimeout(function(){if(typeof doAction==='function')doAction(action);},150);};}
window.vPopup={show:show,hide:hide,isOpen:isOpen};})();