(function(){"use strict";var _iv=null;var _el=null;var _fullText='';var _cb=null;var _PAGE_MAX=160;function _splitPages(text){if(!text)return[''];if(text.indexOf('|')!==-1){return text.split('|').map(function(p){return p.trim();}).filter(Boolean);}
if(text.length<=_PAGE_MAX)return[text];var pages=[];var remaining=text;while(remaining.length>_PAGE_MAX){var cut=remaining.lastIndexOf('. ',_PAGE_MAX);if(cut<_PAGE_MAX*0.4)cut=remaining.lastIndexOf(', ',_PAGE_MAX);if(cut<_PAGE_MAX*0.4)cut=remaining.lastIndexOf(' ',_PAGE_MAX);if(cut<=0)cut=_PAGE_MAX;else cut+=1;pages.push(remaining.slice(0,cut).trim());remaining=remaining.slice(cut).trim();}
if(remaining)pages.push(remaining);return pages;}
function _showContinue(el,pages,idx,total,onDone,opts){if(total>1){var ind=document.createElement('div');ind.className=opts.pageClass||'dm-page-indicator';ind.textContent=(idx+1)+' / '+total;el.appendChild(ind);}
var btn=document.createElement('button');btn.className=opts.continueClass||'dm-continue-btn';btn.innerHTML='<span>Continuar</span> <span style="font-size:16px">\u25B8</span>';btn.addEventListener('click',function(){_typePage(el,pages,idx+1,onDone,opts);});el.appendChild(btn);}
function _typePage(el,pages,pageIdx,onDone,opts){var text=pages[pageIdx]||'';var isLast=pageIdx>=pages.length-1;var total=pages.length;var i=0;var _done=false;el.innerHTML='';var span=document.createElement('span');el.appendChild(span);var cursor=document.createElement('span');cursor.className=opts.cursorClass||'cursor';el.appendChild(cursor);_el=el;_fullText=text;_cb=onDone;var skipTyping=function(e){if(_done)return;_done=true;clearInterval(_iv);_iv=null;span.textContent=text;cursor.remove();el.removeEventListener('click',skipTyping);document.removeEventListener('click',_docSkip,true);if(isLast){if(onDone)onDone();}else{_showContinue(el,pages,pageIdx,total,onDone,opts);}};var _docSkip=function(e){if(_done)return;/* Skip typewriter on tap anywhere on screen */skipTyping(e);};el.addEventListener('click',skipTyping);/* Allow tap anywhere on the overlay/screen to skip typewriter */setTimeout(function(){if(!_done)document.addEventListener('click',_docSkip,true);},200);_iv=setInterval(function(){if(i>=text.length){if(_done)return;_done=true;clearInterval(_iv);_iv=null;cursor.remove();el.removeEventListener('click',skipTyping);document.removeEventListener('click',_docSkip,true);if(opts.paginate){var postMs=Math.max(600,Math.min(1500,text.length*8));setTimeout(function(){if(isLast){if(onDone)onDone();}
else{_showContinue(el,pages,pageIdx,total,onDone,opts);}},postMs);}else{if(onDone)onDone();}
return;}
span.textContent+=text[i];i++;},opts.speed||35);}
window.vTypewriter={write:function(el,text,opts){opts=opts||{};vTypewriter.skip();if(opts.paginate){var pages=_splitPages(text);_typePage(el,pages,0,opts.onDone,opts);}else{_typePage(el,[text],0,opts.onDone,opts);}},skip:function(){if(!_iv)return;clearInterval(_iv);_iv=null;if(_el&&_fullText){_el.textContent=_fullText;}
if(_cb){var cb=_cb;_cb=null;cb();}},isRunning:function(){return _iv!==null;}};})();