var _spaP=window.__spaRouteParams||{};(function(){'use strict';const tg=window.Telegram&&window.Telegram.WebApp;const _vBg=getComputedStyle(document.documentElement).getPropertyValue('--v-bg').trim()||'#2a2420';if(tg){tg.ready();tg.expand();tg.setHeaderColor(_vBg);tg.setBackgroundColor(_vBg);if(tg.BackButton){tg.BackButton.show();tg.BackButton.onClick(()=>{closePage();});}}
const params=new URLSearchParams(window.location.search);const brcode=params.get('code');const amount=params.get('amount')||'';const txid=params.get('txid')||'';const keyDisplay=params.get('key')||'';const keyType=params.get('key_type')||'';const content=document.getElementById('main-content');if(!brcode){content.innerHTML='<div class="error-msg">Nenhum codigo PIX recebido.<br>Volte e tente novamente.</div>'+'<button class="btn btn-close" onclick="closePage()">Fechar</button>';return;}
let html='';html+='<div class="qr-wrapper"><div id="qr-container"></div></div>';html+='<div class="scan-hint">Aponte a camera do app do banco para o QR acima</div>';if(amount){html+='<div class="amount-display">'+vEsc(amount)+'</div>';}
html+='<div class="info-card">';if(keyType&&keyDisplay){html+='<div class="info-row"><span class="info-label">Chave PIX ('+
vEsc(keyType)+')</span><span class="info-value">'+
vEsc(keyDisplay)+'</span></div>';}
if(txid){html+='<div class="info-row"><span class="info-label">Referencia</span>'+'<span class="info-value">'+vEsc(txid)+'</span></div>';}
html+='</div>';html+='<div class="copy-section">'+'<div class="copy-label">Codigo Pix Copia e Cola</div>'+'<div class="code-box" id="code-text">'+vEsc(brcode)+'</div>'+'</div>';html+='<button class="btn btn-copy" id="btn-copy" onclick="copyCode()">Copiar Codigo PIX</button>';html+='<button class="btn btn-close" onclick="closePage()">Fechar</button>';content.innerHTML=html;try{var cs=getComputedStyle(document.documentElement);var qrDark=cs.getPropertyValue('--v-bg').trim()||'#2a2420';var qrLight=cs.getPropertyValue('--v-parchment').trim()||'#f5f0e0';new QRCode(document.getElementById('qr-container'),{text:brcode,width:220,height:220,colorDark:qrDark,colorLight:qrLight,correctLevel:QRCode.CorrectLevel.M,});}catch(e){console.error('[PIX] Erro ao gerar QR Code',e);document.getElementById('qr-container').innerHTML='<div style="color:var(--v-danger);font-size:12px;text-align:center;padding:20px;">'+'Erro ao gerar QR Code.<br>Use o codigo abaixo.</div>';}
window.copyCode=function(){var btn=document.getElementById('btn-copy');if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(brcode).then(function(){showCopied(btn);}).catch(function(err){console.warn('[PIX] Clipboard API failed, using fallback',err);fallbackCopy(btn);});}else{fallbackCopy(btn);}};function fallbackCopy(btn){var textarea=document.createElement('textarea');textarea.value=brcode;textarea.style.position='fixed';textarea.style.left='-9999px';document.body.appendChild(textarea);textarea.select();try{document.execCommand('copy');showCopied(btn);}catch(e){console.error('[PIX] Erro ao copiar',e);btn.textContent='Erro ao copiar';}
document.body.removeChild(textarea);}
function showCopied(btn){btn.textContent='Copiado!';btn.classList.add('copied');setTimeout(function(){btn.textContent='Copiar Codigo PIX';btn.classList.remove('copied');},2000);}
window.closePage=function(){if(tg){tg.close();}else{window.close();}};})();