var tg=null;var _navSent=false;var _navSentTs=0;var _navSentTimer=null;var STORAGE_KEY='valdoria_navigate_state';function _setInfoBtns(disabled){const btns=document.querySelectorAll('.info-btn');if(disabled){btns.forEach(b=>{b.style.pointerEvents='none';b.style.opacity='0.5';});}else{btns.forEach(b=>{b.style.pointerEvents='';b.style.opacity='';});}}
var S={token:'',api:'',uid:0,currentLoc:'city_gates',knownLocs:[],discoveredLocs:[],locations:{},charData:null,quests:[],dungeons:{},canCamp:false,hasMap:0,mapCoverage:new Set(),selectedLoc:null,panX:0,panY:0,zoom:1.0,};var connectionGraph={};async function initAsync(){try{/* Map background: set src from JS — HTML has no src to avoid 404 in SPA context */
var _bg=document.getElementById('map-bg');if(_bg){var _pfx=window.SpaRouter?'navigate/':'';_bg.src=_pfx+'map-static-2x.png';_bg.onerror=function(){console.error('[NAVIGATE] Map bg failed:',_bg.src);};}
tg=window.Telegram?.WebApp;if(tg){tg.ready();tg.expand();try{tg.disableVerticalSwipes();}catch(e){console.warn('[NAVIGATE] disableVerticalSwipes:',e);}
window.__valdoriaExitAction=function(){handleClose();};}
const _spaP=window.__spaRouteParams||{};const params=new URLSearchParams(window.location.search);if(_spaP){Object.keys(_spaP).forEach(function(k){if(!params.has(k))params.set(k,_spaP[k]);});}
S.token=params.get('token')||'';S.api=params.get('api')||'';S.uid=parseInt(params.get('uid')||'0');S.returnTo=params.get('return')||'game';if(window.ValdoriaErrors){ValdoriaErrors.init({appName:'NAVIGATE',apiBase:S.api,token:S.token,uid:S.uid});}
if(S.api&&window.ApiDiscovery){ApiDiscovery.init(S.api,function(newUrl){S.api=newUrl;});}
if(S.api&&S.token&&S.uid&&window.SessionHeartbeat){SessionHeartbeat.init({apiBase:S.api,token:S.token,uid:S.uid});}
let dataB64=params.get('data')||'';if(!dataB64&&S.api&&S.token){console.debug('[NAVIGATE] No URL data param, fetching from API...');dataB64=await fetchPayloadFromAPI();}
if(!dataB64){if(window._navLoadingCtrl)window._navLoadingCtrl.forceHide();else{var _le=document.getElementById('loading');if(_le)_le.classList.add('hidden');}console.error('[NAVIGATE]','Dados do mapa não encontrados');showError('Dados do mapa não encontrados. Volte ao bot e tente novamente.');return;}
const data=JSON.parse(await decompressPayload(dataB64));if(!data){if(window._navLoadingCtrl)window._navLoadingCtrl.forceHide();else{var _le2=document.getElementById('loading');if(_le2)_le2.classList.add('hidden');}console.error('[NAVIGATE]','Falha ao carregar dados');showError('Falha ao carregar dados');return;}
S.currentLoc=data.cl||'city_gates';S.locations=data.lo||{};S.knownLocs=data.kl||Object.keys(S.locations);S.discoveredLocs=data.dl||[];S.charData=data.c||{};S.quests=data.q||[];S.dungeons=data.dd||{};S.canCamp=!!data.cc;S.hasMap=data.hm||0;S.weather=data.wt||null;S.mapCoverage=new Set(data.mc||[]);buildConnectionGraph();restoreViewport();updateHUD();updateLocationBadge();updateBottomBar();const _nc=window._navLoadingCtrl;const updateProgress=(pct)=>{if(_nc)_nc.setProgress(pct);else{var pf=document.getElementById('loading-progress');if(pf)pf.style.width=pct+'%';}};const updateStage=(text)=>{var se=document.getElementById('loading-stage');if(se)se.textContent=text;};updateProgress(5);await renderMapAsync(updateProgress,updateStage);if(typeof applyFont==='function'){const savedFont=localStorage.getItem('valdoria_font')||'medievalsharp';applyFont(savedFont);}
centerOnLocation(S.currentLoc);if(typeof _initMinimap==='function')_initMinimap();document.addEventListener('visibilitychange',function(){if(document.visibilityState==='visible'){if(_navSent&&(Date.now()-_navSentTs>15000)){console.debug('[NAVIGATE] Resetting stale _navSent on visibility change');_navSent=false;_navSentTs=0;clearTimeout(_navSentTimer);_hideTravelOverlay();_setInfoBtns(false);}_onVisibilityRefresh();}});window.addEventListener('pageshow',function(e){if(e.persisted)_onVisibilityRefresh();});updateStage('Pronto!');
function _postHide(){if(typeof playArrivalAnimation==='function')playArrivalAnimation();if(typeof ValdoriaAudio!=='undefined'){const loc=S.locations[S.currentLoc];if(loc&&loc.b)ValdoriaAudio.playBiome(loc.b);else ValdoriaAudio.play('city');}}if(_nc){_nc.setProgress(100);await new Promise(function(r){_nc.hide(function(){_postHide();r();});});}else{const loadingEl=document.getElementById('loading');const isLite=loadingEl&&loadingEl.classList.contains('loading-lite');loadingEl.classList.add('exit-cinematic');await _sleep(isLite?400:900);loadingEl.classList.add('hidden');loadingEl.classList.remove('exit-cinematic');_postHide();}
setTimeout(()=>{if(typeof showGestureTutorial==='function')showGestureTutorial();},1500);
var _bp=document.getElementById('bottom-panel');var _it=document.getElementById('immersive-toggle');var _ir=document.getElementById('immersive-restore');if(_bp)_bp.style.display='';if(_it)_it.style.display='';var _immState=localStorage.getItem('valdoria_immersive');if(_immState==='1'){if(_bp)_bp.classList.add('immersive-collapsed');if(_it)_it.style.display='none';if(_ir)_ir.style.display='';}}catch(e){if(window._navLoadingCtrl)window._navLoadingCtrl.forceHide();else{var _le3=document.getElementById('loading');if(_le3)_le3.classList.add('hidden');}console.error('[NAVIGATE] Init error:',e);showError('Erro ao inicializar',e);}}
async function fetchPayloadFromAPI(retries=2){const url=S.api+'/api/navigate/state?token='+encodeURIComponent(S.token)+'&uid='+S.uid;const headers={};if(window.Telegram?.WebApp?.initData){headers['X-Telegram-Init-Data']=Telegram.WebApp.initData;}
for(let attempt=0;attempt<=retries;attempt++){try{console.debug('[NAVIGATE] API fetch attempt',attempt+1);const r=await fetchT(url,{method:'GET',headers:headers});if(r.status===401||r.status===403){console.warn('[NAVIGATE] Session expired on state fetch ('+r.status+')');if(typeof vToast==='function')vToast('Sessão expirada. Retornando...','warn');setTimeout(function(){_transitionToGame();},1500);return'';}if(!r.ok){console.warn('[NAVIGATE] API state returned',r.status);if(attempt<retries){await _sleep(800*(attempt+1));continue;}
return'';}
const d=await r.json();if(d.data){console.debug('[NAVIGATE] Got payload from API ('+d.data.length+' chars)');return d.data;}
console.warn('[NAVIGATE] API returned ok but no data field');return'';}catch(e){console.error('[NAVIGATE] API fetch error:',e);if(attempt<retries){await _sleep(800*(attempt+1));}}}
return'';}
function _sleep(ms){return new Promise(r=>setTimeout(r,ms));}
var _lastRefreshTs=Date.now();var _refreshing=false;async function _onVisibilityRefresh(){if(document.visibilityState!=='visible')return;if(Date.now()-_lastRefreshTs<30000)return;if(_refreshing)return;_refreshing=true;_lastRefreshTs=Date.now();console.debug('[NAVIGATE] Refreshing map data on visibility change...');try{const dataB64=await fetchPayloadFromAPI(1);if(!dataB64)return;const data=JSON.parse(await decompressPayload(dataB64));if(!data)return;S.currentLoc=data.cl||S.currentLoc;S.locations=data.lo||S.locations;S.knownLocs=data.kl||Object.keys(S.locations);S.discoveredLocs=data.dl||S.discoveredLocs;S.charData=data.c||S.charData;S.quests=data.q||S.quests;S.dungeons=data.dd||S.dungeons;S.canCamp=!!data.cc;S.hasMap=data.hm||0;S.weather=data.wt||null;S.mapCoverage=new Set(data.mc||[]);buildConnectionGraph();_cachedFogState=null;updateHUD();updateLocationBadge();updateBottomBar();refreshDynamicLayers();if(typeof _initMinimap==='function')_initMinimap();console.debug('[NAVIGATE] Map data refreshed successfully');}catch(e){console.warn('[NAVIGATE] Auto-refresh failed:',e);}finally{_refreshing=false;}}
async function zlibInflate(data){return Promise.race([_zlibInflateImpl(data),new Promise((_,rej)=>setTimeout(()=>rej(new Error('Tempo limite de descompressão')),5000))]);}async function _zlibInflateImpl(data){if(typeof DecompressionStream==='undefined'){throw new Error('DecompressionStream não suportado');}
const ds=new DecompressionStream('deflate');const writer=ds.writable.getWriter();writer.write(data);writer.close();const reader=ds.readable.getReader();const chunks=[];while(true){const{done,value}=await reader.read();if(done)break;chunks.push(value);}
const totalLen=chunks.reduce((s,c)=>s+c.length,0);const merged=new Uint8Array(totalLen);let offset=0;for(const chunk of chunks){merged.set(chunk,offset);offset+=chunk.length;}
return merged;}
function buildConnectionGraph(){connectionGraph={};const knownSet=new Set(S.knownLocs);for(const locId of S.knownLocs){connectionGraph[locId]=[];}
for(const[aId,bId]of CONNECTION_EDGES){if(knownSet.has(aId)&&knownSet.has(bId)){if(connectionGraph[aId]&&!connectionGraph[aId].includes(bId)){connectionGraph[aId].push(bId);}
if(connectionGraph[bId]&&!connectionGraph[bId].includes(aId)){connectionGraph[bId].push(aId);}}}
_invalidateMapCaches();if(typeof invalidateBfsCache==='function')invalidateBfsCache();}
function _invalidateMapCaches(){if(typeof _bfsCache!=='undefined'){for(const k in _bfsCache)delete _bfsCache[k];}
_cachedFogState=null;_cachedPxPerTurn=0;if(typeof _invalidateTerrainCaches==='function')_invalidateTerrainCaches();if(typeof _invalidateVisCache==='function')_invalidateVisCache();}
function isConnected(fromId,toId){const conns=connectionGraph[fromId]||[];return conns.includes(toId);}
function saveViewport(){try{sessionStorage.setItem(STORAGE_KEY,JSON.stringify({tk:S.token,px:S.panX,py:S.panY,zm:S.zoom,ts:Date.now(),}));}catch(e){console.warn('[NAVIGATE] saveViewport:',e);}}
function restoreViewport(){try{const raw=sessionStorage.getItem(STORAGE_KEY);if(!raw)return;const snap=JSON.parse(raw);if(snap.tk!==S.token||Date.now()-snap.ts>600000)return;S.panX=snap.px||0;S.panY=snap.py||0;S.zoom=snap.zm||1.0;}catch(e){console.warn('[NAVIGATE] restoreViewport:',e);}}
function updateHUD(){const c=S.charData;if(!c)return;document.getElementById('hud-name').textContent=`${c.ci || ''} ${c.nm || 'Aventureiro'}`;document.getElementById('hud-level').textContent=`Nv.${c.lv || 1}`;const hpEl=document.getElementById('hud-hp');const mpEl=document.getElementById('hud-mp');const hpPct=c.mh>0?Math.min(100,(c.hp/c.mh)*100):0;const mpPct=c.mm>0?Math.min(100,(c.mp/c.mm)*100):0;const oldHpV=hpEl.dataset.pct||'',oldMpV=mpEl.dataset.pct||'';const newHpV=''+Math.round(hpPct),newMpV=''+Math.round(mpPct);hpEl.dataset.pct=newHpV;mpEl.dataset.pct=newMpV;hpEl.style.transform=`scaleX(${hpPct/100})`;mpEl.style.transform=`scaleX(${mpPct/100})`;if(oldHpV&&oldHpV!==newHpV){hpEl.classList.remove('shimmer');void hpEl.offsetWidth;hpEl.classList.add('shimmer');}
if(oldMpV&&oldMpV!==newMpV){mpEl.classList.remove('shimmer');void mpEl.offsetWidth;mpEl.classList.add('shimmer');}}
function updateLocationBadge(){const loc=S.locations[S.currentLoc];if(!loc)return;document.getElementById('badge-icon').textContent=loc.i||'';document.getElementById('badge-name').textContent=loc.n||'Desconhecido';const known=S.knownLocs.length;const total=Object.keys(LOCATION_COORDS).length;document.getElementById('badge-info').textContent=`Mapa ${known}/${total}`;var _wb=document.getElementById('badge-weather');if(_wb&&S.weather){_wb.textContent=(S.weather.i||'')+' '+(S.weather.l||'');_wb.style.display='';}else if(_wb){_wb.style.display='none';}}
function updateBottomBar(){const returnBtn=document.getElementById('btn-return');if(returnBtn&&S.currentLoc==='city_gates'){returnBtn.style.display='none';}}
function finishNavigation(type,target,flags){if(_navSent){console.warn('[NAVIGATE][DEBUG] BLOCKED: double-fire');if(typeof vToast==='function')vToast('Aguarde...');return;}
_navSent=true;_navSentTs=Date.now();clearTimeout(_navSentTimer);_navSentTimer=setTimeout(()=>{if(_navSent){console.warn('[NAVIGATE] Auto-resetting stale _navSent after 15s timeout');_navSent=false;_navSentTs=0;_hideTravelOverlay();_setInfoBtns(false);}},15000);_setInfoBtns(true);if(type==='travel'&&target&&typeof animateTravel==='function'){closeInfoPanel();animateTravel(S.currentLoc,target,()=>_sendNavAction(type,target,flags));return;}
_sendNavAction(type,target,flags);}
function _sendNavAction(type,target,flags){const payload={action:'navigate_action',token:S.token,uid:S.uid,type:type,};if(target)payload.target=target;if(flags?.noMap||(type==='travel'&&S.hasMap===0))payload.noMap=true;if(flags?.firstVisit)payload.firstVisit=true;if(flags?.pace)payload.pace=flags.pace;if(flags?.activity)payload.activity=flags.activity;if(typeof _haptic==='function'){if(flags?.noMap||flags?.firstVisit)_haptic('warn');else if(type==='travel')_haptic('travel');else _haptic('open');}
if(!S.api){showError('Erro: API não configurada. Feche e reabra o mapa.');console.error('[NAVIGATE] No api URL param - cannot send action. Redeploy needed.');_navSent=false;clearTimeout(_navSentTimer);_setInfoBtns(false);return;}
const apiUrl=`${S.api}/api/navigate/action`;_showTravelOverlay(type,target);const _nh={'Content-Type':'application/json'};if(window.Telegram?.WebApp?.initData){_nh['X-Telegram-Init-Data']=Telegram.WebApp.initData;}
fetchT(apiUrl,{method:'POST',headers:_nh,body:JSON.stringify(payload),}).then(r=>{if(r.status===401||r.status===403){console.warn('[NAVIGATE] Session expired ('+r.status+'), returning to game');if(typeof _haptic==='function')_haptic('error');_navSent=false;clearTimeout(_navSentTimer);_hideTravelOverlay();_setInfoBtns(false);if(typeof vToast==='function')vToast('Sessão expirada. Retornando...','warn');setTimeout(function(){_transitionToGame();},1200);return Promise.reject({_handled:true});}if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}).then(d=>{if(!d)return;if(d.url&&(type==='travel'||type==='return')){if(d.travel_log&&d.travel_log.length>0){_showTravelJournal(d.travel_log,d.url);return;}window.__valdoria_transitioning=true;valdoriaSpaNav(d.url);return;}
_transitionToGame();}).catch(e=>{if(e&&e._handled)return;console.error('[NAVIGATE][DEBUG] fetch error:',e);if(typeof _haptic==='function')_haptic('error');_navSent=false;_navSentTs=0;clearTimeout(_navSentTimer);_hideTravelOverlay();_setInfoBtns(false);_showRetryError('Erro ao viajar: '+e.message,type,target,flags);});}
function _showRetryError(msg,type,target,flags){var d=document.getElementById('retry-error-overlay');if(d)d.remove();d=document.createElement('div');d.id='retry-error-overlay';d.className='travel-overlay';d.style.cssText='display:flex;flex-direction:column;align-items:center;justify-content:center;gap:16px;';var wrap=document.createElement('div');wrap.style.cssText='text-align:center;padding:20px;';var icon=document.createElement('div');icon.style.cssText='font-size:24px;margin-bottom:12px;';icon.textContent='⚠️';var msgEl=document.createElement('div');msgEl.style.cssText='color:var(--v-text,#d4c8b0);margin-bottom:16px;';msgEl.textContent=msg;var retryBtn=document.createElement('button');retryBtn.className='action-btn';retryBtn.style.cssText='padding:10px 24px;cursor:pointer;display:block;width:100%;margin-bottom:8px;';retryBtn.textContent='Tentar Novamente';retryBtn.onclick=function(){d.remove();finishNavigation(type,target,flags);};var cancelBtn=document.createElement('button');cancelBtn.className='action-btn';cancelBtn.style.cssText='padding:8px 20px;cursor:pointer;opacity:0.7;display:block;width:100%;';cancelBtn.textContent='Cancelar';cancelBtn.onclick=function(){d.remove();};wrap.appendChild(icon);wrap.appendChild(msgEl);wrap.appendChild(retryBtn);wrap.appendChild(cancelBtn);d.appendChild(wrap);document.body.appendChild(d);}
function _showTravelJournal(log,redirectUrl){_hideTravelOverlay();var bodyHtml='<div class="travel-journal-entries">';for(var i=0;i<log.length;i++){var e=log[i];bodyHtml+='<div class="travel-journal-entry travel-journal-entry-'+e.type+'" style="opacity:0;transform:translateX(-12px)"><span class="travel-journal-entry-icon">'+e.icon+'</span><div class="travel-journal-entry-body"><div class="travel-journal-entry-text">'+e.text+'</div>'+(e.detail?'<div class="travel-journal-entry-detail">'+e.detail+'</div>':'')+'</div></div>';}bodyHtml+='</div>';var _journalDone=false;vPopup.show({id:'v-popup-overlay',header:'<span class="travel-journal-icon">\u{1f4dc}</span> Di\u00e1rio de Viagem',body:bodyHtml,actions:[{label:'Continuar Viagem \u27a1',action:'continue_travel',cls:'v-popup-btn v-popup-btn--primary travel-journal-btn'}],onAction:function(action){if(action==='continue_travel'){if(_journalDone)return;_journalDone=true;var _rl=[];for(var _ri=0;_ri<log.length;_ri++){if(log[_ri].type==='arrival_new'&&log[_ri].loc_id)_rl.push(log[_ri].loc_id);}if(_rl.length)try{localStorage.setItem('valdoria_reveal_locs',JSON.stringify(_rl));}catch(e){console.warn('[NAVIGATE]',e);}window.__valdoria_transitioning=true;valdoriaSpaNav(redirectUrl);return true;}},closeOnOutside:false,onReady:function(overlay){var entries=overlay.querySelectorAll('.travel-journal-entry');var continueBtn=overlay.querySelector('[data-action="continue_travel"]');if(continueBtn)continueBtn.style.opacity='0';entries.forEach(function(el,idx){setTimeout(function(){el.style.transition='opacity var(--v-transition-base), transform var(--v-transition-base)';el.style.opacity='1';el.style.transform='translateX(0)';},300+idx*400);});var totalDelay=Math.max(2500,300+log.length*400+800);setTimeout(function(){if(continueBtn){continueBtn.style.transition='opacity var(--v-transition-base)';continueBtn.style.opacity='1';}},totalDelay);}});}
function _showTravelOverlay(type,target){let overlay=document.getElementById('travel-overlay');if(!overlay){overlay=document.createElement('div');overlay.id='travel-overlay';overlay.className='travel-overlay';document.body.appendChild(overlay);}
const loc=target?S.locations[target]:null;const biome=loc?(BIOME_INFO[loc.b]||BIOME_INFO.plains):null;const danger=loc?.d||0;const edgeDist=target?getConnectionDistance(S.currentLoc,target):0;const compassSvg='<svg class="travel-overlay-compass-svg" viewBox="0 0 48 48"><circle cx="24" cy="24" r="20" fill="none" stroke="#c4953a" stroke-width="1.5" stroke-opacity="0.4"/><polygon points="24,6 27,22 24,20 21,22" fill="#c4953a" fill-opacity="0.8"/><polygon points="24,42 21,26 24,28 27,26" fill="#8a6a3a" fill-opacity="0.6"/><circle cx="24" cy="24" r="2" fill="#c4953a"/></svg>';let text='Preparando...';let biomeText='';let dangerText='';if(type==='travel'&&loc){text='Viajando para '+(loc.n||'destino')+'...';if(biome)biomeText=biome.label+(edgeDist>0?' \u00b7 '+edgeDist+' turno'+(edgeDist!==1?'s':''):'');if(danger>=7)dangerText='\u2620\ufe0f Perigo extremo no caminho';else if(danger>=5)dangerText='\u26a0\ufe0f Alta chance de encontros';}else if(type==='return'){text='Retornando...';}else if(type==='camp'){text='Montando acampamento...';}else if(type==='explore'){text='Explorando a regi\u00e3o...';}
overlay.innerHTML='<div class="travel-overlay-content">'+
compassSvg+'<div class="travel-overlay-text">'+text+'</div>'+
(biomeText?'<div class="travel-overlay-biome">'+biomeText+'</div>':'')+
(dangerText?'<div class="travel-overlay-danger">'+dangerText+'</div>':'')+'<div class="travel-overlay-progress"><div class="travel-overlay-progress-fill" id="travel-progress-fill"></div></div>'+'<div class="travel-overlay-dots"><span>.</span><span>.</span><span>.</span></div>'+'</div>'+'<button class="v-skip-btn" id="travel-skip">Pular >></button>';requestAnimationFrame(()=>{overlay.classList.add('visible');const fill=document.getElementById('travel-progress-fill');if(fill){requestAnimationFrame(()=>{fill.style.transition='width 3s linear';fill.style.width='100%';});}});var _travelSkip=document.getElementById('travel-skip');if(_travelSkip){setTimeout(function(){if(_travelSkip)_travelSkip.classList.add('visible');},3000);_travelSkip.onclick=function(){_hideTravelOverlay();};}}
function _hideTravelOverlay(){const overlay=document.getElementById('travel-overlay');if(overlay){overlay.classList.remove('visible');}}
function handleReturn(){finishNavigation('return');}
function handleClose(){_transitionToGame();}
async function _transitionToGame(){if(!S.api||!S.token){try{tg?.close();}catch(e){console.warn('[NAVIGATE] Close:',e);}return;}
var _transSafety=setTimeout(function(){console.warn('[NAVIGATE] transition safety timeout');_hideTravelOverlay();_navSent=false;clearTimeout(_navSentTimer);},8000);
var h={'Content-Type':'application/json','Authorization':'Bearer '+S.token};if(window.Telegram?.WebApp?.initData)h['X-Telegram-Init-Data']=Telegram.WebApp.initData;h['X-Idempotency-Key']=crypto.randomUUID();try{var r=await fetchT(S.api+'/api/webapp/transition',{method:'POST',headers:h,body:JSON.stringify({from:'navigate',to:(S.returnTo||'game'),user_id:S.uid,payload:{}})});var d=await r.json();window.__valdoria_transitioning=true;if(d.url){clearTimeout(_transSafety);clearTimeout(_navSentTimer);_navSent=false;valdoriaSpaNav(d.url);return;}}catch(e){console.error('[NAVIGATE] transition error:',e);clearTimeout(_transSafety);_hideTravelOverlay();_navSent=false;clearTimeout(_navSentTimer);}
clearTimeout(_transSafety);var base=window.location.href.replace(/\/navigate\/.*/,'');window.__valdoria_transitioning=true;valdoriaSpaNav(base+'/app.html?route=game&token='+S.token+'&api='+encodeURIComponent(S.api)+'&uid='+S.uid+'&return=game&v=1');}
window.addEventListener('pagehide',function(){if(typeof _animFrame!=='undefined'&&_animFrame){cancelAnimationFrame(_animFrame);_animFrame=null;}clearTimeout(_navSentTimer);});
(function(){var toggle=document.getElementById('immersive-toggle');var restore=document.getElementById('immersive-restore');var panel=document.getElementById('bottom-panel');if(!toggle||!restore||!panel)return;toggle.addEventListener('click',function(){panel.classList.add('immersive-collapsed');toggle.style.display='none';restore.style.display='';localStorage.setItem('valdoria_immersive','1');});restore.addEventListener('click',function(){panel.classList.remove('immersive-collapsed');toggle.style.display='';restore.style.display='none';localStorage.setItem('valdoria_immersive','0');});})();
if(!window.__spaRouteName){document.addEventListener('DOMContentLoaded',initAsync);}