var tg=null;var _navSent=false;var _navSentTs=0;var _navSentTimer=null;var STORAGE_KEY='valdoria_navigate_state';function _setInfoBtns(disabled){const btns=document.querySelectorAll('.info-btn');if(disabled){btns.forEach(b=>{b.style.pointerEvents='none';b.style.opacity='0.5';});}else{btns.forEach(b=>{b.style.pointerEvents='';b.style.opacity='';});}}

var S={token:'',api:'',uid:0,currentLoc:'city_gates',knownLocs:[],discoveredLocs:[],locations:{},charData:null,quests:[],dungeons:{},canCamp:false,hasMap:0,mapCoverage:new Set(),selectedLoc:null,panX:0,panY:0,zoom:1.0,};var connectionGraph={};function _navContentCheck(){var _eo=document.getElementById('v-err-overlay');if(_eo&&_eo.style.display!=='none')return true;var _ld=document.getElementById('loading');if(_ld&&_ld.style.display!=='none'&&!_ld.classList.contains('hidden'))return true;var m=document.getElementById('map-viewport')||document.querySelector('.map-container')||document.querySelector('canvas');return !!(m&&m.offsetHeight>0);}async function initAsync(){try{console.warn("[NAVIGATE] initAsync start api="+!!S.api+" token="+!!S.token+" uid="+S.uid);if(window.SpaWatchdog)SpaWatchdog.start('navigate',_navContentCheck,30000);/* Hide Game Hub connection pill during navigate (SPA remnant) */var _ghConnPill=document.getElementById('connection-status');if(_ghConnPill)_ghConnPill.style.display='none';/* Map background: set src from JS — HTML has no src to avoid 404 in SPA context */
var _bg=document.getElementById('map-bg');if(_bg){var _pfx=window.SpaRouter?'navigate/':'';_bg.src=_pfx+'map-static-2x.png';_bg.onerror=function(){console.error('[NAVIGATE] Map bg failed:',_bg.src);};}
var _bgReady=_bg?_bg.decode().catch(function(e){console.warn('[NAVIGATE] img.decode fallback:',e);}):Promise.resolve();
tg=window.Telegram?.WebApp;if(tg){tg.ready();tg.expand();try{tg.disableVerticalSwipes();}catch(e){console.warn('[NAVIGATE] disableVerticalSwipes:',e);}
try{tg.BackButton.hide();}catch(e){}
window.__valdoriaExitAction=function(){handleClose();};}
const _spaP=window.__spaRouteParams||{};const params=new URLSearchParams(window.location.search);if(_spaP){Object.keys(_spaP).forEach(function(k){params.set(k,_spaP[k]);});}
S.token=params.get('token')||'';S.api=params.get('api')||'';S.uid=parseInt(params.get('uid')||'0',10);S.returnTo=params.get('return')||'game';if(window.ValdoriaErrors){ValdoriaErrors.init({appName:'NAVIGATE',apiBase:S.api,token:S.token,uid:S.uid});}
if(S.api&&window.ApiDiscovery){ApiDiscovery.init(S.api,function(newUrl){S.api=newUrl;});}
if(S.api&&S.token&&S.uid&&window.SessionHeartbeat){SessionHeartbeat.init({apiBase:S.api,token:S.token,uid:S.uid});}
let dataB64=params.get('data')||'';if(!dataB64&&S.api&&S.token){console.warn("[NAVIGATE] fetching payload via API (20s timeout)");var _navFetchTimeout=new Promise(function(_,rej){setTimeout(function(){rej(new Error('Navigate fetch timeout (20s)'));},20000);}); /* noqa: preflight */ try{dataB64=await Promise.race([fetchPayloadFromAPI(),_navFetchTimeout]);}catch(_fte){console.error('[NAVIGATE] Fetch timeout or error:',_fte);if(window._loadDbg)_loadDbg('fetch failed, dataB64 cleared');dataB64='';}}
if(!dataB64){if(window._navLoadingCtrl)window._navLoadingCtrl.forceHide();else{var _le=document.getElementById('loading');if(_le)_le.classList.add('hidden');}console.error('[NAVIGATE]','Dados do mapa não encontrados');if(window.vPopup){vPopup.show({header:'⚠️ Mapa Indisponível',body:'<div style="text-align:center;color:var(--v-text-dim);font-size:var(--v-font-sm)">Dados do mapa não encontrados.<br>Retorne ao jogo e tente novamente.</div>',actions:[{label:'Voltar ao Jogo',cls:'v-popup-btn v-popup-btn--primary',action:'back'}],onAction:function(a){if(a==='back'){vPopup.hide();_transitionToGame();return true;}},closeOnOutside:false});}else{showError('Dados do mapa não encontrados. Volte ao bot e tente novamente.');}return;}
const data=JSON.parse(await decompressPayload(dataB64));if(!data){if(window._navLoadingCtrl)window._navLoadingCtrl.forceHide();else{var _le2=document.getElementById('loading');if(_le2)_le2.classList.add('hidden');}console.error('[NAVIGATE]','Falha ao carregar dados');if(window.vPopup){vPopup.show({header:'⚠️ Erro no Mapa',body:'<div style="text-align:center;color:var(--v-text-dim);font-size:var(--v-font-sm)">Falha ao carregar dados do mapa.<br>Retorne ao jogo e tente novamente.</div>',actions:[{label:'Voltar ao Jogo',cls:'v-popup-btn v-popup-btn--primary',action:'back'}],onAction:function(a){if(a==='back'){vPopup.hide();_transitionToGame();return true;}},closeOnOutside:false});}else{showError('Falha ao carregar dados');}return;}
S.currentLoc=data.cl||'city_gates';S.locations=data.lo||{};S.knownLocs=data.kl||Object.keys(S.locations);S.discoveredLocs=data.dl||[];S.charData=data.c||{};S.quests=data.q||[];S.dungeons=data.dd||{};S.canCamp=!!data.cc;S.hasMap=data.hm||0;S.weather=data.wt||null;S.mapCoverage=new Set(data.mc||[]);console.warn('[NAVIGATE] payload parsed: locations='+Object.keys(S.locations).length+' known='+S.knownLocs.length+' current='+S.currentLoc);buildConnectionGraph();restoreViewport();updateHUD();updateBottomBar();const _nc=window._navLoadingCtrl;const updateProgress=(pct)=>{if(_nc)_nc.setProgress(pct);else{var pf=document.getElementById('loading-progress');if(pf)pf.style.width=pct+'%';}};const updateStage=(text)=>{var se=document.getElementById('loading-stage');if(se)se.textContent=text;};updateProgress(5);await renderMapAsync(updateProgress,updateStage);if(typeof applyFont==='function'){const savedFont=localStorage.getItem('valdoria_font')||'medievalsharp';applyFont(savedFont);}
centerOnLocation(S.currentLoc);var _onNavVisChange=function(){if(document.visibilityState==='visible'){if(_navSent&&(Date.now()-_navSentTs>15000)){_navSent=false;_navSentTs=0;clearTimeout(_navSentTimer);_hideTravelOverlay();_setInfoBtns(false);}_onVisibilityRefresh();}};document.addEventListener('visibilitychange',_onNavVisChange);var _onNavPageShow=function(e){if(e.persisted)_onVisibilityRefresh();};window.addEventListener('pageshow',_onNavPageShow);updateStage('Pronto!');await _bgReady;await new Promise(function(r){requestAnimationFrame(function(){requestAnimationFrame(r);});});
function _postHide(){if(window.SpaWatchdog)SpaWatchdog.feed();if(typeof playArrivalAnimation==='function')playArrivalAnimation();if(typeof ValdoriaAudio!=='undefined'){const loc=S.locations[S.currentLoc];if(loc&&loc.b)ValdoriaAudio.playBiome(loc.b);else ValdoriaAudio.play('city');}setTimeout(function(){if(typeof handleLocationTap==='function')handleLocationTap(S.currentLoc);},600);}if(_nc){_nc.setProgress(100);await new Promise(function(r){_nc.hide(function(){_postHide();r();});});}else{const loadingEl=document.getElementById('loading');const isLite=loadingEl&&loadingEl.classList.contains('loading-lite');loadingEl.classList.add('exit-cinematic');await _sleep(isLite?400:900);loadingEl.classList.add('hidden');loadingEl.classList.remove('exit-cinematic');_postHide();}
setTimeout(()=>{if(typeof showGestureTutorial==='function')showGestureTutorial();},1500);
if(!window._spaCleanupFns)window._spaCleanupFns=[];window.__valdoria_reconnect_handler=function(data){console.info('[NAVIGATE] In-place reconnect — refreshing state');if(data.transition&&data.transition.url){var _rp=new URLSearchParams(data.transition.url.split('?')[1]||'');if(_rp.get('token'))S.token=_rp.get('token');if(_rp.get('api'))S.api=_rp.get('api');}(async function(){try{var dataB64=await fetchPayloadFromAPI(2);if(!dataB64){console.warn('[NAVIGATE] Reconnect refresh got no data');if(typeof vToast==='function')vToast('Reconectado!','success');return;}var freshData=JSON.parse(await decompressPayload(dataB64));if(!freshData)return;S.currentLoc=freshData.cl||S.currentLoc;S.locations=freshData.lo||S.locations;S.knownLocs=freshData.kl||Object.keys(S.locations);S.discoveredLocs=freshData.dl||S.discoveredLocs;S.charData=freshData.c||S.charData;S.quests=freshData.q||S.quests;S.dungeons=freshData.dd||S.dungeons;S.canCamp=!!freshData.cc;S.hasMap=freshData.hm||0;S.weather=freshData.wt||null;S.mapCoverage=new Set(freshData.mc||[]);buildConnectionGraph();_cachedFogState=null;updateHUD();updateBottomBar();refreshDynamicLayers();_lastRefreshTs=Date.now();if(typeof vToast==='function')vToast('Conexão restaurada!','success');}catch(e){console.warn('[NAVIGATE] Reconnect refresh error:',e);}})();return true;};window._spaCleanupFns.push(function(){delete window.__valdoria_reconnect_handler;document.removeEventListener('visibilitychange',_onNavVisChange);window.removeEventListener('pageshow',_onNavPageShow);var _travelOv=document.getElementById('travel-overlay');if(_travelOv&&_travelOv.parentNode){_travelOv.parentNode.removeChild(_travelOv);console.log('[NAVIGATE] SPA cleanup: travel overlay removed');}/* Restore Game Hub connection pill */var _ghCp=document.getElementById('connection-status');if(_ghCp)_ghCp.style.display='';});return '__loading_delegated__';}catch(e){if(window._navLoadingCtrl)window._navLoadingCtrl.forceHide();else{var _le3=document.getElementById('loading');if(_le3)_le3.classList.add('hidden');}console.error('[NAVIGATE] Init error:',e);showError('Erro ao inicializar',e);}}
async function fetchPayloadFromAPI(retries=2){const url=S.api+'/api/navigate/state?token='+encodeURIComponent(S.token)+'&uid='+S.uid;const headers={};if(window.Telegram?.WebApp?.initData){headers['X-Telegram-Init-Data']=Telegram.WebApp.initData;}
for(let attempt=0;attempt<=retries;attempt++){try{const r=await fetchT(url,{method:'GET',headers:headers});if(r.status===401||r.status===403){console.warn('[NAVIGATE] Session expired on state fetch ('+r.status+')');if(typeof vToast==='function')vToast('Sessão expirada. Retornando...','warn');setTimeout(function(){_transitionToGame();},1500);return'';}if(r.status===409){const body=await r.json().catch(()=>({}));if(body.status==='displaced'&&window.SessionHeartbeat){SessionHeartbeat.handleDisplaced(body.device||'',body.from_device||'');}return'';}if(!r.ok){console.warn('[NAVIGATE] API state returned',r.status);if(attempt<retries){await _sleep(800*(attempt+1));continue;}
return'';}
const d=await r.json();if(d&&d.status==='displaced'){if(window.SessionHeartbeat){SessionHeartbeat.handleDisplaced(d.device||'',d.from_device||'');}return'';}if(d.data){return d.data;}
console.warn('[NAVIGATE] API returned ok but no data field');return'';}catch(e){console.error('[NAVIGATE] API fetch error:',e);if(attempt<retries){await _sleep(800*(attempt+1));}}}
return'';}
function _sleep(ms){return new Promise(r=>setTimeout(r,ms));}
var _lastRefreshTs=Date.now();var _refreshing=false;async function _onVisibilityRefresh(){if(document.visibilityState!=='visible')return;if(Date.now()-_lastRefreshTs<30000)return;if(_refreshing)return;_refreshing=true;_lastRefreshTs=Date.now();try{const dataB64=await fetchPayloadFromAPI(1);if(!dataB64)return;const data=JSON.parse(await decompressPayload(dataB64));if(!data)return;S.currentLoc=data.cl||S.currentLoc;S.locations=data.lo||S.locations;S.knownLocs=data.kl||Object.keys(S.locations);S.discoveredLocs=data.dl||S.discoveredLocs;S.charData=data.c||S.charData;S.quests=data.q||S.quests;S.dungeons=data.dd||S.dungeons;S.canCamp=!!data.cc;S.hasMap=data.hm||0;S.weather=data.wt||null;S.mapCoverage=new Set(data.mc||[]);buildConnectionGraph();_cachedFogState=null;updateHUD();updateBottomBar();refreshDynamicLayers();}catch(e){console.warn('[NAVIGATE] Auto-refresh failed:',e);}finally{_refreshing=false;}}
async function zlibInflate(data){return Promise.race([_zlibInflateImpl(data),new Promise((_,rej)=>/*_TIMEOUT*/setTimeout(()=>rej(new Error('Tempo limite de descompressão')),5000))]);}async function _zlibInflateImpl(data){if(typeof DecompressionStream==='undefined'){throw new Error('DecompressionStream não suportado');}
const ds=new DecompressionStream('deflate');const writer=ds.writable.getWriter();writer.write(data);writer.close();const reader=ds.readable.getReader();const chunks=[];while(true){const{done,value}=await reader.read();if(done)break;chunks.push(value);}
const totalLen=chunks.reduce((s,c)=>s+c.length,0);const merged=new Uint8Array(totalLen);let offset=0;for(const chunk of chunks){merged.set(chunk,offset);offset+=chunk.length;}
return merged;}
function buildConnectionGraph(){connectionGraph={};/* Safety: current location MUST be in knownLocs */if(S.currentLoc&&!S.knownLocs.includes(S.currentLoc)){console.warn('[NAVIGATE] HEAL: currentLoc',S.currentLoc,'missing from knownLocs');S.knownLocs.push(S.currentLoc);}const knownSet=new Set(S.knownLocs);for(const locId of S.knownLocs){connectionGraph[locId]=[];}
for(const[aId,bId]of CONNECTION_EDGES){if(knownSet.has(aId)&&knownSet.has(bId)){if(connectionGraph[aId]&&!connectionGraph[aId].includes(bId)){connectionGraph[aId].push(bId);}
if(connectionGraph[bId]&&!connectionGraph[bId].includes(aId)){connectionGraph[bId].push(aId);}}}
/* Safety: if currentLoc has 0 connections, force-add its static neighbors */if(S.currentLoc&&connectionGraph[S.currentLoc]&&connectionGraph[S.currentLoc].length===0){console.warn('[NAVIGATE] HEAL: currentLoc',S.currentLoc,'has 0 connections, adding static neighbors');for(var _ei=0;_ei<CONNECTION_EDGES.length;_ei++){var _e=CONNECTION_EDGES[_ei];if(_e[0]===S.currentLoc||_e[1]===S.currentLoc){var _nb=_e[0]===S.currentLoc?_e[1]:_e[0];if(!connectionGraph[_nb])connectionGraph[_nb]=[];if(!connectionGraph[S.currentLoc].includes(_nb))connectionGraph[S.currentLoc].push(_nb);if(!connectionGraph[_nb].includes(S.currentLoc))connectionGraph[_nb].push(S.currentLoc);if(!knownSet.has(_nb)){knownSet.add(_nb);S.knownLocs.push(_nb);}}}}
_invalidateMapCaches();if(typeof invalidateBfsCache==='function')invalidateBfsCache();}
function _invalidateMapCaches(){if(typeof _bfsCache!=='undefined'){for(const k in _bfsCache)delete _bfsCache[k];}
_cachedFogState=null;_cachedPxPerTurn=0;if(typeof _distCache!=='undefined'){_distCache={};_distCacheLoc=null;}if(typeof _invalidateTerrainCaches==='function')_invalidateTerrainCaches();if(typeof _invalidateVisCache==='function')_invalidateVisCache();}
function isConnected(fromId,toId){const conns=connectionGraph[fromId]||[];return conns.includes(toId);}
function saveViewport(){try{sessionStorage.setItem(STORAGE_KEY,JSON.stringify({tk:S.token,px:S.panX,py:S.panY,zm:S.zoom,ts:Date.now(),}));}catch(e){console.warn('[NAVIGATE] saveViewport:',e);}}
function restoreViewport(){try{const raw=sessionStorage.getItem(STORAGE_KEY);if(!raw)return;const snap=JSON.parse(raw);if(snap.tk!==S.token||Date.now()-snap.ts>3600000)return;S.panX=snap.px||0;S.panY=snap.py||0;S.zoom=snap.zm||1.0;}catch(e){console.warn('[NAVIGATE] restoreViewport:',e);}}
function updateHUD(){const c=S.charData;if(!c)return;document.getElementById('hud-name').textContent=`${c.ci || ''} ${c.nm || 'Aventureiro'}`;document.getElementById('hud-level').textContent=`Nv.${c.lv || 1}`;var goldEl=document.getElementById('hud-gold');if(goldEl){if(c.gp>0){goldEl.innerHTML=(Number(c.gp)||0)+' <span class="vi vi-coin sm"></span>';goldEl.style.display='';}else{goldEl.style.display='none';}}var wtEl=document.getElementById('hud-weather');if(wtEl&&S.weather&&S.weather.i){wtEl.textContent=S.weather.i;wtEl.title=S.weather.l||'';wtEl.style.display='';}else if(wtEl){wtEl.style.display='none';}}
function updateBottomBar(){}
function finishNavigation(type,target,flags){console.info('[NAVIGATE] action',{type:type,target:target,pace:flags&&flags.pace,activity:flags&&flags.activity,api:!!S.api,token:!!S.token,uid:S.uid});if(!S.api||!S.token||!S.uid){console.error('[NAVIGATE] BLOCKED: missing session params api='+!!S.api+' token='+!!S.token+' uid='+S.uid);if(typeof vToast==='function')vToast('Sessão expirada. Reabra o mapa.','error');return;}if(_navSent){var _staleMs=Date.now()-(_navSentTs||0);console.warn('[NAVIGATE] BLOCKED: double-fire (stale '+_staleMs+'ms)');if(_staleMs>10000){console.warn('[NAVIGATE] force-resetting stale _navSent after '+_staleMs+'ms');_navSent=false;_navSentTs=0;clearTimeout(_navSentTimer);_hideTravelOverlay();_setInfoBtns(false);}else{if(typeof vToast==='function')vToast('Aguarde...');return;}}
_navSent=true;_navSentTs=Date.now();clearTimeout(_navSentTimer);if(window._loadDbg)_loadDbg("navSent locked");_navSentTimer=/*_TIMEOUT*/setTimeout(()=>{if(_navSent){console.warn('[NAVIGATE] Auto-resetting stale _navSent after 15s timeout');_navSent=false;_navSentTs=0;_hideTravelOverlay();_setInfoBtns(false);}},15000);_setInfoBtns(true);if(type==='travel'&&target&&typeof animateTravel==='function'){closeInfoPanel();animateTravel(S.currentLoc,target,()=>_sendNavAction(type,target,flags));return;}
_sendNavAction(type,target,flags);}
function _sendNavAction(type,target,flags){console.log('[NAVIGATE] sendAction type=%s target=%s',type,target||'(none)');const payload={action:'navigate_action',token:S.token,uid:S.uid,type:type,};if(target)payload.target=target;if(flags?.noMap||(type==='travel'&&S.hasMap===0))payload.noMap=true;if(flags?.firstVisit)payload.firstVisit=true;if(flags?.pace)payload.pace=flags.pace;if(flags?.activity)payload.activity=flags.activity;if(typeof _haptic==='function'){if(flags?.noMap||flags?.firstVisit)_haptic('warn');else if(type==='travel')_haptic('travel');else _haptic('open');}
if(!S.api){showError('Erro de conex\u00e3o. Feche esta janela e reabra o jogo.');console.error('[NAVIGATE] No api URL param - cannot send action. Redeploy needed.');_navSent=false;clearTimeout(_navSentTimer);_setInfoBtns(false);return;}
const apiUrl=`${S.api}/api/navigate/action`;_showTravelOverlay(type,target);const _nh={'Content-Type':'application/json'};if(window.Telegram?.WebApp?.initData){_nh['X-Telegram-Init-Data']=Telegram.WebApp.initData;}
fetchT(apiUrl,{method:'POST',headers:_nh,body:JSON.stringify(payload),}).then(r=>{if(r.status===401||r.status===403){console.warn('[NAVIGATE] Session expired ('+r.status+'), returning to game');if(typeof _haptic==='function')_haptic('error');_navSent=false;clearTimeout(_navSentTimer);_hideTravelOverlay();_setInfoBtns(false);if(typeof vToast==='function')vToast('Sessão expirada. Retornando...','warn');setTimeout(function(){_transitionToGame();},1200);return Promise.reject({_handled:true});}if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}).then(d=>{if(!d)return;console.log('[NAVIGATE] response type=%s hasUrl=%s hasError=%s',type,!!d.url,!!d.error);if(d.error){console.warn('[NAVIGATE] travel_api_error:',d.error);_hideTravelOverlay();_navSent=false;clearTimeout(_navSentTimer);_setInfoBtns(false);_showRetryError(d.message||d.error,type,target,flags);return;}if(d.status==='displaced'){if(window.SessionHeartbeat)SessionHeartbeat.handleDisplaced(d.device||'',d.from_device||'');_navSent=false;clearTimeout(_navSentTimer);_hideTravelOverlay();_setInfoBtns(false);return;}if(d.type==='travel_combat'){console.warn('[NAVIGATE] travel_combat — showing journal then combat');if(d.travel_log&&d.travel_log.length>0&&d.url){_showTravelJournal(d.travel_log,d.url);return;}if(d.url){window.__valdoria_transitioning=true;valdoriaSpaNav(d.url);return;}_transitionToGame();return;}if(d.type==='exhaustion_death'){console.warn('[NAVIGATE] exhaustion_death — showing journal then returning to game');if(d.travel_log&&d.travel_log.length>0){var _gameUrl=window.location.href.replace(/\/navigate\/.*/,'')+'/app.html?route=game&token='+S.token+'&api='+encodeURIComponent(S.api)+'&uid='+S.uid+'&return=game&v=1';_showTravelJournal(d.travel_log,_gameUrl);return;}_transitionToGame();return;}if(d.url&&(type==='travel'||type==='return')){console.info('[NAVIGATE] travel_complete type=%s target=%s hasJournal=%s',type,target||'(none)',!!(d.travel_log&&d.travel_log.length));if(d.travel_log&&d.travel_log.length>0){_showTravelJournal(d.travel_log,d.url);return;}_hideTravelOverlay();window.__valdoria_transitioning=true;valdoriaSpaNav(d.url);return;}
console.warn('[NAVIGATE] no URL in response for type=%s — falling through to _transitionToGame',type);if(window._loadDbg)_loadDbg("navSent unlocked (success)");_transitionToGame();}).catch(e=>{if(e&&e._handled)return;console.error('[NAVIGATE] fetch error:',e);if(typeof _haptic==='function')_haptic('error');_navSent=false;_navSentTs=0;clearTimeout(_navSentTimer);if(window._loadDbg)_loadDbg('navSent unlocked (error)');_hideTravelOverlay();_setInfoBtns(false);_showRetryError('Erro ao viajar: '+e.message,type,target,flags);});}
function _showRetryError(msg,type,target,flags){vPopup.show({header:'⚠️ Erro de Viagem',body:'<div style="text-align:center;color:var(--v-text-dim);font-size:var(--v-font-sm)">'+vEsc(msg)+'</div>',actions:[{label:'Tentar Novamente',cls:'v-popup-btn v-popup-btn--primary',action:'retry'},{label:'Cancelar',cls:'v-popup-btn v-popup-btn--secondary',action:'cancel'}],onAction:function(a){if(a==='retry'){vPopup.hide();finishNavigation(type,target,flags);return true;}if(a==='cancel'){vPopup.hide();return true;}},closeOnOutside:true});}
function _showTravelJournal(log,redirectUrl){_hideTravelOverlay();var _hasDeath=log.some(function(e){return e.type==='exhaustion_death';});
/* --- Compact consecutive safe passages --- */
var _SAFE_TYPES={'safe':1,'forced_march_ok':1,'weather_save_ok':1};var compacted=[];var safeRun=0;for(var _ci=0;_ci<log.length;_ci++){if(_SAFE_TYPES[log[_ci].type]){safeRun++;continue;}if(safeRun>0){compacted.push(safeRun===1?{type:'safe',icon:'\u2714\ufe0f',text:'Trecho seguro',detail:'',_compact:true}:{type:'safe',icon:'\u2714\ufe0f',text:safeRun+' trechos seguros',detail:'',_group:true});safeRun=0;}compacted.push(log[_ci]);}if(safeRun>0){compacted.push(safeRun===1?{type:'safe',icon:'\u2714\ufe0f',text:'Trecho seguro',detail:'',_compact:true}:{type:'safe',icon:'\u2714\ufe0f',text:safeRun+' trechos seguros',detail:'',_group:true});}
/* --- Stats --- */
var _xpT=0,_gpT=0,_hpL=0,_safes=0,_enc=0,_disc=0;for(var _si=0;_si<log.length;_si++){var _st=log[_si].type;if(log[_si].xp)_xpT+=log[_si].xp;if(log[_si].gp)_gpT+=log[_si].gp;if(log[_si].hp_lost)_hpL+=log[_si].hp_lost;if(_SAFE_TYPES[_st])_safes++;if(_st==='encounter')_enc++;if(_st==='arrival_new'||_st==='discovery'||_st==='cartograph_ok')_disc++;}
/* --- Paginate: max 5 events per page --- */
var PER_PAGE=5;var pages=[];for(var _pi=0;_pi<compacted.length;_pi+=PER_PAGE){pages.push(compacted.slice(_pi,_pi+PER_PAGE));}if(pages.length===0)pages.push([]);var totalPages=pages.length;
/* --- Build HTML --- */
var bodyHtml='';
var _evData=[];var _evIdx=0;for(var pg=0;pg<totalPages;pg++){bodyHtml+='<div class="tj-page'+(pg===0?' tj-page--active':'')+'" data-page="'+pg+'"><div class="tj-timeline">';var items=pages[pg];for(var i=0;i<items.length;i++){var e=items[i];var _cls='tj-event';if(e._compact)_cls+=' tj-event--compact';if(e._group)_cls+=' tj-event--group';var _hasDetail=e.detail&&e.detail.length>0&&!e._compact&&!e._group;if(_hasDetail){_evData.push({icon:e.icon,text:e.text,detail:e.detail});}bodyHtml+='<div class="'+_cls+'"><div class="tj-dot tj-dot--'+vEsc(e.type)+'">'+vEsc(e.icon)+'</div><div class="tj-card tj-card--'+vEsc(e.type)+'"'+(_hasDetail?' data-ev-idx="'+(_evData.length-1)+'"':'')+'><div class="tj-title">'+vEsc(e.text)+'</div>'+(_hasDetail?'<div class="tj-expand">\u25b8 Ver detalhes</div>':'')+'</div></div>';}bodyHtml+='</div></div>';}
/* --- Summary --- */
bodyHtml+='<div class="tj-summary" data-summary>';bodyHtml+='<div class="tj-stat"><div class="tj-stat-val">'+log.length+'</div><div class="tj-stat-label">Eventos</div></div><div class="tj-stat-sep"></div>';if(_xpT>0)bodyHtml+='<div class="tj-stat"><div class="tj-stat-val tj-stat-val--xp">+'+_xpT+'</div><div class="tj-stat-label">XP</div></div>';if(_gpT>0)bodyHtml+='<div class="tj-stat"><div class="tj-stat-val tj-stat-val--gp">+'+_gpT+'</div><div class="tj-stat-label">Ouro</div></div>';if(_hpL>0)bodyHtml+='<div class="tj-stat"><div class="tj-stat-val tj-stat-val--hp">-'+_hpL+'</div><div class="tj-stat-label">HP</div></div>';if(!_xpT&&!_gpT&&!_hpL){if(_disc>0)bodyHtml+='<div class="tj-stat"><div class="tj-stat-val">'+_disc+'</div><div class="tj-stat-label">Descobertas</div></div>';if(_enc>0)bodyHtml+='<div class="tj-stat"><div class="tj-stat-val">'+_enc+'</div><div class="tj-stat-label">Encontros</div></div>';if(_safes>0)bodyHtml+='<div class="tj-stat"><div class="tj-stat-val">'+_safes+'</div><div class="tj-stat-label">Seguros</div></div>';}bodyHtml+='</div>';
/* --- Pager (only if >1 page) --- */
if(totalPages>1){bodyHtml+='<div class="tj-pager" data-pager><button class="tj-pager-btn" data-pg-prev disabled>\u25c2</button><div class="tj-pager-dots">';for(var _di=0;_di<totalPages;_di++){bodyHtml+='<div class="tj-pager-dot'+(_di===0?' active':'')+'"></div>';}bodyHtml+='</div><button class="tj-pager-btn" data-pg-next>\u25b8</button></div>';}
/* ornament removed — header ::before handles it */
/* --- Show popup --- */
var _journalDone=false;var _btnLabel=_hasDeath?'Despertar no Templo \ud83c\udfdb\ufe0f':'Continuar Viagem \u27a1';var _curPage=0;
vPopup.show({id:'v-popup-overlay',header:'\ud83d\udcdc Di\u00e1rio de Viagem',body:bodyHtml,actions:[{label:_btnLabel,action:'continue_travel',cls:'v-popup-btn v-popup-btn--primary'}],onAction:function(action){if(action==='continue_travel'){if(_journalDone)return;_journalDone=true;var _rl=[];for(var _ri=0;_ri<log.length;_ri++){if(log[_ri].type==='arrival_new'&&log[_ri].loc_id)_rl.push(log[_ri].loc_id);}if(_rl.length)try{localStorage.setItem('valdoria_reveal_locs',JSON.stringify(_rl));}catch(e){console.warn('[NAVIGATE]',e);}window.__valdoria_transitioning=true;if(typeof redirectUrl==='function'){redirectUrl();}else{valdoriaSpaNav(redirectUrl);}return true;}},closeOnOutside:false,onReady:function(overlay){overlay.setAttribute('data-journal','1');
/* Detail popup handlers — open stacked popup */
overlay.querySelectorAll('.tj-expand').forEach(function(el){el.addEventListener('click',function(){var card=el.closest('.tj-card');var idx=parseInt(card.getAttribute('data-ev-idx'),10);if(isNaN(idx)||!_evData[idx])return;var ev=_evData[idx];var detailOverlay=document.getElementById('tj-detail-overlay');vPopup.show({id:'tj-detail-overlay',header:ev.icon+' '+ev.text,body:'<div class="tj-detail-popup"><div class="tj-detail-icon">'+vEsc(ev.icon)+'</div><div class="tj-detail-title">'+vEsc(ev.text)+'</div><div class="tj-detail-sep"></div><div class="tj-detail-text">'+vEsc(ev.detail)+'</div></div>',actions:[{label:'Voltar ao Di\u00e1rio',action:'back',cls:'v-popup-btn v-popup-btn--cancel'}],onAction:function(a){if(a==='back'){vPopup.hide();return true;}}});});});
/* Pager handlers */
var _pages=overlay.querySelectorAll('.tj-page');var _dots=overlay.querySelectorAll('.tj-pager-dot');var _prev=overlay.querySelector('[data-pg-prev]');var _next=overlay.querySelector('[data-pg-next]');function _goPage(n){if(n<0||n>=totalPages)return;_curPage=n;_pages.forEach(function(p,idx){p.classList.toggle('tj-page--active',idx===n);});_dots.forEach(function(d,idx){d.classList.toggle('active',idx===n);});if(_prev)_prev.disabled=(n===0);if(_next)_next.disabled=(n===totalPages-1);/* Reveal events on new page */var newEvents=_pages[n].querySelectorAll('.tj-event');newEvents.forEach(function(el,idx){el.classList.remove('tj-revealed');setTimeout(function(){el.classList.add('tj-revealed');},80+idx*120);});}if(_prev)_prev.addEventListener('click',function(){_goPage(_curPage-1);});if(_next)_next.addEventListener('click',function(){_goPage(_curPage+1);});
/* Initial reveal animation */
var firstEvents=overlay.querySelectorAll('.tj-page--active .tj-event');var summary=overlay.querySelector('[data-summary]');var continueBtn=overlay.querySelector('[data-action="continue_travel"]');if(continueBtn)continueBtn.style.opacity='0';var _stagger=Math.min(280,1400/Math.max(1,firstEvents.length));firstEvents.forEach(function(el,idx){setTimeout(function(){el.classList.add('tj-revealed');},200+idx*_stagger);});var totalDelay=Math.max(2000,200+firstEvents.length*_stagger+400);if(summary){setTimeout(function(){summary.classList.add('tj-revealed');},totalDelay-300);}setTimeout(function(){if(continueBtn){continueBtn.style.transition='opacity var(--v-transition-base)';continueBtn.style.opacity='1';}},totalDelay);}});}
function _showTravelOverlay(type,target){let overlay=document.getElementById('travel-overlay');if(!overlay){overlay=document.createElement('div');overlay.id='travel-overlay';overlay.className='travel-overlay';document.body.appendChild(overlay);}
const loc=target?S.locations[target]:null;const biome=loc?(BIOME_INFO[loc.b]||BIOME_INFO.plains):null;const danger=loc?.d||0;const edgeDist=target?getConnectionDistance(S.currentLoc,target):0;const compassSvg='<svg class="travel-overlay-compass-svg" viewBox="0 0 48 48"><circle cx="24" cy="24" r="20" fill="none" stroke="#c4953a" stroke-width="1.5" stroke-opacity="0.4"/><polygon points="24,6 27,22 24,20 21,22" fill="#c4953a" fill-opacity="0.8"/><polygon points="24,42 21,26 24,28 27,26" fill="#8a6a3a" fill-opacity="0.6"/><circle cx="24" cy="24" r="2" fill="#c4953a"/></svg>';let text='Preparando...';let biomeText='';let dangerText='';if(type==='travel'&&loc){text='Viajando para '+(loc.n||'destino')+'...';if(biome)biomeText=biome.label+(edgeDist>0?' \u00b7 '+edgeDist+' turno'+(edgeDist!==1?'s':''):'');if(danger>=7)dangerText='\u2620\ufe0f Perigo extremo no caminho';else if(danger>=5)dangerText='\u26a0\ufe0f Alta chance de encontros';}else if(type==='return'){text='Retornando...';}else if(type==='camp'){text='Montando acampamento...';}else if(type==='explore'){text='Explorando a regi\u00e3o...';}
overlay.innerHTML='<div class="travel-overlay-content">'+
compassSvg+'<div class="travel-overlay-text">'+vEsc(text)+'</div>'+
(biomeText?'<div class="travel-overlay-biome">'+vEsc(biomeText)+'</div>':'')+
(dangerText?'<div class="travel-overlay-danger">'+vEsc(dangerText)+'</div>':'')+'<div class="travel-overlay-progress"><div class="travel-overlay-progress-fill" id="travel-progress-fill"></div></div>'+'<div class="travel-overlay-dots"><span>.</span><span>.</span><span>.</span></div>'+'</div>'+'<button class="v-skip-btn" id="travel-skip">Pular >></button>';requestAnimationFrame(()=>{overlay.classList.add('visible');const fill=document.getElementById('travel-progress-fill');if(fill){requestAnimationFrame(()=>{fill.style.transition='width 3s linear';fill.style.width='100%';});}});var _travelSkip=document.getElementById('travel-skip');if(_travelSkip){setTimeout(function(){if(_travelSkip)_travelSkip.classList.add('visible');},3000);_travelSkip.onclick=function(){_hideTravelOverlay();};}}
function _hideTravelOverlay(){const overlay=document.getElementById('travel-overlay');if(overlay){console.log('[NAVIGATE] hideTravelOverlay — removing overlay');var skipBtn=overlay.querySelector('.v-skip-btn');if(skipBtn)skipBtn.classList.remove('visible');overlay.classList.remove('visible');setTimeout(function(){if(overlay.parentNode){overlay.parentNode.removeChild(overlay);console.log('[NAVIGATE] travel overlay removed from DOM');}},400);}}
function handleReturn(){finishNavigation('return');}
function handleClose(){_transitionToGame();}
async function _transitionToGame(){if(!S.api||!S.token){window.__valdoria_transitioning=true;try{tg?.close();}catch(e){console.warn('[NAVIGATE] Close:',e);}return;}
var _transSafety=setTimeout(function(){console.warn('[NAVIGATE] transition safety timeout');_hideTravelOverlay();_navSent=false;clearTimeout(_navSentTimer);},8000);
var h={'Content-Type':'application/json','Authorization':'Bearer '+S.token};if(window.Telegram?.WebApp?.initData)h['X-Telegram-Init-Data']=Telegram.WebApp.initData;h['X-Idempotency-Key']=crypto.randomUUID();try{var r=await fetchT(S.api+'/api/webapp/transition',{method:'POST',headers:h,body:JSON.stringify({from:'navigate',to:(S.returnTo||'game'),user_id:S.uid,payload:{}})});var d=await r.json();window.__valdoria_transitioning=true;if(d.url){clearTimeout(_transSafety);clearTimeout(_navSentTimer);_navSent=false;valdoriaSpaNav(d.url);return;}}catch(e){console.error('[NAVIGATE] transition error:',e);clearTimeout(_transSafety);_hideTravelOverlay();_navSent=false;clearTimeout(_navSentTimer);}
clearTimeout(_transSafety);var base=window.location.href.replace(/\/navigate\/.*/,'');window.__valdoria_transitioning=true;valdoriaSpaNav(base+'/app.html?route=game&token='+S.token+'&api='+encodeURIComponent(S.api)+'&uid='+S.uid+'&return=game&v=1');}
window.addEventListener('pagehide',function(){if(typeof _animFrame!=='undefined'&&_animFrame){cancelAnimationFrame(_animFrame);_animFrame=null;}clearTimeout(_navSentTimer);if(typeof ValdoriaAudio!=='undefined'&&ValdoriaAudio.getCurrentTrack){try{var _trk=ValdoriaAudio.getCurrentTrack();if(_trk)localStorage.setItem('valdoria_audio_resume',_trk);}catch(e){}}});
if(!window.__spaRouteName){document.addEventListener('DOMContentLoaded',initAsync);}