var _spaP=window.__spaRouteParams||{};var _diceDetail=(function(){var t=window._valdoriaPerformanceTier||'full';return t==='lite'?0:t==='medium'?1:2;})();const tg=window.Telegram&&window.Telegram.WebApp;const _vBg=getComputedStyle(document.documentElement).getPropertyValue('--v-bg').trim()||'#2a2420';if(tg){tg.ready();tg.expand();tg.setHeaderColor(_vBg);tg.setBackgroundColor(_vBg);if(tg.BackButton){tg.BackButton.show();tg.BackButton.onClick(()=>{try{tg.close();}catch(e){console.warn('[DICE] tg.close:',e);}});}}
if(typeof ValdoriaAudio!=='undefined')ValdoriaAudio.play('tavern');
const params=new URLSearchParams(window.location.search);if(_spaP){Object.keys(_spaP).forEach(function(k){if(!params.has(k))params.set(k,_spaP[k]);});}
const MODE=params.get('mode')||'free';const GAME_FORMULA=params.get('formula');const GAME_RESULT=params.get('r')?parseInt(decodeBase64Utf8(params.get('r'))):null;const GAME_RAW=params.get('raw')?JSON.parse(decodeBase64Utf8(params.get('raw'))):null;const GAME_LABEL=params.get('label')?decodeURIComponent(params.get('label')):'';const GAME_TYPE=params.get('type')||'';const GAME_DC=params.get('dc')?parseInt(params.get('dc')):null;const GAME_TOKEN=params.get('token')||'';let currentDie='d20';let currentMod=0;let isRolling=false;let showingResult=false;let rollHistory=[];const container=document.getElementById('canvasContainer');const W=260,H=260;const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(40,W/H,0.1,100);camera.position.set(0,3.5,6);camera.lookAt(0,0,0);const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});renderer.setSize(W,H);renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;container.appendChild(renderer.domElement);const ambient=new THREE.AmbientLight(0xffffff,0.5);scene.add(ambient);const keyLight=new THREE.DirectionalLight(0xfff5e0,1.2);keyLight.position.set(3,6,4);keyLight.castShadow=true;keyLight.shadow.mapSize.set(512,512);keyLight.shadow.camera.near=0.5;keyLight.shadow.camera.far=20;keyLight.shadow.camera.left=-3;keyLight.shadow.camera.right=3;keyLight.shadow.camera.top=3;keyLight.shadow.camera.bottom=-3;scene.add(keyLight);const fillLight=new THREE.DirectionalLight(0xc8d8ff,0.3);fillLight.position.set(-3,2,-2);scene.add(fillLight);const rimLight=new THREE.PointLight(0xd4af37,0.4,10);rimLight.position.set(0,1,-4);scene.add(rimLight);const groundGeo=new THREE.PlaneGeometry(10,10);const groundMat=new THREE.ShadowMaterial({opacity:0.35});const ground=new THREE.Mesh(groundGeo,groundMat);ground.rotation.x=-Math.PI/2;ground.position.y=-1.5;ground.receiveShadow=true;scene.add(ground);let dieMesh=null;let idleTime=0;let animFrame=null;let rollAnim=null;const _cs=getComputedStyle(document.documentElement);const _cssVar=(v)=>_cs.getPropertyValue(v).trim();const V_GOLD_HEX=_cssVar('--v-gold')||'#c4953a';const V_SUCCESS_HEX=_cssVar('--v-success')||'#4caf50';const V_DANGER_HEX=_cssVar('--v-danger')||'#e74c3c';const FACE_COLOR=0x2e2218;const EDGE_COLOR=parseInt(V_GOLD_HEX.replace('#',''),16);const NUM_COLOR=V_GOLD_HEX;const FACE_COLOR_HEX='#2e2218';function createDieMesh(dieType){if(dieMesh){scene.remove(dieMesh);dieMesh=null;}
const builders={d4:buildD4,d6:buildD6,d8:buildD8,d10:buildD10,d12:buildD12,d20:buildD20};const builder=builders[dieType]||builders.d20;dieMesh=builder();dieMesh.castShadow=true;dieMesh.position.set(0,0,0);scene.add(dieMesh);return dieMesh;}
function makeNumberTexture(num,shape,size,fontScale){size=size||256;fontScale=fontScale||1.0;const c=document.createElement('canvas');c.width=size;c.height=size;const ctx=c.getContext('2d');ctx.fillStyle=FACE_COLOR_HEX;ctx.fillRect(0,0,size,size);if(_diceDetail>=1){const grad=ctx.createRadialGradient(size/2,size/2,0,size/2,size/2,size/2);grad.addColorStop(0,'rgba(80,64,48,0.3)');grad.addColorStop(1,'rgba(50,40,28,0.3)');ctx.fillStyle=grad;ctx.fillRect(0,0,size,size);}const text=String(num);const fontSize=(text.length>1?size*0.32:size*0.42)*fontScale;ctx.font=`bold ${fontSize}px "Cinzel", Georgia, serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.shadowColor='rgba(212,175,55,0.6)';ctx.shadowBlur=size*0.08;ctx.fillStyle=NUM_COLOR;ctx.fillText(text,size/2,size/2);if(num===6||num===9){const w=ctx.measureText(text).width;ctx.fillRect(size/2-w/2,size/2+fontSize*0.38,w,fontSize*0.06);}
const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;return tex;}
function makeFaceMaterial(num,shape,fontScale){return new THREE.MeshStandardMaterial({map:makeNumberTexture(num,shape,undefined,fontScale),metalness:0.15,roughness:0.55,side:THREE.DoubleSide,});}
function addEdges(mesh,geo,threshold){const edges=new THREE.EdgesGeometry(geo,threshold!==undefined?threshold:15);const line=new THREE.LineSegments(edges,new THREE.LineBasicMaterial({color:EDGE_COLOR,transparent:true,opacity:0.35}));mesh.add(line);}
function computePerFaceUVs(geo,vertsPerFace){const pos=geo.attributes.position;const totalVerts=pos.count;const faceCount=totalVerts/vertsPerFace;const uvs=new Float32Array(totalVerts*2);for(let f=0;f<faceCount;f++){const base=f*vertsPerFace;const verts=[];const center=new THREE.Vector3();for(let j=0;j<vertsPerFace;j++){const v=new THREE.Vector3().fromBufferAttribute(pos,base+j);verts.push(v);center.add(v);}
center.divideScalar(vertsPerFace);const ab=new THREE.Vector3().subVectors(verts[1],verts[0]);const ac=new THREE.Vector3().subVectors(verts[2],verts[0]);const normal=new THREE.Vector3().crossVectors(ab,ac).normalize();const tangent=new THREE.Vector3().subVectors(verts[0],center);tangent.sub(normal.clone().multiplyScalar(tangent.dot(normal)));tangent.normalize();const bitangent=new THREE.Vector3().crossVectors(normal,tangent).normalize();const proj=verts.map(v=>{const d=new THREE.Vector3().subVectors(v,center);return{u:d.dot(tangent),v:d.dot(bitangent)};});let maxExt=0;for(const p of proj){maxExt=Math.max(maxExt,Math.abs(p.u),Math.abs(p.v));}
maxExt=maxExt||1;const halfRange=0.42;const scale=halfRange/maxExt;for(let j=0;j<vertsPerFace;j++){uvs[(base+j)*2]=0.5+proj[j].u*scale;uvs[(base+j)*2+1]=0.5+proj[j].v*scale;}}
geo.setAttribute('uv',new THREE.Float32BufferAttribute(uvs,2));}
function buildPolyhedron(geo,faceCount,vertsPerFace,numbers,shapeHint,fontScale){const nonIndexed=geo.toNonIndexed();nonIndexed.clearGroups();for(let i=0;i<faceCount;i++){nonIndexed.addGroup(i*vertsPerFace,vertsPerFace,i);}
computePerFaceUVs(nonIndexed,vertsPerFace);const pos=nonIndexed.attributes.position;const normals=[];for(let i=0;i<faceCount;i++){const base=i*vertsPerFace;const a=new THREE.Vector3().fromBufferAttribute(pos,base);const b=new THREE.Vector3().fromBufferAttribute(pos,base+1);const c=new THREE.Vector3().fromBufferAttribute(pos,base+2);const ab=new THREE.Vector3().subVectors(b,a);const ac=new THREE.Vector3().subVectors(c,a);normals.push(new THREE.Vector3().crossVectors(ab,ac).normalize());}
const mats=numbers.map((n,i)=>{let hint=shapeHint;if(hint==='tri-auto')hint=normals[i].y>0?'tri-up':'tri-down';return makeFaceMaterial(n,hint,fontScale);});const mesh=new THREE.Mesh(nonIndexed,mats);addEdges(mesh,nonIndexed);mesh.userData={type:null,numbers,normals};return mesh;}
const D6_NUMBERS=[3,4,1,6,2,5];const D6_NORMALS=[new THREE.Vector3(1,0,0),new THREE.Vector3(-1,0,0),new THREE.Vector3(0,1,0),new THREE.Vector3(0,-1,0),new THREE.Vector3(0,0,1),new THREE.Vector3(0,0,-1),];function buildD6(){const geo=new THREE.BoxGeometry(1.2,1.2,1.2);const mats=D6_NUMBERS.map(n=>makeFaceMaterial(n,'square'));const mesh=new THREE.Mesh(geo,mats);addEdges(mesh,geo);mesh.userData={type:'d6',numbers:D6_NUMBERS,normals:D6_NORMALS};return mesh;}
function buildD4(){const geo=new THREE.TetrahedronGeometry(1.0);const numbers=[1,2,3,4];const mesh=buildPolyhedron(geo,4,3,numbers,'tri-auto',0.65);mesh.userData.type='d4';return mesh;}
function buildD8(){const geo=new THREE.OctahedronGeometry(1.0);const numbers=[1,2,3,4,5,6,7,8];const mesh=buildPolyhedron(geo,8,3,numbers,'tri-auto');mesh.userData.type='d8';return mesh;}
function buildD20(){const R=1.0;let geo=new THREE.IcosahedronGeometry(R,0);geo=geo.toNonIndexed();const pos=geo.attributes.position;const colorsArr=new Float32Array(pos.count*3);const cLow=new THREE.Color(0x2a1e10);const cHigh=new THREE.Color(0xc4953a);const cTmp=new THREE.Color();for(let i=0;i<pos.count;i++){const t=(pos.getY(i)/R+1)/2;cTmp.copy(cLow).lerp(cHigh,t);colorsArr[i*3]=cTmp.r;colorsArr[i*3+1]=cTmp.g;colorsArr[i*3+2]=cTmp.b;}
geo.setAttribute('color',new THREE.BufferAttribute(colorsArr,3));const fNormals=[];const fCenters=[];for(let f=0;f<20;f++){const i=f*3;const a=new THREE.Vector3().fromBufferAttribute(pos,i);const b=new THREE.Vector3().fromBufferAttribute(pos,i+1);const c=new THREE.Vector3().fromBufferAttribute(pos,i+2);const center=a.clone().add(b).add(c).divideScalar(3);const normal=new THREE.Vector3().crossVectors(b.clone().sub(a),c.clone().sub(a)).normalize();if(normal.dot(center)<0)normal.negate();fCenters.push(center);fNormals.push(normal);}
const bodyMat=new THREE.MeshPhongMaterial({vertexColors:true,shininess:100,specular:new THREE.Color(0x554433),flatShading:true,});const mesh=new THREE.Mesh(geo,bodyMat);const edgeGeo=new THREE.EdgesGeometry(new THREE.IcosahedronGeometry(R*1.003,0));mesh.add(new THREE.LineSegments(edgeGeo,new THREE.LineBasicMaterial({color:EDGE_COLOR,transparent:true,opacity:0.5})));for(let i=0;i<20;i++){const num=i+1;const s=256;const cv=document.createElement('canvas');cv.width=s;cv.height=s;const ctx=cv.getContext('2d');ctx.clearRect(0,0,s,s);const fontSize=num>=10?s*0.42:s*0.52;ctx.font=`bold ${fontSize}px "Cinzel", Georgia, serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.strokeStyle='rgba(0,0,0,0.7)';ctx.lineWidth=8;ctx.lineJoin='round';ctx.strokeText(String(num),s/2,s/2);ctx.shadowColor='rgba(212,175,55,0.5)';ctx.shadowBlur=s*0.06;ctx.fillStyle='#fff8e0';ctx.fillText(String(num),s/2,s/2);if(num===6||num===9){const w=ctx.measureText(String(num)).width;ctx.fillRect(s/2-w/2,s/2+fontSize*0.38,w,fontSize*0.06);}
const tex=new THREE.CanvasTexture(cv);const mat=new THREE.MeshBasicMaterial({map:tex,transparent:true,depthWrite:false,side:THREE.DoubleSide,});const plane=new THREE.Mesh(new THREE.PlaneGeometry(0.38,0.38),mat);const normal=fNormals[i];const center=fCenters[i];plane.position.copy(center.clone().add(normal.clone().multiplyScalar(0.008)));const worldUp=new THREE.Vector3(0,1,0);let faceUp=worldUp.clone().addScaledVector(normal,-worldUp.dot(normal));if(faceUp.lengthSq()<0.001){const worldRight=new THREE.Vector3(1,0,0);faceUp=worldRight.clone().addScaledVector(normal,-worldRight.dot(normal));}
faceUp.normalize();const faceRight=new THREE.Vector3().crossVectors(faceUp,normal).normalize();plane.rotation.setFromRotationMatrix(new THREE.Matrix4().makeBasis(faceRight,faceUp,normal));mesh.add(plane);}
const numbers=[];for(let i=1;i<=20;i++)numbers.push(i);mesh.userData={type:'d20',numbers,normals:fNormals};mesh.castShadow=true;return mesh;}
function buildD12(){const geo=new THREE.DodecahedronGeometry(1.0);const numbers=[];for(let i=1;i<=12;i++)numbers.push(i);const mesh=buildPolyhedron(geo,12,9,numbers,'penta');mesh.userData.type='d12';return mesh;}
function buildD10(){const scale=1.15;const step=Math.PI*2/10;const hOff=0.105;const rawVerts=[];for(let i=0;i<10;i++){const angle=i*step;rawVerts.push(new THREE.Vector3(Math.cos(angle),Math.sin(angle),hOff*(i%2?1:-1)).normalize().multiplyScalar(scale));}
rawVerts.push(new THREE.Vector3(0,0,-1).multiplyScalar(scale));rawVerts.push(new THREE.Vector3(0,0,1).multiplyScalar(scale));const kiteFaces=[[5,7,11,0],[4,2,10,1],[1,3,11,2],[0,8,10,3],[7,9,11,4],[8,6,10,5],[9,1,11,6],[2,0,10,7],[3,5,11,8],[6,4,10,9],];const equatTris=[[1,0,2],[1,2,3],[3,2,4],[3,4,5],[5,4,6],[5,6,7],[7,6,8],[7,8,9],[9,8,0],[9,0,1],];const positions=[],uvArr=[],normArr=[];const groups=[];let offset=0;const af=Math.PI*6/5;const kiteVerts=4;const kiteAngleStep=Math.PI*2/kiteVerts;function polyUV(j){const angle=kiteAngleStep*j+af;return[(Math.cos(angle)+1)/2,(Math.sin(angle)+1)/2];}
const kUV0=polyUV(0),kUV1=polyUV(1),kUV2=polyUV(2),kUV3=polyUV(3);const faceNormals=[];const faceNumbers=[];kiteFaces.forEach((face,fi)=>{const[a,b,pole,num]=face;const va=rawVerts[a],vb=rawVerts[b],vc=rawVerts[pole];positions.push(va.x,va.y,va.z,vb.x,vb.y,vb.z,vc.x,vc.y,vc.z);const e1=new THREE.Vector3().subVectors(vb,va);const e2=new THREE.Vector3().subVectors(vc,va);const n=new THREE.Vector3().crossVectors(e1,e2).normalize();const center=new THREE.Vector3().addVectors(va,vb).add(vc).divideScalar(3);if(n.dot(center)<0)n.negate();normArr.push(n.x,n.y,n.z,n.x,n.y,n.z,n.x,n.y,n.z);const triAngle=Math.PI*2/3;for(let j=0;j<3;j++){const ang=triAngle*j+af;uvArr.push((Math.cos(ang)+1)/2,(Math.sin(ang)+1)/2);}
groups.push({start:offset,count:3,materialIndex:fi});offset+=3;faceNormals.push(n);faceNumbers.push(num);});equatTris.forEach(tri=>{const[a,b,c]=tri;const va=rawVerts[a],vb=rawVerts[b],vc=rawVerts[c];positions.push(va.x,va.y,va.z,vb.x,vb.y,vb.z,vc.x,vc.y,vc.z);const e1=new THREE.Vector3().subVectors(vb,va);const e2=new THREE.Vector3().subVectors(vc,va);const n=new THREE.Vector3().crossVectors(e1,e2).normalize();const center=new THREE.Vector3().addVectors(va,vb).add(vc).divideScalar(3);if(n.dot(center)<0)n.negate();normArr.push(n.x,n.y,n.z,n.x,n.y,n.z,n.x,n.y,n.z);uvArr.push(0,0,1,0,0.5,1);groups.push({start:offset,count:3,materialIndex:10});offset+=3;});const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geo.setAttribute('normal',new THREE.Float32BufferAttribute(normArr,3));geo.setAttribute('uv',new THREE.Float32BufferAttribute(uvArr,2));groups.forEach(g=>geo.addGroup(g.start,g.count,g.materialIndex));const mats=faceNumbers.map(n=>makeFaceMaterial(n,'kite',0.8));mats.push(new THREE.MeshStandardMaterial({color:FACE_COLOR,metalness:0.15,roughness:0.55,side:THREE.DoubleSide}));const mesh=new THREE.Mesh(geo,mats);addEdges(mesh,geo,20);mesh.userData={type:'d10',numbers:faceNumbers,normals:faceNormals};return mesh;}
function getTargetQuaternion(mesh,resultValue){const{numbers,normals}=mesh.userData;let faceIdx=numbers.indexOf(resultValue);if(faceIdx===-1)faceIdx=0;const faceNormal=normals[faceIdx].clone();const targetDir=new THREE.Vector3(0,0.85,0.52).normalize();const quat=new THREE.Quaternion();quat.setFromUnitVectors(faceNormal,targetDir);return quat;}
function animate(time){animFrame=requestAnimationFrame(animate);if(rollAnim){updateRollAnimation(time);}else if(showingResult){}else if(dieMesh){idleTime+=0.012;dieMesh.rotation.y=idleTime*0.3;dieMesh.rotation.x=Math.sin(idleTime*0.5)*0.12-0.2;dieMesh.position.y=Math.sin(idleTime*0.8)*0.08;}
renderer.render(scene,camera);}
function updateRollAnimation(time){const elapsed=time-rollAnim.startTime;const dur=rollAnim.duration;const t=Math.min(elapsed/dur,1);const mesh=dieMesh;if(!mesh)return;const ra=rollAnim;const elapsedSec=elapsed/1000;function computeSpinQ(tSec){const sa=(ra.initialSpin/ra.spinDecay)*(1-Math.exp(-ra.spinDecay*tSec));const pq=new THREE.Quaternion().setFromEuler(new THREE.Euler(ra.spinDirX*ra.spinScaleX*sa,ra.spinDirY*ra.spinScaleY*sa*1.1,ra.spinDirZ*ra.spinScaleZ*sa*0.8));const tsa=(ra.tumbleSpeed/ra.tumbleDecay)*(1-Math.exp(-ra.tumbleDecay*tSec));const pa=tSec*ra.precessionSpeed;const cta=ra.tumbleAxis.clone().applyAxisAngle(ra.precessionAxis,pa);const tq=new THREE.Quaternion().setFromAxisAngle(cta,tsa);return pq.multiply(tq);}
if(elapsedSec<ra.tThrowEnd){const tl=elapsedSec;const y=ra.v0_throw*tl-0.5*ra.G*tl*tl;const x=ra.vx0*tl;const z=ra.vz0*tl;mesh.position.set(clampPos(x),Math.max(0,y),clampPos(z));mesh.quaternion.copy(computeSpinQ(elapsedSec));}else if(elapsedSec<ra.tB1End){const tl=elapsedSec-ra.tThrowEnd;const y=ra.v0_b1*tl-0.5*ra.G*tl*tl;const x=ra.x_at_b1+ra.vx1*tl;const z=ra.z_at_b1+ra.vz1*tl;mesh.position.set(clampPos(x),Math.max(0,y),clampPos(z));mesh.quaternion.copy(computeSpinQ(elapsedSec));if(!ra.bounce1Haptic){ra.bounce1Haptic=true;haptic('light');}}else if(elapsedSec<ra.tB2End){const tl=elapsedSec-ra.tB1End;const y=ra.v0_b2*tl-0.5*ra.G*tl*tl;const x=ra.x_at_b2+ra.vx2*tl;const z=ra.z_at_b2+ra.vz2*tl;mesh.position.set(clampPos(x),Math.max(0,y),clampPos(z));mesh.quaternion.copy(computeSpinQ(elapsedSec));if(!ra.bounce2Haptic){ra.bounce2Haptic=true;haptic('light');}}else{const tl=elapsedSec-ra.tB2End;const p=Math.min(tl/ra.settleTime,1);const slerpT=Math.min(1,p*1.5);const easeSlerpT=1-Math.pow(1-slerpT,3);const posEase=1-Math.pow(1-p,3);const x=ra.x_at_settle*(1-posEase);const z=ra.z_at_settle*(1-posEase);let y=0;if(p<0.4){y=0.08*Math.exp(-10*p)*Math.abs(Math.sin(p*Math.PI*4));}
mesh.position.set(x,y,z);const currentQ=ra.settleStartQ.clone().slerp(ra.targetQ,easeSlerpT);if(p>0.15&&p<0.95){const wt=p-0.15;const env=Math.exp(-ra.wobbleDamp*wt);const w1=ra.wobbleAmp*env*Math.sin(ra.wobbleFreq*wt*Math.PI*2);const w2=ra.wobbleAmp*0.6*env*Math.sin(ra.wobbleFreq*1.3*wt*Math.PI*2+0.7);currentQ.multiply(new THREE.Quaternion().setFromAxisAngle(ra.wobbleAxis1,w1));currentQ.multiply(new THREE.Quaternion().setFromAxisAngle(ra.wobbleAxis2,w2));}
mesh.quaternion.copy(currentQ);}
const normH=Math.max(0,mesh.position.y)/2.5;ground.material.opacity=0.35-0.25*normH;if(t>=1){mesh.position.set(0,0,0);mesh.quaternion.copy(ra.targetQ);ground.material.opacity=0.35;const onDone=ra.onDone;rollAnim=null;if(onDone)onDone();}}
function dieMax(d){return parseInt(d.replace('d',''));}
function randInt(a,b){return Math.floor(Math.random()*(b-a+1))+a;}
function haptic(s){if(tg&&tg.HapticFeedback)tg.HapticFeedback.impactOccurred(s);}
function clampPos(v){return Math.max(-1.8,Math.min(1.8,v));}
function onDieTap(){if(isRolling)return;isRolling=true;showingResult=false;document.getElementById('tapHint').style.display='none';document.getElementById('btnAction').disabled=true;document.getElementById('resultPanel').classList.remove('visible');const max=dieMax(currentDie);let finalRaw,finalTotal;if(MODE==='game'&&GAME_RESULT!==null){finalTotal=GAME_RESULT;if(GAME_RAW)finalRaw=GAME_RAW;else{const mm=GAME_FORMULA?GAME_FORMULA.match(/[+-]\d+$/):null;finalRaw=[Math.max(1,Math.min(max,finalTotal-(mm?parseInt(mm[0]):0)))];}}else{finalRaw=[randInt(1,max)];finalTotal=finalRaw[0]+currentMod;}
haptic('medium');let resultFaceValue=finalRaw[0];if(currentDie==='d10'){resultFaceValue=(finalRaw[0]-1)%10;}
createDieMesh(currentDie);const targetQ=getTargetQuaternion(dieMesh,resultFaceValue);const G=40;const throwH=2.2+Math.random()*0.6;const v0_throw=Math.sqrt(2*G*throwH);const t_throw=2*v0_throw/G;const e1=0.55+Math.random()*0.15;const v0_b1=e1*v0_throw;const t_b1=2*v0_b1/G;const e2=0.50+Math.random()*0.15;const v0_b2=e2*v0_b1;const t_b2=2*v0_b2/G;const totalAirborne=t_throw+t_b1+t_b2;const settleTime=0.42;const duration=(totalAirborne+settleTime)*1000;const tThrowEnd=t_throw;const tB1End=t_throw+t_b1;const tB2End=totalAirborne;const vx0=(Math.random()-0.5)*6.0;const vz0=(Math.random()-0.5)*2.0;const hFric=0.5+Math.random()*0.2;const x_at_b1=clampPos(vx0*t_throw);const z_at_b1=clampPos(vz0*t_throw);const vx1=vx0*hFric+(Math.random()-0.5)*0.5;const vz1=vz0*hFric+(Math.random()-0.5)*0.3;const x_at_b2=clampPos(x_at_b1+vx1*t_b1);const z_at_b2=clampPos(z_at_b1+vz1*t_b1);const vx2=vx1*hFric+(Math.random()-0.5)*0.3;const vz2=vz1*hFric+(Math.random()-0.5)*0.2;const x_at_settle=clampPos(x_at_b2+vx2*t_b2);const z_at_settle=clampPos(z_at_b2+vz2*t_b2);const dieMult={d4:0.7,d6:0.85,d8:0.95,d10:1.0,d12:1.05,d20:1.1}[currentDie]||1.0;const initialSpin=(10+Math.random()*4)*dieMult;const spinDecay=2.0+Math.random()*0.5;const spinDirX=Math.random()>0.5?1:-1;const spinDirY=Math.random()>0.5?1:-1;const spinDirZ=Math.random()>0.5?1:-1;const spinScaleX=0.8+Math.random()*0.4;const spinScaleY=0.8+Math.random()*0.4;const spinScaleZ=0.5+Math.random()*0.4;const tumbleAxis=new THREE.Vector3(Math.random()-0.5,Math.random()-0.5,Math.random()-0.5).normalize();const tumbleSpeed=3+Math.random()*4;const tumbleDecay=1.5+Math.random()*1.0;const precessionSpeed=1.5+Math.random()*2.0;const precessionAxis=new THREE.Vector3(0,1,0);const wobbleAmp=0.06+Math.random()*0.06;const wobbleFreq=14+Math.random()*6;const wobbleDamp=6+Math.random()*2;const wobbleAxis1=new THREE.Vector3(1,0,0);const wobbleAxis2=new THREE.Vector3(0,0,1);rollAnim={startTime:performance.now(),duration,targetQ,G,v0_throw,v0_b1,v0_b2,tThrowEnd,tB1End,tB2End,settleTime,vx0,vz0,vx1,vz1,vx2,vz2,x_at_b1,z_at_b1,x_at_b2,z_at_b2,x_at_settle,z_at_settle,initialSpin,spinDecay,spinDirX,spinDirY,spinDirZ,spinScaleX,spinScaleY,spinScaleZ,tumbleAxis,tumbleSpeed,tumbleDecay,precessionSpeed,precessionAxis,wobbleAmp,wobbleFreq,wobbleDamp,wobbleAxis1,wobbleAxis2,bounce1Haptic:false,bounce2Haptic:false,settleStartQ:null,onDone:()=>finishRoll(finalRaw,finalTotal,max),};function computeSettleQ(tSec){const ra=rollAnim;const sa=(ra.initialSpin/ra.spinDecay)*(1-Math.exp(-ra.spinDecay*tSec));const pq=new THREE.Quaternion().setFromEuler(new THREE.Euler(ra.spinDirX*ra.spinScaleX*sa,ra.spinDirY*ra.spinScaleY*sa*1.1,ra.spinDirZ*ra.spinScaleZ*sa*0.8));const tsa=(ra.tumbleSpeed/ra.tumbleDecay)*(1-Math.exp(-ra.tumbleDecay*tSec));const pa=tSec*ra.precessionSpeed;const cta=ra.tumbleAxis.clone().applyAxisAngle(ra.precessionAxis,pa);const tq=new THREE.Quaternion().setFromAxisAngle(cta,tsa);return pq.multiply(tq);}
rollAnim.settleStartQ=computeSettleQ(totalAirborne);}
function finishRoll(rawRolls,total,max){const panel=document.getElementById('resultPanel');const btnAction=document.getElementById('btnAction');const btnReroll=document.getElementById('btnReroll');showingResult=true;const isCrit=currentDie==='d20'&&rawRolls[0]===20;const isFail=currentDie==='d20'&&rawRolls[0]===1;if(isCrit||isFail){haptic('heavy');document.body.classList.remove('screen-shake');void document.body.offsetWidth;document.body.classList.add('screen-shake');setTimeout(()=>document.body.classList.remove('screen-shake'),450);spawnRing(isCrit?V_SUCCESS_HEX:V_DANGER_HEX);spawnParticles(isCrit?V_SUCCESS_HEX:V_DANGER_HEX,40);if(dieMesh){const mesh=dieMesh;const glowColor=parseInt((isCrit?V_SUCCESS_HEX:V_DANGER_HEX).replace('#',''),16);const glow=new THREE.PointLight(glowColor,1.5,4);glow.position.set(0,0.5,1);mesh.add(glow);let intensity=1.5;const fadeGlow=setInterval(()=>{intensity-=0.05;if(intensity<=0){mesh.remove(glow);clearInterval(fadeGlow);}
else glow.intensity=intensity;},50);}}else{haptic('heavy');spawnParticles(V_GOLD_HEX,20);}
const totalEl=document.getElementById('resultTotal');totalEl.textContent=total;const totalLen=String(total).length;totalEl.style.fontSize=totalLen>=5?'24px':totalLen>=4?'30px':'';const mod=MODE==='game'?(GAME_FORMULA?GAME_FORMULA.replace(/^\d*d\d+/,''):''):(currentMod!==0?(currentMod>0?'+'+currentMod:''+currentMod):'');const rollStr=rawRolls.join(' + ');const bdEl=document.getElementById('resultBreakdown');const bdText=rawRolls.length>1?`[${rollStr}]${mod} = ${total}`:mod?`${rawRolls[0]}${mod} = ${total}`:'';bdEl.textContent=bdText;bdEl.style.fontSize=bdText.length>50?'10px':bdText.length>35?'11px':'';bdEl.style.letterSpacing=bdText.length>35?'0':'';const lbl=document.getElementById('resultLabel');if(isCrit){lbl.textContent='ACERTO CRITICO!';lbl.className='result-label critical';}
else if(isFail){lbl.textContent='FALHA CRITICA!';lbl.className='result-label crit-fail';}
else if(MODE==='game'&&GAME_DC!==null){if(total>=GAME_DC){lbl.textContent='SUCESSO!';lbl.className='result-label success';}
else{lbl.textContent='FALHA';lbl.className='result-label failure';}}else{lbl.textContent='';lbl.className='result-label';}
panel.classList.add('visible');if(MODE!=='game'){rollHistory.unshift({die:currentDie,raw:rawRolls[0],mod:currentMod,total,isCrit,isFail});renderHistory();}
isRolling=false;if(MODE==='game'){btnAction.textContent='Confirmar';btnAction.disabled=false;btnAction.onclick=confirmGameRoll;}else{btnAction.style.display='none';btnReroll.style.display='';}}
function spawnRing(color){const c=document.getElementById('particles');const cx=c.offsetWidth/2,cy=c.offsetHeight/2;const r=document.createElement('div');r.className='impact-ring';r.style.borderColor=color;r.style.left=cx+'px';r.style.top=cy+'px';r.animate([{width:'0',height:'0',marginLeft:'0',marginTop:'0',opacity:0.8,borderWidth:'3px'},{width:'220px',height:'220px',marginLeft:'-110px',marginTop:'-110px',opacity:0,borderWidth:'1px'}],{duration:550,easing:'ease-out'});c.appendChild(r);setTimeout(()=>r.remove(),550);}
function spawnParticles(color,n){const c=document.getElementById('particles');const cx=c.offsetWidth/2,cy=c.offsetHeight/2;for(let i=0;i<n;i++){const p=document.createElement('div');p.className='particle';p.style.background=color;const s=2+Math.random()*5;p.style.width=s+'px';p.style.height=s+'px';p.style.left=cx+'px';p.style.top=cy+'px';const a=(Math.PI*2*i)/n+(Math.random()-0.5)*0.6;const dist=50+Math.random()*130;const dx=Math.cos(a)*dist,dy=Math.sin(a)*dist;const dur=450+Math.random()*550;const sp=Math.random()>0.65;p.animate([{opacity:0.9,transform:'translate(0,0) scale(1)'},{opacity:sp?1:0.6,transform:`translate(${dx * 0.4}px,${dy * 0.4}px) scale(${sp ? 1.6 : 1})`,offset:0.25},{opacity:0,transform:`translate(${dx}px,${dy}px) scale(0)`}],{duration:dur,easing:'cubic-bezier(0,0.3,0.5,1)'});c.appendChild(p);setTimeout(()=>p.remove(),dur);}}
const _apiBase=params.get('api')||'';const _apiUid=params.get('uid')||'';async function confirmGameRoll(){const payload={action:'roll_complete',result:GAME_RESULT,formula:GAME_FORMULA,token:GAME_TOKEN,type:GAME_TYPE};if(_apiBase&&GAME_TOKEN&&_apiUid){try{const _ch={'Content-Type':'application/json','Authorization':`Bearer ${GAME_TOKEN}`};if(tg?.initData)_ch['X-Telegram-Init-Data']=tg.initData;const _ac=new AbortController();const _tid=/*_TIMEOUT*/setTimeout(()=>_ac.abort(),15000);const resp=await fetch(`${_apiBase}/api/dice/apply`,{method:'POST',headers:_ch,signal:_ac.signal,body:JSON.stringify({user_id:parseInt(_apiUid),token:GAME_TOKEN,result:GAME_RESULT,formula:GAME_FORMULA,type:GAME_TYPE})});if(resp.ok){console.debug('[DICE] Roll confirmed via API');setTimeout(()=>{try{tg?.close();}catch(e){console.warn('[DICE]',e);}},300);return;}
console.warn('[DICE] API returned',resp.status,'— falling back to sendData');}catch(e){console.warn('[DICE] API fetch failed — falling back to sendData',e);}}
if(tg){tg.sendData(JSON.stringify(payload));setTimeout(()=>{try{tg.close();}catch(e){console.warn('[DICE] tg.close:',e);}},300);}}
function resetRoll(){isRolling=false;showingResult=false;rollAnim=null;createDieMesh(currentDie);idleTime=0;document.getElementById('resultPanel').classList.remove('visible');document.getElementById('tapHint').style.display='';const btn=document.getElementById('btnAction');btn.textContent='Rolar Dados';btn.disabled=false;btn.onclick=onDieTap;btn.style.display='';document.getElementById('btnReroll').style.display='none';}
function updateDieType(d){document.getElementById('dieBadge').textContent=d;document.querySelectorAll('.dice-chip').forEach(c=>{c.classList.toggle('active',c.dataset.die===d);});}
function changeMod(delta){if(isRolling)return;currentMod=Math.max(-10,Math.min(20,currentMod+delta));document.getElementById('modValue').textContent=currentMod>=0?'+'+currentMod:''+currentMod;}
function renderHistory(){const section=document.getElementById('historySection');if(rollHistory.length>0&&section)section.style.display='';document.getElementById('history').innerHTML=rollHistory.slice(0,10).map(h=>{const cls=h.isCrit?'h-crit':h.isFail?'h-fail':'h-result';const modStr=h.mod?(h.mod>0?'+'+h.mod:''+h.mod):'';return`<div class="history-item"><span>${h.die}${modStr}</span><span class="${cls}">${h.total}</span></div>`;}).join('');}
function init(){if(MODE==='game'){document.body.classList.add('game-mode');if(GAME_LABEL)document.getElementById('headerLabel').textContent=GAME_LABEL;if(GAME_FORMULA){document.getElementById('headerFormula').textContent=GAME_FORMULA;const m=GAME_FORMULA.match(/d(\d+)/);if(m)currentDie='d'+m[1];}
const titles={attack:'Ataque',skill:'Teste de Habilidade',damage:'Dano',save:'Salvaguarda',initiative:'Iniciativa',death_save:'Salvaguarda contra Morte'};if(titles[GAME_TYPE])document.getElementById('headerTitle').textContent=titles[GAME_TYPE];}
updateDieType(currentDie);document.querySelectorAll('.dice-chip').forEach(chip=>{chip.addEventListener('click',()=>{if(isRolling)return;document.querySelectorAll('.dice-chip').forEach(c=>c.classList.remove('active'));chip.classList.add('active');currentDie=chip.dataset.die;updateDieType(currentDie);resetRoll();});});createDieMesh(currentDie);animate(performance.now());}
var _diceLoadStart=Date.now();init();(function(){var elapsed=Date.now()-_diceLoadStart;var remaining=Math.max(0,(window.VALDORIA_MIN_LOAD_MS||5000)-elapsed);setTimeout(function(){if(window._diceLoadingCtrl){window._diceLoadingCtrl.hide();}else{var lo=document.getElementById('loadingOverlay');if(lo){lo.classList.add('v-hidden');setTimeout(function(){lo.remove();},500);}}},remaining);}());