// MIN_LOAD_MS enforced by loading-guard.js
(function(){"use strict";var _routes={};var _current=null;var _loadedCSS={};var _loadedJS={};var _navigating=false;var _visited={};var _coldStartDone=false;var Router={register:function(name,config){_routes[name]=config;},navigate:function(name,params){if(_navigating)return Promise.resolve();if(!_routes[name]){console.error("[SPA] Unknown route:",name);_hideLoading();_showRouteError("Rota desconhecida: "+name);return Promise.resolve();}
_navigating=true;return _doNavigate(name,params||{}).then(function(){_navigating=false;}).catch(function(e){_navigating=false;console.error("[SPA] Navigation error:",e);_hideLoading();var _rr=document.getElementById("route-root");if(_rr)_rr.style.visibility="";/* Never expose internal paths/URLs to the user. Map error categories to friendly messages. */var _emsg=String((e&&e.message)||'');var _friendly='Falha de conex\u00e3o. Verifique sua internet e tente novamente.';if(_emsg.indexOf('Rota desconhecida')>=0){_friendly='Tela n\u00e3o encontrada. Feche e reabra o jogo.';}_showRouteError(_friendly);});},_routes:_routes,current:function(){return _current;},wasVisited:function(name){return!!_visited[name];},isLoaded:function(src){return!!_loadedJS[src];},markLoaded:function(src){_loadedJS[src]=true;},external:function(url){if(window.ValdoriaAudio&&ValdoriaAudio.getCurrentTrack){try{var track=ValdoriaAudio.getCurrentTrack();if(track){localStorage.setItem("valdoria_audio_resume",track);localStorage.setItem("valdoria_audio_resume_ts",String(Date.now()));}}catch(e){console.warn('[SPA]',e);}}
window.__valdoria_transitioning=true;window.location.replace(url);},};function _doNavigate(name,params){if(document.documentElement.classList.contains("dev-panel-active")){console.info("[SPA] skip navigate '"+name+"' — dev panel host (game in iframe)");_navigating=false;return Promise.resolve();}console.warn("[SPA] navigate to="+name+" coldStart="+!_coldStartDone+" visited="+!!_visited[name]);var route=_routes[name];var routeRoot=document.getElementById("route-root");if(!routeRoot){console.warn("[SPA] #route-root missing, creating");routeRoot=document.createElement("div");routeRoot.id="route-root";document.body.appendChild(routeRoot);}_cleanupCurrentRoute(routeRoot);_showLoading();routeRoot.style.visibility="hidden";window.__spaRouteParams=params;window.__spaRouteName=name;return _fetchRouteHTML(route).then(function(bodyHtml){routeRoot.innerHTML=bodyHtml;var _shellIds=["loading"];_shellIds.forEach(function(id){var dup=routeRoot.querySelector("#"+id);if(dup)dup.remove();});return _loadExternals(route.external||[]);}).then(function(){return _loadCSS(route.css||[]);}).then(function(){window.__spaRevisit=!!_visited[name];return _loadScripts(route.sharedJs||[]);}).then(function(){return _loadScripts(route.js||[]);}).then(function(){_current=name;_visited[name]=true;if(route.init&&typeof route.init==="function")return route.init(params);}).then(function(initResult){_coldStartDone=true;console.warn("[SPA] coldStartDone set for route="+name);if(window._loadDbg)_loadDbg("initResult="+initResult+" hideLoading="+(initResult!=="__loading_delegated__"));routeRoot.style.visibility="";if(initResult!=="__loading_delegated__")_hideLoading();_prefetchAdjacentRoutes(name);});}
function _cleanupCurrentRoute(routeRoot){if(!_current)return;console.warn("[SPA] cleanup route="+_current);if(window.SpaWatchdog)SpaWatchdog.stop();var prev=_routes[_current];if(prev&&prev.cleanup)try{prev.cleanup();}catch(e){console.warn("[SPA] Cleanup:",e);}
if(window._spaCleanupFns&&window._spaCleanupFns.length){while(window._spaCleanupFns.length){try{window._spaCleanupFns.pop()();}catch(e){console.warn("[SPA] cleanup fn:",e);}}}
window._spaCleanupFns=[];if(window.vProcessing&&vProcessing.isActive())vProcessing.hide();delete window.showLoading;delete window.hideLoading;delete window.hideLoadingWithDelay;delete window.forceHideLoading;delete window.setLoadingContext;delete window.resetLoadingTimers;if(window._loadDbg)_loadDbg("cleaned loading globals");if(prev&&prev.css)prev.css.forEach(function(h){if(_loadedCSS[h]){_loadedCSS[h].remove();delete _loadedCSS[h];}});if(prev&&prev.js)prev.js.forEach(function(src){var base=src.split("?")[0];delete _loadedJS[base];});if(prev&&prev.sharedJs)prev.sharedJs.forEach(function(src){var base=src.split("?")[0];delete _loadedJS[base];});var shellSrcs=["spa/router.js","spa/routes.js","spa/spa-nav.js","spa/init.js"];document.body.querySelectorAll("script[src]").forEach(function(s){var srcAttr=(s.getAttribute("src")||"").split("?")[0];if(shellSrcs.indexOf(srcAttr)>=0)return;if(srcAttr.indexOf("://")>=0)return;s.remove();});routeRoot.innerHTML="";}
function _fetchRouteHTML(route){if(route.html)return Promise.resolve(route.html);if(route.page){return fetch(route.page+"?v="+Date.now()).then(function(r){if(!r.ok){console.error("[SPA] Fetch "+route.page+" HTTP "+r.status);throw new Error("html_fetch_failed");}return r.text();}).then(function(full){return _extractBody(full);});}
return Promise.resolve("");}
function _extractBody(html){var re=/<body[^>]*>([\s\S]*)<\/body>/i;var m=re.exec(html);if(!m)return"";return m[1].replace(/<script[\s\S]*?<\/script>/gi,"");}
function _loadCSS(hrefs){hrefs.forEach(function(h){if(_loadedCSS[h])return;var link=document.createElement("link");link.rel="stylesheet";link.href=h+"?v="+Date.now();link.onerror=function(){console.error("[SPA] CSS failed:",h);};document.head.appendChild(link);_loadedCSS[h]=link;});return Promise.resolve();}
function _loadExternals(urls){return Promise.all(urls.map(function(ext){var src=typeof ext==='object'?ext.src:ext;if(_loadedJS[src])return Promise.resolve();return _loadOneScript(src,typeof ext==='object'?ext:null);}));}
function _loadScripts(srcs){var chain=Promise.resolve();srcs.forEach(function(s){chain=chain.then(function(){return _loadedJS[s]?Promise.resolve():_loadOneScript(s+"?v="+Date.now());});});return chain;}
function _loadOneScript(src,sriConfig){return new Promise(function(resolve,reject){var s=document.createElement("script");s.src=src;if(sriConfig&&sriConfig.integrity){s.integrity=sriConfig.integrity;s.crossOrigin="anonymous";}
s.onload=function(){_loadedJS[src.split("?")[0]]=true;resolve();};s.onerror=function(){/* Log full src for dev; reject with generic marker — _showRouteError maps to friendly message, NEVER exposes path. */console.error("[SPA] Script failed:",src);reject(new Error("script_load_failed"));};document.body.appendChild(s);});}
function _showLoading(){if(window._loadDbg)_loadDbg("showLoading coldStart="+!_coldStartDone);if(!_coldStartDone){if(typeof showLoading==="function"){showLoading();return;}var el=document.getElementById("loading");if(el){el.style.display="";el.classList.remove("hidden");}return;}if(window.vProcessing)vProcessing.show({text:"Carregando..."});}
function _hideLoading(){if(window._loadDbg)_loadDbg("hideLoading coldStart="+!_coldStartDone);if(!_coldStartDone){_coldStartDone=true;if(typeof hideLoading==="function"){hideLoading();return;}var el=document.getElementById("loading");if(el)el.style.display="none";return;}if(window.vProcessing)vProcessing.hide();}
function _hardReload(){var u=location.href.replace(/[&?]_r=\d+/g,"");location.replace(u+(u.indexOf("?")>=0?"&":"?")+"_r="+Date.now());}
function _showRouteError(msg){var root=document.getElementById("route-root");if(!root)return;/* Sanitize: never expose paths/URLs/filenames to the user (XSS + info leak defense). */var _safe=String(msg||'Falha de conex\u00e3o. Verifique sua internet e tente novamente.');if(/[/\\]|https?:|\.js|\.css|\.html/i.test(_safe)){console.warn('[SPA] _showRouteError path-like text, replacing with generic msg');_safe='Falha de conex\u00e3o. Verifique sua internet e tente novamente.';}while(root.firstChild)root.removeChild(root.firstChild);var _el=document.createElement('div');_el.style.cssText='display:flex;flex-direction:column;align-items:center;justify-content:center;height:80vh;color:var(--v-text,#d4c8b0);font-family:var(--v-font,serif);text-align:center;padding:24px';var _t=document.createElement('div');_t.style.cssText='font-size:18px;margin-bottom:12px';_t.textContent='Ops! Algo deu errado';var _m=document.createElement('div');_m.style.cssText='font-size:13px;color:var(--v-text-dim,#a09484);margin-bottom:24px;max-width:300px;word-break:break-word';_m.textContent=_safe;var _b=document.createElement('button');_b.style.cssText='padding:10px 28px;background:var(--v-gold,#c4953a);color:#1a1612;border:none;border-radius:8px;font-family:var(--v-font,serif);font-size:14px;cursor:pointer';_b.textContent='Tentar novamente';_b.onclick=_hardReload;_el.appendChild(_t);_el.appendChild(_m);_el.appendChild(_b);root.appendChild(_el);}
var _PREFETCH_MAP={'game':['explore','navigate','combat','inventory','market'],'explore':['combat','game'],'combat':['game','explore'],'navigate':['game','explore'],'inventory':['game','market'],'market':['game','inventory'],'dungeon':['game'],'levelup':['game'],'prologue':['game'],'guild':['game'],'codex':['game'],'character_creator':['game'],'workstation':['game','inventory'],'dice':['game']};function _prefetchAdjacentRoutes(currentRoute){var targets=_PREFETCH_MAP[currentRoute];if(!targets)return;var idle=window.requestIdleCallback||function(fn){setTimeout(fn,200);};idle(function(){targets.forEach(function(routeName){var route=_routes[routeName];if(!route)return;(route.js||[]).forEach(function(src){if(!_loadedJS[src]){fetch(src+'?v='+Date.now()).catch(function(){/* prefetch */});}});(route.css||[]).forEach(function(href){if(!_loadedCSS[href]){fetch(href+'?v='+Date.now()).catch(function(){/* prefetch */});}});(route.sharedJs||[]).forEach(function(src){if(!_loadedJS[src]){fetch(src+'?v='+Date.now()).catch(function(){/* prefetch */});}});});});}
window.SpaRouter=Router;window._hardReload=_hardReload;})();